all:
	jsonnet -o auditee.json auditee.jsonnet
	jsonnet -o general.json general.jsonnet
	jsonnet -o note.json note.jsonnet
	jsonnet -o federal_award.json federal_award.jsonnet
	jsonnet -o passthrough.json passthrough.jsonnet
