from audit.fixtures.excel import FORM_SECTIONS
from audit.fixtures.excel import (
    ADDITIONAL_EINS_TEMPLATE,
    ADDITIONAL_UEIS_TEMPLATE,
    CORRECTIVE_ACTION_PLAN_TEMPLATE,
    FEDERAL_AWARDS_TEMPLATE,
    FINDINGS_TEXT_TEMPLATE,
    FINDINGS_UNIFORM_GUIDANCE_TEMPLATE,
    NOTES_TO_SEFA_TEMPLATE,
    SECONDARY_AUDITORS_TEMPLATE,
)


sections_to_template_paths = {
    FORM_SECTIONS.ADDITIONAL_EINS: ADDITIONAL_EINS_TEMPLATE,
    FORM_SECTIONS.ADDITIONAL_UEIS: ADDITIONAL_UEIS_TEMPLATE,
    FORM_SECTIONS.CORRECTIVE_ACTION_PLAN: CORRECTIVE_ACTION_PLAN_TEMPLATE,
    FORM_SECTIONS.FEDERAL_AWARDS_EXPENDED: FEDERAL_AWARDS_TEMPLATE,
    FORM_SECTIONS.FINDINGS_TEXT: FINDINGS_TEXT_TEMPLATE,
    FORM_SECTIONS.FINDINGS_UNIFORM_GUIDANCE: FINDINGS_UNIFORM_GUIDANCE_TEMPLATE,
    FORM_SECTIONS.NOTES_TO_SEFA: NOTES_TO_SEFA_TEMPLATE,
    FORM_SECTIONS.SECONDARY_AUDITORS: SECONDARY_AUDITORS_TEMPLATE,
}
