from peewee import *

database = PostgresqlDatabase('postgres', **{'host': 'localhost', 'user': 'postgres', 'password': ''})

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class Elecauditheader(BaseModel):
    agencycfda = TextField(null=True)
    auditeecertifyname = TextField(null=True)
    auditeecertifytitle = TextField(null=True)
    auditeecontact = TextField(null=True)
    auditeedatesigned = DateField(null=True)
    auditeeemail = TextField(null=True)
    auditeefax = TextField(null=True)
    auditeename = TextField(null=True)
    auditeenametitle = TextField(null=True)
    auditeephone = TextField(null=True)
    auditeetitle = TextField(null=True)
    auditor_ein = TextField(null=True)
    audittype = TextField(null=True)
    audityear = TextField(null=True)
    city = TextField(null=True)
    cog_agency = TextField(null=True)
    cog_over = TextField(null=True)
    cogagency = TextField(null=True)
    copies = TextField(null=True)
    cpacity = TextField(null=True)
    cpacontact = TextField(null=True)
    cpacountry = TextField(null=True)
    cpadatesigned = DateField(null=True)
    cpaemail = TextField(null=True)
    cpafax = TextField(null=True)
    cpafirmname = TextField(null=True)
    cpaforeign = TextField(null=True)
    cpanametitle = TextField(null=True)
    cpaphone = TextField(null=True)
    cpastate = TextField(null=True)
    cpastreet1 = TextField(null=True)
    cpastreet2 = TextField(null=True)
    cpatitle = TextField(null=True)
    cpazipcode = TextField(null=True)
    cyfindings = TextField(null=True)
    datefinished = DateField(null=True)
    datefirewall = DateField(null=True)
    datereceived = DateField(null=True)
    datereceivedother = DateField(null=True)
    datetoed = DateField(null=True)
    dbkey = DecimalField(null=True)
    dollarthreshold = DecimalField(null=True)
    duns = TextField(null=True)
    dup_reports = TextField(null=True)
    ein = TextField(null=True)
    einsubcode = TextField(null=True)
    elecauditheaderid = TextField(null=True)
    entity_type = TextField(null=True)
    facaccepteddate = DateField(null=True)
    findingrefnum = TextField(null=True)
    fyenddate = DateField(null=True)
    fystartdate = DateField(null=True)
    goingconcern = TextField(null=True)
    id = TextField(null=True)
    image = DecimalField(null=True)
    initialdate = DateField(null=True)
    lowrisk = TextField(null=True)
    materialnoncompliance = TextField(null=True)
    materialweakness = TextField(null=True)
    materialweakness_mp = TextField(null=True)
    multiple_cpas = TextField(null=True)
    multipleduns = TextField(null=True)
    multipleeins = TextField(null=True)
    multipleueis = TextField(null=True)
    numbermonths = DecimalField(null=True)
    opeid = TextField(null=True)
    oversightagency = TextField(null=True)
    periodcovered = TextField(null=True)
    previousdatefirewall = TextField(null=True)
    pyschedule = TextField(null=True)
    qcosts = TextField(null=True)
    reportablecondition = TextField(null=True)
    reportablecondition_mp = TextField(null=True)
    reportrequired = TextField(null=True)
    sd_materialweakness = TextField(null=True)
    sd_materialweakness_mp = TextField(null=True)
    significantdeficiency = TextField(null=True)
    significantdeficiency_mp = TextField(null=True)
    sp_framework = TextField(null=True)
    sp_framework_required = TextField(null=True)
    state = TextField(null=True)
    street1 = TextField(null=True)
    street2 = TextField(null=True)
    suppression_code = TextField(null=True)
    totfedexpend = DecimalField(null=True)
    typeaudit_code = TextField(null=True)
    typefinding = TextField(null=True)
    typefunding = TextField(null=True)
    typeofentity = TextField(null=True)
    typereport_fs = TextField(null=True)
    typereport_mp = TextField(null=True)
    typereport_sp_framework = TextField(null=True)
    uei = TextField(null=True)
    zipcode = TextField(null=True)

    class Meta:
        table_name = 'ELECAUDITHEADER'
        primary_key = False

