# Generated by Django 4.2.6 on 2023-11-27 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("census_historical_migration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportMigrationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_year", models.TextField(blank=True, null=True)),
                ("dbkey", models.TextField(blank=True, null=True)),
                (
                    "run_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("migration_status", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MigrationErrorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_summary", models.CharField(blank=True, null=True)),
                ("error_stack", models.TextField()),
                (
                    "report_migration_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census_historical_migration.reportmigrationstatus",
                    ),
                ),
            ],
        ),
    ]
