# Generated by Django 4.2.6 on 2023-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census_historical_migration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(blank=True, db_column="REPORT_ID", null=True),
                ),
                ("dbkey", models.TextField(blank=True, db_column="DBKEY", null=True)),
                (
                    "audityear",
                    models.TextField(blank=True, db_column="AUDITYEAR", null=True),
                ),
                ("ein", models.TextField(blank=True, db_column="EIN", null=True)),
                ("uei", models.TextField(blank=True, db_column="UEI", null=True)),
                (
                    "census_table_NAME",
                    models.TextField(
                        blank=True, db_column="CENSUS_TABLE_NAME", null=True
                    ),
                ),
                (
                    "census_column_name",
                    models.TextField(
                        blank=True, db_column="CENSUS_COLUMN_NAME", null=True
                    ),
                ),
                (
                    "census_data",
                    models.TextField(blank=True, db_column="CENSUS_DATA", null=True),
                ),
                (
                    "gsafac_table_name",
                    models.TextField(
                        blank=True, db_column="GSAFAC_TABLE_NAME", null=True
                    ),
                ),
                (
                    "gsafac_column_name",
                    models.TextField(
                        blank=True, db_column="GSAFAC_COLUMN_NAME", null=True
                    ),
                ),
                (
                    "gsafac_data",
                    models.TextField(blank=True, db_column="GSAFAC_DATA", null=True),
                ),
                (
                    "transformation_function",
                    models.TextField(
                        blank=True, db_column="TRANSFORMATION_FUNCTION", null=True
                    ),
                ),
                (
                    "run_datetime",
                    models.DateField(blank=True, db_column="RUN_DATETIME", null=True),
                ),
                (
                    "is_run_success",
                    models.TextField(blank=True, db_column="IS_RUN_SUCCESS", null=True),
                ),
                (
                    "git_hash",
                    models.TextField(blank=True, db_column="GIT_HASH", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FailedSacs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dbkey", models.TextField(blank=True, db_column="DBKEY", null=True)),
                (
                    "audityear",
                    models.TextField(blank=True, db_column="AUDITYEAR", null=True),
                ),
                ("ein", models.TextField(blank=True, db_column="EIN", null=True)),
                ("uei", models.TextField(blank=True, db_column="UEI", null=True)),
                ("error", models.TextField(blank=True, db_column="ERROR", null=True)),
                (
                    "run_datetime",
                    models.DateField(blank=True, db_column="RUN_DATETIME", null=True),
                ),
            ],
        ),
    ]
