# Generated by Django 4.2.6 on 2023-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census_historical_migration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CHANGE_RECORDS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("REPORTID", models.TextField(blank=True, null=True)),
                ("DBKEY", models.TextField(blank=True, null=True)),
                ("AUDITYEAR", models.TextField(blank=True, null=True)),
                ("EIN", models.TextField(blank=True, null=True)),
                ("UEI", models.TextField(blank=True, null=True)),
                ("CENSUS_TABLE_NAME", models.TextField(blank=True, null=True)),
                ("CENSUS_COLUMN_NAME", models.TextField(blank=True, null=True)),
                ("CENSUS_DATA", models.TextField(blank=True, null=True)),
                ("GSAFAC_TABLE_NAME", models.TextField(blank=True, null=True)),
                ("GSAFAC_COLUMN_NAME", models.TextField(blank=True, null=True)),
                ("GSAFAC_DATA", models.TextField(blank=True, null=True)),
                ("TRANSFORMATION_FUNCTION", models.TextField(blank=True, null=True)),
                ("RUN_DATETIME", models.DateField(blank=True, null=True)),
                ("IS_RUN_SUCCESS", models.TextField(blank=True, null=True)),
                ("GIT_HASH", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAILED_SACS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DBKEY", models.TextField(blank=True, null=True)),
                ("AUDITYEAR", models.TextField(blank=True, null=True)),
                ("EIN", models.TextField(blank=True, null=True)),
                ("UEI", models.TextField(blank=True, null=True)),
                ("ERROR", models.TextField(blank=True, null=True)),
                ("RUN_DATETIME", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
