# Generated by Django 4.2.6 on 2023-12-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "census_historical_migration",
            "0002_reportmigrationstatus_migrationerrordetail",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="migrationerrordetail",
            name="error_stack",
        ),
        migrations.RemoveField(
            model_name="migrationerrordetail",
            name="error_summary",
        ),
        migrations.AddField(
            model_name="migrationerrordetail",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationerrordetail",
            name="exception_class",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationerrordetail",
            name="tag",
            field=models.TextField(blank=True, null=True),
        ),
    ]
