# Generated by Django 5.0.2 on 2024-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "census_historical_migration",
            "0003_remove_migrationerrordetail_error_stack_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="elecaudits",
            name="MULTIPLEUEIS",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="elecaudits",
            name="UEI",
            field=models.TextField(blank=True, null=True),
        ),
    ]
