# Generated by Django 5.0.4 on 2024-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census_historical_migration", "0004_elecaudits_multipleueis_elecaudits_uei"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportmigrationstatus",
            name="invalid_migration_tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportmigrationstatus",
            name="skipped_validation_methods",
            field=models.TextField(blank=True, null=True),
        ),
    ]
