# Generated by Django 5.0.2 on 2024-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census_historical_migration", "0004_elecaudits_multipleueis_elecaudits_uei"),
    ]

    operations = [
        migrations.CreateModel(
            name="ELECRPT_REVISIONS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ELECRPTREVISIONID", models.TextField(blank=True, null=True)),
                ("REPORTID", models.TextField(blank=True, null=True)),
                ("VERSION", models.TextField(blank=True, null=True)),
                ("DBKEY", models.TextField(blank=True, null=True)),
                ("AUDITYEAR", models.TextField(blank=True, null=True)),
                ("GENINFO", models.TextField(blank=True, null=True)),
                ("GENINFO_EXPLAIN", models.TextField(blank=True, null=True)),
                ("FEDERALAWARDS", models.TextField(blank=True, null=True)),
                ("FEDERALAWARDS_EXPLAIN", models.TextField(blank=True, null=True)),
                ("NOTESTOSEFA", models.TextField(blank=True, null=True)),
                ("NOTESTOSEFA_EXPLAIN", models.TextField(blank=True, null=True)),
                ("AUDITINFO", models.TextField(blank=True, null=True)),
                ("AUDITINFO_EXPLAIN", models.TextField(blank=True, null=True)),
                ("FINDINGS", models.TextField(blank=True, null=True)),
                ("FINDINGS_EXPLAIN", models.TextField(blank=True, null=True)),
                ("FINDINGSTEXT", models.TextField(blank=True, null=True)),
                ("FINDINGSTEXT_EXPLAIN", models.TextField(blank=True, null=True)),
                ("CAP", models.TextField(blank=True, null=True)),
                ("CAP_EXPLAIN", models.TextField(blank=True, null=True)),
                ("OTHER", models.TextField(blank=True, null=True)),
                ("OTHER_EXPLAIN", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FEDERALAGENCYLOOKUP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID", models.TextField(blank=True, null=True)),
                ("CFDAPREFIX", models.TextField(blank=True, null=True)),
                ("NAME", models.TextField(blank=True, null=True)),
                ("ACRONYM", models.TextField(blank=True, null=True)),
                ("STARTEXT", models.TextField(blank=True, null=True)),
                ("ENDEXT", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
