name: Deploy to the staging cloud.gov environment
on:
  push:
    branches:
      - prod

jobs:
  testing:
    uses: ./.github/workflows/testing/testing-from-ghcr.yml
    secrets: inherit

  linting:
    uses: ./.github/workflows/linting/linting.yml
    secrets: inherit

  scan-dev:
    name: Zap scan of the dev site
    uses: ./.github/workflows/security/zap-scan.yml
    with:
      url: "https://fac-dev.app.cloud.gov/"

  deploy-infrastructure-staging:
    name: Deploy infrastructure (staging)
    needs:
      - testing
      - scan-dev
    uses: ./.github/workflows/terraform/terraform-apply-env.yml
    with:
      environment: "staging"
    secrets: inherit

  deploy-staging:
    name: Deploy staging app to cloud.gov
    needs:
      - deploy-infrastructure-staging
    uses: ./.github/workflows/deployments/deploy-apps.yml
    with:
      environment: "staging"
    secrets: inherit
