name: Deploy to the dev and management cloud.gov environments
on:
  workflow_dispatch: null

jobs:
  # ensure that every time a push to main occurs, the container is built and published to ghcr
  build-container:
    uses: ./.github/workflows/docker/build-docker-container.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      docker-name: fac
      image-name: web-container
      repo-name: gsa-tts/fac
      work-dir: ./backend

  testing:
    needs: [build-container]
    uses: ./.github/workflows/testing/testing-from-ghcr.yml
    secrets: inherit

  linting:
    uses: ./.github/workflows/linting/linting.yml
    secrets: inherit

  # deploy to Dev & Management spaces
  deploy-infrastructure-dev:
    name: Deploy infrastructure (dev)
    needs:
      - testing
    uses: ./.github/workflows/terraform/terraform-apply-env.yml
    with:
      environment: "dev"
    secrets: inherit

  deploy-infastructure-management:
    name: Deploy infrastructure (dev)
    needs:
      - testing
    uses: ./.github/workflows/terraform/terraform-apply-env.yml
    with:
      environment: "management"
    secrets: inherit

  deploy-dev:
    name: Deploy dev app to cloud.gov
    needs:
      - deploy-infrastructure-dev
    uses: ./.github/workflows/deployments/deploy-application.yml
    with:
      environment: "dev"
    secrets: inherit

  scan-dev-post-deploy:
    name: Zap scan of the dev site
    needs:
      - deploy-dev
    uses: ./.github/workflows/security/zap-scan.yml
    with:
      url: "https://fac-dev.app.cloud.gov/"

