services:
  #---------------------------------------------
  # Metabase app
  #---------------------------------------------
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 4123:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: metabase-db
      # This appears to be an open issue, and one that the community would like, though is not implemented https://github.com/metabase/metabase/issues/37836
      # It would appear we are locked to public schema, and we will have to accept that the metabase tables will be with our tables.
      #MB_DB_CONNECTION_URI: postgres://postgres@db/postgres?currentSchema=metabase
      #MB_DB_CONNECTION_URI: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres&currentSchema=metabase
    healthcheck:
      test: curl --fail -I http://localhost:4123/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase-db:
    image: "postgres:15"
    hostname: metabase-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - metabase-db:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  metabase-db:
