services:
  e2e:
    build: cypress
    container_name: cypress
    # depends_on:
    #   - web
    environment:
      - CYPRESS_baseUrl=http://localhost:8000
    volumes:
      - /src/node_modules
      - /src/cypress
