# used by cloud.gov
# Test comment 2022-12-14 to kick off deploy to make sure it's still broken
web: echo 'Starting procfile....' &&
    python manage.py collectstatic --noinput &&
    echo "collectstatic finished" &&
    python manage.py migrate &&
    npm install &&
    npm run build &&
    python manage.py collectstatic --noinput &&
    gunicorn config.wsgi -t 60
