# used by cloud.gov
web: gunicorn config.wsgi -c gunicorn.conf.py --preload
# web: newrelic-admin run-program gunicorn config.wsgi -c gunicorn.conf.py
# web: gunicorn config.wsgi -c gunicorn.conf.py

