# dependencies are in ../requirements

[tool.black]
line-length=88
exclude = "node_modules/"

[tool.mypy]
ignore_missing_imports = true
explicit_package_bases = true
exclude = ".venv/"

[tool.pylint."MESSAGES CONTROL"]
# Tadhg 2022-05-03: I added the below because I've found them unhelpful.
#                   Anybody should feel free to alter these as needed.

[tool.bandit]
# TDB 2022-12-07 - test_schemas and test_validators use random number generation, which bandit doesn't like
exclude_dirs = [
    "audit/test_schemas.py",
    "audit/test_validators.py",
    "node_modules",
]

enable = [
    "use-symbolic-message-instead",
    "useless-supression",
    "fixme",
]
disable = [
    "attribute-defined-outside-init",
    "duplicate-code",
    "format",
    "import-error",
    "missing-module-docstring",
    "no-value-for-parameter",
    "pointless-string-statement",
    "protected-access",
    "too-few-public-methods",
    "unnecessary-lambda",
    "unsubscriptable-object",
]

[tool.djlint]
ignore="H006,H022,H023,H019,H031"
# img_height,https,entity,javascript,lang
