# dependencies are in ../requirements

[tool.black]
line-length=88
exclude = "node_modules/"

[tool.mypy]
ignore_missing_imports = true
explicit_package_bases = true
exclude = ".venv/|audit/migrations/|dissemination/migrations|census_historical_migration/migrations"

[tool.pylint."MESSAGES CONTROL"]
# Tadhg 2022-05-03: I added the below because I've found them unhelpful.
#                   Anybody should feel free to alter these as needed.
enable = [
    "use-symbolic-message-instead",
    "useless-supression",
    "fixme",
]
disable = [
    "attribute-defined-outside-init",
    "duplicate-code",
    "format",
    "import-error",
    "missing-module-docstring",
    "no-member",  # PyLint is consistently wrong about "missing" Django object methods
    "no-value-for-parameter",
    "pointless-string-statement",
    "protected-access",
    "too-few-public-methods",
    "unnecessary-lambda",
    "unsubscriptable-object",
]


[tool.bandit]
# TDB 2022-12-07 - test_schemas and test_validators use random number generation, which bandit doesn't like
# 2024-11-14 - create_stream_yaml and create_partition_statements will never be touched by users, yet bandit doesn't like the SQL injection risk.
exclude_dirs = [
    "audit/cross_validation/test_check_has_federal_awards.py",
    "audit/test_schemas.py",
    "audit/test_validators.py",
    "node_modules",
    "dissemination/sql/fac-snapshot-db/create_partition_statements.py",
    "dissemination/sql/sling/bulk_data_export/create_stream_yaml.py",
    "dissemination/test_search.py",
    "dissemination/tests.py",
    ".venv"
]

[tool.djlint]
ignore="H006,H022,H023,H019,H031"
profile="django"
use_gitignore=true
# img_height,https,entity,javascript,lang
