@startuml FAC_System_Context_unified
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(User, "User", "Auditee/Auditor/Public")
Person(Staff, "User", "FAC Staff")
Person(Agency, "User", "Agency User")


Boundary(cloudgov, "Cloud.gov Boundary") {
    Boundary(atob, "ATO Boundary") {
        Boundary(backend, "Django web application") {
            System(admin, "Django Admin interface")
            System(submissions, "Django authenticated frontend")
            System(publicinfo, "Django unauthenticated frontend")
        }
        Boundary(services, "FAC Services") {
            System(api, "REST API", "PostgREST")
            System(scan, "Virus Scanner", "ClamAV")
        }
    }
    System(db, "Database", "postgres")
    System(s3, "PDF/XLS storage", "Brokered S3")
}

Boundary(gsaplatforms, "GSA Platforms Boundary") {
    System(Login, "Login.gov", "ID provider")
    System(datagov, "api.data.gov", "Access Provider")
    System(samgov, "SAM.gov", "UEI Source")
    System(Email, "GSA Email")
}

AddRelTag("authenticated", $lineColor="#008787", $textColor="#008787")
Rel(User, submissions, "Submits/edits audits", "via Login.gov", $tags="authenticated")
Rel(User, publicinfo, "Searches for/reads information")
Rel(Staff, admin, "Manages audits, roles, users", "via Login.gov", $tags="authenticated")
Rel(Agency, api, "Retrieves audits")

Rel(User, Login, "Authenticates with")
Rel(Agency, datagov, "Authenticates with")
Rel(Staff, Login, "Authenticates with")

Rel(backend, Email, "Sends emails using")
Rel(Email, User, "Sends emails to")

Rel(datagov, api, "Searches, filters, requests audit", "via api.data.gov", $tags="authenticated")
Rel(Login, backend, "Provides identities", "email address")
Rel(api, db, "Fetches Audits")
Rel(api, s3, "Fetches Audit Attachments")

Rel(backend, samgov, "Looks up UEI info")
Rel(backend, scan, "Scans attachments")
Rel(backend, db, "read/write")
Rel(backend, s3, "Stores single audit packages/Excel files")

@enduml
