@startuml FAC_System_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(User, "User", "Auditee/Auditor/Public")
Person(Staff, "User", "FAC Staff")


Boundary(cloudgov, "Cloud.gov Boundary") {
    Boundary(atob, "ATO Boundary") {
        Boundary(backend, "Django backend") {
            System(web, "REST API", "DRF")
            System(admin, "Django Admin interface")
        }
        System(frontend, "Frontend", "Federalist")
    }
    System(db, "Database", "postgres")
    System(s3, "PDF storage", "Brokered S3")
}

Boundary(gsaplatforms, "GSA Platforms Boundary") {
    System(Login, "Login.gov", "ID provider")
    System(Email, "GSA Email")
}

Rel(User, frontend, "Submits/Retrieves Audits")
Rel(User, web, "Retrieves Audits")

Rel(User, Login, "Authenticates with")
Rel(Email, User, "Sends emails to")
Rel(Staff, admin, "Manages audits, roles, users")

Rel(Login, backend, "Provides identities", "email address")

Rel(backend, Email, "Sends emails using")
Rel(frontend, web, "GET/POST data")

Rel(backend, db, "read/write")
Rel(backend, s3, "Stores single audit packages")

@enduml
