

-- TABLES: SELECT | INSERT | UPDATE | DELETE | TRUNCATE | REFERENCES | TRIGGER | MAINTAIN
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public_data_v1_0_0 
    GRANT SELECT 
    ON TABLES 
    TO api_fac_gov;

-- SEQ: USAGE | SELECT | UPDATE
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public_data_v1_0_0 
    GRANT SELECT, USAGE 
    ON SEQUENCES 
    TO api_fac_gov;
