---
name: Terraform Format and Lint
on:
  workflow_call:

jobs:
  test:
    name: Test format and validity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Format
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./terraform

      - name: Terraform Validate
        uses: dflook/terraform-validate@v1
        with:
          path: ./terraform

