from django.db import models
from django.contrib.postgres.fields import ArrayField

from . import docs


class FindingText(models.Model):
    """Specific findings details. References General"""

    report_id = models.TextField(
        "G-FAC generated identifier.l",
    )
    finding_ref_number = models.TextField(
        "Finding Reference Number - FK",
        null=True,
        help_text=docs.finding_ref_nums_findingstext,
    )
    contains_chart_or_table = models.BooleanField(
        "Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
        null=True,
        help_text=docs.charts_tables_findingstext,
    )
    finding_text = models.TextField(
        "Content of the finding text",
        null=True,
        help_text=docs.text_findingstext,
    )


class AdditionalUei(models.Model):
    """Additional UEIs for this audit."""

    report_id = models.TextField()
    additional_uei = models.TextField()


class Finding(models.Model):
    """A finding from the audit. References FederalAward and FindingText"""

    award_reference = models.TextField(
        "Order that the award line was reported in Award",
        null=True,
    )
    report_id = models.TextField(
        "G-FAC generated identifier. FK along with other fields - refers to Award",
    )
    finding_ref_number = models.TextField(
        "Findings Reference Numbers",
        help_text=docs.finding_ref_nums_findings,
    )
    is_material_weakness = models.BooleanField(
        "Material Weakness finding",
        null=True,
        help_text=docs.material_weakness_findings,
    )
    is_modified_opinion = models.BooleanField(
        "Modified Opinion finding", null=True, help_text=docs.modified_opinion
    )
    is_other_findings = models.BooleanField(
        "Other findings", null=True, help_text=docs.other_findings
    )
    is_other_non_compliance = models.BooleanField(
        "Other non-compliance", null=True, help_text=docs.other_non_compliance
    )
    # each element in the list is a FK to Finding
    prior_finding_ref_numbers = models.TextField(
        "Audit finding reference numbers from the immediate prior audit",
        help_text=docs.prior_finding_ref_nums,
        null=True,
    )
    is_questioned_costs = models.BooleanField(
        "Questioned Costs", null=True, help_text=docs.questioned_costs_findings
    )
    is_repeat_finding = models.BooleanField(
        "Indicates whether or not the audit finding was a repeat of an audit finding in the immediate prior audit",
        null=True,
        help_text=docs.repeat_finding,
    )
    is_significant_deficiency = models.BooleanField(
        "Significant Deficiency finding",
        null=True,
        help_text=docs.significant_deficiency_findings,
    )
    type_requirement = models.TextField(
        "Type Requirement Failure",
        null=True,
        help_text=docs.type_requirement_findings,
    )


class FederalAward(models.Model):
    """Information about the federal award section of the form. References General"""

    report_id = models.TextField(
        "G-FAC generated identifier. FK  to a General",
    )

    award_reference = models.TextField(
        "Order that the award line was reported",
    )

    federal_agency_prefix = models.TextField(
        "2-char code refers to an agency",
    )
    federal_award_extension = models.TextField(
        "3-digit extn for a program defined by the agency",
    )
    additional_award_identification = models.TextField(
        "Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
        null=True,
        help_text=docs.award_identification,
    )
    federal_program_name = models.TextField(
        "Name of Federal Program",
        null=True,
        help_text=docs.federal_program_name,
    )
    amount_expended = models.DecimalField(
        "Amount Expended for the Federal Program",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.amount,
    )
    cluster_name = models.TextField(
        "The name of the cluster",
        null=True,
        help_text=docs.cluster_name,
    )
    other_cluster_name = models.TextField(
        "The name of the cluster (if not listed in the Compliance Supplement)",
        null=True,
        help_text=docs.other_cluster_name,
    )
    state_cluster_name = models.TextField(
        "The name of the state cluster",
        null=True,
        help_text=docs.state_cluster_name,
    )
    cluster_total = models.DecimalField(
        "Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.cluster_total,
    )
    federal_program_total = models.DecimalField(
        "Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.program_total,
    )
    is_loan = models.BooleanField(
        "Indicate whether or not the program is a Loan or Loan Guarantee (only available for audit years 2013 and beyond)",
        null=True,
        help_text=docs.loans,
    )
    # This wants to be N/A sometimes.
    loan_balance = models.DecimalField(
        "The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.loan_balance,
    )
    is_direct = models.BooleanField(
        "Indicate whether or not the award was received directly from a Federal awarding agency",
        null=True,
        help_text=docs.direct,
    )

    is_major = models.BooleanField(
        "Indicate whether or not the Federal program is a major program",
        null=True,
        help_text=docs.major_program,
    )
    mp_audit_report_type = models.TextField(
        "Type of Report Issued on the Major Program Compliance",
        null=True,
        help_text=docs.type_report_major_program_cfdainfo,
    )
    findings_count = models.IntegerField(
        "Number of findings for the federal program (only available for audit years 2013 and beyond)",
        null=True,
        help_text=docs.findings_count,
    )

    is_passthrough_award = models.BooleanField(
        "Indicates whether or not funds were passed through to any subrecipients for the Federal program",
        null=True,
        help_text=docs.passthrough_award,
    )
    passthrough_name = models.TextField(
        "If no (Direct Award), Name of Passthrough Entity",
        null=True,
    )
    passthrough_id = models.TextField(
        "If no (Direct Award), Identifying Number Assigned by the Pass-through Entity, if assigned",
        null=True,
    )
    passthrough_amount = models.DecimalField(
        "Amount passed through to subrecipients",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.passthrough_amount,
    )
    type_requirement = models.TextField(
        "Type Requirement Failure",
        null=True,
        help_text=docs.type_requirement_cfdainfo,
    )


class CapText(models.Model):
    """Corrective action plan text. Referebces General"""

    report_id = models.TextField(
        "GSA FAC generated identifier. FK refers to a General",
    )
    finding_ref_number = models.TextField(
        "Audit Finding Reference Number",
        help_text=docs.finding_ref_nums_captext,
    )
    contains_chart_or_table = models.BooleanField(
        "Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
        null=True,
        help_text=docs.charts_tables_captext,
    )
    planned_action = models.TextField(
        "Content of the Corrective Action Plan (CAP)",
        null=True,
        help_text=docs.text_captext,
    )


class Note(models.Model):
    """Note to Schedule of Expenditures of Federal Awards (SEFA)"""

    report_id = models.TextField(
        "G-FAC generated identifier. FK refers to a General",
    )
    content = models.TextField("Content of the Note", null=True, help_text=docs.content)
    note_title = models.TextField("Note Title", null=True, help_text=docs.title)
    accounting_policies = models.TextField(null=True)
    is_minimis_rate_used = models.BooleanField("", null=True)
    rate_explained = models.TextField(null=True)


class Revision(models.Model):
    """Documents what was revised on the associated form from the previous version"""

    findings = models.TextField(
        "Indicates what items on the Findings page were edited during the revision",
        null=True,
        help_text=docs.findings_revisions,
    )
    revision_id = models.IntegerField(
        "Internal Unique Identifier for the record",
        null=True,
        help_text=docs.elec_report_revision_id,
    )
    federal_awards = models.TextField(
        "Indicates what items on the Federal Awards page were edited during the revision",
        null=True,
        help_text=docs.federal_awards,
    )
    general_info_explain = models.TextField(
        "Explanation of what items on the General Info page were edited during the revision",
        null=True,
        help_text=docs.general_info_explain,
    )
    federal_awards_explain = models.TextField(
        "Explanation of what items on the Federal Awards page were edited during the revision",
        null=True,
        help_text=docs.federal_awards_explain,
    )
    notes_to_sefa_explain = models.TextField(
        "Explanation of what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
        null=True,
        help_text=docs.notes_to_sefa_explain,
    )
    audit_info_explain = models.TextField(
        "Explanation of what items on the Audit Info page were edited during the revision",
        null=True,
        help_text=docs.auditinfo_explain,
    )
    findings_explain = models.TextField(
        "Explanation of what items on the Findings page were edited during the revision",
        null=True,
        help_text=docs.findings_explain,
    )
    findings_text_explain = models.TextField(
        "Explanation of what items on the Text of the Audit Findings page were edited during the revision",
        null=True,
        help_text=docs.findings_text_explain,
    )
    cap_explain = models.TextField(
        "Explanation of what items on the CAP Text page were edited during the revision",
        null=True,
        help_text=docs.cap_explain,
    )
    other_explain = models.TextField(
        "Explanation of what other miscellaneous items were edited during the revision",
        null=True,
        help_text=docs.other_explain,
    )
    audit_info = models.TextField(
        "Indicates what items on the Audit Info page were edited during the revision",
        null=True,
        help_text=docs.audit_info,
    )
    notes_to_sefa = models.TextField(
        "Indicates what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
        null=True,
        help_text=docs.notes_to_sefa,
    )
    findings_text = models.TextField(
        "Indicates what items on the Text of the Audit Findings page were edited during the revision",
        max_length=6,
        null=True,
        help_text=docs.findings_text,
    )
    cap = models.TextField(
        "Indicates what items on the CAP Text page were edited during the revision",
        max_length=6,
        null=True,
        help_text=docs.cap,
    )
    other = models.TextField(
        "Indicates what other miscellaneous items were edited during the revision",
        null=True,
        help_text=docs.other,
    )
    general_info = models.TextField(
        "Indicates what items on the General Info page were edited during the revision",
        null=True,
        help_text=docs.general_info,
    )
    audit_year = models.IntegerField(
        "Audit year from fy_start_date",
        help_text=docs.audit_year_revisions,
    )
    report_id = models.TextField(
        "G-FAC generated identifier. FK refers to General",
    )


class Passthrough(models.Model):
    """The pass-through entity information, when it is not a direct federal award"""

    """
    We may not need this table. We can simply add three columns
    pertating to passthrough in FederalAward table
    """
    award_reference = models.TextField(
        "Order that the award line was reported",
        null=True,
    )
    report_id = models.TextField(
        "G-FAC generated identifier. FK refers to General",
    )
    # This doesn't seem like it should be null but it is sometimes
    passthrough_id = models.TextField(
        "Identifying Number Assigned by the Pass-through Entity",
        null=True,
        help_text=docs.passthrough_id,
    )
    passthrough_name = models.TextField(
        "Name of Pass-through Entity",
        null=True,
        help_text=docs.passthrough_name,
    )


class General(models.Model):
    # Relational fields
    # null = True for these so we can load in phases, may want to tighten validation later

    report_id = models.TextField(
        "G-FAC generated identifier. ",
        unique=True,
    )
    auditee_certify_name = models.TextField(
        "Name of Auditee Certifying Official",
        null=True,
        help_text=docs.auditee_certify_name,
    )
    auditee_certify_title = models.TextField(
        "Title of Auditee Certifying Official",
        null=True,
        help_text=docs.auditee_certify_title,
    )
    auditee_contact_name = models.TextField(
        "Name of Auditee Contact",
        null=True,
        help_text=docs.auditee_contact,
    )
    auditee_email = models.TextField(
        "Auditee Email address",
        null=True,
        help_text=docs.auditee_email,
    )
    auditee_name = models.TextField("Name of the Auditee", help_text=docs.auditee_name)
    auditee_phone = models.TextField(
        "Auditee Phone Number", help_text=docs.auditee_phone
    )
    hist_auditee_fax = models.TextField(
        "Auditee Fax Number in C-FAC",
        null=True,
    )
    auditee_contact_title = models.TextField(
        "Title of Auditee Contact",
        null=True,
        help_text=docs.auditee_title,
    )
    auditee_address_line_1 = models.TextField(
        "Auditee Street Address", help_text=docs.street1
    )
    hist_auditee_address_line_2 = models.TextField(
        "Auditee Street Address Line 2 in C-FAC",
        null=True,
    )

    auditee_city = models.TextField("Auditee City", help_text=docs.city)
    auditee_state = models.TextField(
        "Auditee State", max_length=2, help_text=docs.state
    )
    auditee_ein = models.TextField(
        "Primary Employer Identification Number",
        null=True,
    )
    hist_auditee_duns = models.TextField(
        "Primary Employer Identification Number",
        null=True,
    )
    auditee_uei = models.TextField("", null=True, help_text=docs.uei_general)
    # auditee_addl_uei_list = ArrayField(
    #     models.TextField("", null=True, help_text=docs.uei_general),
    #     null=True,
    #     default=list,
    # )
    # No nesting of structures.
    # Just store the bool, and load the workbook into a separate table
    # This adds a lot of complexity to the process.
    additional_ueis = models.BooleanField(default=False)

    hist_auditee_addl_ein_list = ArrayField(
        models.TextField("", null=True, help_text=docs.uei_general),
        null=True,
        default=list,
    )
    hist_auditee_addl_duns_list = ArrayField(
        models.TextField("", null=True, help_text=docs.uei_general),
        null=True,
        default=list,
    )
    auditee_zip = models.TextField(
        "Auditee Zip Code",
        null=True,
        help_text=docs.zip_code,
    )
    auditor_phone = models.TextField(
        "CPA phone number", null=True, help_text=docs.auditor_phone
    )
    hist_auditor_fax = models.TextField(
        "CPA fax number in C-FAC",
        null=True,
    )
    auditor_state = models.TextField(
        "CPA State", null=True, help_text=docs.auditor_state
    )
    auditor_city = models.TextField("CPA City", null=True, help_text=docs.auditor_city)
    auditor_contact_title = models.TextField(
        "Title of CPA Contact",
        null=True,
        help_text=docs.auditor_title,
    )
    auditor_address_line_1 = models.TextField(
        "CPA Street Address",
        null=True,
        help_text=docs.auditor_street1,
    )
    hist_auditor_address_line_2 = models.TextField(
        "CPA Street Address Line 2 in C-FAC",
        null=True,
    )
    auditor_zip = models.TextField(
        "CPA Zip Code",
        null=True,
        help_text=docs.auditor_zip_code,
    )
    auditor_country = models.TextField(
        "CPA Country", null=True, help_text=docs.auditor_country
    )
    auditor_contact_name = models.TextField(
        "Name of CPA Contact",
        null=True,
        help_text=docs.auditor_contact,
    )
    auditor_email = models.TextField(
        "CPA mail address (optional)",
        null=True,
        help_text=docs.auditor_email,
    )
    auditor_firm_name = models.TextField(
        "CPA Firm Name", help_text=docs.auditor_firm_name
    )
    # Once loaded, would like to add these as regular addresses and just change this to a country field
    auditor_foreign_addr = models.TextField(
        "CPA Address - if international",
        null=True,
        help_text=docs.auditor_foreign,
    )
    auditor_ein = models.TextField(
        "CPA Firm EIN (only available for audit years 2013 and beyond)",
        null=True,
        help_text=docs.auditor_ein,
    )

    # Agency
    cognizant_agency = models.TextField(
        "Two digit Federal agency prefix of the cognizant agency",
        null=True,
        help_text=docs.cognizant_agency,
    )
    oversight_agency = models.TextField(
        "Two digit Federal agency prefix of the oversight agency",
        null=True,
        help_text=docs.oversight_agency,
    )

    # Dates
    initial_date_received = models.DateField(
        "The first date an audit component or Form SF-SAC was received by the Federal audit Clearinghouse (FAC).",
        null=True,
        help_text=docs.initial_date_received,
    )
    ready_for_certification_date = models.DateField(
        "The date at which the audit transitioned to 'ready for certification'",
        null=True,
    )
    auditor_certified_date = models.DateField(
        "The date at which the audit transitioned to 'auditor certified'", null=True
    )
    auditee_certified_date = models.DateField(
        "The date at which the audit transitioned to 'auditee certified'", null=True
    )
    certified_date = models.DateField(
        "The date at which the audit transitioned to 'certified'", null=True
    )
    submitted_date = models.DateField(
        "The date at which the audit transitioned to 'submitted'", null=True
    )
    auditor_signature_date = models.DateField(
        "The date on which the auditor signed the audit", null=True
    )
    auditee_signature_date = models.DateField(
        "The date on which the auditee signed the audit", null=True
    )
    fy_end_date = models.DateField(
        "Fiscal Year End Date", null=True, help_text=docs.fy_end_date
    )
    fy_start_date = models.DateField(
        "Fiscal Year Start Date", null=True, help_text=docs.fy_start_date
    )
    audit_year = models.IntegerField(
        "Audit year from fy_start_date.",
        help_text=docs.audit_year_general,
    )

    audit_type = models.TextField(
        "Type of Audit",
        help_text=docs.audit_type,
    )

    # Audit Info
    gaap_results = models.TextField(
        "GAAP Results by Auditor",
        null=True,
    )  # Concatenation of choices
    sp_framework = models.TextField(
        "Special Purpose Framework that was used as the basis of accounting",
        null=True,
        help_text=docs.sp_framework,
    )
    is_sp_framework_required = models.BooleanField(
        "Indicate whether or not the special purpose framework used as basis of accounting by state law or tribal law",
        null=True,
        help_text=docs.sp_framework_required,
    )
    sp_framework_auditor_opinion = models.TextField(
        "The auditor's opinion on the special purpose framework",
        null=True,
        help_text=docs.type_report_special_purpose_framework,
    )
    is_going_concern = models.BooleanField(
        "Whether or not the audit contained a going concern paragraph on financial statements",
        null=True,
        help_text=docs.going_concern,
    )
    is_significant_deficiency = models.BooleanField(
        "Whether or not the audit disclosed a significant deficiency on financial statements",
        null=True,
        help_text=docs.significant_deficiency_general,
    )
    is_material_weakness = models.BooleanField(
        "", null=True, help_text=docs.material_weakness_general
    )
    is_material_noncompliance = models.BooleanField(
        "Whether or not the audit disclosed a material noncompliance on financial statements",
        null=True,
        help_text=docs.material_noncompliance,
    )
    is_duplicate_reports = models.BooleanField(
        "Whether or not the financial statements include departments that have separate expenditures not included in this audit",
        null=True,
        help_text=docs.dup_reports,
    )  # is_aicpa_audit_guide_included
    dollar_threshold = models.DecimalField(
        "Dollar Threshold to distinguish between Type A and Type B programs.",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.dollar_threshold,
    )
    is_low_risk = models.BooleanField(
        "Indicate whether or not the auditee qualified as a low-risk auditee",
        null=True,
        help_text=docs.low_risk,
    )
    agencies_with_prior_findings = models.TextField(
        "List of agencues with prior findings",
        null=True,
    )  # Concatenation of agency codes
    # End of Audit Info

    entity_type = models.TextField(
        "Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
        null=True,
        help_text=docs.entity_type,
    )
    number_months = models.IntegerField(
        "Number of Months Covered by the 'Other' Audit Period",
        null=True,
        help_text=docs.number_months,
    )
    audit_period_covered = models.TextField(
        "Audit Period Covered by Audit", max_length=40, help_text=docs.period_covered
    )
    total_amount_expended = models.DecimalField(
        "Total Federal Expenditures",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.total_fed_expenditures,
    )
    type_report_major_program = models.TextField(
        "Type of Report Issued on the Major Program Compliance",
        null=True,
        help_text=docs.type_report_major_program_general,
    )
    type_audit_code = models.TextField("Determines if audit is A133 or UG", default="")

    # Metadata
    hist_dbkey = models.IntegerField(
        "Identifier for a submission along with audit_year in C-FAC",
        null=True,
    )
    is_public = models.BooleanField(
        "True for public records, False for non-public records", null=True
    )
    # Choices are: C-FAC and G-FAC
    data_source = models.TextField("Origin of the upload", max_length=12)

    class Meta:
        unique_together = (("report_id",),)
        """
            General
            The root of the submission tree
        """

    def __str__(self):
        return f"Id:{self.report_id} UEI:{self.auditee_uei}, AY2x:{self.audit_year}"


class SecondaryAuditor(models.Model):
    report_id = models.TextField(
        "G-FAC generated identifier. FK to General",
    )
    # auditor_seq_number = models.IntegerField("Order that the Auditor was reported")
    auditor_ein = models.TextField(
        "CPA Firm EIN (only available for audit years 2013 and beyond)",
        null=True,
        help_text=docs.auditor_ein,
    )
    auditor_name = models.TextField("CPA Firm Name", help_text=docs.auditor_firm_name)
    contact_name = models.TextField(
        "Name of CPA Contact",
        null=True,
    )
    contact_title = models.TextField(
        "Title of CPA Contact",
        null=True,
        help_text=docs.auditor_title,
    )
    contact_email = models.TextField(
        "CPA mail address (optional)",
        null=True,
        help_text=docs.auditor_email,
    )
    contact_phone = models.TextField(
        "CPA phone number", null=True, help_text=docs.auditor_phone
    )
    hist_contact_fax = models.TextField(
        "CPA fax number",
        null=True,
    )
    address_street = models.TextField(
        "CPA Street Address",
        null=True,
        help_text=docs.auditor_street1,
    )
    hist_address_street_line_2 = models.TextField(
        "CPA Street Address Line 2 in C-FAC",
        null=True,
    )
    address_city = models.TextField("CPA City", null=True, help_text=docs.auditor_city)
    address_state = models.TextField(
        "CPA State", null=True, help_text=docs.auditor_state
    )
    address_zipcode = models.TextField(
        "CPA Zip Code",
        null=True,
        help_text=docs.auditor_zip_code,
    )


class CensusGen22(models.Model):
    index = models.BigIntegerField(blank=True, primary_key=True)
    audityear = models.TextField(db_column='AUDITYEAR', blank=True, null=True)  # Field name made lowercase.
    dbkey = models.TextField(db_column='DBKEY', blank=True, null=True)  # Field name made lowercase.
    typeofentity = models.TextField(db_column='TYPEOFENTITY', blank=True, null=True)  # Field name made lowercase.
    fyenddate = models.TextField(db_column='FYENDDATE', blank=True, null=True)  # Field name made lowercase.
    audittype = models.TextField(db_column='AUDITTYPE', blank=True, null=True)  # Field name made lowercase.
    periodcovered = models.TextField(db_column='PERIODCOVERED', blank=True, null=True)  # Field name made lowercase.
    numbermonths = models.TextField(db_column='NUMBERMONTHS', blank=True, null=True)  # Field name made lowercase.
    ein = models.TextField(db_column='EIN', blank=True, null=True)  # Field name made lowercase.
    multipleeins = models.TextField(db_column='MULTIPLEEINS', blank=True, null=True)  # Field name made lowercase.
    einsubcode = models.TextField(db_column='EINSUBCODE', blank=True, null=True)  # Field name made lowercase.
    duns = models.TextField(db_column='DUNS', blank=True, null=True)  # Field name made lowercase.
    multipleduns = models.TextField(db_column='MULTIPLEDUNS', blank=True, null=True)  # Field name made lowercase.
    auditeename = models.TextField(db_column='AUDITEENAME', blank=True, null=True)  # Field name made lowercase.
    street1 = models.TextField(db_column='STREET1', blank=True, null=True)  # Field name made lowercase.
    street2 = models.TextField(db_column='STREET2', blank=True, null=True)  # Field name made lowercase.
    city = models.TextField(db_column='CITY', blank=True, null=True)  # Field name made lowercase.
    state = models.TextField(db_column='STATE', blank=True, null=True)  # Field name made lowercase.
    zipcode = models.TextField(db_column='ZIPCODE', blank=True, null=True)  # Field name made lowercase.
    auditeecontact = models.TextField(db_column='AUDITEECONTACT', blank=True, null=True)  # Field name made lowercase.
    auditeetitle = models.TextField(db_column='AUDITEETITLE', blank=True, null=True)  # Field name made lowercase.
    auditeephone = models.TextField(db_column='AUDITEEPHONE', blank=True, null=True)  # Field name made lowercase.
    auditeefax = models.TextField(db_column='AUDITEEFAX', blank=True, null=True)  # Field name made lowercase.
    auditeeemail = models.TextField(db_column='AUDITEEEMAIL', blank=True, null=True)  # Field name made lowercase.
    auditeedatesigned = models.TextField(db_column='AUDITEEDATESIGNED', blank=True, null=True)  # Field name made lowercase.
    auditeenametitle = models.TextField(db_column='AUDITEENAMETITLE', blank=True, null=True)  # Field name made lowercase.
    cpafirmname = models.TextField(db_column='CPAFIRMNAME', blank=True, null=True)  # Field name made lowercase.
    cpastreet1 = models.TextField(db_column='CPASTREET1', blank=True, null=True)  # Field name made lowercase.
    cpastreet2 = models.TextField(db_column='CPASTREET2', blank=True, null=True)  # Field name made lowercase.
    cpacity = models.TextField(db_column='CPACITY', blank=True, null=True)  # Field name made lowercase.
    cpastate = models.TextField(db_column='CPASTATE', blank=True, null=True)  # Field name made lowercase.
    cpazipcode = models.TextField(db_column='CPAZIPCODE', blank=True, null=True)  # Field name made lowercase.
    cpacontact = models.TextField(db_column='CPACONTACT', blank=True, null=True)  # Field name made lowercase.
    cpatitle = models.TextField(db_column='CPATITLE', blank=True, null=True)  # Field name made lowercase.
    cpaphone = models.TextField(db_column='CPAPHONE', blank=True, null=True)  # Field name made lowercase.
    cpafax = models.TextField(db_column='CPAFAX', blank=True, null=True)  # Field name made lowercase.
    cpaemail = models.TextField(db_column='CPAEMAIL', blank=True, null=True)  # Field name made lowercase.
    cpadatesigned = models.TextField(db_column='CPADATESIGNED', blank=True, null=True)  # Field name made lowercase.
    cog_over = models.TextField(db_column='COG_OVER', blank=True, null=True)  # Field name made lowercase.
    cogagency = models.TextField(db_column='COGAGENCY', blank=True, null=True)  # Field name made lowercase.
    oversightagency = models.TextField(db_column='OVERSIGHTAGENCY', blank=True, null=True)  # Field name made lowercase.
    typereport_fs = models.TextField(db_column='TYPEREPORT_FS', blank=True, null=True)  # Field name made lowercase.
    sp_framework = models.TextField(db_column='SP_FRAMEWORK', blank=True, null=True)  # Field name made lowercase.
    sp_framework_required = models.TextField(db_column='SP_FRAMEWORK_REQUIRED', blank=True, null=True)  # Field name made lowercase.
    typereport_sp_framework = models.TextField(db_column='TYPEREPORT_SP_FRAMEWORK', blank=True, null=True)  # Field name made lowercase.
    goingconcern = models.TextField(db_column='GOINGCONCERN', blank=True, null=True)  # Field name made lowercase.
    reportablecondition = models.TextField(db_column='REPORTABLECONDITION', blank=True, null=True)  # Field name made lowercase.
    materialweakness = models.TextField(db_column='MATERIALWEAKNESS', blank=True, null=True)  # Field name made lowercase.
    materialnoncompliance = models.TextField(db_column='MATERIALNONCOMPLIANCE', blank=True, null=True)  # Field name made lowercase.
    typereport_mp = models.TextField(db_column='TYPEREPORT_MP', blank=True, null=True)  # Field name made lowercase.
    dup_reports = models.TextField(db_column='DUP_REPORTS', blank=True, null=True)  # Field name made lowercase.
    dollarthreshold = models.TextField(db_column='DOLLARTHRESHOLD', blank=True, null=True)  # Field name made lowercase.
    lowrisk = models.TextField(db_column='LOWRISK', blank=True, null=True)  # Field name made lowercase.
    reportablecondition_mp = models.TextField(db_column='REPORTABLECONDITION_MP', blank=True, null=True)  # Field name made lowercase.
    materialweakness_mp = models.TextField(db_column='MATERIALWEAKNESS_MP', blank=True, null=True)  # Field name made lowercase.
    qcosts = models.TextField(db_column='QCOSTS', blank=True, null=True)  # Field name made lowercase.
    cyfindings = models.TextField(db_column='CYFINDINGS', blank=True, null=True)  # Field name made lowercase.
    pyschedule = models.TextField(db_column='PYSCHEDULE', blank=True, null=True)  # Field name made lowercase.
    totfedexpend = models.TextField(db_column='TOTFEDEXPEND', blank=True, null=True)  # Field name made lowercase.
    datefirewall = models.TextField(db_column='DATEFIREWALL', blank=True, null=True)  # Field name made lowercase.
    previousdatefirewall = models.TextField(db_column='PREVIOUSDATEFIREWALL', blank=True, null=True)  # Field name made lowercase.
    reportrequired = models.TextField(db_column='REPORTREQUIRED', blank=True, null=True)  # Field name made lowercase.
    multiple_cpas = models.TextField(db_column='MULTIPLE_CPAS', blank=True, null=True)  # Field name made lowercase.
    auditor_ein = models.TextField(db_column='AUDITOR_EIN', blank=True, null=True)  # Field name made lowercase.
    facaccepteddate = models.TextField(db_column='FACACCEPTEDDATE', blank=True, null=True)  # Field name made lowercase.
    cpaforeign = models.TextField(db_column='CPAFOREIGN', blank=True, null=True)  # Field name made lowercase.
    cpacountry = models.TextField(db_column='CPACOUNTRY', blank=True, null=True)  # Field name made lowercase.
    entity_type = models.TextField(db_column='ENTITY_TYPE', blank=True, null=True)  # Field name made lowercase.
    uei = models.TextField(db_column='UEI', blank=True, null=True)  # Field name made lowercase.
    multipleueis = models.TextField(db_column='MULTIPLEUEIS', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'census_gen22'


class cognizant_agencies_21_25(models.Model):
    index = models.BigIntegerField(blank=True, primary_key=True)
    dbkey = models.TextField(db_column='DBKEY', blank=True, null=True)  
    ein = models.TextField(db_column='EIN', blank=True, null=True) 
    uei = models.TextField(db_column='UEI', blank=True, null=True)
    auditeename = models.TextField(db_column='AUDITEENAME', blank=True, null=True)
    cogagency = models.TextField(db_column='COGAGENCY', blank=True, null=True)
    date_added = models.TextField(db_column='DATE_ADDED', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cognizant_agencies_21_25'
