from django.db import models
from django.contrib.postgres.fields import ArrayField

from . import docs

BIGINT_MAX_DIGITS = 25

REPORT_ID_FK_HELP_TEXT = "; foreign key everywhere else"
class FindingText(models.Model):
    """Specific findings details. References General"""

    report_id = models.TextField(
        REPORT_ID_FK_HELP_TEXT,
    )
    finding_ref_number = models.TextField(
        "Finding Reference Number - FK",
        null=True,
        help_text=docs.finding_ref_nums_findingstext,
    )
    contains_chart_or_table = models.BooleanField(
        "Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
        null=True,
        help_text=docs.charts_tables_findingstext,
    )
    finding_text = models.TextField(
        "Content of the finding text",
        null=True,
        help_text=docs.text_findingstext,
    )


class AdditionalUei(models.Model):
    """Additional UEIs for this audit."""
    report_id = models.TextField()
    additional_uei = models.TextField()


class Finding(models.Model):
    """A finding from the audit. References FederalAward and FindingText"""

    award_reference = models.TextField(
        "Order that the award line was reported in Award",
    )
    finding_ref_number = models.TextField(
        "Findings Reference Numbers",
        help_text=docs.finding_ref_nums_findings,
    )
    is_material_weakness = models.TextField(
        "Material Weakness finding",
        help_text=docs.material_weakness_findings,
    )
    is_modified_opinion = models.TextField(
        "Modified Opinion finding", 
        help_text=docs.modified_opinion
    )



    report_id = models.TextField(
        REPORT_ID_FK_HELP_TEXT,
    )
    is_other_findings = models.BooleanField(
        "Other findings", null=True, help_text=docs.other_findings
    )
    is_other_non_compliance = models.BooleanField(
        "Other non-compliance", null=True, help_text=docs.other_non_compliance
    )
    # each element in the list is a FK to Finding
    prior_finding_ref_numbers = models.TextField(
        "Audit finding reference numbers from the immediate prior audit",
        help_text=docs.prior_finding_ref_nums,
        null=True,
    )
    is_questioned_costs = models.BooleanField(
        "Questioned Costs", null=True, help_text=docs.questioned_costs_findings
    )
    is_repeat_finding = models.BooleanField(
        "Indicates whether or not the audit finding was a repeat of an audit finding in the immediate prior audit",
        null=True,
        help_text=docs.repeat_finding,
    )
    is_significant_deficiency = models.BooleanField(
        "Significant Deficiency finding",
        null=True,
        help_text=docs.significant_deficiency_findings,
    )
    type_requirement = models.TextField(
        "Type Requirement Failure",
        null=True,
        help_text=docs.type_requirement_findings,
    )


class FederalAward(models.Model):
    """Information about the federal award section of the form. References General"""

    additional_award_identification = models.TextField(
        "Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
        help_text=docs.award_identification,
    )
    amount_expended = models.BigIntegerField(
        "Amount Expended for the Federal Program",
        help_text=docs.amount,
    )
    award_reference = models.TextField(
        "Order that the award line was reported",
    )
    cluster_name = models.TextField(
        "The name of the cluster",
        help_text=docs.cluster_name,
    )
    cluster_total = models.BigIntegerField(
        "Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
        help_text=docs.cluster_total,
    )
    federal_agency_prefix = models.TextField(
        "2-char code refers to an agency",
    )
    federal_award_extension = models.TextField(
        "3-digit extn for a program defined by the agency",
    )
    federal_program_name = models.TextField(
        "Name of Federal Program",
        help_text=docs.federal_program_name,
    )
    federal_program_total = models.BigIntegerField(
        "Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
        help_text=docs.program_total,
    )
    findings_count = models.IntegerField(
        "Number of findings for the federal program (only available for audit years 2013 and beyond)",
        help_text=docs.findings_count,
    )
    is_direct = models.TextField(
        "Indicate whether or not the award was received directly from a Federal awarding agency",
        help_text=docs.direct,
    )
    is_loan = models.TextField(
        "Indicate whether or not the program is a Loan or Loan Guarantee (only available for audit years 2013 and beyond)",
        help_text=docs.loans,
    )
    is_major = models.TextField(
        "Indicate whether or not the Federal program is a major program",
        help_text=docs.major_program,
    )
    is_passthrough_award = models.TextField(
        "Indicates whether or not funds were passed through to any subrecipients for the Federal program",
        help_text=docs.passthrough_award,
    )
    loan_balance = models.TextField(
        "The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
        help_text=docs.loan_balance,
    )
    audit_report_type = models.TextField(
        "Type of Report Issued on the Major Program Compliance",
        help_text=docs.type_report_major_program_cfdainfo,
    )
    other_cluster_name = models.TextField(
        "The name of the cluster (if not listed in the Compliance Supplement)",
        help_text=docs.other_cluster_name,
    )
    passthrough_amount = models.BigIntegerField(
        "Amount passed through to subrecipients",
        help_text=docs.passthrough_amount,
        null=True
    )
    report_id = models.TextField(
        REPORT_ID_FK_HELP_TEXT,
    )
    state_cluster_name = models.TextField(
        "The name of the state cluster",
        help_text=docs.state_cluster_name,
    )



    # type_requirement = models.TextField(
    #     "Type Requirement Failure",
    #     null=True,
    #     help_text=docs.type_requirement_cfdainfo,
    # )


class CapText(models.Model):
    """Corrective action plan text. Referebces General"""

    contains_chart_or_table = models.TextField(
        "Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
        help_text=docs.charts_tables_captext,
    )
    finding_ref_number = models.TextField(
        "Audit Finding Reference Number",
        help_text=docs.finding_ref_nums_captext,
    )
    planned_action = models.TextField(
        "Content of the Corrective Action Plan (CAP)",
        help_text=docs.text_captext,
    )
    report_id = models.TextField(
        "GSA FAC generated identifier. FK refers to a General",
    )


class Note(models.Model):
    """Note to Schedule of Expenditures of Federal Awards (SEFA)"""
    accounting_policies = models.TextField(
        "A description of the significant accounting policies used in preparing the SEFA (2 CFR 200.510(b)(6))",
    )
    is_minimis_rate_used = models.TextField(
        "'Yes', 'No', or 'Both' (2 CFR 200.414(f))"
    )
    rate_explained = models.TextField("Explanation for minimis rate")
    report_id = models.TextField(
        REPORT_ID_FK_HELP_TEXT,
    )
    content = models.TextField("Content of the Note", help_text=docs.content)
    note_title = models.TextField("Note title", help_text=docs.title)


class Revision(models.Model):
    """Documents what was revised on the associated form from the previous version"""

    findings = models.TextField(
        "Indicates what items on the Findings page were edited during the revision",
        null=True,
        help_text=docs.findings_revisions,
    )
    revision_id = models.IntegerField(
        "Internal Unique Identifier for the record",
        null=True,
        help_text=docs.elec_report_revision_id,
    )
    federal_awards = models.TextField(
        "Indicates what items on the Federal Awards page were edited during the revision",
        null=True,
        help_text=docs.federal_awards,
    )
    general_info_explain = models.TextField(
        "Explanation of what items on the General Info page were edited during the revision",
        null=True,
        help_text=docs.general_info_explain,
    )
    federal_awards_explain = models.TextField(
        "Explanation of what items on the Federal Awards page were edited during the revision",
        null=True,
        help_text=docs.federal_awards_explain,
    )
    notes_to_sefa_explain = models.TextField(
        "Explanation of what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
        null=True,
        help_text=docs.notes_to_sefa_explain,
    )
    audit_info_explain = models.TextField(
        "Explanation of what items on the Audit Info page were edited during the revision",
        null=True,
        help_text=docs.auditinfo_explain,
    )
    findings_explain = models.TextField(
        "Explanation of what items on the Findings page were edited during the revision",
        null=True,
        help_text=docs.findings_explain,
    )
    findings_text_explain = models.TextField(
        "Explanation of what items on the Text of the Audit Findings page were edited during the revision",
        null=True,
        help_text=docs.findings_text_explain,
    )
    cap_explain = models.TextField(
        "Explanation of what items on the CAP Text page were edited during the revision",
        null=True,
        help_text=docs.cap_explain,
    )
    other_explain = models.TextField(
        "Explanation of what other miscellaneous items were edited during the revision",
        null=True,
        help_text=docs.other_explain,
    )
    audit_info = models.TextField(
        "Indicates what items on the Audit Info page were edited during the revision",
        null=True,
        help_text=docs.audit_info,
    )
    notes_to_sefa = models.TextField(
        "Indicates what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
        null=True,
        help_text=docs.notes_to_sefa,
    )
    findings_text = models.TextField(
        "Indicates what items on the Text of the Audit Findings page were edited during the revision",
        max_length=6,
        null=True,
        help_text=docs.findings_text,
    )
    cap = models.TextField(
        "Indicates what items on the CAP Text page were edited during the revision",
        max_length=6,
        null=True,
        help_text=docs.cap,
    )
    other = models.TextField(
        "Indicates what other miscellaneous items were edited during the revision",
        null=True,
        help_text=docs.other,
    )
    general_info = models.TextField(
        "Indicates what items on the General Info page were edited during the revision",
        null=True,
        help_text=docs.general_info,
    )
    audit_year = models.IntegerField(
        "Audit year from fy_start_date",
        help_text=docs.audit_year_revisions,
    )
    report_id = models.TextField(
        "G-FAC generated identifier. FK refers to General",
    )


class Passthrough(models.Model):
    """The pass-through entity information, when it is not a direct federal award"""
    award_reference = models.TextField(
        "Order that the award line was reported",
    )
    report_id = models.TextField(
        "G-FAC generated identifier. FK refers to General",
    )
    passthrough_id = models.TextField(
        "Identifying Number Assigned by the Pass-through Entity",
        help_text=docs.passthrough_id,
    )
    passthrough_name = models.TextField(
        "Name of Pass-through Entity",
        help_text=docs.passthrough_name,
    )


class General(models.Model):
    # Relational fields
    # null = True for these so we can load in phases, may want to tighten validation later

    report_id = models.TextField(
        "G-FAC generated identifier. ",
        unique=True,
    )
    auditee_certify_name = models.TextField(
        "Name of Auditee Certifying Official",
        null=True,
        help_text=docs.auditee_certify_name,
    )
    auditee_certify_title = models.TextField(
        "Title of Auditee Certifying Official",
        null=True,
        help_text=docs.auditee_certify_title,
    )
    auditee_contact_name = models.TextField(
        "Name of Auditee Contact",
        null=True,
        help_text=docs.auditee_contact,
    )
    auditee_email = models.TextField(
        "Auditee Email address",
        null=True,
        help_text=docs.auditee_email,
    )
    auditee_name = models.TextField("Name of the Auditee", help_text=docs.auditee_name)
    auditee_phone = models.TextField(
        "Auditee Phone Number", help_text=docs.auditee_phone
    )
    hist_auditee_fax = models.TextField(
        "Auditee Fax Number in C-FAC",
        null=True,
    )
    auditee_contact_title = models.TextField(
        "Title of Auditee Contact",
        null=True,
        help_text=docs.auditee_title,
    )
    auditee_address_line_1 = models.TextField(
        "Auditee Street Address", help_text=docs.street1
    )
    hist_auditee_address_line_2 = models.TextField(
        "Auditee Street Address Line 2 in C-FAC",
        null=True,
    )

    auditee_city = models.TextField("Auditee City", help_text=docs.city)
    auditee_state = models.TextField(
        "Auditee State", max_length=2, help_text=docs.state
    )
    auditee_ein = models.TextField(
        "Primary Employer Identification Number",
        null=True,
    )
    hist_auditee_duns = models.TextField(
        "Primary Employer Identification Number",
        null=True,
    )
    auditee_uei = models.TextField("", null=True, help_text=docs.uei_general)
    # auditee_addl_uei_list = ArrayField(
    #     models.TextField("", null=True, help_text=docs.uei_general),
    #     null=True,
    #     default=list,
    # )
    # No nesting of structures.
    # Just store the bool, and load the workbook into a separate table
    # This adds a lot of complexity to the process.
    additional_ueis = models.BooleanField(default=False)

    hist_auditee_addl_ein_list = ArrayField(
        models.TextField("", null=True, help_text=docs.uei_general),
        null=True,
        default=list,
    )
    hist_auditee_addl_duns_list = ArrayField(
        models.TextField("", null=True, help_text=docs.uei_general),
        null=True,
        default=list,
    )
    auditee_zip = models.TextField(
        "Auditee Zip Code",
        null=True,
        help_text=docs.zip_code,
    )
    auditor_phone = models.TextField(
        "CPA phone number", null=True, help_text=docs.auditor_phone
    )
    hist_auditor_fax = models.TextField(
        "CPA fax number in C-FAC",
        null=True,
    )
    auditor_state = models.TextField(
        "CPA State", null=True, help_text=docs.auditor_state
    )
    auditor_city = models.TextField("CPA City", null=True, help_text=docs.auditor_city)
    auditor_contact_title = models.TextField(
        "Title of CPA Contact",
        null=True,
        help_text=docs.auditor_title,
    )
    auditor_address_line_1 = models.TextField(
        "CPA Street Address",
        null=True,
        help_text=docs.auditor_street1,
    )
    hist_auditor_address_line_2 = models.TextField(
        "CPA Street Address Line 2 in C-FAC",
        null=True,
    )
    auditor_zip = models.TextField(
        "CPA Zip Code",
        null=True,
        help_text=docs.auditor_zip_code,
    )
    auditor_country = models.TextField(
        "CPA Country", null=True, help_text=docs.auditor_country
    )
    auditor_contact_name = models.TextField(
        "Name of CPA Contact",
        null=True,
        help_text=docs.auditor_contact,
    )
    auditor_email = models.TextField(
        "CPA mail address (optional)",
        null=True,
        help_text=docs.auditor_email,
    )
    auditor_firm_name = models.TextField(
        "CPA Firm Name", help_text=docs.auditor_firm_name
    )
    # Once loaded, would like to add these as regular addresses and just change this to a country field
    auditor_foreign_addr = models.TextField(
        "CPA Address - if international",
        null=True,
        help_text=docs.auditor_foreign,
    )
    auditor_ein = models.TextField(
        "CPA Firm EIN (only available for audit years 2013 and beyond)",
        null=True,
        help_text=docs.auditor_ein,
    )

    # Agency
    cognizant_agency = models.TextField(
        "Two digit Federal agency prefix of the cognizant agency",
        null=True,
        help_text=docs.cognizant_agency,
    )
    oversight_agency = models.TextField(
        "Two digit Federal agency prefix of the oversight agency",
        null=True,
        help_text=docs.oversight_agency,
    )

    # Dates
    initial_date_received = models.DateField(
        "The first date an audit component or Form SF-SAC was received by the Federal audit Clearinghouse (FAC).",
        null=True,
        help_text=docs.initial_date_received,
    )
    ready_for_certification_date = models.DateField(
        "The date at which the audit transitioned to 'ready for certification'",
        null=True,
    )
    auditor_certified_date = models.DateField(
        "The date at which the audit transitioned to 'auditor certified'", null=True
    )
    auditee_certified_date = models.DateField(
        "The date at which the audit transitioned to 'auditee certified'", null=True
    )
    certified_date = models.DateField(
        "The date at which the audit transitioned to 'certified'", null=True
    )
    submitted_date = models.DateField(
        "The date at which the audit transitioned to 'submitted'", null=True
    )
    auditor_signature_date = models.DateField(
        "The date on which the auditor signed the audit", null=True
    )
    auditee_signature_date = models.DateField(
        "The date on which the auditee signed the audit", null=True
    )
    fy_end_date = models.DateField(
        "Fiscal Year End Date", null=True, help_text=docs.fy_end_date
    )
    fy_start_date = models.DateField(
        "Fiscal Year Start Date", null=True, help_text=docs.fy_start_date
    )
    audit_year = models.IntegerField(
        "Audit year from fy_start_date.",
        help_text=docs.audit_year_general,
    )

    audit_type = models.TextField(
        "Type of Audit",
        help_text=docs.audit_type,
    )

    # Audit Info
    gaap_results = models.TextField(
        "GAAP Results by Auditor",
        null=True,
    )  # Concatenation of choices
    sp_framework = models.TextField(
        "Special Purpose Framework that was used as the basis of accounting",
        null=True,
        help_text=docs.sp_framework,
    )
    is_sp_framework_required = models.BooleanField(
        "Indicate whether or not the special purpose framework used as basis of accounting by state law or tribal law",
        null=True,
        help_text=docs.sp_framework_required,
    )
    sp_framework_auditor_opinion = models.TextField(
        "The auditor's opinion on the special purpose framework",
        null=True,
        help_text=docs.type_report_special_purpose_framework,
    )
    is_going_concern = models.BooleanField(
        "Whether or not the audit contained a going concern paragraph on financial statements",
        null=True,
        help_text=docs.going_concern,
    )
    is_significant_deficiency = models.BooleanField(
        "Whether or not the audit disclosed a significant deficiency on financial statements",
        null=True,
        help_text=docs.significant_deficiency_general,
    )
    is_material_weakness = models.BooleanField(
        "", null=True, help_text=docs.material_weakness_general
    )
    is_material_noncompliance = models.BooleanField(
        "Whether or not the audit disclosed a material noncompliance on financial statements",
        null=True,
        help_text=docs.material_noncompliance,
    )
    is_duplicate_reports = models.BooleanField(
        "Whether or not the financial statements include departments that have separate expenditures not included in this audit",
        null=True,
        help_text=docs.dup_reports,
    )  # is_aicpa_audit_guide_included
    dollar_threshold = models.DecimalField(
        "Dollar Threshold to distinguish between Type A and Type B programs.",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.dollar_threshold,
    )
    is_low_risk = models.BooleanField(
        "Indicate whether or not the auditee qualified as a low-risk auditee",
        null=True,
        help_text=docs.low_risk,
    )
    agencies_with_prior_findings = models.TextField(
        "List of agencues with prior findings",
        null=True,
    )  # Concatenation of agency codes
    # End of Audit Info

    entity_type = models.TextField(
        "Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
        null=True,
        help_text=docs.entity_type,
    )
    number_months = models.IntegerField(
        "Number of Months Covered by the 'Other' Audit Period",
        null=True,
        help_text=docs.number_months,
    )
    audit_period_covered = models.TextField(
        "Audit Period Covered by Audit", max_length=40, help_text=docs.period_covered
    )
    total_amount_expended = models.DecimalField(
        "Total Federal Expenditures",
        null=True,
        max_digits=23,
        decimal_places=2,
        help_text=docs.total_fed_expenditures,
    )
    type_report_major_program = models.TextField(
        "Type of Report Issued on the Major Program Compliance",
        null=True,
        help_text=docs.type_report_major_program_general,
    )
    type_audit_code = models.TextField("Determines if audit is A133 or UG", default="")

    # Metadata
    hist_dbkey = models.IntegerField(
        "Identifier for a submission along with audit_year in C-FAC",
        null=True,
    )
    is_public = models.BooleanField(
        "True for public records, False for non-public records", null=True
    )
    # Choices are: C-FAC and G-FAC
    data_source = models.TextField("Origin of the upload", max_length=12)

    class Meta:
        unique_together = (("report_id",),)
        """
            General
            The root of the submission tree
        """

    def __str__(self):
        return f"Id:{self.report_id} UEI:{self.auditee_uei}, AY2x:{self.audit_year}"


class SecondaryAuditor(models.Model):
    address_city = models.TextField(
        "CPA City",
        help_text=docs.auditor_city,
    )
    # The General model enforces a max_length for State abbreviations.
    # We're validating these on intake, so it might not be necessary to 
    # enforce a max_length here
    address_state = models.TextField(
        "CPA State",
        max_length=2,
        help_text=docs.auditor_state,
    )
    address_street = models.TextField(
        "CPA Street Address",
        help_text=docs.auditor_street1,
    )
    address_zipcode = models.TextField(
        "CPA Zip Code",
        help_text=docs.auditor_zip_code,
    )
    auditor_ein = models.TextField(
        "CPA Firm EIN (only available for audit years 2013 and beyond)",
        help_text=docs.auditor_ein,
    )
    auditor_name = models.TextField(
        "CPA Firm Name", 
        help_text=docs.auditor_firm_name,
    )
    contact_email = models.TextField(
        "CPA mail address (optional)",
        help_text=docs.auditor_email,
    )
    contact_name = models.TextField(
        "Name of CPA Contact",
    )
    contact_phone = models.TextField(
        "CPA phone number",
        help_text=docs.auditor_phone,
    )
    contact_title = models.TextField(
        "Title of CPA Contact",
        help_text=docs.auditor_title,
    )
    report_id = models.TextField(
        "G-FAC generated identifier. FK to General",
    )
