from peewee import *
from playhouse.postgres_ext import *

database = PostgresqlDatabase('postgres', **{'host': 'localhost', 'port': 5432, 'user': 'postgres'})

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class DisseminationGeneral(BaseModel):
    id = BigAutoField()
    report_id = CharField(index=True)
    audit_period_covered = CharField()
    audit_type = CharField()
    audit_year = CharField()
    # FIXME Added null=True
    auditee_addl_duns_list = ArrayField(field_class=CharField, null=True)
    auditee_addl_ein_list = ArrayField(field_class=IntegerField, null=True)
    auditee_addl_uei_list = ArrayField(field_class=CharField, null=True)
    auditee_address_line_1 = CharField()
    auditee_certified_date = DateField(null=True)
    auditee_certify_name = CharField(null=True)
    auditee_certify_title = CharField(null=True)
    auditee_city = CharField()
    auditee_contact_name = CharField(null=True)
    auditee_contact_title = CharField(null=True)
    auditee_duns = ArrayField(field_class=CharField, null=True)
    # FIXME: Should be text?
    auditee_ein = IntegerField(null=True)
    auditee_email = CharField(null=True)
    auditee_name = CharField()
    auditee_phone = BigIntegerField()
    auditee_state = CharField()
    auditee_uei = CharField(null=True)
    auditee_zip = CharField(null=True)
    auditor_address_line_1 = CharField(null=True)
    auditor_certified_date = DateField(null=True)
    auditor_city = CharField(null=True)
    auditor_contact_name = CharField(null=True)
    auditor_contact_title = CharField(null=True)
    auditor_country = CharField(null=True)
    auditor_ein = CharField(null=True)
    auditor_email = CharField(null=True)
    auditor_firm_name = CharField()
    auditor_foreign_addr = CharField(null=True)
    auditor_phone = BigIntegerField(null=True)
    auditor_state = CharField(null=True)
    auditor_zip = CharField(null=True)
    cfac_report_id = CharField(null=True)
    cfac_version = CharField(null=True)
    cognizant_agency = CharField(null=True)
    condition_or_deficiency_major_program = BooleanField(null=True)
    create_date = DateTimeField()
    current_or_former_findings = BooleanField(null=True)
    data_source = CharField()
    date_published = DateField(null=True)
    date_received = DateField(null=True)
    dbkey = CharField()
    dollar_threshold = DoubleField(null=True)
    ein_subcode = IntegerField(null=True)
    entity_type = CharField(null=True)
    fac_accepted_date = DateField()
    form_date_received = DateField(null=True)
    fy_end_date = DateField(null=True)
    fy_start_date = DateField(null=True)
    hist_auditee_address_line_2 = CharField(null=True)
    hist_auditee_fax = BigIntegerField(null=True)
    hist_auditor_address_line_2 = CharField(null=True)
    hist_auditor_fax = BigIntegerField(null=True)
    hist_completed_date = DateField(null=True)
    hist_component_date_received = DateField(null=True)
    hist_previous_completed_on = DateField(null=True)
    hist_previous_date_published = DateField(null=True)
    hist_reportable_condition = BooleanField(null=True)
    hist_type_of_entity = CharField(null=True)
    initial_date_received = DateField(null=True)
    is_duplicate_reports = BooleanField(null=True)
    is_going_concern = BooleanField(null=True)
    is_low_risk = BooleanField(null=True)
    is_material_noncompliance = BooleanField(null=True)
    is_material_weakness = BooleanField(null=True)
    is_public = BooleanField(null=True)
    is_significant_deficiency = BooleanField(null=True)
    is_special_framework_required = BooleanField(null=True)
    material_weakness = BooleanField(null=True)
    material_weakness_major_program = BooleanField(null=True)
    modified_date = DateTimeField(null=True)
    multiple_auditors = BooleanField(null=True)
    multiple_duns = BooleanField(null=True)
    multiple_ein = BooleanField(null=True)
    multiple_uei = BooleanField(null=True)
    number_months = IntegerField(null=True)
    oversight_agency = IntegerField(null=True)
    pdf_url = ArrayField(field_class=CharField, null=True)
    prior_year_schedule = BooleanField(null=True)
    questioned_costs = BooleanField(null=True)
    report_required = BooleanField(null=True)
    special_framework = CharField(null=True)
    suppression_code = CharField(null=True)
    total_fed_expenditures = BigIntegerField(null=True)
    type_audit_code = CharField()
    type_report_financial_statements = CharField(null=True)
    type_report_major_program = CharField(null=True)
    type_report_special_purpose_framework = CharField(null=True)

    class Meta:
        table_name = 'dissemination_general'

