# Generated by Django 4.2.3 on 2023-08-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_Create_content_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="meta_description",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="title",
            field=models.CharField(unique=True),
        ),
    ]
