--------------------------------------------------------
--  File created - Thursday-June-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AURORA$SNS$NODE_NUMBER$
--------------------------------------------------------

   CREATE SEQUENCE  "AURORA$SNS$NODE_NUMBER$"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "AURORA$SNS$NODE_NUMBER$" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Sequence JAVA$POLICY$SEQUENCE$
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA$POLICY$SEQUENCE$"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "JAVA$POLICY$SEQUENCE$" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Sequence SEQ_FACDISSEM_ADMINS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FACDISSEM_ADMINS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SEQ_FACDISSEM_ADMINS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Sequence SEQ_FACDISSEM_APPLICATION_JOBS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FACDISSEM_APPLICATION_JOBS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SEQ_FACDISSEM_APPLICATION_JOBS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Sequence SEQ_FACDISSEM_AUDIT_LOGS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FACDISSEM_AUDIT_LOGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17200253 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SEQ_FACDISSEM_AUDIT_LOGS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Sequence SEQ_FACDISSEM_JOB_LOG
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FACDISSEM_JOB_LOG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4306 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SEQ_FACDISSEM_JOB_LOG" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Sequence SEQ_FACDISSEM_USER_ACTIVITY
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FACDISSEM_USER_ACTIVITY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10967 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SEQ_FACDISSEM_USER_ACTIVITY" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Sequence SEQ_FEDERALAGENCYLOOKUP
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FEDERALAGENCYLOOKUP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 73 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SEQ_FEDERALAGENCYLOOKUP" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table CFDALOOKUP
--------------------------------------------------------

  CREATE TABLE "CFDALOOKUP" 
   (	"ID" NUMBER(12,0), 
	"FEDERALPROGRAMNAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"CFDAPREFIX" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"CFDAEXT" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "CFDALOOKUP" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "CFDALOOKUP" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "CFDALOOKUP" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "CFDALOOKUP" TO "FACDISSEM_READER";
  GRANT SELECT ON "CFDALOOKUP" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "CFDALOOKUP" TO "FACDISSEM_APP";
  GRANT INSERT ON "CFDALOOKUP" TO "FACDISSEM_APP";
  GRANT SELECT ON "CFDALOOKUP" TO "FACDISSEM_APP";
  GRANT UPDATE ON "CFDALOOKUP" TO "FACDISSEM_APP";
  GRANT DELETE ON "CFDALOOKUP" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "CFDALOOKUP" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "CFDALOOKUP" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "CFDALOOKUP" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table CFDA_AGENCIES
--------------------------------------------------------

  CREATE TABLE "CFDA_AGENCIES" 
   (	"AGENCYNUM" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"AGENCYNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"I_9" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"III_9" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"III_10A" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT UPDATE ON "CFDA_AGENCIES" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "CFDA_AGENCIES" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "CFDA_AGENCIES" TO "FACDISSEM_SOURCE";
  GRANT DELETE ON "CFDA_AGENCIES" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "CFDA_AGENCIES" TO "FACDISSEM_APP";
  GRANT SELECT ON "CFDA_AGENCIES" TO "FACDISSEM_APP";
  GRANT INSERT ON "CFDA_AGENCIES" TO "FACDISSEM_APP";
  GRANT DELETE ON "CFDA_AGENCIES" TO "FACDISSEM_APP";
  GRANT UPDATE ON "CFDA_AGENCIES" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "CFDA_AGENCIES" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "CFDA_AGENCIES" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "CFDA_AGENCIES" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "CFDA_AGENCIES" TO "FACDISSEM_READER";
  GRANT DELETE ON "CFDA_AGENCIES" TO "FACDISSEM_APP2";
  GRANT INSERT ON "CFDA_AGENCIES" TO "FACDISSEM_APP2";
  GRANT SELECT ON "CFDA_AGENCIES" TO "FACDISSEM_APP2";
  GRANT UPDATE ON "CFDA_AGENCIES" TO "FACDISSEM_APP2";
--------------------------------------------------------
--  DDL for Table CLUSTERNAMELOOKUP
--------------------------------------------------------

  CREATE TABLE "CLUSTERNAMELOOKUP" 
   (	"ID" NUMBER(12,0), 
	"NAME" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP", 
	"SORT_NUM" NUMBER(4,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP";
  GRANT DELETE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP";
  GRANT INSERT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP";
  GRANT UPDATE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP";
  GRANT DELETE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP2";
  GRANT INSERT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP2";
  GRANT SELECT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP2";
  GRANT UPDATE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_APP2";
  GRANT SELECT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_READER";
  GRANT DELETE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_SOURCE";
  GRANT DELETE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "CLUSTERNAMELOOKUP" TO "FACDISSEM_UPDATER";
--------------------------------------------------------
--  DDL for Table ELECAUDITFINDINGS
--------------------------------------------------------

  CREATE TABLE "ELECAUDITFINDINGS" 
   (	"ELECAUDITFINDINGSID" NUMBER, 
	"QCOSTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"OTHERFINDINGS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SIGNIFICANTDEFICIENCY" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"OTHERNONCOMPLIANCE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREQUIREMENT" VARCHAR2(16 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTID" NUMBER, 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"VERSION" NUMBER(2,0), 
	"ELECAUDITSID" NUMBER, 
	"MODIFIEDOPINION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"REPEATFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIORFINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "ELECAUDITFINDINGS" TO "FACDISSEM_READER";
  GRANT DELETE ON "ELECAUDITFINDINGS" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECAUDITFINDINGS" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECAUDITFINDINGS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECAUDITFINDINGS" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECAUDITFINDINGS" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECAUDITFINDINGS" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECAUDITFINDINGS" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECAUDITFINDINGS" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECAUDITFINDINGS" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECAUDITFINDINGS" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECAUDITFINDINGS" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECAUDITFINDINGS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECAUDITHEADER
--------------------------------------------------------

  CREATE TABLE "ELECAUDITHEADER" 
   (	"ID" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"FYENDDATE" DATE, 
	"AUDITTYPE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PERIODCOVERED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"NUMBERMONTHS" NUMBER(2,0), 
	"MULTIPLEEINS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"EINSUBCODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEDUNS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"DUNS" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEENAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"STREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"STREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEECONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEETITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEDATESIGNED" DATE, 
	"AUDITEENAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAFIRMNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CPACITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"CPACONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CPATITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"CPADATESIGNED" DATE, 
	"CPANAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"COG_OVER" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"COGAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREPORT_FS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTABLECONDITION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MATERIALNONCOMPLIANCE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"GOINGCONCERN" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREPORT_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DOLLARTHRESHOLD" NUMBER(12,0), 
	"LOWRISK" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTREQUIRED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTFEDEXPEND" NUMBER(14,0), 
	"COPIES" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTABLECONDITION_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MATERIALWEAKNESS_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"QCOSTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CYFINDINGS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PYSCHEDULE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"DUP_REPORTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"COG_AGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"OVERSIGHTAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"DATERECEIVED" DATE, 
	"DATEFIREWALL" DATE, 
	"PREVIOUSDATEFIREWALL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGREFNUM" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEOFENTITY" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"IMAGE" NUMBER(1,0), 
	"AGENCYCFDA" VARCHAR2(198 BYTE) COLLATE "USING_NLS_COMP", 
	"INITIALDATE" DATE, 
	"DATERECEIVEDOTHER" DATE, 
	"MULTIPLE_CPAS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEECERTIFYNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEECERTIFYTITLE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FACACCEPTEDDATE" DATE, 
	"AUDITOR_EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"ELECAUDITHEADERID" NUMBER, 
	"SD_MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SD_MATERIALWEAKNESS_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SIGNIFICANTDEFICIENCY" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SIGNIFICANTDEFICIENCY_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SP_FRAMEWORK" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"SP_FRAMEWORK_REQUIRED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREPORT_SP_FRAMEWORK" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPRESSION_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"ENTITY_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEAUDIT_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"FYSTARTDATE" DATE, 
	"CPAFOREIGN" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CPACOUNTRY" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"OPEID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DATETOED" DATE, 
	"DATEFINISHED" DATE, 
	"TYPEFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEFUNDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "ELECAUDITHEADER" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECAUDITHEADER" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECAUDITHEADER" TO "FACDISSEM_SOURCE";
  GRANT DELETE ON "ELECAUDITHEADER" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECAUDITHEADER" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECAUDITHEADER" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECAUDITHEADER" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECAUDITHEADER" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECAUDITHEADER" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECAUDITHEADER" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECAUDITHEADER" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECAUDITHEADER" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECAUDITHEADER" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECAUDITHEADER3049
--------------------------------------------------------

  CREATE TABLE "ELECAUDITHEADER3049" 
   (	"ID" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"FYENDDATE" DATE, 
	"AUDITTYPE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PERIODCOVERED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"NUMBERMONTHS" NUMBER, 
	"MULTIPLEEINS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"EINSUBCODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEENAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"STREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"STREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"ZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEECONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEETITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEEDATESIGNED" DATE, 
	"AUDITEENAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAFIRMNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CPACITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"CPACONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CPATITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"CPADATESIGNED" DATE, 
	"CPANAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"COG_OVER" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"COGAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREPORT_FS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTABLECONDITION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MATERIALNONCOMPLIANCE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"GOINGCONCERN" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREPORT_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DOLLARTHRESHOLD" NUMBER, 
	"LOWRISK" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTREQUIRED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTFEDEXPEND" NUMBER, 
	"COPIES" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTABLECONDITION_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MATERIALWEAKNESS_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"QCOSTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CYFINDINGS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PYSCHEDULE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"DUP_REPORTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"COG_AGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"OVERSIGHTAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"DATERECEIVED" DATE, 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "ELECAUDITHEADER3049" TO "FACDISSEM_READER";
  GRANT DELETE ON "ELECAUDITHEADER3049" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECAUDITHEADER3049" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECAUDITHEADER3049" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECAUDITHEADER3049" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECAUDITHEADER3049" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECAUDITHEADER3049" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECAUDITHEADER3049" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECAUDITHEADER3049" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECAUDITHEADER3049" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECAUDITHEADER3049" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECAUDITHEADER3049" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECAUDITHEADER3049" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECAUDITHEADER_IMS
--------------------------------------------------------

  CREATE TABLE "ELECAUDITHEADER_IMS" 
   (	"ID" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP", 
	"ID2" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEAUDIT_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPRESSION_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTID" NUMBER(6,0), 
	"VERSION" NUMBER(2,0), 
	"IMAGE_EXISTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_READER";
  GRANT DELETE ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECAUDITHEADER_IMS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECAUDITS
--------------------------------------------------------

  CREATE TABLE "ELECAUDITS" 
   (	"ID" VARCHAR2(84 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"CFDASEQNUM" NUMBER(7,0), 
	"CFDA" VARCHAR2(53 BYTE) COLLATE "USING_NLS_COMP", 
	"FEDERALPROGRAMNAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"AMOUNT" NUMBER(12,0), 
	"MAJORPROGRAM" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREQUIREMENT" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"QCOSTS2" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGS" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"RD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"DIRECT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CFDA_PREFIX" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"CFDA_EXT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"CFDA2" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREPORT_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPEREPORT_MP_OVERRIDE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ARRA" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"LOANS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"ELECAUDITSID" NUMBER, 
	"FINDINGSCOUNT" NUMBER(7,0), 
	"LOANBALANCE" NUMBER(12,0), 
	"PASSTHROUGHAMOUNT" NUMBER(12,0), 
	"AWARDIDENTIFICATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CLUSTERNAME" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSTHROUGHAWARD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"STATECLUSTERNAME" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP", 
	"PROGRAMTOTAL" NUMBER(12,0), 
	"CLUSTERTOTAL" NUMBER(12,0), 
	"OTHERCLUSTERNAME" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP", 
	"CFDAPROGRAMNAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "ELECAUDITS" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECAUDITS" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECAUDITS" TO "FACDISSEM_SOURCE";
  GRANT DELETE ON "ELECAUDITS" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECAUDITS" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECAUDITS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECAUDITS" TO "CTXSYS";
  GRANT SELECT ON "ELECAUDITS" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECAUDITS" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECAUDITS" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECAUDITS" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECAUDITS" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECAUDITS" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECAUDITS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECCAPTEXT
--------------------------------------------------------

  CREATE TABLE "ELECCAPTEXT" 
   (	"SEQ_NUMBER" NUMBER, 
	"REPORTID" NUMBER(12,0), 
	"VERSION" NUMBER(2,0), 
	"DBKEY" NUMBER(12,0), 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEXT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARTSTABLES" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "ELECCAPTEXT" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECCAPTEXT" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECCAPTEXT" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECCAPTEXT" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECCAPTEXT" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECCAPTEXT" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECCAPTEXT" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECCAPTEXT" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECCAPTEXT" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECCAPTEXT" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECCAPTEXT" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECCAPTEXT" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECCAPTEXT" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECCPAS
--------------------------------------------------------

  CREATE TABLE "ELECCPAS" 
   (	"ID" VARCHAR2(84 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"SEQNUM" NUMBER(4,0), 
	"VERSION" NUMBER(2,0), 
	"CPAFIRMNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP", 
	"CPACITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CPASTATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"CPACONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CPATITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"CPAEIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT UPDATE ON "ELECCPAS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECCPAS" TO "FACDISSEM_READER";
  GRANT DELETE ON "ELECCPAS" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECCPAS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECCPAS" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECCPAS" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECCPAS" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECCPAS" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECCPAS" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECCPAS" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECCPAS" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECCPAS" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECCPAS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECEINS
--------------------------------------------------------

  CREATE TABLE "ELECEINS" 
   (	"ID" VARCHAR2(54 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"EINSEQNUM" NUMBER, 
	"DUNS" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"DUNSEQNUM" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "ELECEINS" TO "FACDISSEM_READER";
  GRANT DELETE ON "ELECEINS" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECEINS" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECEINS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECEINS" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECEINS" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECEINS" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECEINS" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECEINS" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECEINS" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECEINS" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECEINS" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECEINS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECFINDINGSTEXT
--------------------------------------------------------

  CREATE TABLE "ELECFINDINGSTEXT" 
   (	"SEQ_NUMBER" NUMBER, 
	"REPORTID" NUMBER(12,0), 
	"VERSION" NUMBER(2,0), 
	"DBKEY" NUMBER(12,0), 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEXT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARTSTABLES" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT INSERT ON "ELECFINDINGSTEXT" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECFINDINGSTEXT" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECFINDINGSTEXT" TO "FACDISSEM_READER";
  GRANT DELETE ON "ELECFINDINGSTEXT" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECFINDINGSTEXT" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECFINDINGSTEXT" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECFINDINGSTEXT" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECFINDINGSTEXT" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECFINDINGSTEXT" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECFINDINGSTEXT" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECFINDINGSTEXT" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECFINDINGSTEXT" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECFINDINGSTEXT" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECNOTES
--------------------------------------------------------

  CREATE TABLE "ELECNOTES" 
   (	"ID" NUMBER, 
	"REPORTID" NUMBER(12,0), 
	"VERSION" NUMBER(2,0), 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(12,0), 
	"SEQ_NUMBER" NUMBER(4,0), 
	"TYPE_ID" NUMBER(12,0), 
	"NOTE_INDEX" NUMBER(4,0), 
	"TITLE" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "ELECNOTES" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECNOTES" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECNOTES" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECNOTES" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECNOTES" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECNOTES" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECNOTES" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECNOTES" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECNOTES" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECNOTES" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECNOTES" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECNOTES" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECNOTES" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECPASSTHROUGH
--------------------------------------------------------

  CREATE TABLE "ELECPASSTHROUGH" 
   (	"ID" NUMBER(12,0), 
	"DBKEY" NUMBER(6,0), 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"ELECAUDITSID" NUMBER, 
	"PASSTHROUGHNAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSTHROUGHID" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "ELECPASSTHROUGH" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECPASSTHROUGH" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECPASSTHROUGH" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECPASSTHROUGH" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECPASSTHROUGH" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECPASSTHROUGH" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECPASSTHROUGH" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECPASSTHROUGH" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECPASSTHROUGH" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECPASSTHROUGH" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECPASSTHROUGH" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECPASSTHROUGH" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECPASSTHROUGH" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECREPORTSAGENCY
--------------------------------------------------------

  CREATE TABLE "ELECREPORTSAGENCY" 
   (	"ID" VARCHAR2(46 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0), 
	"AGENCYCFDA" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"PYAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIORFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENTFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT SELECT ON "ELECREPORTSAGENCY" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECREPORTSAGENCY" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECREPORTSAGENCY" TO "FACDISSEM_SOURCE";
  GRANT DELETE ON "ELECREPORTSAGENCY" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECREPORTSAGENCY" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECREPORTSAGENCY" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECREPORTSAGENCY" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECREPORTSAGENCY" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECREPORTSAGENCY" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECREPORTSAGENCY" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECREPORTSAGENCY" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECREPORTSAGENCY" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECREPORTSAGENCY" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECRPT_REVISIONS
--------------------------------------------------------

  CREATE TABLE "ELECRPT_REVISIONS" 
   (	"ELECRPTREVISIONID" NUMBER, 
	"REPORTID" NUMBER(12,0), 
	"VERSION" NUMBER(2,0), 
	"DBKEY" NUMBER(12,0), 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"GENINFO" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP", 
	"GENINFO_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"FEDERALAWARDS" VARCHAR2(140 CHAR) COLLATE "USING_NLS_COMP", 
	"FEDERALAWARDS_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTESTOSEFA" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP", 
	"NOTESTOSEFA_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITINFO" VARCHAR2(200 CHAR) COLLATE "USING_NLS_COMP", 
	"AUDITINFO_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGS" VARCHAR2(110 CHAR) COLLATE "USING_NLS_COMP", 
	"FINDINGS_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"FINDINGSTEXT" VARCHAR2(6 CHAR) COLLATE "USING_NLS_COMP", 
	"FINDINGSTEXT_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"CAP" VARCHAR2(6 CHAR) COLLATE "USING_NLS_COMP", 
	"CAP_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"OTHER" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP", 
	"OTHER_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "ELECRPT_REVISIONS" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECRPT_REVISIONS" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECRPT_REVISIONS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECRPT_REVISIONS" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECRPT_REVISIONS" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECRPT_REVISIONS" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECRPT_REVISIONS" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECRPT_REVISIONS" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECRPT_REVISIONS" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECRPT_REVISIONS" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECRPT_REVISIONS" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECRPT_REVISIONS" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECRPT_REVISIONS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table ELECUEIS
--------------------------------------------------------

  CREATE TABLE "ELECUEIS" 
   (	"UEISID" NUMBER, 
	"REPORTID" NUMBER(12,0), 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"VERSION" NUMBER(2,0), 
	"UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"SEQNUM" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DBKEY" NUMBER(6,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "ELECUEIS" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "ELECUEIS" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "ELECUEIS" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "ELECUEIS" TO "FACDISSEM_READER";
  GRANT SELECT ON "ELECUEIS" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "ELECUEIS" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "ELECUEIS" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "ELECUEIS" TO "FACDISSEM_APP";
  GRANT INSERT ON "ELECUEIS" TO "FACDISSEM_APP";
  GRANT SELECT ON "ELECUEIS" TO "FACDISSEM_APP";
  GRANT UPDATE ON "ELECUEIS" TO "FACDISSEM_APP";
  GRANT DELETE ON "ELECUEIS" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "ELECUEIS" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for Table FEDERALAGENCYLOOKUP
--------------------------------------------------------

  CREATE TABLE "FEDERALAGENCYLOOKUP" 
   (	"ID" NUMBER(12,0), 
	"CFDAPREFIX" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"ACRONYM" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"STARTEXT" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"ENDEXT" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP";
  GRANT INSERT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP";
  GRANT SELECT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP";
  GRANT UPDATE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP";
  GRANT SELECT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_READER";
  GRANT DELETE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_SOURCE";
  GRANT DELETE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP2";
  GRANT INSERT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP2";
  GRANT SELECT ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP2";
  GRANT UPDATE ON "FEDERALAGENCYLOOKUP" TO "FACDISSEM_APP2";
--------------------------------------------------------
--  DDL for Table IDES_SHISTORY
--------------------------------------------------------

  CREATE TABLE "IDES_SHISTORY" 
   (	"ID" VARCHAR2(84 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTID" NUMBER(12,0), 
	"DBKEY" NUMBER(6,0), 
	"VERSION" NUMBER(2,0), 
	"FINAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDIT_UPLOAD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEE_SUBMIT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEE_SUBMIT_DATE" DATE, 
	"AUDITOR_SUBMIT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITOR_SUBMIT_DATE" DATE, 
	"FAC_SUBMIT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"FAC_SUBMIT_DATE" DATE, 
	"CREATED" DATE, 
	"DATEMODIFIED" DATE, 
	"SH_MODDATE" DATE, 
	"AUDIT_UPLOAD_DATE" DATE, 
	"EMAIL_SENT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_SENT_DATE" DATE, 
	"AUDITEE_REJECT_DATE" DATE, 
	"AUDITOR_REJECT_DATE" DATE, 
	"AUDITEE_IDES_EMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"CPA_IDES_EMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"NEW_AUDIT_UPLOAD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AUDITEE_RESENT_DATE" DATE, 
	"AUDITOR_RESENT_DATE" DATE, 
	"AUDITEE_SIG_CODE" NUMBER(12,0), 
	"AUDITOR_SIG_CODE" NUMBER(12,0), 
	"SUBMITTED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  GRANT DELETE ON "IDES_SHISTORY" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "IDES_SHISTORY" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "IDES_SHISTORY" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "IDES_SHISTORY" TO "FACDISSEM_READER";
  GRANT SELECT ON "IDES_SHISTORY" TO "FACDISSEM_UPDATER";
  GRANT DELETE ON "IDES_SHISTORY" TO "FACDISSEM_APP";
  GRANT INSERT ON "IDES_SHISTORY" TO "FACDISSEM_APP";
  GRANT SELECT ON "IDES_SHISTORY" TO "FACDISSEM_APP";
  GRANT UPDATE ON "IDES_SHISTORY" TO "FACDISSEM_APP";
  GRANT DELETE ON "IDES_SHISTORY" TO "FACDISSEM_SOURCE";
  GRANT INSERT ON "IDES_SHISTORY" TO "FACDISSEM_SOURCE";
  GRANT SELECT ON "IDES_SHISTORY" TO "FACDISSEM_SOURCE";
  GRANT UPDATE ON "IDES_SHISTORY" TO "FACDISSEM_SOURCE";
--------------------------------------------------------
--  DDL for View COG2016_2020
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COG2016_2020" ("DBKEY", "EIN", "AUDITEENAME", "COGAGENCY", "DATE_ADDED") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT DBKEY,
             EIN2016_2020                                  AS EIN,
             AUDITEENAME2016_2020                          AS AUDITEENAME,
             COGAGENCY2016_2020,
             TO_DATE (DATEADDED2016_2020, 'DD-MON-YY')     AS DATE_ADDED
        FROM FACDISSEM_OWNER.COGREFLIST
       WHERE     EIN2016_2020 IS NOT NULL
             AND AUDITEENAME2016_2020 IS NOT NULL
             AND COGAGENCY2016_2020 IS NOT NULL
             AND DATEADDED2016_2020 IS NOT NULL
    ORDER BY COGAGENCY2016_2020, DBKEY
;
  GRANT DELETE ON "COG2016_2020" TO "FACDISSEM_READER";
  GRANT INSERT ON "COG2016_2020" TO "FACDISSEM_READER";
  GRANT DELETE ON "COG2016_2020" TO "FACDISSEM_APP";
  GRANT INSERT ON "COG2016_2020" TO "FACDISSEM_APP";
  GRANT SELECT ON "COG2016_2020" TO "FACDISSEM_APP";
  GRANT UPDATE ON "COG2016_2020" TO "FACDISSEM_APP";
  GRANT SELECT ON "COG2016_2020" TO "FACDISSEM_READER";
  GRANT UPDATE ON "COG2016_2020" TO "FACDISSEM_READER";
  GRANT DELETE ON "COG2016_2020" TO "FACDISSEM_UPDATER";
  GRANT INSERT ON "COG2016_2020" TO "FACDISSEM_UPDATER";
  GRANT SELECT ON "COG2016_2020" TO "FACDISSEM_UPDATER";
  GRANT UPDATE ON "COG2016_2020" TO "FACDISSEM_UPDATER";
--------------------------------------------------------
--  DDL for View COG2021_2025
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COG2021_2025" ("DBKEY", "EIN", "AUDITEENAME", "COGAGENCY", "DATE_ADDED", "UEI") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT DBKEY,
             EIN2021_2025                                  AS EIN,
             AUDITEENAME2021_2025                          AS AUDITEENAME,
             COGAGENCY2021_2025,
             TO_DATE (DATEADDED2021_2025, 'DD-MON-YY')     AS DATE_ADDED,
             UEI2021_2025                                  AS UEI
        FROM FACDISSEM_OWNER.COGREFLIST
       WHERE     EIN2021_2025 IS NOT NULL
             AND AUDITEENAME2021_2025 IS NOT NULL
             AND COGAGENCY2021_2025 IS NOT NULL
             AND DATEADDED2021_2025 IS NOT NULL
    ORDER BY COGAGENCY2021_2025, DBKEY
;
  GRANT DELETE ON "COG2021_2025" TO "FACDISSEM_READER";
  GRANT INSERT ON "COG2021_2025" TO "FACDISSEM_READER";
  GRANT SELECT ON "COG2021_2025" TO "FACDISSEM_READER";
  GRANT UPDATE ON "COG2021_2025" TO "FACDISSEM_READER";
  GRANT DELETE ON "COG2021_2025" TO "FACDISSEM_APP";
  GRANT INSERT ON "COG2021_2025" TO "FACDISSEM_APP";
  GRANT SELECT ON "COG2021_2025" TO "FACDISSEM_APP";
  GRANT UPDATE ON "COG2021_2025" TO "FACDISSEM_APP";
--------------------------------------------------------
--  DDL for View PRAVEEN_TEST
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "PRAVEEN_TEST" ("FINDINGTEXT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select SEQ_NUMBER||'|'||DBKEY||'|'||AUDITYEAR||'|'||FINDINGREFNUMS||'|'|| regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(TEXT,CHR(10),''),CHR(11),''),CHR(13),''),CHR(9),''), '  ','')||'|'CHARTSTABLES from  facdissem_owner.elecfindingstext where audityear = '2019' order by seq_number
;
--------------------------------------------------------
--  DDL for View V_ELECCAPTEXT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "V_ELECCAPTEXT" ("SEQ_NUMBER", "REPORTID", "VERSION", "DBKEY", "AUDITYEAR", "FINDINGREFNUMS", "TEXT", "CHARTSTABLES") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT SEQ_NUMBER,
          REPORTID,
          VERSION,
          a.DBKEY,
          a.AUDITYEAR,
          FINDINGREFNUMS,
          CASE
             WHEN SUPPRESSION_CODE = 'IT' THEN 'Exemption for Indian Tribes.'
             ELSE TEXT
          END
             TEXT,
          CHARTSTABLES
     FROM eleccaptext a, elecstatuscontrol b, elecauditheader c
    WHERE     (a.audityear = b.audityear AND b.audityear = c.audityear)
          AND (a.dbkey = b.dbkey AND b.dbkey = c.dbkey)
          AND b.sflag >= 50
;
  GRANT SELECT ON "V_ELECCAPTEXT" TO "FACDISSEM_READER";
--------------------------------------------------------
--  DDL for View V_ELECFINDINGSTEXT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "V_ELECFINDINGSTEXT" ("SEQ_NUMBER", "REPORTID", "VERSION", "DBKEY", "AUDITYEAR", "FINDINGREFNUMS", "TEXT", "CHARTSTABLES") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT SEQ_NUMBER,
          REPORTID,
          VERSION,
          a.DBKEY,
          a.AUDITYEAR,
          FINDINGREFNUMS,
          CASE
             WHEN SUPPRESSION_CODE = 'IT' THEN 'Exemption for Indian Tribes.'
             ELSE TEXT
          END
             TEXT,
          CHARTSTABLES
     FROM elecfindingstext a, elecstatuscontrol b, elecauditheader c
    WHERE     (a.audityear = b.audityear AND b.audityear = c.audityear)
          AND (a.dbkey = b.dbkey AND b.dbkey = c.dbkey)
          AND b.sflag >= 50
;
  GRANT SELECT ON "V_ELECFINDINGSTEXT" TO "FACDISSEM_READER";
--------------------------------------------------------
--  DDL for View V_ELECNOTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "V_ELECNOTES" ("ID", "REPORTID", "VERSION", "AUDITYEAR", "DBKEY", "SEQ_NUMBER", "TYPE_ID", "NOTE_INDEX", "TITLE", "CONTENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT a.ID,
          REPORTID,
          VERSION,
          a.AUDITYEAR,
          a.DBKEY,
          SEQ_NUMBER,
          TYPE_ID,
          NOTE_INDEX,
          TITLE,
          CASE
             WHEN SUPPRESSION_CODE = 'IT' THEN 'Exemption for Indian Tribes.'
             ELSE CONTENT
          END
             content
     FROM elecnotes a,
          elecstatuscontrol b,
          elecauditheader c
    WHERE     (a.audityear = b.audityear AND b.audityear = c.audityear)
          AND (a.dbkey = b.dbkey AND b.dbkey = c.dbkey)
          AND b.sflag >= 50
;
  GRANT SELECT ON "V_ELECNOTES" TO "FACDISSEM_READER";
--------------------------------------------------------
--  DDL for Index CFDA_AGENCIES_AGENCYNUMKEY
--------------------------------------------------------

  CREATE INDEX "CFDA_AGENCIES_AGENCYNUMKEY" ON "CFDA_AGENCIES" ("AGENCYNUM") 
  ;
--------------------------------------------------------
--  DDL for Index PK_CLUSTERNAMELOOKUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CLUSTERNAMELOOKUP" ON "CLUSTERNAMELOOKUP" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITFINDINGS_ID2KEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITFINDINGS_ID2KEY" ON "ELECAUDITFINDINGS" ("ELECAUDITSID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITFINDINGS_IDKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELECAUDITFINDINGS_IDKEY" ON "ELECAUDITFINDINGS" ("ELECAUDITFINDINGSID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITFINDINGS_REPORTID
--------------------------------------------------------

  CREATE INDEX "ELECAUDITFINDINGS_REPORTID" ON "ELECAUDITFINDINGS" ("REPORTID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITFINDINGS_AUDITYEAR
--------------------------------------------------------

  CREATE INDEX "ELECAUDITFINDINGS_AUDITYEAR" ON "ELECAUDITFINDINGS" ("AUDITYEAR") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_DBKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_DBKEY" ON "ELECAUDITHEADER" ("DBKEY") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_STKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_STKEY" ON "ELECAUDITHEADER" ("STATE") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_IDKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELECAUDITHEADER_IDKEY" ON "ELECAUDITHEADER" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_EINKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_EINKEY" ON "ELECAUDITHEADER" ("EIN") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_AUDITYEAR
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_AUDITYEAR" ON "ELECAUDITHEADER" ("AUDITYEAR") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_NAMEKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_NAMEKEY" ON "ELECAUDITHEADER" ("AUDITEENAME") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER3049_NAMEKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER3049_NAMEKEY" ON "ELECAUDITHEADER3049" ("AUDITEENAME") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER3049_DBKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER3049_DBKEY" ON "ELECAUDITHEADER3049" ("DBKEY") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER3049_IDKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER3049_IDKEY" ON "ELECAUDITHEADER3049" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER3049_STKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER3049_STKEY" ON "ELECAUDITHEADER3049" ("STATE") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER3049_EINKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER3049_EINKEY" ON "ELECAUDITHEADER3049" ("EIN") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER3049_AUDITYEAR
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER3049_AUDITYEAR" ON "ELECAUDITHEADER3049" ("AUDITYEAR") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_IMS_AUDITYEAR
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_IMS_AUDITYEAR" ON "ELECAUDITHEADER_IMS" ("AUDITYEAR") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_IMS_DBKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_IMS_DBKEY" ON "ELECAUDITHEADER_IMS" ("DBKEY") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_IMS_IDX
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_IMS_IDX" ON "ELECAUDITHEADER_IMS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITHEADER_IMS_REPORTID
--------------------------------------------------------

  CREATE INDEX "ELECAUDITHEADER_IMS_REPORTID" ON "ELECAUDITHEADER_IMS" ("REPORTID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITS_AUDITYEARKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITS_AUDITYEARKEY" ON "ELECAUDITS" ("AUDITYEAR") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITS_CFDAKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITS_CFDAKEY" ON "ELECAUDITS" ("CFDA") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITS_DBKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITS_DBKEY" ON "ELECAUDITS" ("DBKEY") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELECAUDITS_PK" ON "ELECAUDITS" ("ELECAUDITSID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITS_CFDA2KEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITS_CFDA2KEY" ON "ELECAUDITS" ("CFDA2") 
  ;
--------------------------------------------------------
--  DDL for Index ELECAUDITS_IDKEY
--------------------------------------------------------

  CREATE INDEX "ELECAUDITS_IDKEY" ON "ELECAUDITS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECCPAS_IDKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELECCPAS_IDKEY" ON "ELECCPAS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECCPAS_DBKEY
--------------------------------------------------------

  CREATE INDEX "ELECCPAS_DBKEY" ON "ELECCPAS" ("DBKEY") 
  ;
--------------------------------------------------------
--  DDL for Index ELECEINS_AUDITYEAR
--------------------------------------------------------

  CREATE INDEX "ELECEINS_AUDITYEAR" ON "ELECEINS" ("AUDITYEAR") 
  ;
--------------------------------------------------------
--  DDL for Index ELECEINS_EIN
--------------------------------------------------------

  CREATE INDEX "ELECEINS_EIN" ON "ELECEINS" ("EIN") 
  ;
--------------------------------------------------------
--  DDL for Index ELECEINS_IDKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELECEINS_IDKEY" ON "ELECEINS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECEINS_DBKEY
--------------------------------------------------------

  CREATE INDEX "ELECEINS_DBKEY" ON "ELECEINS" ("DBKEY") 
  ;
--------------------------------------------------------
--  DDL for Index ELECPASSTHROUGH_IDX0
--------------------------------------------------------

  CREATE INDEX "ELECPASSTHROUGH_IDX0" ON "ELECPASSTHROUGH" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECPASSTHROUGH_IDX1
--------------------------------------------------------

  CREATE INDEX "ELECPASSTHROUGH_IDX1" ON "ELECPASSTHROUGH" ("ELECAUDITSID") 
  ;
--------------------------------------------------------
--  DDL for Index ELECPASSTHROUGH_IDX2
--------------------------------------------------------

  CREATE INDEX "ELECPASSTHROUGH_IDX2" ON "ELECPASSTHROUGH" ("DBKEY", "AUDITYEAR") 
  ;
--------------------------------------------------------
--  DDL for Index ELECREPORTSAGENCY_IDKEY
--------------------------------------------------------

  CREATE INDEX "ELECREPORTSAGENCY_IDKEY" ON "ELECREPORTSAGENCY" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index ELEC_DBKEY_YEAR_CFDA
--------------------------------------------------------

  CREATE INDEX "ELEC_DBKEY_YEAR_CFDA" ON "ELECREPORTSAGENCY" ("AUDITYEAR", "DBKEY", "AGENCYCFDA") 
  ;
--------------------------------------------------------
--  DDL for Index ELECREPORTSAGENCY_DBKEY
--------------------------------------------------------

  CREATE INDEX "ELECREPORTSAGENCY_DBKEY" ON "ELECREPORTSAGENCY" ("DBKEY") 
  ;
--------------------------------------------------------
--  DDL for Index PK_FEDERALAGENCYLOOKUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FEDERALAGENCYLOOKUP" ON "FEDERALAGENCYLOOKUP" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index IDES_SHISTORY_IDKEY
--------------------------------------------------------

  CREATE INDEX "IDES_SHISTORY_IDKEY" ON "IDES_SHISTORY" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Trigger RG_INS_FEDERALAGENCYLOOKUP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "RG_INS_FEDERALAGENCYLOOKUP" 
        BEFORE INSERT ON FACDISSEM_OWNER.FEDERALAGENCYLOOKUP 
        FOR EACH ROW
BEGIN
              SELECT FACDISSEM_OWNER.SEQ_FEDERALAGENCYLOOKUP.NEXTVAL
              INTO   :new.id
              FROM   dual;
           END;

/
ALTER TRIGGER "RG_INS_FEDERALAGENCYLOOKUP" ENABLE;
--------------------------------------------------------
--  Constraints for Table CFDALOOKUP
--------------------------------------------------------

  ALTER TABLE "CFDALOOKUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CFDALOOKUP" MODIFY ("FEDERALPROGRAMNAME" NOT NULL ENABLE);
  ALTER TABLE "CFDALOOKUP" MODIFY ("CFDAPREFIX" NOT NULL ENABLE);
  ALTER TABLE "CFDALOOKUP" MODIFY ("CFDAEXT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLUSTERNAMELOOKUP
--------------------------------------------------------

  ALTER TABLE "CLUSTERNAMELOOKUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLUSTERNAMELOOKUP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CLUSTERNAMELOOKUP" ADD CONSTRAINT "PK_CLUSTERNAMELOOKUP" PRIMARY KEY ("ID")
  USING INDEX "PK_CLUSTERNAMELOOKUP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELECAUDITFINDINGS
--------------------------------------------------------

  ALTER TABLE "ELECAUDITFINDINGS" ADD CONSTRAINT "ELECAUDITFINDINGS_ID_PK" PRIMARY KEY ("ELECAUDITFINDINGSID")
  USING INDEX "ELECAUDITFINDINGS_IDKEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELECAUDITHEADER
--------------------------------------------------------

  ALTER TABLE "ELECAUDITHEADER" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECAUDITHEADER" MODIFY ("DBKEY" NOT NULL ENABLE);
  ALTER TABLE "ELECAUDITHEADER" ADD CONSTRAINT "ELECAUDITHEADER_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "ELECAUDITHEADER_IDKEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELECAUDITHEADER_IMS
--------------------------------------------------------

  ALTER TABLE "ELECAUDITHEADER_IMS" MODIFY ("DBKEY" NOT NULL ENABLE);
  ALTER TABLE "ELECAUDITHEADER_IMS" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECAUDITS
--------------------------------------------------------

  ALTER TABLE "ELECAUDITS" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECAUDITS" MODIFY ("DBKEY" NOT NULL ENABLE);
  ALTER TABLE "ELECAUDITS" MODIFY ("CFDASEQNUM" NOT NULL ENABLE);
  ALTER TABLE "ELECAUDITS" ADD CONSTRAINT "ELECAUDITS_PK" PRIMARY KEY ("ELECAUDITSID")
  USING INDEX "ELECAUDITS_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELECCAPTEXT
--------------------------------------------------------

  ALTER TABLE "ELECCAPTEXT" MODIFY ("SEQ_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ELECCAPTEXT" MODIFY ("REPORTID" NOT NULL ENABLE);
  ALTER TABLE "ELECCAPTEXT" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ELECCAPTEXT" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECCAPTEXT" MODIFY ("CHARTSTABLES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECCPAS
--------------------------------------------------------

  ALTER TABLE "ELECCPAS" ADD CONSTRAINT "ELECCPAS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "ELECCPAS_IDKEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELECEINS
--------------------------------------------------------

  ALTER TABLE "ELECEINS" ADD CONSTRAINT "ELECEINS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "ELECEINS_IDKEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELECFINDINGSTEXT
--------------------------------------------------------

  ALTER TABLE "ELECFINDINGSTEXT" MODIFY ("SEQ_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ELECFINDINGSTEXT" MODIFY ("REPORTID" NOT NULL ENABLE);
  ALTER TABLE "ELECFINDINGSTEXT" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ELECFINDINGSTEXT" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECFINDINGSTEXT" MODIFY ("CHARTSTABLES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECNOTES
--------------------------------------------------------

  ALTER TABLE "ELECNOTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ELECNOTES" MODIFY ("REPORTID" NOT NULL ENABLE);
  ALTER TABLE "ELECNOTES" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ELECNOTES" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECNOTES" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ELECNOTES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ELECNOTES" MODIFY ("CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECPASSTHROUGH
--------------------------------------------------------

  ALTER TABLE "ELECPASSTHROUGH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ELECPASSTHROUGH" MODIFY ("DBKEY" NOT NULL ENABLE);
  ALTER TABLE "ELECPASSTHROUGH" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECPASSTHROUGH" MODIFY ("ELECAUDITSID" NOT NULL ENABLE);
  ALTER TABLE "ELECPASSTHROUGH" MODIFY ("PASSTHROUGHNAME" NOT NULL ENABLE);
  ALTER TABLE "ELECPASSTHROUGH" MODIFY ("PASSTHROUGHID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECREPORTSAGENCY
--------------------------------------------------------

  ALTER TABLE "ELECREPORTSAGENCY" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECREPORTSAGENCY" MODIFY ("DBKEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECRPT_REVISIONS
--------------------------------------------------------

  ALTER TABLE "ELECRPT_REVISIONS" MODIFY ("ELECRPTREVISIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECUEIS
--------------------------------------------------------

  ALTER TABLE "ELECUEIS" MODIFY ("UEISID" NOT NULL ENABLE);
  ALTER TABLE "ELECUEIS" MODIFY ("REPORTID" NOT NULL ENABLE);
  ALTER TABLE "ELECUEIS" MODIFY ("AUDITYEAR" NOT NULL ENABLE);
  ALTER TABLE "ELECUEIS" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ELECUEIS" MODIFY ("UEI" NOT NULL ENABLE);
  ALTER TABLE "ELECUEIS" MODIFY ("SEQNUM" NOT NULL ENABLE);
  ALTER TABLE "ELECUEIS" MODIFY ("DBKEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FEDERALAGENCYLOOKUP
--------------------------------------------------------

  ALTER TABLE "FEDERALAGENCYLOOKUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FEDERALAGENCYLOOKUP" MODIFY ("CFDAPREFIX" NOT NULL ENABLE);
  ALTER TABLE "FEDERALAGENCYLOOKUP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "FEDERALAGENCYLOOKUP" MODIFY ("ACRONYM" NOT NULL ENABLE);
  ALTER TABLE "FEDERALAGENCYLOOKUP" ADD CONSTRAINT "PK_FEDERALAGENCYLOOKUP" PRIMARY KEY ("ID")
  USING INDEX "PK_FEDERALAGENCYLOOKUP"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ELECAUDITFINDINGS
--------------------------------------------------------

  ALTER TABLE "ELECAUDITFINDINGS" ADD CONSTRAINT "FK_FINDINGS_ELECAUDITS" FOREIGN KEY ("ELECAUDITSID")
	  REFERENCES "ELECAUDITS" ("ELECAUDITSID") ENABLE;
