---
applications:
  - name: gsa-fac
    buildpacks:
      - python_buildpack
    memory: 512M
    path: ../
    timeout: 180
    env:
      ENV: PRODUCTION
      DJANGO_BASE_URL: https://fac-prod.app.cloud.gov
      ALLOWED_HOSTS: fac-prod.app.cloud.gov
      AV_SCAN_URL: https://fac-av-production.apps.internal:61443/scan
    routes:
      - route: fac-prod.app.cloud.gov
    instances: 2
    services:
      - fac-db
      - fac-public-s3
      - fac-key-service
      - production-deployer

  - name: postgrest
    instances: 2
    disk_quota: 256M
    memory: 128M
    timeout: 180
    docker:
      image: postgrest/postgrest:v10.1.2
    routes:
      - route: fac-prod-postgrest.app.cloud.gov
    env:
      PGRST_DB_URI: ((DB_URI))
      PGRST_DB_ANON_ROLE: anon

  - name: swagger
    instances: 2
    disk_quota: 256M
    memory: 256M
    timeout: 20
    health-check-type: process
    docker:
      image: swaggerapi/swagger-ui
    routes:
      - route: fac-prod-swagger.app.cloud.gov
    env:
      API_URL: https://fac-prod-postgrest.app.cloud.gov
      SWAGGER_JSON_URL: https://fac-prod-postgrest.app.cloud.gov/
    port: 8080
