---
applications:
  - name: swagger
    instances: 2
    disk_quota: 256M
    memory: 256M
    timeout: 20
    health-check-type: process
    docker:
      image: swaggerapi/swagger-ui
    routes:
      - route: fac-prod-swagger.app.cloud.gov
    env:
      API_URL: https://fac-prod-postgrest.app.cloud.gov
      SWAGGER_JSON_URL: https://fac-prod-postgrest.app.cloud.gov/
    port: 8080