from django.db import models


class ELECAUDITHEADER(models.Model):
    ID = models.CharField(max_length=40)
    AUDITYEAR = models.CharField(max_length=40)
    DBKEY = models.IntegerField()
    FYENDDATE = models.DateField()
    AUDITTYPE = models.CharField(max_length=40)
    PERIODCOVERED = models.CharField(max_length=40)
    models.IntegerField()
    MULTIPLEEINS = models.CharField(max_length=40)
    EIN = models.CharField(max_length=40)
    EINSUBCODE = models.CharField(max_length=40)
    MULTIPLEDUNS = models.CharField(max_length=40)
    DUNS = models.CharField(max_length=40)
    AUDITEENAME = models.CharField(max_length=40)
    STREET1 = models.CharField(max_length=40)
    STREET2 = models.CharField(max_length=40)
    CITY = models.CharField(max_length=40)
    STATE = models.CharField(max_length=40)
    ZIPCODE = models.CharField(max_length=40)
    AUDITEECONTACT = models.CharField(max_length=40)
    AUDITEETITLE = models.CharField(max_length=40)
    AUDITEEPHONE = models.CharField(max_length=40)
    AUDITEEFAX = models.CharField(max_length=40)
    AUDITEEEMAIL = models.CharField(max_length=40)
    AUDITEEDATESIGNED = models.DateField()
    AUDITEENAMETITLE = models.CharField(max_length=40)
    CPAFIRMNAME = models.CharField(max_length=40)
    CPASTREET1 = models.CharField(max_length=40)
    CPASTREET2 = models.CharField(max_length=40)
    CPACITY = models.CharField(max_length=40)
    CPASTATE = models.CharField(max_length=40)
    CPAZIPCODE = models.CharField(max_length=40)
    CPACONTACT = models.CharField(max_length=40)
    CPATITLE = models.CharField(max_length=40)
    CPAPHONE = models.CharField(max_length=40)
    CPAFAX = models.CharField(max_length=40)
    CPAEMAIL = models.CharField(max_length=40)
    CPADATESIGNED = models.DateField()
    CPANAMETITLE = models.CharField(max_length=40)
    COG_OVER = models.CharField(max_length=40)
    COGAGENCY = models.CharField(max_length=40)
    TYPEREPORT_FS = models.CharField(max_length=40)
    REPORTABLECONDITION = models.CharField(max_length=40)
    MATERIALWEAKNESS = models.CharField(max_length=40)
    MATERIALNONCOMPLIANCE = models.CharField(max_length=2)
    GOINGCONCERN = models.CharField(max_length=40)
    TYPEREPORT_MP = models.CharField(max_length=40)
    DOLLARTHRESHOLD = models.IntegerField()
    LOWRISK = models.CharField(max_length=2)
    REPORTREQUIRED = models.CharField(max_length=2)
    TOTFEDEXPEND = models.IntegerField()
    COPIES = models.CharField(max_length=40)
    REPORTABLECONDITION_MP = models.CharField(max_length=2)
    MATERIALWEAKNESS_MP = models.CharField(max_length=40)
    QCOSTS = models.CharField(max_length=2)
    CYFINDINGS = models.CharField(max_length=2)
    PYSCHEDULE = models.CharField(max_length=2)
    DUP_REPORTS = models.CharField(max_length=2)
    COG_AGENCY = models.CharField(max_length=2)
    OVERSIGHTAGENCY = models.CharField(max_length=2)
    DATERECEIVED = models.DateField()
    DATEFIREWALL = models.DateField()
    PREVIOUSDATEFIREWALL = models.CharField(max_length=40)
    FINDINGREFNUM = models.CharField(max_length=40)
    TYPEOFENTITY = models.CharField(max_length=40)
    IMAGE = models.IntegerField()
    AGENCYCFDA = models.CharField(max_length=40)
    INITIALDATE = models.DateField()
    DATERECEIVEDOTHER = models.DateField()
    MULTIPLE_CPAS = models.CharField(max_length=40)
    AUDITEECERTIFYNAME = models.CharField(max_length=40)
    AUDITEECERTIFYTITLE = models.CharField(max_length=40)
    FACACCEPTEDDATE = models.DateField()
    AUDITOR_EIN = models.CharField(max_length=40)
    ELECAUDITHEADERID = models.IntegerField()
    SD_MATERIALWEAKNESS = models.CharField(max_length=40)
    SD_MATERIALWEAKNESS_MP = models.CharField(max_length=40)
    SIGNIFICANTDEFICIENCY = models.CharField(max_length=40)
    SIGNIFICANTDEFICIENCY_MP = models.CharField(max_length=40)
    SP_FRAMEWORK = models.CharField(max_length=40)
    SP_FRAMEWORK_REQUIRED = models.CharField(max_length=40)
    TYPEREPORT_SP_FRAMEWORK = models.CharField(max_length=40)
    SUPPRESSION_CODE = models.CharField(max_length=40)
    ENTITY_TYPE = models.CharField(max_length=40)
    TYPEAUDIT_CODE = models.CharField(max_length=40)
    FYSTARTDATE = models.DateField()
    CPAFOREIGN = models.CharField(max_length=40)
    CPACOUNTRY = models.CharField(max_length=40)
    UEI = models.CharField(max_length=40)
    MULTIPLEUEIS = models.CharField(max_length=40)
    OPEID = models.CharField(max_length=40)
    DATETOED = models.DateField()
    DATEFINISHED = models.DateField()
    TYPEFINDING = models.CharField(max_length=2)
    TYPEFUNDING = models.CharField(max_length=2)

class ELECAUDITS(models.Model):
    ID = models.CharField(max_length=40)
    AUDITYEAR = models.CharField(max_length=40)
    DBKEY = models.IntegerField()
    CFDASEQNUM = models.IntegerField()
    CFDA =  models.CharField(max_length=2)
    FEDERALPROGRAMNAME= models.CharField(max_length=255)
    AMOUNT = models.IntegerField()
    MAJORPROGRAM = models.CharField(max_length=40) 
    TYPEREQUIREMENT = models.CharField(max_length=40)
    QCOSTS2 = models.CharField(max_length=40)
    FINDINGS =models.CharField(max_length=40)
    FINDINGREFNUMS = models.CharField(max_length=255)
    RD = models.CharField(max_length=2)
    DIRECT = models.CharField(max_length=2)
    CFDA_PREFIX = models.CharField(max_length=4)
    CFDA_EXT = models.CharField(max_length=4)
    EIN = models.CharField(max_length=40)
    CFDA2 = models.CharField(max_length=2)
    TYPEREPORT_MP = models.CharField(max_length=2)
    TYPEREPORT_MP_OVERRIDE = models.CharField(max_length=2)
    ARRA = models.CharField(max_length=40) 
    LOANS = models.CharField(max_length=2) 
    ELECAUDITSID =models.IntegerField()
    FINDINGSCOUNT =models.IntegerField()
    LOANBALANCE =models.IntegerField()
    PASSTHROUGHAMOUNT =models.IntegerField()
    AWARDIDENTIFICATION = models.CharField(max_length=255)
    CLUSTERNAME = models.CharField(max_length=255)
    PASSTHROUGHAWARD = models.CharField(max_length=4)
    STATECLUSTERNAME = models.CharField(max_length=255)
    PROGRAMTOTAL = models.IntegerField()
    CLUSTERTOTAL = models.IntegerField()
    OTHERCLUSTERNAME = models.CharField(max_length=255)
    CFDAPROGRAMNAME = models.CharField(max_length=255)
    UEI = models.CharField(max_length=40)
    MULTIPLEUEIS = models.CharField(max_length=2)
