app_name: gsa-fac
mem_amount: 512M
cf_env_name: STAGING
env_name: staging
service_name: staging
endpoint: fac-staging.app.cloud.gov
instances: 1
services:
  - fac-db
  - fac-public-s3
  - fac-private-s3
  - fac-key-service
  - newrelic-creds
  - https-proxy-creds
  - smtp-proxy-creds
  - fac-logdrain
