@api_user_id = 61ba59b2-f545-4c2f-9b24-9655c706a06c
# @api_user_id = 1e2845a0-c844-4a6f-84ac-f398b58ce7c9
@scheme = http
@api_url = localhost:3000
# @scheme = https
# @api_url = api-preview.fac.gov

###
GET {{scheme}}://{{api_url}}/general?limit=1
// Have to use the JWT when testing locally.
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}  
x-api-key: {{$processEnv API_GOV_KEY}}


###
GET {{scheme}}://{{api_url}}/audit_access
// Have to use the JWT and API UUID when testing locally.
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}  
x-api-user-id: {{api_user_id}}
x-api-key: {{$processEnv API_GOV_KEY}} 
accept-profile: admin_api_v1_1_0

###
GET {{scheme}}://{{api_url}}/singleauditchecklist
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}     
x-api-user-id: {{api_user_id}}
accept-profile: admin_api_v1_1_0
x-api-key: {{$processEnv API_GOV_KEY}}   

###
// This should list everything using a view.
GET {{scheme}}://{{api_url}}/tribal_access
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}     
x-api-user-id: {{api_user_id}}
accept-profile: admin_api_v1_1_0
x-api-key: {{$processEnv API_GOV_KEY}}   


###
// Call the RPC to add access
POST {{scheme}}://{{api_url}}/rpc/add_tribal_access_email
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
x-api-user-id: {{api_user_id}}
content-profile: admin_api_v1_1_0
content-type: application/json 
Prefer: params=single-object
x-api-key: {{$processEnv API_GOV_KEY}}   

{
    "email": "darth.vader@deathstar.gsa.gov"
}

### 
// Call the RPC to remove access
POST {{scheme}}://{{api_url}}/rpc/add_tribal_access_emails
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
x-api-user-id: {{api_user_id}}
content-profile: admin_api_v1_1_0
content-type: application/json 
Prefer: params=single-object
x-api-key: {{$processEnv API_GOV_KEY}}   

{
    "emails": [
        "darth.vader@deathstar.gsa.gov",
        "bob.darth.vader@deathstar.gsa.gov",
        "darthy.vader@deathstar.gsa.gov",
        "bob@deathstar.gsa.gov"
    ]
}

### 
// Call the RPC to remove access
POST {{scheme}}://{{api_url}}/rpc/remove_tribal_access_email
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
x-api-user-id: {{api_user_id}}
content-profile: admin_api_v1_1_0
content-type: application/json 
Prefer: params=single-object
x-api-key: {{$processEnv API_GOV_KEY}}   

{
    "email": "darth.vader@deathstar.gsa.gov"
}


### 
// Call the RPC to remove access
POST {{scheme}}://{{api_url}}/rpc/remove_tribal_access_emails
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
x-api-user-id: {{api_user_id}}
content-profile: admin_api_v1_1_0
content-type: application/json 
Prefer: params=single-object
x-api-key: {{$processEnv API_GOV_KEY}}   

{
    "emails": [
        "darth.vader@deathstar.gsa.gov",
        "bob.darth.vader@deathstar.gsa.gov",
        "darthy.vader@deathstar.gsa.gov",
        "bob@deathstar.gsa.gov"
    ]
}


###
// This should list everything using a view.
GET {{scheme}}://{{api_url}}/admin_api_events
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}     
x-api-user-id: {{api_user_id}}
accept-profile: admin_api_v1_1_0
x-api-key: {{$processEnv API_GOV_KEY}}   

