name: Reusable deploy

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy to
    if: github.event.ref == 'refs/heads/main'
    needs: [linting, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: @actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Update service keys
        uses: 18f/cg-deploy-action@main
        env:
          SAM_API_KEY: ${{ secrets.SAM_API_KEY }}
          DJANGO_SECRET_LOGIN_KEY: $${{ secrets.DJANGO_SECRET_LOGIN_KEY }}
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-tts-oros-fac
          cf_space: dev
          full_command: 'cf update-user-provided-service fac-key-service -p "{\"SAM_API_KEY\":\"$SAM_API_KEY\", \"DJANGO_SECRET_LOGIN_KEY\":\"$DJANGO_SECRET_LOGIN_KEY\"}"'

      - name: Deploy to cloud.gov
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-tts-oros-fac
          cf_space: dev
          push_arguments: "-f backend/manifests/manifest-dev.yml --strategy rolling"
