--------------------------------------------------------
--  DDL for Table CFDALOOKUP
--------------------------------------------------------
CREATE TABLE "CFDALOOKUP" (
    "ID" NUMBER(12, 0),
    "FEDERALPROGRAMNAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP",
    "CFDAPREFIX" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "CFDAEXT" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table CFDA_AGENCIES
--------------------------------------------------------
CREATE TABLE "CFDA_AGENCIES" (
    "AGENCYNUM" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "AGENCYNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP",
    "I_9" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "III_9" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "III_10A" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table CLUSTERNAMELOOKUP
--------------------------------------------------------
CREATE TABLE "CLUSTERNAMELOOKUP" (
    "ID" NUMBER(12, 0),
    "NAME" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP",
    "SORT_NUM" NUMBER(4, 0)
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECAUDITFINDINGS
--------------------------------------------------------

CREATE TABLE "ELECAUDITFINDINGS" (
    "ELECAUDITFINDINGSID" NUMBER,
    "ELECAUDITSID" NUMBER,
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "REPORTID" NUMBER,
    "VERSION" NUMBER(2, 0),
    "QCOSTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "OTHERFINDINGS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "SIGNIFICANTDEFICIENCY" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "OTHERNONCOMPLIANCE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREQUIREMENT" VARCHAR2(16 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP",
    "MODIFIEDOPINION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "REPEATFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "PRIORFINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECAUDITHEADER
--------------------------------------------------------
CREATE TABLE "ELECAUDITHEADER" (
    "ELECAUDITHEADERID" NUMBER,
    "ID" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "FYENDDATE" DATE,
    "AUDITTYPE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "PERIODCOVERED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "NUMBERMONTHS" NUMBER(2, 0),
    "MULTIPLEEINS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "EINSUBCODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP",
    "MULTIPLEDUNS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "DUNS" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEENAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
    "STREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "STREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "CITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
    "STATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "ZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEECONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEETITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEDATESIGNED" DATE,
    "AUDITEENAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
    "CPAFIRMNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "CPACITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "CPAZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "CPACONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "CPATITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP",
    "CPAPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "CPAFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "CPAEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP",
    "CPADATESIGNED" DATE,
    "CPANAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
    "COG_OVER" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "COGAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREPORT_FS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTABLECONDITION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "MATERIALNONCOMPLIANCE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "GOINGCONCERN" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREPORT_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DOLLARTHRESHOLD" NUMBER(12, 0),
    "LOWRISK" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTREQUIRED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TOTFEDEXPEND" NUMBER(14, 0),
    "COPIES" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTABLECONDITION_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "MATERIALWEAKNESS_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "QCOSTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "CYFINDINGS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "PYSCHEDULE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "DUP_REPORTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "COG_AGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "OVERSIGHTAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "DATERECEIVED" DATE,
    "DATEFIREWALL" DATE,
    "PREVIOUSDATEFIREWALL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGREFNUM" CHAR(1 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEOFENTITY" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP",
    "IMAGE" NUMBER(1, 0),
    "AGENCYCFDA" VARCHAR2(198 BYTE) COLLATE "USING_NLS_COMP",
    "INITIALDATE" DATE,
    "DATERECEIVEDOTHER" DATE,
    "MULTIPLE_CPAS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEECERTIFYNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEECERTIFYTITLE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "FACACCEPTEDDATE" DATE,
    "AUDITOR_EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "SD_MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "SD_MATERIALWEAKNESS_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "SIGNIFICANTDEFICIENCY" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "SIGNIFICANTDEFICIENCY_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "SP_FRAMEWORK" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP",
    "SP_FRAMEWORK_REQUIRED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREPORT_SP_FRAMEWORK" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP",
    "SUPPRESSION_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "ENTITY_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEAUDIT_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "OPEID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP",
    "DATETOED" DATE,
    "DATEFINISHED" DATE,
    "TYPEFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEFUNDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "FYSTARTDATE" DATE,
    "CPAFOREIGN" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP",
    "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "CPACOUNTRY" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";


--------------------------------------------------------
--  DDL for Table ELECAUDITHEADER3049
--------------------------------------------------------
CREATE TABLE "ELECAUDITHEADER3049" (
    "ID" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "FYENDDATE" DATE,
    "AUDITTYPE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "PERIODCOVERED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "NUMBERMONTHS" NUMBER,
    "MULTIPLEEINS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "EINSUBCODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEENAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
    "STREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "STREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "CITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
    "STATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "ZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEECONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEETITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEEDATESIGNED" DATE,
    "AUDITEENAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
    "CPAFIRMNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTREET2" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "CPACITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "CPAZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "CPACONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "CPATITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP",
    "CPAPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "CPAFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "CPAEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP",
    "CPADATESIGNED" DATE,
    "CPANAMETITLE" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
    "COG_OVER" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "COGAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREPORT_FS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTABLECONDITION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "MATERIALWEAKNESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "MATERIALNONCOMPLIANCE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "GOINGCONCERN" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREPORT_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DOLLARTHRESHOLD" NUMBER,
    "LOWRISK" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTREQUIRED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TOTFEDEXPEND" NUMBER,
    "COPIES" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTABLECONDITION_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "MATERIALWEAKNESS_MP" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "QCOSTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "CYFINDINGS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "PYSCHEDULE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "DUP_REPORTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "COG_AGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "OVERSIGHTAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "DATERECEIVED" DATE,
    "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECAUDITHEADER_IMS
--------------------------------------------------------
CREATE TABLE "ELECAUDITHEADER_IMS" (
    "ID" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP",
    "ID2" VARCHAR2(44 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTID" NUMBER(6, 0),
    "VERSION" NUMBER(2, 0),
    "TYPEAUDIT_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "SUPPRESSION_CODE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "IMAGE_EXISTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";


--------------------------------------------------------
--  DDL for Table ELECAUDITS
--------------------------------------------------------
CREATE TABLE "ELECAUDITS" (
    "ELECAUDITSID" NUMBER,
    "ID" VARCHAR2(84 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "CFDASEQNUM" NUMBER(7, 0),
    "CFDA" VARCHAR2(53 BYTE) COLLATE "USING_NLS_COMP",
    "FEDERALPROGRAMNAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP",
    "AMOUNT" NUMBER(12, 0),
    "MAJORPROGRAM" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREQUIREMENT" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP",
    "QCOSTS2" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGS" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP",
    "RD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "DIRECT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "CFDA_PREFIX" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "CFDA_EXT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "CFDA2" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREPORT_MP" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "TYPEREPORT_MP_OVERRIDE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "ARRA" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "LOANS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGSCOUNT" NUMBER(7, 0),
    "LOANBALANCE" NUMBER(12, 0),
    "PASSTHROUGHAMOUNT" NUMBER(12, 0),
    "AWARDIDENTIFICATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "CLUSTERNAME" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP",
    "PASSTHROUGHAWARD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "STATECLUSTERNAME" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP",
    "PROGRAMTOTAL" NUMBER(12, 0),
    "CLUSTERTOTAL" NUMBER(12, 0),
    "OTHERCLUSTERNAME" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP",
    "CFDAPROGRAMNAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP"
    -- "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    -- "MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECCAPTEXT
--------------------------------------------------------

CREATE TABLE "ELECCAPTEXT" (
    "SEQ_NUMBER" NUMBER,
    "DBKEY" NUMBER(12, 0),
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP",
    "TEXT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP",
    "CHARTSTABLES" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTID" NUMBER(12, 0),
    "VERSION" NUMBER(2, 0),
    "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECCPAS
--------------------------------------------------------
CREATE TABLE "ELECCPAS" (
    "ID" VARCHAR2(84 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "SEQNUM" NUMBER(4, 0),
    "VERSION" NUMBER(2, 0),
    "CPAFIRMNAME" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTREET1" VARCHAR2(45 BYTE) COLLATE "USING_NLS_COMP",
    "CPACITY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP",
    "CPASTATE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "CPAZIPCODE" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "CPACONTACT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP",
    "CPATITLE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP",
    "CPAPHONE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "CPAFAX" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP",
    "CPAEMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP",
    "CPAEIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECEINS
--------------------------------------------------------
CREATE TABLE "ELECEINS" (
    "ID" VARCHAR2(54 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "EINSEQNUM" NUMBER,
    "DUNS" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "DUNSEQNUM" NUMBER
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECFINDINGSTEXT
--------------------------------------------------------
-- SEQ_NUMBER,DBKEY,AUDITYEAR,FINDINGREFNUMS,TEXT,CHARTSTABLES,REPORTID,VERSION,UEI,MULTIPLEUEIS

CREATE TABLE "ELECFINDINGSTEXT" (
    "SEQ_NUMBER" NUMBER,
    "DBKEY" NUMBER(12, 0),
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGREFNUMS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP",
    "TEXT" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP",
    "CHARTSTABLES" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTID" NUMBER(12, 0),
    "VERSION" NUMBER(2, 0),
    "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECNOTES
--------------------------------------------------------
CREATE TABLE "ELECNOTES" (
    "ID" NUMBER,
    "REPORTID" NUMBER(12, 0),
    "VERSION" NUMBER(2, 0),
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(12, 0),
    "SEQ_NUMBER" NUMBER(4, 0),
    "TYPE_ID" NUMBER(12, 0),
    "NOTE_INDEX" NUMBER(4, 0),
    "TITLE" VARCHAR2(75 BYTE) COLLATE "USING_NLS_COMP",
    "CONTENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP",
    "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECPASSTHROUGH
--------------------------------------------------------
CREATE TABLE "ELECPASSTHROUGH" (
    "ID" NUMBER(12, 0),
    "DBKEY" NUMBER(6, 0),
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "ELECAUDITSID" NUMBER,
    "PASSTHROUGHNAME" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP",
    "PASSTHROUGHID" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECREPORTSAGENCY
--------------------------------------------------------
CREATE TABLE "ELECREPORTSAGENCY" (
    "ID" VARCHAR2(46 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0),
    "AGENCYCFDA" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "EIN" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP",
    "PYAGENCY" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "PRIORFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "CURRENTFINDING" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "MULTIPLEUEIS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECRPT_REVISIONS
--------------------------------------------------------

CREATE TABLE "ELECRPT_REVISIONS" (
    "ELECRPTREVISIONID" NUMBER,
    "DBKEY" NUMBER(12, 0),
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "GENINFO" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP",
    "GENINFO_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "FEDERALAWARDS" VARCHAR2(140 CHAR) COLLATE "USING_NLS_COMP",
    "FEDERALAWARDS_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "NOTESTOSEFA" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP",
    "NOTESTOSEFA_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITINFO" VARCHAR2(200 CHAR) COLLATE "USING_NLS_COMP",
    "AUDITINFO_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGS" VARCHAR2(110 CHAR) COLLATE "USING_NLS_COMP",
    "FINDINGS_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "FINDINGSTEXT" VARCHAR2(6 CHAR) COLLATE "USING_NLS_COMP",
    "FINDINGSTEXT_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "CAP" VARCHAR2(6 CHAR) COLLATE "USING_NLS_COMP",
    "CAP_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "OTHER" VARCHAR2(75 CHAR) COLLATE "USING_NLS_COMP",
    "OTHER_EXPLAIN" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTID" NUMBER(12, 0),
    "VERSION" NUMBER(2, 0)
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table ELECUEIS
--------------------------------------------------------
CREATE TABLE "ELECUEIS" (
    "UEISID" NUMBER,
    "REPORTID" NUMBER(12, 0),
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "VERSION" NUMBER(2, 0),
    "UEI" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP",
    "SEQNUM" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "DBKEY" NUMBER(6, 0)
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table FEDERALAGENCYLOOKUP
--------------------------------------------------------
CREATE TABLE "FEDERALAGENCYLOOKUP" (
    "ID" NUMBER(12, 0),
    "CFDAPREFIX" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP",
    "NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP",
    "ACRONYM" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP",
    "STARTEXT" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP",
    "ENDEXT" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

--------------------------------------------------------
--  DDL for Table IDES_SHISTORY
--------------------------------------------------------
CREATE TABLE "IDES_SHISTORY" (
    "ID" VARCHAR2(84 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITYEAR" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP",
    "REPORTID" NUMBER(12, 0),
    "DBKEY" NUMBER(6, 0),
    "VERSION" NUMBER(2, 0),
    "FINAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "AUDIT_UPLOAD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEE_SUBMIT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEE_SUBMIT_DATE" DATE,
    "AUDITOR_SUBMIT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITOR_SUBMIT_DATE" DATE,
    "FAC_SUBMIT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "FAC_SUBMIT_DATE" DATE,
    "CREATED" DATE,
    "DATEMODIFIED" DATE,
    "SH_MODDATE" DATE,
    "AUDIT_UPLOAD_DATE" DATE,
    "EMAIL_SENT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "EMAIL_SENT_DATE" DATE,
    "AUDITEE_REJECT_DATE" DATE,
    "AUDITOR_REJECT_DATE" DATE,
    "AUDITEE_IDES_EMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP",
    "CPA_IDES_EMAIL" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP",
    "NEW_AUDIT_UPLOAD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP",
    "AUDITEE_RESENT_DATE" DATE,
    "AUDITOR_RESENT_DATE" DATE,
    "AUDITEE_SIG_CODE" NUMBER(12, 0),
    "AUDITOR_SIG_CODE" NUMBER(12, 0),
    "SUBMITTED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP";

/*
--------------------------------------------------------
--  DDL for View COG2016_2020
--------------------------------------------------------
CREATE
OR REPLACE EDITIONABLE VIEW "COG2016_2020" (
    "DBKEY",
    "EIN",
    "AUDITEENAME",
    "COGAGENCY",
    "DATE_ADDED"
) DEFAULT COLLATION "USING_NLS_COMP" AS
SELECT
    DBKEY,
    EIN2016_2020 AS EIN,
    AUDITEENAME2016_2020 AS AUDITEENAME,
    COGAGENCY2016_2020,
    TO_DATE (DATEADDED2016_2020, 'DD-MON-YY') AS DATE_ADDED
FROM
    FACDISSEM_OWNER.COGREFLIST
WHERE
    EIN2016_2020 IS NOT NULL
    AND AUDITEENAME2016_2020 IS NOT NULL
    AND COGAGENCY2016_2020 IS NOT NULL
    AND DATEADDED2016_2020 IS NOT NULL
ORDER BY
    COGAGENCY2016_2020,
    DBKEY;

--------------------------------------------------------
--  DDL for View COG2021_2025
--------------------------------------------------------
CREATE
OR REPLACE EDITIONABLE VIEW "COG2021_2025" (
    "DBKEY",
    "EIN",
    "AUDITEENAME",
    "COGAGENCY",
    "DATE_ADDED",
    "UEI"
) DEFAULT COLLATION "USING_NLS_COMP" AS
SELECT
    DBKEY,
    EIN2021_2025 AS EIN,
    AUDITEENAME2021_2025 AS AUDITEENAME,
    COGAGENCY2021_2025,
    TO_DATE (DATEADDED2021_2025, 'DD-MON-YY') AS DATE_ADDED,
    UEI2021_2025 AS UEI
FROM
    FACDISSEM_OWNER.COGREFLIST
WHERE
    EIN2021_2025 IS NOT NULL
    AND AUDITEENAME2021_2025 IS NOT NULL
    AND COGAGENCY2021_2025 IS NOT NULL
    AND DATEADDED2021_2025 IS NOT NULL
ORDER BY
    COGAGENCY2021_2025,
    DBKEY;
*/

/* 

--------------------------------------------------------
--  DDL for View V_ELECCAPTEXT
--------------------------------------------------------
CREATE
OR REPLACE EDITIONABLE VIEW "V_ELECCAPTEXT" (
    "SEQ_NUMBER",
    "REPORTID",
    "VERSION",
    "DBKEY",
    "AUDITYEAR",
    "FINDINGREFNUMS",
    "TEXT",
    "CHARTSTABLES"
) DEFAULT COLLATION "USING_NLS_COMP" AS
SELECT
    SEQ_NUMBER,
    REPORTID,
    VERSION,
    a.DBKEY,
    a.AUDITYEAR,
    FINDINGREFNUMS,
    CASE
        WHEN SUPPRESSION_CODE = 'IT' THEN 'Exemption for Indian Tribes.'
        ELSE TEXT
    END TEXT,
    CHARTSTABLES
FROM
    eleccaptext a,
    elecstatuscontrol b,
    elecauditheader c
WHERE
    (
        a.audityear = b.audityear
        AND b.audityear = c.audityear
    )
    AND (
        a.dbkey = b.dbkey
        AND b.dbkey = c.dbkey
    )
    AND b.sflag >= 50;

--------------------------------------------------------
--  DDL for View V_ELECFINDINGSTEXT
--------------------------------------------------------
CREATE
OR REPLACE EDITIONABLE VIEW "V_ELECFINDINGSTEXT" (
    "SEQ_NUMBER",
    "REPORTID",
    "VERSION",
    "DBKEY",
    "AUDITYEAR",
    "FINDINGREFNUMS",
    "TEXT",
    "CHARTSTABLES"
) DEFAULT COLLATION "USING_NLS_COMP" AS
SELECT
    SEQ_NUMBER,
    REPORTID,
    VERSION,
    a.DBKEY,
    a.AUDITYEAR,
    FINDINGREFNUMS,
    CASE
        WHEN SUPPRESSION_CODE = 'IT' THEN 'Exemption for Indian Tribes.'
        ELSE TEXT
    END TEXT,
    CHARTSTABLES
FROM
    elecfindingstext a,
    elecstatuscontrol b,
    elecauditheader c
WHERE
    (
        a.audityear = b.audityear
        AND b.audityear = c.audityear
    )
    AND (
        a.dbkey = b.dbkey
        AND b.dbkey = c.dbkey
    )
    AND b.sflag >= 50;

--------------------------------------------------------
--  DDL for View V_ELECNOTES
--------------------------------------------------------
CREATE
OR REPLACE EDITIONABLE VIEW "V_ELECNOTES" (
    "ID",
    "REPORTID",
    "VERSION",
    "AUDITYEAR",
    "DBKEY",
    "SEQ_NUMBER",
    "TYPE_ID",
    "NOTE_INDEX",
    "TITLE",
    "CONTENT"
) DEFAULT COLLATION "USING_NLS_COMP" AS
SELECT
    a.ID,
    REPORTID,
    VERSION,
    a.AUDITYEAR,
    a.DBKEY,
    SEQ_NUMBER,
    TYPE_ID,
    NOTE_INDEX,
    TITLE,
    CASE
        WHEN SUPPRESSION_CODE = 'IT' THEN 'Exemption for Indian Tribes.'
        ELSE CONTENT
    END content
FROM
    elecnotes a,
    elecstatuscontrol b,
    elecauditheader c
WHERE
    (
        a.audityear = b.audityear
        AND b.audityear = c.audityear
    )
    AND (
        a.dbkey = b.dbkey
        AND b.dbkey = c.dbkey
    )
    AND b.sflag >= 50;
*/

/*
 --------------------------------------------------------
 --  Constraints for Table CFDALOOKUP
 --------------------------------------------------------
 ALTER TABLE
 "CFDALOOKUP"
 MODIFY
 ("ID" NOT NULL ENABLE);
 
 ALTER TABLE
 "CFDALOOKUP"
 MODIFY
 ("FEDERALPROGRAMNAME" NOT NULL ENABLE);
 
 ALTER TABLE
 "CFDALOOKUP"
 MODIFY
 ("CFDAPREFIX" NOT NULL ENABLE);
 
 ALTER TABLE
 "CFDALOOKUP"
 MODIFY
 ("CFDAEXT" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table CLUSTERNAMELOOKUP
 --------------------------------------------------------
 ALTER TABLE
 "CLUSTERNAMELOOKUP"
 MODIFY
 ("ID" NOT NULL ENABLE);
 
 ALTER TABLE
 "CLUSTERNAMELOOKUP"
 MODIFY
 ("NAME" NOT NULL ENABLE);
 
 ALTER TABLE
 "CLUSTERNAMELOOKUP"
 ADD
 CONSTRAINT "PK_CLUSTERNAMELOOKUP" PRIMARY KEY ("ID") USING INDEX "PK_CLUSTERNAMELOOKUP" ENABLE;
 
 --------------------------------------------------------
 --  Constraints for Table ELECAUDITFINDINGS
 --------------------------------------------------------
 ALTER TABLE
 "ELECAUDITFINDINGS"
 ADD
 CONSTRAINT "ELECAUDITFINDINGS_ID_PK" PRIMARY KEY ("ELECAUDITFINDINGSID") USING INDEX "ELECAUDITFINDINGS_IDKEY" ENABLE;
 
 --------------------------------------------------------
 --  Constraints for Table ELECAUDITHEADER
 --------------------------------------------------------
 ALTER TABLE
 "ELECAUDITHEADER"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECAUDITHEADER"
 MODIFY
 ("DBKEY" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECAUDITHEADER"
 ADD
 CONSTRAINT "ELECAUDITHEADER_ID_PK" PRIMARY KEY ("ID") USING INDEX "ELECAUDITHEADER_IDKEY" ENABLE;
 
 --------------------------------------------------------
 --  Constraints for Table ELECAUDITHEADER_IMS
 --------------------------------------------------------
 ALTER TABLE
 "ELECAUDITHEADER_IMS"
 MODIFY
 ("DBKEY" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECAUDITHEADER_IMS"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table ELECAUDITS
 --------------------------------------------------------
 ALTER TABLE
 "ELECAUDITS"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECAUDITS"
 MODIFY
 ("DBKEY" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECAUDITS"
 MODIFY
 ("CFDASEQNUM" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECAUDITS"
 ADD
 CONSTRAINT "ELECAUDITS_PK" PRIMARY KEY ("ELECAUDITSID") USING INDEX "ELECAUDITS_PK" ENABLE;
 
 --------------------------------------------------------
 --  Constraints for Table ELECCAPTEXT
 --------------------------------------------------------
 ALTER TABLE
 "ELECCAPTEXT"
 MODIFY
 ("SEQ_NUMBER" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECCAPTEXT"
 MODIFY
 ("REPORTID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECCAPTEXT"
 MODIFY
 ("VERSION" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECCAPTEXT"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECCAPTEXT"
 MODIFY
 ("CHARTSTABLES" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table ELECCPAS
 --------------------------------------------------------
 ALTER TABLE
 "ELECCPAS"
 ADD
 CONSTRAINT "ELECCPAS_ID_PK" PRIMARY KEY ("ID") USING INDEX "ELECCPAS_IDKEY" ENABLE;
 
 --------------------------------------------------------
 --  Constraints for Table ELECEINS
 --------------------------------------------------------
 ALTER TABLE
 "ELECEINS"
 ADD
 CONSTRAINT "ELECEINS_ID_PK" PRIMARY KEY ("ID") USING INDEX "ELECEINS_IDKEY" ENABLE;
 
 --------------------------------------------------------
 --  Constraints for Table ELECFINDINGSTEXT
 --------------------------------------------------------
 ALTER TABLE
 "ELECFINDINGSTEXT"
 MODIFY
 ("SEQ_NUMBER" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECFINDINGSTEXT"
 MODIFY
 ("REPORTID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECFINDINGSTEXT"
 MODIFY
 ("VERSION" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECFINDINGSTEXT"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECFINDINGSTEXT"
 MODIFY
 ("CHARTSTABLES" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table ELECNOTES
 --------------------------------------------------------
 ALTER TABLE
 "ELECNOTES"
 MODIFY
 ("ID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECNOTES"
 MODIFY
 ("REPORTID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECNOTES"
 MODIFY
 ("VERSION" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECNOTES"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECNOTES"
 MODIFY
 ("TYPE_ID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECNOTES"
 MODIFY
 ("TITLE" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECNOTES"
 MODIFY
 ("CONTENT" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table ELECPASSTHROUGH
 --------------------------------------------------------
 ALTER TABLE
 "ELECPASSTHROUGH"
 MODIFY
 ("ID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECPASSTHROUGH"
 MODIFY
 ("DBKEY" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECPASSTHROUGH"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECPASSTHROUGH"
 MODIFY
 ("ELECAUDITSID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECPASSTHROUGH"
 MODIFY
 ("PASSTHROUGHNAME" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECPASSTHROUGH"
 MODIFY
 ("PASSTHROUGHID" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table ELECREPORTSAGENCY
 --------------------------------------------------------
 ALTER TABLE
 "ELECREPORTSAGENCY"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECREPORTSAGENCY"
 MODIFY
 ("DBKEY" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table ELECRPT_REVISIONS
 --------------------------------------------------------
 ALTER TABLE
 "ELECRPT_REVISIONS"
 MODIFY
 ("ELECRPTREVISIONID" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table ELECUEIS
 --------------------------------------------------------
 ALTER TABLE
 "ELECUEIS"
 MODIFY
 ("UEISID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECUEIS"
 MODIFY
 ("REPORTID" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECUEIS"
 MODIFY
 ("AUDITYEAR" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECUEIS"
 MODIFY
 ("VERSION" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECUEIS"
 MODIFY
 ("UEI" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECUEIS"
 MODIFY
 ("SEQNUM" NOT NULL ENABLE);
 
 ALTER TABLE
 "ELECUEIS"
 MODIFY
 ("DBKEY" NOT NULL ENABLE);
 
 --------------------------------------------------------
 --  Constraints for Table FEDERALAGENCYLOOKUP
 --------------------------------------------------------
 ALTER TABLE
 "FEDERALAGENCYLOOKUP"
 MODIFY
 ("ID" NOT NULL ENABLE);
 
 ALTER TABLE
 "FEDERALAGENCYLOOKUP"
 MODIFY
 ("CFDAPREFIX" NOT NULL ENABLE);
 
 ALTER TABLE
 "FEDERALAGENCYLOOKUP"
 MODIFY
 ("NAME" NOT NULL ENABLE);
 
 ALTER TABLE
 "FEDERALAGENCYLOOKUP"
 MODIFY
 ("ACRONYM" NOT NULL ENABLE);
 
 ALTER TABLE
 "FEDERALAGENCYLOOKUP"
 ADD
 CONSTRAINT "PK_FEDERALAGENCYLOOKUP" PRIMARY KEY ("ID") USING INDEX "PK_FEDERALAGENCYLOOKUP" ENABLE;
 
 --------------------------------------------------------
 --  Ref Constraints for Table ELECAUDITFINDINGS
 --------------------------------------------------------
 ALTER TABLE
 "ELECAUDITFINDINGS"
 ADD
 CONSTRAINT "FK_FINDINGS_ELECAUDITS" FOREIGN KEY ("ELECAUDITSID") REFERENCES "ELECAUDITS" ("ELECAUDITSID") ENABLE;
 */