# Generated by Django 5.2.3 on 2026-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(verbose_name="Report ID")),
                (
                    "uei",
                    models.CharField(blank=True, null=True, verbose_name="Current UEI"),
                ),
                (
                    "ein",
                    models.CharField(blank=True, null=True, verbose_name="Current EIN"),
                ),
                (
                    "field_to_edit",
                    models.CharField(
                        choices=[("uei", "UEI"), ("ein", "EIN")],
                        default="uei",
                        verbose_name="Field To Edit",
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="New Value"),
                ),
                (
                    "editor_email",
                    models.EmailField(
                        max_length=254, null=True, verbose_name="Editor Email"
                    ),
                ),
                (
                    "edit_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Edit Timestamp"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edit Field Record",
                "verbose_name_plural": "Edit Field Record",
                "ordering": ["-edit_timestamp"],
            },
        ),
    ]
