# Generated by Django 5.2.3 on 2026-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editrecord",
            name="auditee_name",
            field=models.CharField(blank=True, null=True, verbose_name="Current name"),
        ),
        migrations.AlterField(
            model_name="editrecord",
            name="field_to_edit",
            field=models.CharField(
                choices=[("uei", "UEI"), ("ein", "EIN"), ("auditee_name", "Name")],
                default="auditee_uei",
                verbose_name="Field To Edit",
            ),
        ),
    ]
