# Generated by Django 5.2.3 on 2026-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0002_editrecord_auditee_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editrecord",
            name="auditee_name",
        ),
        migrations.RemoveField(
            model_name="editrecord",
            name="ein",
        ),
        migrations.RemoveField(
            model_name="editrecord",
            name="uei",
        ),
        migrations.AddField(
            model_name="editrecord",
            name="old_value",
            field=models.CharField(
                blank=True, null=True, verbose_name="Current Value To Change"
            ),
        ),
        migrations.AlterField(
            model_name="editrecord",
            name="field_to_edit",
            field=models.CharField(
                choices=[("uei", "UEI"), ("ein", "EIN"), ("auditee_name", "Name")],
                default="uei",
                verbose_name="Field To Edit",
            ),
        ),
    ]
