# Generated by Django 5.2.11 on 2026-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "curation",
            "0003_remove_editrecord_auditee_name_remove_editrecord_ein_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="editrecord",
            name="field_to_edit",
            field=models.CharField(
                choices=[
                    ("uei", "UEI"),
                    ("ein", "EIN"),
                    ("auditee_name", "Auditee Name"),
                ],
                default="uei",
                verbose_name="Field To Edit",
            ),
        ),
    ]
