# Generated by Django 4.2.3 on 2023-08-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SukCfda19",
            fields=[
                (
                    "index",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "audityear",
                    models.BigIntegerField(
                        blank=True, db_column="AUDITYEAR", null=True
                    ),
                ),
                (
                    "dbkey",
                    models.BigIntegerField(blank=True, db_column="DBKEY", null=True),
                ),
                ("ein", models.BigIntegerField(blank=True, db_column="EIN", null=True)),
                ("cfda", models.TextField(blank=True, db_column="CFDA", null=True)),
                (
                    "awardidentification",
                    models.TextField(
                        blank=True, db_column="AWARDIDENTIFICATION", null=True
                    ),
                ),
                ("rd", models.FloatField(blank=True, db_column="RD", null=True)),
                (
                    "federalprogramname",
                    models.TextField(
                        blank=True, db_column="FEDERALPROGRAMNAME", null=True
                    ),
                ),
                (
                    "amount",
                    models.FloatField(blank=True, db_column="AMOUNT", null=True),
                ),
                (
                    "clustername",
                    models.TextField(blank=True, db_column="CLUSTERNAME", null=True),
                ),
                (
                    "stateclustername",
                    models.TextField(
                        blank=True, db_column="STATECLUSTERNAME", null=True
                    ),
                ),
                (
                    "programtotal",
                    models.FloatField(blank=True, db_column="PROGRAMTOTAL", null=True),
                ),
                (
                    "clustertotal",
                    models.FloatField(blank=True, db_column="CLUSTERTOTAL", null=True),
                ),
                ("direct", models.TextField(blank=True, db_column="DIRECT", null=True)),
                (
                    "passthroughaward",
                    models.TextField(
                        blank=True, db_column="PASSTHROUGHAWARD", null=True
                    ),
                ),
                (
                    "passthroughamount",
                    models.FloatField(
                        blank=True, db_column="PASSTHROUGHAMOUNT", null=True
                    ),
                ),
                (
                    "majorprogram",
                    models.TextField(blank=True, db_column="MAJORPROGRAM", null=True),
                ),
                (
                    "typereport_mp",
                    models.TextField(blank=True, db_column="TYPEREPORT_MP", null=True),
                ),
                (
                    "typerequirement",
                    models.FloatField(
                        blank=True, db_column="TYPEREQUIREMENT", null=True
                    ),
                ),
                (
                    "qcosts2",
                    models.FloatField(blank=True, db_column="QCOSTS2", null=True),
                ),
                (
                    "findings",
                    models.FloatField(blank=True, db_column="FINDINGS", null=True),
                ),
                (
                    "findingrefnums",
                    models.FloatField(
                        blank=True, db_column="FINDINGREFNUMS", null=True
                    ),
                ),
                ("arra", models.FloatField(blank=True, db_column="ARRA", null=True)),
                ("loans", models.TextField(blank=True, db_column="LOANS", null=True)),
                (
                    "loanbalance",
                    models.FloatField(blank=True, db_column="LOANBALANCE", null=True),
                ),
                (
                    "findingscount",
                    models.FloatField(blank=True, db_column="FINDINGSCOUNT", null=True),
                ),
                (
                    "elecauditsid",
                    models.FloatField(blank=True, db_column="ELECAUDITSID", null=True),
                ),
                (
                    "otherclustername",
                    models.TextField(
                        blank=True, db_column="OTHERCLUSTERNAME", null=True
                    ),
                ),
                (
                    "cfdaprogramname",
                    models.TextField(
                        blank=True, db_column="CFDAPROGRAMNAME", null=True
                    ),
                ),
            ],
        ),
    ]
