# Generated by Django 4.2.3 on 2023-08-10 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census2019", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SukCfda19",
            new_name="Cfda19",
        ),
    ]
