# Generated by Django 4.2.3 on 2023-08-10 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census2019", "0002_rename_sukcfda19_cfda19"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cfda19",
            new_name="Cfda",
        ),
    ]
