from django.db import models
from .constants import REPORT_ID_FK_HELP_TEXT
from dissemination.models import docs


class FederalAward(models.Model):
    """Information about the federal award section of the form. References General"""

    # 20240125 - These are indices that would be used in our ALN search/annotation.
    # class Meta:
    #     indexes = [
    #         models.Index(fields=["report_id",]),
    #         # This is possibly redundant with the pairwise index?
    #         models.Index(fields=["federal_agency_prefix",]),
    #         models.Index(fields=["federal_agency_prefix", "federal_award_extension"]),
    #         models.Index(fields=[
    #             "report_id",
    #             "federal_agency_prefix",
    #             "findings_count"
    #             ]),
    #     ]
    HASH_FIELDS = [
        "report_id",
        "award_reference",
        "federal_agency_prefix",
        "federal_award_extension",
        "aln",
        "findings_count",
        "additional_award_identification",
        "federal_program_name",
        "amount_expended",
        "federal_program_total",
        "cluster_name",
        "state_cluster_name",
        "other_cluster_name",
        "cluster_total",
        "is_direct",
        "is_passthrough_award",
        "passthrough_amount",
        "is_major",
        "audit_report_type",
        "is_loan",
        "loan_balance",
    ]

    additional_award_identification = models.TextField(
        "Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
        help_text=docs.award_identification,
    )
    amount_expended = models.BigIntegerField(
        "Amount Expended for the Federal Program",
        help_text=docs.amount,
    )
    award_reference = models.TextField(
        "Order that the award line was reported",
    )
    cluster_name = models.TextField(
        "The name of the cluster",
        help_text=docs.cluster_name,
    )
    cluster_total = models.BigIntegerField(
        "Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
        help_text=docs.cluster_total,
    )
    federal_agency_prefix = models.TextField(
        "2-char code refers to an agency",
    )
    federal_award_extension = models.TextField(
        "3-digit extn for a program defined by the agency",
    )
    federal_program_name = models.TextField(
        "Name of Federal Program",
        help_text=docs.federal_program_name,
    )
    federal_program_total = models.BigIntegerField(
        "Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
        help_text=docs.program_total,
    )
    findings_count = models.IntegerField(
        "Number of findings for the federal program (only available for audit years 2013 and beyond)",
        help_text=docs.findings_count,
    )
    is_direct = models.TextField(
        "Indicate whether or not the award was received directly from a Federal awarding agency",
        help_text=docs.direct,
    )
    is_loan = models.TextField(
        "Indicate whether or not the program is a Loan or Loan Guarantee (only available for audit years 2013 and beyond)",
        help_text=docs.loans,
    )
    is_major = models.TextField(
        "Indicate whether or not the Federal program is a major program",
        help_text=docs.major_program,
    )
    is_passthrough_award = models.TextField(
        "Indicates whether or not funds were passed through to any subrecipients for the Federal program",
        help_text=docs.passthrough_award,
    )
    loan_balance = models.TextField(
        "The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
        help_text=docs.loan_balance,
    )
    audit_report_type = models.TextField(
        "Type of Report Issued on the Major Program Compliance",
        help_text=docs.type_report_major_program_cfdainfo,
    )
    other_cluster_name = models.TextField(
        "The name of the cluster (if not listed in the Compliance Supplement)",
        help_text=docs.other_cluster_name,
    )
    passthrough_amount = models.BigIntegerField(
        "Amount passed through to subrecipients",
        help_text=docs.passthrough_amount,
        null=True,
    )
    state_cluster_name = models.TextField(
        "The name of the state cluster",
        help_text=docs.state_cluster_name,
    )
    report_id = models.ForeignKey(
        "General",
        help_text=REPORT_ID_FK_HELP_TEXT,
        on_delete=models.CASCADE,
        to_field="report_id",
        db_column="report_id",
    )
    hash = models.CharField(
        help_text="A hash of the row",
        blank=True,
        null=True,
    )
