# This uses an env var called PG to 
# set the connection string.
source: PG
target: LOCAL

streams:

  public.dissemination_general.xlsx:
    mode: full-refresh
    target_options:
      format: xlsx
    object: file:///tmp/sling/dg.xlsx
    sql: |
      SELECT * from public.dissemination_general
      WHERE is_public = true

  public.dissemination_general.csv:
    mode: full-refresh
    object: file:///tmp/sling/dg.csv
    sql: |
      SELECT * from public.dissemination_general
      WHERE is_public = true
    target_options:
      format: csv


  public.dissemination_federalaward:
    mode: full-refresh
    object: file:///tmp/sling/dfa/*.csv
    target_options:
        file_max_rows: 1000
        format: csv
    sql: |
      SELECT * FROM 
        public.dissemination_general dg,
        public.dissemination_federalaward dfa
      WHERE
        dfa.report_id = dg.report_id
        AND
        dg.is_public = true



