#!/bin/bash

declare -a keys=(
    "101078"
    "101101" 
    "101106"
    "99989"
    "175887"
    )

for key in "${keys[@]}"
do
   echo "$key"
   python main.py --output ../../backend/data_fixtures/historic/ --dbkey $key
done
