# Generated by Django 4.2.3 on 2023-09-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name="CognizantAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=17)),
                (
                    "cognizant_agency",
                    models.CharField(max_length=2, verbose_name="Cog Agency"),
                ),
                (
                    "date_assigned",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Assigned"
                    ),
                ),
                (
                    "assignor_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                ("override_comment", models.TextField(verbose_name="Comment")),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("computed", "Computed by FAC"),
                            ("manual", "Manual Override"),
                        ],
                        default="computed",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognizantBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbkey",
                    models.CharField(max_length=20, null=True, verbose_name="dbkey"),
                ),
                ("ein", models.CharField(max_length=30, null=True, verbose_name="EIN")),
                ("uei", models.CharField(max_length=30, null=True, verbose_name="UEI")),
                (
                    "cognizant_agency",
                    models.CharField(max_length=2, verbose_name="Cog Agency"),
                ),
                (
                    "date_assigned",
                    models.DateTimeField(null=True, verbose_name="Date Assigned"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
        ),
    ]
