# Generated by Django 4.2.3 on 2023-09-07 10:03

from django.db import migrations, models
from typing import List


class Migration(migrations.Migration):
    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="CognizantBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbkey",
                    models.CharField(
                        max_length=20,
                        null=True,
                        verbose_name="Identifier for a submission along with audit_year in Census FAC",
                    ),
                ),
                (
                    "ein",
                    models.CharField(
                        max_length=30,
                        null=True,
                        verbose_name="Primary Employer Identification Number",
                    ),
                ),
                (
                    "uei",
                    models.CharField(
                        max_length=30,
                        null=True,
                        verbose_name="Unique Employer Identification Number",
                    ),
                ),
                (
                    "cognizant_agency",
                    models.CharField(
                        max_length=2,
                        verbose_name="Two digit Federal agency prefix of the cognizant agency",
                    ),
                ),
                (
                    "date_assigned",
                    models.DateTimeField(
                        verbose_name="Time when the cog agency was assigned to the entity"
                    ),
                ),
            ],
        ),
    ]
