# Generated by Django 4.2.3 on 2023-09-11 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0039_delete_cognizantbaseline_and_more"),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognizantbaseline",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Record to be ignored if this field is False"
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="date_assigned",
            field=models.DateTimeField(
                null=True,
                verbose_name="Time when the cog agency was assigned to the entity",
            ),
        ),
        migrations.CreateModel(
            name="CognizantAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cognizant_agency",
                    models.CharField(
                        max_length=2,
                        verbose_name="Two digit Federal agency prefix of the cognizant agency",
                    ),
                ),
                (
                    "date_assigned",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Time when the cog agency was assigned to the entity",
                    ),
                ),
                (
                    "assignor_email",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Who originally set the cog agency or who overrode it",
                    ),
                ),
                (
                    "override_comment",
                    models.TextField(
                        verbose_name="Comment by assignor explaining the justification for an override"
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("computed", "Computed by FAC"),
                            ("manual", "Manual Override"),
                        ],
                        default="computed",
                        max_length=20,
                    ),
                ),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
            ],
        ),
    ]
