# Generated by Django 4.2.5 on 2023-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cognizantassignment",
            name="report_id",
            field=models.CharField(),
        ),
    ]
