# Generated by Django 4.2.5 on 2023-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognizantbaseline",
            name="source",
            field=models.CharField(default="GSA", max_length=10, verbose_name="Source"),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="date_assigned",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date Assigned"
            ),
        ),
    ]
