# Generated by Django 4.2.5 on 2023-10-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0003_alter_cognizantassignment_report_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="date_assigned",
            field=models.DateTimeField(
                default=True, null=True, verbose_name="Date Assigned"
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="source",
            field=models.CharField(
                default="GSAFAC", max_length=10, verbose_name="Source"
            ),
        ),
    ]
