# Generated by Django 4.2.5 on 2023-10-13 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0004_alter_cognizantbaseline_date_assigned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="cognizant_agency",
            field=models.CharField(
                help_text="Two digit Federal agency prefix of the cognizant agency",
                max_length=2,
                verbose_name="Cog Agency",
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="date_assigned",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Time when the cog agency was assigned to the entity",
                null=True,
                verbose_name="Date Assigned",
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="dbkey",
            field=models.CharField(
                help_text="Identifier for a submission along with audit_year in Census FAC",
                max_length=20,
                null=True,
                verbose_name="dbkey",
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="ein",
            field=models.CharField(
                help_text="Primary Employer Identification Number",
                max_length=30,
                null=True,
                verbose_name="EIN",
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Record to be ignored if this field is False",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="source",
            field=models.CharField(
                default="GSAFAC",
                help_text="Source of cognizant data",
                max_length=10,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="cognizantbaseline",
            name="uei",
            field=models.CharField(
                help_text="Unique Employer Identification Number",
                max_length=30,
                null=True,
                verbose_name="UEI",
            ),
        ),
    ]
