# Generated by Django 5.1.2 on 2024-12-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_adminapievent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CognizantBaseline",
        ),
    ]
