# Generated by Django 5.1.7 on 2025-04-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_delete_cognizantbaseline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CognizantAssignment",
        ),
    ]
