# Generated by Django 5.1.2 on 2025-03-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_delete_cognizantbaseline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CognizantAssignment",
        ),
    ]
