# Generated by Django 5.2.16 on 2026-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_delete_cognizantbaseline"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Master toggle to enable or disable the banner",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional custom message. If left blank, a default maintenance message will be generated using start and end times.",
                        max_length=500,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the banner should start showing (optional)",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the banner should stop showing (optional)",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
