from historic.base import NoMapping, MapRetype, MapOneOf
from historic.retyping import to_int_to_str

cfac_to_gfac = {'agencycfda': NoMapping(),
                'auditeecertifyname': 'auditee_certify_name',
                'auditeecertifytitle': 'auditee_certify_title',
                'auditeecontact': 'auditee_contact_name',
                'auditeedatesigned': 'auditee_certified_date',
                'auditeeemail': 'auditee_email',
                'auditeefax': 'hist_auditee_fax',
                'auditeename': 'auditee_name',
                'auditeenametitle': NoMapping(),
                'auditeephone': 'auditee_phone',
                'auditeetitle': 'auditee_contact_title',
                'auditor_ein': 'auditor_ein',
                'audittype': 'audit_type',
                'audityear': 'audit_year',
                'city': 'auditee_city',
                # FIXME: Which?
                'cog_agency': MapOneOf('cog_agency', 'cognizant_agency'),
                'cog_over': NoMapping(),
                'cogagency': MapOneOf('cog_agency', 'cognizant_agency'),
                'copies': NoMapping(),
                'cpacity': 'auditor_city',
                'cpacontact': 'auditor_contact_name',
                'cpacountry': 'auditor_country',
                'cpadatesigned': 'auditor_certified_date',
                'cpaemail': 'auditor_email',
                'cpafax': 'hist_auditor_fax',
                'cpafirmname': 'auditor_firm_name',
                'cpaforeign': 'auditor_foreign_addr',
                'cpanametitle': NoMapping(),
                'cpaphone': 'auditor_phone',
                'cpastate': 'auditor_state',
                'cpastreet1': 'auditor_address_line_1',
                'cpastreet2': 'hist_auditor_address_line_2',
                'cpatitle': 'auditor_contact_title',
                'cpazipcode': 'auditor_zip',
                'cyfindings': 'current_or_former_findings',
                'datefinished': 'date_published',
                'datefirewall': NoMapping(),
                'datereceived': 'date_received',
                'datereceivedother': 'form_date_received',
                'datetoed': NoMapping(),
                'dbkey': MapRetype('dbkey', to_int_to_str),
                'dollarthreshold': 'dollar_threshold',
                'duns': NoMapping(),
                'dup_reports': NoMapping(),
                'ein': 'auditee_ein',
                'einsubcode': 'ein_subcode',
                'elecauditheaderid': NoMapping(),
                'entity_type': 'entity_type',
                'facaccepteddate': 'fac_accepted_date',
                'findingrefnum': NoMapping(),
                'fyenddate': 'fy_end_date',
                'fystartdate': 'fy_start_date',
                'goingconcern': NoMapping(),
                'id': NoMapping(),
                'image': NoMapping(),
                'initialdate': 'create_date',
                'lowrisk': 'is_low_risk',
                'materialnoncompliance': 'is_material_noncompliance',
                'materialweakness': 'is_material_weakness',
                'materialweakness_mp': NoMapping(),
                'multiple_cpas': NoMapping(),
                'multipleduns': NoMapping(),
                'multipleeins': NoMapping(),
                'multipleueis': NoMapping(),
                'numbermonths': NoMapping(),
                'opeid': NoMapping(),
                'oversightagency': 'oversight_agency',
                'periodcovered': 'audit_period_covered',
                'previousdatefirewall': NoMapping(),
                'pyschedule': 'prior_year_schedule',
                'qcosts': 'questioned_costs',
                'reportablecondition': NoMapping(),
                'reportablecondition_mp': NoMapping(),
                'reportrequired': NoMapping(),
                'sd_materialweakness': NoMapping(),
                'sd_materialweakness_mp': NoMapping(),
                'significantdeficiency': 'is_significant_deficiency',
                'significantdeficiency_mp': NoMapping(),
                'sp_framework': 'special_framework',
                'sp_framework_required': NoMapping(),
                'state': 'auditee_state',
                'street1': 'auditee_address_line_1',
                'street2': 'hist_auditee_address_line_2',
                'suppression_code': 'suppression_code',
                'totfedexpend': 'total_fed_expenditures',
                'typeaudit_code': 'type_audit_code',
                'typefinding': NoMapping(),
                'typefunding': NoMapping(),
                'typeofentity': NoMapping(),
                'typereport_fs': 'type_report_financial_statements',
                'typereport_mp': 'type_report_major_program',
                'typereport_sp_framework': 'type_report_special_purpose_framework',
                'uei': 'auditee_uei',
                'zipcode': 'auditee_zip'
                }

gfac_columns = {
    'report_id',
    'audit_period_covered',
    'audit_type',
    'audit_year',
    # FIXME Added null=True
    'auditee_addl_duns_list',
    'auditee_addl_ein_list',
    'auditee_addl_uei_list',
    'auditee_address_line_1',
    'auditee_certified_date',
    'auditee_certify_name',
    'auditee_certify_title',
    'auditee_city',
    'auditee_contact_name',
    'auditee_contact_title',
    'auditee_duns',  # FIXME: Should be text?
    'auditee_ein',
    'auditee_email',
    'auditee_name',
    'auditee_phone',
    'auditee_state',
    'auditee_uei',
    'auditee_zip',
    'auditor_address_line_1',
    'auditor_certified_date',
    'auditor_city',
    'auditor_contact_name',
    'auditor_contact_title',
    'auditor_country',
    'auditor_ein',
    'auditor_email',
    'auditor_firm_name',
    'auditor_foreign_addr',
    'auditor_phone',
    'auditor_state',
    'auditor_zip',
    'cfac_report_id',
    'cfac_version',
    'cognizant_agency',
    'condition_or_deficiency_major_program',
    'create_date',
    'current_or_former_findings',
    'data_source',
    'date_published',
    'date_received',
    'dbkey',
    'dollar_threshold',
    'ein_subcode',
    'entity_type',
    'fac_accepted_date',
    'form_date_received',
    'fy_end_date',
    'fy_start_date',
    'hist_auditee_address_line_2',
    'hist_auditee_fax',
    'hist_auditor_address_line_2',
    'hist_auditor_fax',
    'hist_completed_date',
    'hist_component_date_received',
    'hist_previous_completed_on',
    'hist_previous_date_published',
    'hist_reportable_condition',
    'hist_type_of_entity',
    'initial_date_received',
    'is_duplicate_reports',
    'is_going_concern',
    'is_low_risk',
    'is_material_noncompliance',
    'is_material_weakness',
    'is_public',
    'is_significant_deficiency',
    'is_special_framework_required',
    'material_weakness',
    'material_weakness_major_program',
    'modified_date',
    'multiple_auditors',
    'multiple_duns',
    'multiple_ein',
    'multiple_uei',
    'number_months',
    'oversight_agency',
    'pdf_url',
    'prior_year_schedule',
    'questioned_costs',
    'report_required',
    'special_framework',
    'suppression_code',
    'total_fed_expenditures',
    'type_audit_code',
    'type_report_financial_statements',
    'type_report_major_program',
    'type_report_special_purpose_framework',

}
