from historic.base import NoMapping, MapRetype
from historic.retyping import to_boolean

cfac_to_gfac = {
    "AGENCYCFDA": NoMapping(),
    "AUDITEECERTIFYNAME": "auditee_certify_name",
    "AUDITEECERTIFYTITLE": "auditee_certify_title",
    "AUDITEECONTACT": "auditee_contact_name",
    "AUDITEEDATESIGNED": "auditee_certified_date",
    "AUDITEEEMAIL": "auditee_email",
    "AUDITEEFAX": NoMapping(),
    "AUDITEENAME": "auditee_name",
    "AUDITEENAMETITLE": NoMapping(),
    "AUDITEEPHONE": "auditee_phone",
    "AUDITEETITLE": "auditee_contact_title",
    "AUDITOR_EIN": "auditor_ein",
    "AUDITTYPE": "audit_type",
    "AUDITYEAR": "audit_year",
    "CITY": "auditee_city",
    "COG_AGENCY": NoMapping(),
    "COG_OVER": NoMapping(),
    "COGAGENCY": "cognizant_agency",
    "COPIES": NoMapping(),
    "CPACITY": "auditor_city",
    "CPACONTACT": "auditor_contact_name",
    "CPACOUNTRY": "auditor_country",
    "CPADATESIGNED": "auditor_certified_date",
    "CPAEMAIL": "auditor_email",
    "CPAFAX": NoMapping(),
    "CPAFIRMNAME": "auditor_firm_name",
    "CPAFOREIGN": "auditor_foreign_addr",
    "CPANAMETITLE": NoMapping(),
    "CPAPHONE": "auditor_phone",
    "CPASTATE": "auditor_state",
    "CPASTREET1": "auditor_address_line_1",
    "CPASTREET2": NoMapping(),
    "CPATITLE": "auditor_contact_title",
    "CPAZIPCODE": "auditor_zip",
    "CYFINDINGS": NoMapping(),
    "DATEFINISHED": "submitted_date",
    "DATEFIREWALL": NoMapping(),
    "DATERECEIVED": "initial_date_received",
    "DATERECEIVEDOTHER": NoMapping(),
    "DATETOED": NoMapping(),
    # 'dbkey': MapRetype('dbkey', to_int_to_str),
    "DBKEY": "hist_dbkey",
    "DOLLARTHRESHOLD": "dollar_threshold",
    "DUNS": NoMapping(),
    "DUP_REPORTS": NoMapping(),
    "EIN": "auditee_ein",
    "EINSUBCODE": NoMapping(),
    "ELECAUDITHEADERID": NoMapping(),
    "ENTITY_TYPE": "entity_type",
    "FACACCEPTEDDATE": NoMapping(),
    "FINDINGREFNUM": NoMapping(),
    "FYENDDATE": "fy_end_date",
    "FYSTARTDATE": "fy_start_date",
    "GOINGCONCERN": NoMapping(),
    "ID": NoMapping(),
    "IMAGE": NoMapping(),
    "INITIALDATE": NoMapping(),
    "LOWRISK": MapRetype("is_low_risk", to_boolean),
    "MATERIALNONCOMPLIANCE": MapRetype("is_material_noncompliance", to_boolean),
    "MATERIALWEAKNESS": MapRetype("is_material_weakness", to_boolean),
    "MATERIALWEAKNESS_MP": NoMapping(),
    "MULTIPLE_CPAS": NoMapping(),
    "MULTIPLEDUNS": NoMapping(),
    "MULTIPLEEINS": NoMapping(),
    "MULTIPLEUEIS": NoMapping(),
    "NUMBERMONTHS": "number_months",
    "OPEID": NoMapping(),
    "OVERSIGHTAGENCY": "oversight_agency",
    "PERIODCOVERED": "audit_period_covered",
    "PREVIOUSDATEFIREWALL": NoMapping(),
    "PYSCHEDULE": NoMapping(),
    "QCOSTS": NoMapping(),
    "REPORTABLECONDITION": NoMapping(),
    "REPORTABLECONDITION_MP": NoMapping(),
    "REPORTREQUIRED": NoMapping(),
    "SD_MATERIALWEAKNESS": NoMapping(),
    "SD_MATERIALWEAKNESS_MP": NoMapping(),
    "SIGNIFICANTDEFICIENCY": MapRetype("is_significant_deficiency", to_boolean),
    "SIGNIFICANTDEFICIENCY_MP": NoMapping(),
    "SP_FRAMEWORK": "sp_framework",
    "SP_FRAMEWORK_REQUIRED": MapRetype("is_sp_framework_required", to_boolean),
    "STATE": "auditee_state",
    "STREET1": "auditee_address_line_1",
    "STREET2": NoMapping(),
    "SUPPRESSION_CODE": NoMapping(),
    "TOTFEDEXPEND": "total_fed_expenditures",
    "TYPEAUDIT_CODE": "type_audit_code",
    "TYPEFINDING": NoMapping(),
    "TYPEFUNDING": NoMapping(),
    "TYPEOFENTITY": NoMapping(),
    "TYPEREPORT_FS": "gaap_results",
    "TYPEREPORT_MP": "type_report_major_program",
    "TYPEREPORT_SP_FRAMEWORK": "sp_framework_auditor_opinion",
    "UEI": "auditee_uei",
    "ZIPCODE": "auditee_zip",
}

gfac_columns = {
    "report_id",
    "audit_period_covered",
    "audit_type",
    "audit_year",
    "auditee_addl_duns_list",
    "auditee_addl_ein_list",
    "auditee_addl_uei_list",
    "auditee_address_line_1",
    "auditee_certified_date",
    "auditee_certify_name",
    "auditee_certify_title",
    "auditee_city",
    "auditee_contact_name",
    "auditee_contact_title",
    "auditee_duns",  # FIXME: Should be text?
    "auditee_ein",
    "auditee_email",
    "auditee_name",
    "auditee_phone",
    "auditee_state",
    "auditee_uei",
    "auditee_zip",
    "auditor_address_line_1",
    "auditor_certified_date",
    "auditor_city",
    "auditor_contact_name",
    "auditor_contact_title",
    "auditor_country",
    "auditor_ein",
    "auditor_email",
    "auditor_firm_name",
    "auditor_foreign_addr",
    "auditor_phone",
    "auditor_state",
    "auditor_zip",
    "cfac_report_id",
    "cfac_version",
    "cognizant_agency",
    "condition_or_deficiency_major_program",
    "create_date",
    "current_or_former_findings",
    "data_source",
    "date_published",
    "date_received",
    "dbkey",
    "dollar_threshold",
    "ein_subcode",
    "entity_type",
    "fac_accepted_date",
    "form_date_received",
    "fy_end_date",
    "fy_start_date",
    "hist_auditee_address_line_2",
    "hist_auditee_fax",
    "hist_auditor_address_line_2",
    "hist_auditor_fax",
    "hist_completed_date",
    "hist_component_date_received",
    "hist_previous_completed_on",
    "hist_previous_date_published",
    "hist_reportable_condition",
    "hist_type_of_entity",
    "initial_date_received",
    "is_duplicate_reports",
    "is_going_concern",
    "is_low_risk",
    "is_material_noncompliance",
    "is_material_weakness",
    "is_public",
    "is_significant_deficiency",
    "is_special_framework_required",
    "material_weakness",
    "material_weakness_major_program",
    "modified_date",
    "multiple_auditors",
    "multiple_duns",
    "multiple_ein",
    "multiple_uei",
    "number_months",
    "oversight_agency",
    "pdf_url",
    "prior_year_schedule",
    "questioned_costs",
    "report_required",
    "special_framework",
    "suppression_code",
    "total_fed_expenditures",
    "type_audit_code",
    "type_report_financial_statements",
    "type_report_major_program",
    "type_report_special_purpose_framework",
}
