# Generated by Django 4.1.4 on 2023-01-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0001_initial_schema_from_downloads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="ein",
            field=models.IntegerField(
                verbose_name="Primary Employer Identification Number"
            ),
        ),
    ]
