# Generated by Django 4.2.3 on 2023-09-15 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0001_initial_schema_from_downloads"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agencies",
        ),
        migrations.DeleteModel(
            name="Captext",
        ),
        migrations.DeleteModel(
            name="CfdaInfo",
        ),
        migrations.DeleteModel(
            name="DunsInfo",
        ),
        migrations.DeleteModel(
            name="EinInfo",
        ),
        migrations.DeleteModel(
            name="Findings",
        ),
        migrations.DeleteModel(
            name="Findingstext",
        ),
        migrations.DeleteModel(
            name="General",
        ),
        migrations.DeleteModel(
            name="MultipleCpasInfo",
        ),
        migrations.DeleteModel(
            name="Notes",
        ),
        migrations.DeleteModel(
            name="Passthrough",
        ),
        migrations.DeleteModel(
            name="Revisions",
        ),
        migrations.DeleteModel(
            name="UeiInfo",
        ),
    ]
