# Generated by Django 4.1.4 on 2023-01-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0002_alter_cfdainfo_ein"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Captext",
            new_name="Capext",
        ),
        migrations.AddField(
            model_name="findings",
            name="findings_text",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_distro.findingstext",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="agency",
            field=models.ManyToManyField(null=True, to="data_distro.agencies"),
        ),
        migrations.AddField(
            model_name="general",
            name="cap_text",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_distro.capext",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="cfda",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_distro.cfdainfo",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="findings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_distro.findings",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="notes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_distro.notes",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="passthrough",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_distro.passthrough",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="revisions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_distro.revisions",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dbkey",
            field=models.CharField(
                help_text="Census mapping: GENERAL, DBKEY",
                max_length=40,
                verbose_name="Audit Year and DBKEY (database key) combined make up the primary key. Only on records created by census.",
            ),
        ),
    ]
