# Generated by Django 4.1.4 on 2023-01-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0002_rename_duninfo_dunsinfo_general_date_firewall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="arra",
            field=models.BooleanField(
                null=True,
                verbose_name="American Recovery and Reinvestment Act Funded Program",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="direct",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the award was received directly from a Federal awarding agency",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="loans",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the program is a Loan or Loan Guarantee (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="major_program",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the Federal program is a major program",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="passthrough_award",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicates whether or not funds were passed through to any subrecipients for the Federal program",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="research_and_development",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the program is a Research and Development program",
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="material_weakness",
            field=models.BooleanField(
                null=True, verbose_name="Material Weakness finding"
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="modified_opinion",
            field=models.BooleanField(
                null=True, verbose_name="Modified Opinion finding"
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="other_findings",
            field=models.BooleanField(null=True, verbose_name="Other findings"),
        ),
        migrations.AlterField(
            model_name="findings",
            name="other_non_compliance",
            field=models.BooleanField(
                null=True, verbose_name="Other Noncompliance finding"
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="questioned_costs",
            field=models.BooleanField(null=True, verbose_name="Questioned Costs"),
        ),
        migrations.AlterField(
            model_name="findings",
            name="repeat_finding",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicates whether or not the audit finding was a repeat of an audit finding in the immediate prior audit",
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="significant_deficiency",
            field=models.BooleanField(
                null=True, verbose_name="Significant Deficiency finding"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="condition_or_deficiency",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether or not the audit disclosed a reportable condition/significant deficiency on financial statements",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="condition_or_deficiency_major_program",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether or not the audit disclosed a reportable condition/significant deficiency for any major program in the Schedule of Findings and Questioned Costs",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="current_or_former_findings",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not current year findings or prior year findings affecting direct funds were reported",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dup_reports",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether or not the financial statements include departments that have separate expenditures not included in this audit",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="going_concern",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether or not the audit contained a going concern paragraph  on financial statements",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="low_risk",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the auditee qualified as a low-risk auditee",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="material_noncompliance",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether or not the audit disclosed a material noncompliance on financial statements",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="material_weakness",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether or not the audit disclosed any reportable condition/significant deficiency as a material weakness on financial statements",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="material_weakness_major_program",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether any reportable condition/signficant deficiency was disclosed as a material weakness for a major program in the Schedule of Findings and Questioned Costs",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="multiple_cpas",
            field=models.BooleanField(
                null=True,
                verbose_name="Identifies if the Submission Contains Multiple CPAs",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="multiple_duns",
            field=models.BooleanField(
                null=True,
                verbose_name="Identifies if the Submission Contains Multiple DUNS",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="multiple_eins",
            field=models.BooleanField(
                null=True,
                verbose_name="Identifies if the Submission Contains Multiple EINs",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="multiple_ueis",
            field=models.BooleanField(
                null=True,
                verbose_name="Identifies if the Submission Contains Multiple UEIs",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="prior_year_schedule",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the report includes a Summary Schedule of Prior Year Audit Findings",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="questoned_costs",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the audit disclosed any known questioned costs.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="report_required",
            field=models.BooleanField(
                null=True, verbose_name="Distribution to Federal Agency required?"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="sp_framework_required",
            field=models.BooleanField(
                null=True,
                verbose_name="Indicate whether or not the special purpose framework used as basis of accounting by state law or tribal law",
            ),
        ),
    ]
