# Generated by Django 4.1.4 on 2023-01-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0004_alter_findingstext_charts_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captext",
            name="charts_tables",
            field=models.BooleanField(
                max_length=1,
                null=True,
                verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
            ),
        ),
    ]
