# Generated by Django 4.1.4 on 2023-01-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0005_alter_captext_charts_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="cfda",
            field=models.FloatField(verbose_name="Federal Agency Prefix and Extension"),
        ),
    ]
