# Generated by Django 4.1.4 on 2023-01-30 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("data_distro", "0006_split_significantdef_from_condition_add_docs"),
        ("data_distro", "0007_remove_auditor_dbkey_auditee_dbkey_list_and_more"),
        ("data_distro", "0008_alter_findings_type_requirement"),
        ("data_distro", "0009_alter_cfdainfo_award_identification_and_more"),
        ("data_distro", "0010_alter_cfdainfo_auditor_ein"),
        ("data_distro", "0011_alter_cfdainfo_type_report_major_program"),
        ("data_distro", "0012_alter_cfdainfo_cfda_program_name"),
        ("data_distro", "0013_alter_notes_note_index"),
        ("data_distro", "0014_alter_general_agency_alter_general_auditor_and_more"),
        ("data_distro", "0015_alter_general_agency_alter_general_auditor_and_more"),
        ("data_distro", "0016_alter_revisions_auditinfo_explain"),
        ("data_distro", "0017_alter_revisions_audit_info"),
        ("data_distro", "0018_alter_revisions_federal_awards"),
        ("data_distro", "0019_alter_revisions_elec_report_revision_id"),
        ("data_distro", "0020_alter_agencies_agency_cfda_and_more"),
        ("data_distro", "0021_alter_passthrough_passthrough_name"),
        ("data_distro", "0022_alter_general_total_fed_expenditures"),
        ("data_distro", "0023_alter_general_fy_end_date"),
        ("data_distro", "0024_alter_general_auditee_date_signed"),
        ("data_distro", "0025_alter_auditor_auditor_ein_and_more"),
    ]

    dependencies = [
        ("data_distro", "0005_delete_duplicate_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cfdainfo",
            name="ein",
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="questioned_costs",
            field=models.CharField(
                help_text="Census mapping: CFDA INFO, QCOSTS2",
                max_length=40,
                null=True,
                verbose_name="Questioned Costs",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="date_firewall",
            field=models.DateField(
                help_text="Census mapping: GENERAL, DATEFIREWALL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="previous_date_firewall",
            field=models.DateField(
                help_text="Census mapping: GENERAL, PREVIOUSDATEFIREWALL", null=True
            ),
        ),
        migrations.RemoveField(
            model_name="general",
            name="condition_or_deficiency",
        ),
        migrations.AddField(
            model_name="general",
            name="reportable_condition",
            field=models.BooleanField(
                help_text="Data sources: SF-SAC 1997-2000: II/3; SF-SAC 2001-2003: II/3; SF-SAC 2004-2007: II/3; SF-SAC 2008-2009: II/3; SF-SAC 2010-2012: II/3; SF-SAC 2013-2015: II/3; SF-SAC 2016-2018: III/2/c; SF-SAC 2019-2021: III/2/c; SF-SAC 2022: III/2/c Census mapping: GENERAL, REPORTABLECONDITION",
                null=True,
                verbose_name="Whether or not the audit disclosed a reportable condition on financial statements",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="significant_deficiency",
            field=models.BooleanField(
                help_text="Data sources: SF-SAC 1997-2000: II/3; SF-SAC 2001-2003: II/3; SF-SAC 2004-2007: II/3; SF-SAC 2008-2009: II/3; SF-SAC 2010-2012: II/3; SF-SAC 2013-2015: II/3; SF-SAC 2016-2018: III/2/c; SF-SAC 2019-2021: III/2/c; SF-SAC 2022: III/2/c Census mapping: GENERAL, SIGNIFICANTDEFICIENCY",
                null=True,
                verbose_name="Whether or not the audit disclosed a significant deficiency on financial statements",
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="significant_deficiency",
            field=models.BooleanField(
                help_text="Data sources: SF-SAC 1997-2000: II/3; SF-SAC 2001-2003: II/3; SF-SAC 2004-2007: II/3; SF-SAC 2008-2009: II/3; SF-SAC 2010-2012: II/3; SF-SAC 2013-2015: II/3; SF-SAC 2016-2018: III/2/c; SF-SAC 2019-2021: III/2/c; SF-SAC 2022: III/2/c Census mapping: FINDINGS, SIGNIFICANTDEFICIENCY",
                null=True,
                verbose_name="Significant Deficiency finding",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency_over",
            field=models.CharField(
                help_text="Census mapping: GENERAL, COG_OVER", max_length=2, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="auditor",
            name="dbkey",
        ),
        migrations.AddField(
            model_name="auditee",
            name="dbkey_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Census mapping: GENERAL, DBKEY",
                    max_length=40,
                    verbose_name="Audit Year and DBKEY (database key) combined make up the primary key. Only on records created by census.",
                ),
                default=[0],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditor",
            name="dbkey_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Census mapping: MULTIPLE CPAS INFO, DBKEY",
                    max_length=40,
                    verbose_name="Audit Year and DBKEY (database key) combined make up the primary key. Only on records created by census.",
                ),
                default=[0],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="findings",
            name="finding_ref_nums",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/d; SF-SAC 2016-2018: III/4/e; SF-SAC 2019-2021: III/4/e; SF-SAC 2022: III/4/e Census mapping: FINDINGS, FINDINGSREFNUMS",
                max_length=100,
                verbose_name="Findings Reference Numbers",
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="prior_finding_ref_nums",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2016-2018: III/4/n; SF-SAC 2019-2021: III/4/n; SF-SAC 2022: III/4/n Census mapping: FINDINGS, PRIORFINDINGREFNUMS",
                max_length=100,
                null=True,
                verbose_name="Audit finding reference numbers from the immediate prior audit",
            ),
        ),
        migrations.AlterField(
            model_name="findings",
            name="type_requirement",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: FINDINGS, TYPEREQUIREMENT",
                max_length=40,
                null=True,
                verbose_name="Type Requirement Failure",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="award_identification",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/c; SF-SAC 2019-2021: II/1/c; SF-SAC 2022: II/1/c Census mapping: CFDA INFO, AWARDIDENTIFICATION",
                max_length=50,
                null=True,
                verbose_name="Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="findings",
            field=models.TextField(
                help_text="Census mapping: CFDA INFO, FINDINGS",
                null=True,
                verbose_name="Items on the Findings page",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="research_and_development",
            field=models.BooleanField(
                help_text="Data sources: SF-SAC 2001-2003: III/10/b; SF-SAC 2004-2007: III/9/c; SF-SAC 2008-2009: III/9/c; SF-SAC 2010-2012: III/9/c; SF-SAC 2013-2015: III/6/e Census mapping: CFDA INFO, RD",
                null=True,
                verbose_name="Indicate whether or not the program is a Research and Development program",
            ),
        ),
        migrations.AddField(
            model_name="cfdainfo",
            name="auditor_ein",
            field=models.IntegerField(
                help_text="Census mapping: GENERAL, AUDITOR_EIN",
                null=True,
                verbose_name="Primary Employer Identification Number",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="type_report_major_program",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2004-2007: III/9/h; SF-SAC 2008-2009: III/9/h; SF-SAC 2010-2012: III/9/i; SF-SAC 2013-2015: III/6/j; SF-SAC 2016-2018: III/1/b; SF-SAC 2019-2021: III/1/b; SF-SAC 2022: III/1/b Census mapping: CFDA INFO, TYPEREPORT_MP",
                max_length=40,
                null=True,
                verbose_name="Type of Report Issued on the Major Program Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="cfda_program_name",
            field=models.CharField(
                help_text="Census mapping: CFDA INFO, CFDAPROGRAMNAME",
                max_length=300,
                null=True,
                verbose_name="Name of Federal Program (auto-generated by FAC from the CFDA catalog)",
            ),
        ),
        migrations.AlterField(
            model_name="notes",
            name="note_index",
            field=models.IntegerField(
                help_text="Census mapping: NOTES, NOTE_INDEX",
                null=True,
                verbose_name="Display Index for the Note",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="agency",
            field=models.ManyToManyField(null=True, to="data_distro.agencies"),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor",
            field=models.ManyToManyField(null=True, to="data_distro.auditor"),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="cap",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, CAP",
                max_length=6,
                null=True,
                verbose_name="Indicates what items on the CAP Text page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="cap_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, CAP_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the CAP Text page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="federal_awards_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FEDERALAWARDS_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the Federal Awards page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="findings",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, FINDINGS",
                max_length=110,
                null=True,
                verbose_name="Indicates what items on the Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="findings_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGS_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="findings_text",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, FINDINGSTEXT",
                max_length=6,
                null=True,
                verbose_name="Indicates what items on the Text of the Audit Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="findings_text_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGSTEXT_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the Text of the Audit Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="general_info",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, GENINFO",
                max_length=75,
                null=True,
                verbose_name="Indicates what items on the General Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="notes_to_sefa",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, NOTESTOSEFA",
                max_length=50,
                null=True,
                verbose_name="Indicates what items on the Notes to SEFA page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="notes_to_sefa_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, NOTESTOSEFA_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the Notes to SEFA page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="other",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, OTHER",
                max_length=65,
                null=True,
                verbose_name="Indicates what other miscellaneous items were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="other_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, OTHER_EXPLAIN",
                null=True,
                verbose_name="Explanation of what other miscellaneous items were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="agency",
            field=models.ManyToManyField(to="data_distro.agencies"),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor",
            field=models.ManyToManyField(to="data_distro.auditor"),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="general_info_explain",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, GENINFO_EXPLAIN",
                max_length=150,
                null=True,
                verbose_name="Explanation of what items on the General Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="auditinfo_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, AUDITINFO_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the Audit Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="audit_info",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, AUDITINFO",
                max_length=200,
                null=True,
                verbose_name="Indicates what items on the Audit Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="federal_awards",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, FEDERALAWARDS",
                max_length=140,
                null=True,
                verbose_name="Indicates what items on the Federal Awards page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="elec_report_revision_id",
            field=models.IntegerField(
                help_text="Census mapping: REVISIONS, ELECRPTREVISIONID",
                null=True,
                verbose_name="Internal Unique Identifier for the record",
            ),
        ),
        migrations.AlterField(
            model_name="agencies",
            name="agency_cfda",
            field=models.IntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/5; SF-SAC 2001-2003: III/9; SF-SAC 2004-2007: III/8; SF-SAC 2008-2009: III/8; SF-SAC 2010-2012: III/8; SF-SAC 2013-2015: III/5; SF-SAC 2016-2018: III/3/d; SF-SAC 2019-2021: III/3/d; SF-SAC 2022: III/3/d Census mapping: AGENCIES, AGENCY",
                verbose_name="2-digit prefix of Federal Agency requiring copy of audit report",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_id",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/m; SF-SAC 2019-2021: II/1/m; SF-SAC 2022: II/1/m Census mapping: PASSTHROUGH, PASSTHROUGHID",
                max_length=70,
                null=True,
                verbose_name="Identifying Number Assigned by the Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_name",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/l; SF-SAC 2019-2021: II/1/l; SF-SAC 2022: II/1/l Census mapping: PASSTHROUGH, PASSTHROUGHNAME",
                max_length=70,
                null=True,
                verbose_name="Name of Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="total_fed_expenditures",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/c- Total; SF-SAC 2001-2003: III/10/d -Total; SF-SAC 2004-2007: III/9/e -Total; SF-SAC 2008-2009: III/9/e -Total; SF-SAC 2010-2012: III/9/f -Total; SF-SAC 2013-2015: III/6/d -Total; SF-SAC 2016-2018: II/1/e- Total; SF-SAC 2019-2021: II/1/e - Total; SF-SAC 2022: II/1/e - Total Census mapping: GENERAL, TOTFEDEXPEND",
                null=True,
                verbose_name="Total Federal Expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="fy_end_date",
            field=models.DateField(
                help_text="Data sources: SF-SAC 1997-2000: Part I, Item 1; SF-SAC 2001-2003: Part I, Item 1; SF-SAC 2004-2007: Part I, Item 1; SF-SAC 2008-2009: Part I, Item 1; SF-SAC 2010-2012: Part I, Item 1; SF-SAC 2013-2015: Part I, Item 1; SF-SAC 2016-2018: Part I, Item 1; SF-SAC 2019-2021: I/1/b; SF-SAC 2022: I/1/b Census mapping: GENERAL, FYENDDATE",
                null=True,
                verbose_name="Fiscal Year End Date",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_date_signed",
            field=models.DateField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEEDATESIGNED",
                null=True,
                verbose_name="Date of Auditee signature",
            ),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="auditor_ein",
            field=models.IntegerField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN",
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cpa_date_signed",
            field=models.DateField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/g; SF-SAC 2001-2003: I/7/g; SF-SAC 2004-2007: I/7/g; SF-SAC 2008-2009: I/6/g; SF-SAC 2010-2012: I/6/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, CPADATESIGNED",
                null=True,
                verbose_name="Date of CPA signature",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="fac_accepted_date",
            field=models.DateField(
                help_text="Census mapping: GENERAL, FACACCEPTEDDATE",
                verbose_name="The most recent date an audit report was submitted to the FAC that passed FAC screening and was accepted as a valid OMB Circular A-133 report submission.",
            ),
        ),
    ]
