# Generated by Django 4.1.4 on 2023-02-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0006_modify_models_to_work_with_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditee",
            name="dbkey_list",
        ),
        migrations.RemoveField(
            model_name="auditor",
            name="dbkey_list",
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="program_total",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/g; SF-SAC 2019-2021: II/1/g; SF-SAC 2022: II/1/g Census mapping: CFDA INFO, PROGRAMTOTAL",
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="questioned_costs",
            field=models.CharField(
                help_text="Census mapping: CFDA INFO, QCOSTS2",
                max_length=40,
                null=True,
                verbose_name="Dollar amount of questioned costs (Depricated since 2002)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency_over",
            field=models.CharField(
                help_text="Census mapping: GENERAL, COG_OVER",
                max_length=2,
                null=True,
                verbose_name="A value of 'C' means the entity was assigned a Cognizant agency (had over $50 million in total expenses). A value of 'O' means the entity was assigned a Oversight agency (had less tham=n $50 million in total expenses)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="date_firewall",
            field=models.DateField(
                help_text="Census mapping: GENERAL, DATEFIREWALL",
                null=True,
                verbose_name="The date the audit information was made available on the dissemination site",
            ),
        ),
    ]
