# Generated by Django 4.1.4 on 2023-01-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0006_alter_cfdainfo_cfda"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfdainfo",
            name="ein",
            field=models.IntegerField(
                default=None, verbose_name="Primary Employer Identification Number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agencies",
            name="ein",
            field=models.IntegerField(
                null=True,
                verbose_name="Employer Identification Number (EIN) of primary grantee",
            ),
        ),
    ]
