# Generated by Django 4.1.4 on 2023-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0006_modify_models_to_work_with_2022_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencies",
            name="agency_name",
            field=models.CharField(
                max_length=125,
                null=True,
                verbose_name="Name of the Federal Agency requiring copy of audit report",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="entity_type",
            field=models.CharField(
                help_text="Census mapping: GENERAL, ENTITY_TYPE",
                max_length=50,
                null=True,
                verbose_name="Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
            ),
        ),
    ]
