# Generated by Django 4.1.4 on 2023-02-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0007_agencies_agency_name_alter_general_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="type_of_entity",
            field=models.CharField(
                help_text="Census mapping: GENERAL, TYPEOFENTITY",
                max_length=40,
                null=True,
                verbose_name="Contact FAC for information",
            ),
        ),
    ]
