# Generated by Django 4.1.4 on 2023-02-01 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_distro",
            "0007_remove_auditee_dbkey_list_remove_auditor_dbkey_list_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditee",
            name="auditee_name_title",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEENAMETITLE",
                max_length=70,
                null=True,
                verbose_name="Title of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="auditee",
            name="auditee_title",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEETITLE",
                max_length=40,
                null=True,
                verbose_name="Title of Auditee Contact",
            ),
        ),
        migrations.AlterField(
            model_name="auditee",
            name="duns_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    help_text="Data sources: SF-SAC 2004-2007: I/5/d; SF-SAC 2008-2009: I/4/d; SF-SAC 2010-2012: I/4/d; SF-SAC 2013-2015: I/4/d; SF-SAC 2016-2018: I/4/d; SF-SAC 2019-2021: I/4/d; SF-SAC 2022: I/4/d Census mapping: GENERAL, DUNS",
                    null=True,
                    verbose_name="Multiple Data Universal Numbering System Numbers, an array of DUNS numbers of the Auditee.",
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="auditee",
            name="ein",
            field=models.IntegerField(
                help_text="Data sources: SF-SAC 1997-2000: I/5/a; SF-SAC 2001-2003: I/5/a; SF-SAC 2004-2007: I/5/a; SF-SAC 2008-2009: I/4/a; SF-SAC 2010-2012: I/4/a; SF-SAC 2013-2015: I/4/a; SF-SAC 2016-2018: I/4/a; SF-SAC 2019-2021: I/4/a; SF-SAC 2022: I/4/a Census mapping: GENERAL, EIN",
                null=True,
                verbose_name="Primary Employer Identification Number",
            ),
        ),
        migrations.AlterField(
            model_name="auditee",
            name="uei_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    max_length=12,
                    null=True,
                    verbose_name="Unique Entity ID",
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="auditee",
            name="zip_code",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, ZIPCODE",
                max_length=12,
                null=True,
                verbose_name="Auditee Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="cpa_title",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                max_length=40,
                null=True,
                verbose_name="Title of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="cluster_total",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/h; SF-SAC 2019-2021: II/1/h; SF-SAC 2022: II/1/h Census mapping: CFDA INFO, CLUSTERTOTAL",
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
            ),
        ),
    ]
