# Generated by Django 4.1.4 on 2023-01-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0007_cfdainfo_ein_alter_agencies_ein"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfdainfo",
            name="findings",
            field=models.TextField(
                default=None, verbose_name="Items on the Findings page"
            ),
            preserve_default=False,
        ),
    ]
