# Generated by Django 4.1.4 on 2023-01-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0008_cfdainfo_findings"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfdainfo",
            name="questioned_costs",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Questioned Costs"
            ),
        ),
    ]
