# Generated by Django 4.1.4 2023-02-08 21:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0008_alter_general_type_of_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agencies",
            name="audit_year",
        ),
        migrations.RemoveField(
            model_name="agencies",
            name="dbkey",
        ),
        migrations.RemoveField(
            model_name="agencies",
            name="ein",
        ),
        migrations.RemoveField(
            model_name="auditee",
            name="ein",
        ),
        migrations.AddField(
            model_name="auditee",
            name="agency",
            field=models.ManyToManyField(to="data_distro.agencies"),
        ),
        migrations.AddField(
            model_name="auditee",
            name="ein_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    help_text="Data sources: SF-SAC 1997-2000: I/5/a; SF-SAC 2001-2003: I/5/a; SF-SAC 2004-2007: I/5/a; SF-SAC 2008-2009: I/4/a; SF-SAC 2010-2012: I/4/a; SF-SAC 2013-2015: I/4/a; SF-SAC 2016-2018: I/4/a; SF-SAC 2019-2021: I/4/a; SF-SAC 2022: I/4/a Census mapping: GENERAL, EIN",
                    null=True,
                    verbose_name="Primary Employer Identification Number",
                ),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notes",
            name="content",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, CONTENT",
                null=True,
                verbose_name="Content of the Note",
            ),
        ),
        migrations.AlterField(
            model_name="notes",
            name="title",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, TITLE",
                max_length=75,
                null=True,
                verbose_name="Note Title",
            ),
        ),
    ]
