# Generated by Django 4.1.4 on 2023-01-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0009_cfdainfo_questioned_costs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="general",
            old_name="questoned_costs",
            new_name="questioned_costs",
        ),
    ]
