# Generated by Django 4.1.4 on 2023-02-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0010_add_Agencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_name",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/l; SF-SAC 2019-2021: II/1/l; SF-SAC 2022: II/1/l Census mapping: PASSTHROUGH, PASSTHROUGHNAME",
                max_length=150,
                null=True,
                verbose_name="Name of Pass-through Entity",
            ),
        ),
    ]
