# Generated by Django 4.1.4 on 2023-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0010_rename_questoned_costs_general_questioned_costs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="cfda",
            field=models.CharField(
                max_length=52, verbose_name="Federal Agency Prefix and Extension"
            ),
        ),
    ]
