# Generated by Django 4.1.4 on 2023-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0011_alter_cfdainfo_cfda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplecpasinfo",
            name="cpa_ein",
            field=models.IntegerField(
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="multiplecpasinfo",
            name="cpa_fax",
            field=models.IntegerField(
                null=True, verbose_name="CPA fax number (optional)"
            ),
        ),
    ]
