# Generated by Django 4.1.4 on 2023-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0012_alter_multiplecpasinfo_cpa_ein_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="auditee_fax",
            field=models.IntegerField(
                null=True, verbose_name="Auditee Fax Number (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cpa_fax",
            field=models.IntegerField(
                null=True, verbose_name="CPA fax number (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="multiplecpasinfo",
            name="cpa_mail",
            field=models.CharField(
                max_length=60, null=True, verbose_name="CPA email address (optional)"
            ),
        ),
    ]
