# Generated by Django 4.1.4 on 2023-02-10 18:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0012_update_docs_with_multiple_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditee",
            name="duns_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    help_text="Data sources: SF-SAC 2004-2007: I/5/git ad; SF-SAC 2008-2009: I/4/d; SF-SAC 2010-2012: I/4/d; SF-SAC 2013-2015: I/4/d; SF-SAC 2016-2018: I/4/d; SF-SAC 2019-2021: I/4/d; SF-SAC 2022: I/4/d Census mapping: GENERAL, DUNS (AND) Data sources: SF-SAC 2004-2007: I/5/f; SF-SAC 2008-2009: I/4/f; SF-SAC 2010-2012: I/4/f; SF-SAC 2013-2015: I/4/f; SF-SAC 2016-2018: I/4/f; SF-SAC 2019-2021: I/4/f; SF-SAC 2022: I/4/f Census mapping: DUN INFO, DUNS",
                    null=True,
                    verbose_name="Multiple Data Universal Numbering System Numbers (DUNS) of the Auditee, in the order they were listed.",
                ),
                size=None,
            ),
        ),
    ]
