# Generated by Django 4.1.4 on 2023-01-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_distro",
            "0013_alter_general_auditee_fax_alter_general_cpa_fax_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="cluster_name",
            field=models.CharField(
                max_length=75, null=True, verbose_name="The name of the cluster"
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="finding_ref_nums",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Findings Reference Numbers"
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="findings",
            field=models.TextField(
                null=True, verbose_name="Items on the Findings page"
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="loan_balance",
            field=models.CharField(
                max_length=40,
                null=True,
                verbose_name="The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="other_cluster_name",
            field=models.CharField(
                max_length=75,
                null=True,
                verbose_name="The name of the cluster (if not listed in the Compliance Supplement)",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="passthrough_amount",
            field=models.IntegerField(
                null=True, verbose_name="Amount passed through to subrecipients"
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="program_total",
            field=models.BigIntegerField(
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension"
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="state_cluster_name",
            field=models.CharField(
                max_length=75, null=True, verbose_name="The name of the state cluster"
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="type_requirement",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Type Requirement Failure"
            ),
        ),
    ]
