# Generated by Django 4.1.4 on 2023-01-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0014_alter_cfdainfo_cluster_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="cognizant_agency_over",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_name",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="Name of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_title",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="Title of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="completed_on",
            field=models.DateField(
                null=True,
                verbose_name="Date the Audit was Posted to the Internet as Complete",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="component_date_received",
            field=models.DateField(
                null=True,
                verbose_name="The most recent date an audit component was received by the FAC. This field was not populated before 2004. Receipt of Financial statements only are not processed until the rest of the audit or a Form SF-SAC is also received.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="fy_start_date",
            field=models.DateField(null=True, verbose_name="Fiscal Year Start Date"),
        ),
        migrations.AlterField(
            model_name="general",
            name="initial_date_received",
            field=models.DateField(
                null=True,
                verbose_name="The first date an audit component or Form SF-SAC was received by the Federal audit Clearinghouse (FAC).",
            ),
        ),
    ]
