# Generated by Django 4.1.4 on 2023-02-13 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0015_rename_city_auditee_auditee_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditee",
            old_name="zip_code",
            new_name="auditee_zip_code",
        ),
    ]
