# Generated by Django 4.1.4 on 2023-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0015_general_cognizant_agency_over_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="amount",
            field=models.BigIntegerField(
                verbose_name="Amount Expended for the Federal Program"
            ),
        ),
    ]
