# Generated by Django 4.1.4 on 2023-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0016_rename_zip_code_auditee_auditee_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="federal_program_name",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/b; SF-SAC 2001-2003: III/10/c; SF-SAC 2004-2007: III/9/d; SF-SAC 2008-2009: III/9/d; SF-SAC 2010-2012: III/9/e; SF-SAC 2013-2015: III/6/c; SF-SAC 2016-2018: II/1/d; SF-SAC 2019-2021: II/1/d; SF-SAC 2022: II/1/d Census mapping: CFDA INFO, FEDERALPROGRAMNAME",
                max_length=300,
                null=True,
                verbose_name="Name of Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="findings_count",
            field=models.IntegerField(
                help_text="Data sources: SF-SAC 2013-2015: III/6/k; SF-SAC 2016-2018: III/1/c; SF-SAC 2019-2021: III/1/c; SF-SAC 2022: III/1/c Census mapping: CFDA INFO, FINDINGSCOUNT",
                null=True,
                verbose_name="Number of findings for the federal program (only available for audit years 2013 and beyond)",
            ),
        ),
    ]
