# Generated by Django 4.1.4 on 2023-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0016_alter_cfdainfo_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfdainfo",
            name="cluster_total",
            field=models.BigIntegerField(
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name"
            ),
        ),
        migrations.AlterField(
            model_name="cfdainfo",
            name="passthrough_amount",
            field=models.BigIntegerField(
                null=True, verbose_name="Amount passed through to subrecipients"
            ),
        ),
    ]
