# Generated by Django 4.1.4 on 2023-02-23 21:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0017_cfdainfo_nulls_for_old_data"),
    ]

    operations = [
        # This was a duplicate
        migrations.RemoveField(
            model_name="auditor",
            name="auditor_ein",
        ),
        # This is now handled with prior_agency_findings
        migrations.RemoveField(
            model_name="general",
            name="agency",
        ),
        # This is now split up into primary and secondary auditors
        migrations.RemoveField(
            model_name="general",
            name="auditor",
        ),
        # Link findings to the award info
        migrations.AddField(
            model_name="cfdainfo",
            name="Findings",
            field=models.ManyToManyField(to="data_distro.findings"),
        ),
        migrations.AddField(
            model_name="cfdainfo",
            name="agency_prior_findings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    help_text="Data sources: SF-SAC 1997-2000: III/5; SF-SAC 2001-2003: III/9; SF-SAC 2004-2007: III/8; SF-SAC 2008-2009: III/8; SF-SAC 2010-2012: III/8; SF-SAC 2013-2015: III/5; SF-SAC 2016-2018: III/3/d; SF-SAC 2019-2021: III/3/d; SF-SAC 2022: III/3/d Census mapping: AGENCIES, AGENCY",
                    null=True,
                    verbose_name="Federal Agencies with Current or Prior Year Audit Findings on Direct Awards. An empty list means None.",
                ),
                null=True,
                size=None,
            ),
        ),
        # Making sure everything links to general for easy data pulling
        migrations.AddField(
            model_name="general",
            name="findings_text",
            field=models.ManyToManyField(to="data_distro.findingstext"),
        ),
        migrations.AddField(
            model_name="general",
            name="primary_auditor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_auditor",
                to="data_distro.auditor",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="secondary_auditors",
            field=models.ManyToManyField(
                related_name="secondary_auditor", to="data_distro.auditor"
            ),
        ),
        # This isn't being used at the moment, but would like to add it back in a new iteration
        migrations.AlterField(
            model_name="agencies",
            name="agency_cfda",
            field=models.IntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/5; SF-SAC 2001-2003: III/9; SF-SAC 2004-2007: III/8; SF-SAC 2008-2009: III/8; SF-SAC 2010-2012: III/8; SF-SAC 2013-2015: III/5; SF-SAC 2016-2018: III/3/d; SF-SAC 2019-2021: III/3/d; SF-SAC 2022: III/3/d Census mapping: AGENCIES, AGENCYCFDA",
                verbose_name="2-digit prefix of Federal Agency requiring copy of audit report",
            ),
        ),
        # spelling fix
        migrations.AlterField(
            model_name="cfdainfo",
            name="questioned_costs",
            field=models.CharField(
                help_text="Census mapping: CFDA INFO, QCOSTS2",
                max_length=40,
                null=True,
                verbose_name="Dollar amount of questioned costs (Deprecated since 2002)",
            ),
        ),
        migrations.AlterField(
            model_name="findingstext",
            name="finding_ref_nums",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2019-2021: III/5/a; SF-SAC 2022: III/5/a Census mapping: FINDINGSTEXT, FINDINGREFNUMS",
                max_length=100,
                null=True,
                verbose_name="Audit Finding Reference Number",
            ),
        ),
        # adding null
        migrations.AlterField(
            model_name="findingstext",
            name="seq_number",
            field=models.IntegerField(
                help_text="Census mapping: FINDINGSTEXT, SEQ_NUMBER",
                null=True,
                verbose_name="Order that the findings text was reported",
            ),
        ),
        # adding null
        migrations.AlterField(
            model_name="findingstext",
            name="text",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: III/5/b; SF-SAC 2022: III/5/b Census mapping: FINDINGSTEXT, TEXT",
                null=True,
                verbose_name="Content of the finding text",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency_over",
            field=models.CharField(
                help_text="Census mapping: GENERAL, COG_OVER",
                max_length=2,
                null=True,
                verbose_name="A value of 'C' means the entity was assigned a Cognizant agency (had over $50 million in total expenses). A value of 'O' means the entity was assigned a Oversight agency (had less than $50 million in total expenses)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dbkey",
            field=models.CharField(
                help_text="Census mapping: GENERAL, DBKEY",
                max_length=40,
                verbose_name="Audit Year and DBKEY (database key) combined make up the primary key. Only on records created by Census.",
            ),
        ),
        # not one-to-one-relationship
        migrations.RemoveField(
            model_name="general",
            name="findings",
        ),
        # making it many-to-many
        migrations.AddField(
            model_name="general",
            name="findings",
            field=models.ManyToManyField(to="data_distro.findings"),
        ),
    ]
