# Generated by Django 4.1.4 on 2023-01-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0017_alter_cfdainfo_cluster_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiplecpasinfo",
            name="cpa_mail",
        ),
        migrations.AddField(
            model_name="multiplecpasinfo",
            name="cpa_email",
            field=models.CharField(
                max_length=60, null=True, verbose_name="CPA mail address (optional)"
            ),
        ),
    ]
