# Generated by Django 4.1.4 on 2023-01-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0018_remove_multiplecpasinfo_cpa_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplecpasinfo",
            name="cpa_phone",
            field=models.IntegerField(null=True, verbose_name="CPA phone number"),
        ),
    ]
