# Generated by Django 4.1.4 on 2023-02-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_distro",
            "0018_remove_auditor_auditor_ein_remove_general_agency_and_more",
        ),
    ]

    operations = [
        # rename current findings to findings_page
        migrations.RenameField(
            model_name="cfdainfo",
            old_name="findings",
            new_name="findings_page",
        ),
        # this needed to be many to many
        migrations.RemoveField(
            model_name="cfdainfo",
            name="Findings",
        ),
        # add many to many
        migrations.AddField(
            model_name="cfdainfo",
            name="findings",
            field=models.ManyToManyField(to="data_distro.findings"),
        ),
    ]
