# Generated by Django 4.1.4 on 2023-02-24 18:41
# naming standardization, removing unnecessary abbreviations, simplifying id names,
# many to many for Findings text

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0019_differentiate_findings_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="captext",
            old_name="finding_ref_nums",
            new_name="finding_ref_number",
        ),
        migrations.RenameField(
            model_name="captext",
            old_name="seq_number",
            new_name="sequence_number",
        ),
        migrations.RenameField(
            model_name="cfdainfo",
            old_name="cfda",
            new_name="agency_cfda",
        ),
        migrations.RenameField(
            model_name="cfdainfo",
            old_name="cfda_program_name",
            new_name="agency_name",
        ),
        migrations.RenameField(
            model_name="cfdainfo",
            old_name="agency_prior_findings",
            new_name="agency_prior_findings_list",
        ),
        migrations.RenameField(
            model_name="cfdainfo",
            old_name="elec_audits_id",
            new_name="audit_id",
        ),
        migrations.RenameField(
            model_name="cfdainfo",
            old_name="auditor_ein",
            new_name="cpa_ein",
        ),
        migrations.RenameField(
            model_name="cfdainfo",
            old_name="finding_ref_nums",
            new_name="finding_ref_numbers",
        ),
        migrations.RenameField(
            model_name="findings",
            old_name="elec_audit_findings_id",
            new_name="audit_findings_id",
        ),
        migrations.RenameField(
            model_name="findings",
            old_name="elec_audits_id",
            new_name="audit_id",
        ),
        migrations.RenameField(
            model_name="findings",
            old_name="finding_ref_nums",
            new_name="finding_ref_number",
        ),
        migrations.RenameField(
            model_name="findings",
            old_name="prior_finding_ref_nums",
            new_name="prior_finding_ref_numbers",
        ),
        migrations.RenameField(
            model_name="findingstext",
            old_name="finding_ref_nums",
            new_name="finding_ref_number",
        ),
        migrations.RenameField(
            model_name="findingstext",
            old_name="seq_number",
            new_name="seqence_number",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="completed_on",
            new_name="completed_date",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="date_firewall",
            new_name="date_published",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="previous_date_firewall",
            new_name="previous_date_published",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="sp_framework",
            new_name="special_framework",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="sp_framework_required",
            new_name="special_framework_required",
        ),
        migrations.RenameField(
            model_name="notes",
            old_name="seq_number",
            new_name="sequence_number",
        ),
        migrations.RenameField(
            model_name="passthrough",
            old_name="elec_audits_id",
            new_name="audit_id",
        ),
        migrations.RenameField(
            model_name="revisions",
            old_name="auditinfo_explain",
            new_name="audit_info_explain",
        ),
        migrations.RenameField(
            model_name="revisions",
            old_name="elec_report_revision_id",
            new_name="revision_id",
        ),
        migrations.RenameField(
            model_name="auditor",
            old_name="seqnum",
            new_name="seqence_number",
        ),
        migrations.AddField(
            model_name="agencies",
            name="agency_aln",
            field=models.CharField(
                max_length=40,
                null=True,
                verbose_name="Assistance Listing Number (ALN), a 2-digit prefix of Federal Agency",
            ),
        ),
        migrations.AddField(
            model_name="agencies",
            name="federal_program_name",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/b; SF-SAC 2001-2003: III/10/c; SF-SAC 2004-2007: III/9/d; SF-SAC 2008-2009: III/9/d; SF-SAC 2010-2012: III/9/e; SF-SAC 2013-2015: III/6/c; SF-SAC 2016-2018: II/1/d; SF-SAC 2019-2021: II/1/d; SF-SAC 2022: II/1/d Census mapping: CFDA INFO, FEDERALPROGRAMNAME",
                max_length=300,
                null=True,
                verbose_name="Name of Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="agencies",
            name="agency_cfda",
            field=models.IntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/5; SF-SAC 2001-2003: III/9; SF-SAC 2004-2007: III/8; SF-SAC 2008-2009: III/8; SF-SAC 2010-2012: III/8; SF-SAC 2013-2015: III/5; SF-SAC 2016-2018: III/3/d; SF-SAC 2019-2021: III/3/d; SF-SAC 2022: III/3/d Census mapping: AGENCIES, AGENCYCFDA",
                null=True,
                verbose_name="Catalog of Federal Domestic Assistance (CFDA) code, a 2-digit prefix of Federal Agency requiring copy of audit.",
            ),
        ),
        # This is becoming many to many
        migrations.RemoveField(
            model_name="findings",
            name="findings_text",
        ),
        # verbose_name update
        migrations.AlterField(
            model_name="general",
            name="material_weakness_major_program",
            field=models.BooleanField(
                help_text="Data sources: SF-SAC 2001-2003: III/6; SF-SAC 2004-2007: III/5; SF-SAC 2008-2009: III/5; SF-SAC 2010-2012: III/5 Census mapping: GENERAL, MATERIALWEAKNESS_MP",
                null=True,
                verbose_name="Indicate whether any reportable condition/significant deficiency was disclosed as a material weakness for a major program in the Schedule of Findings and Questioned Costs",
            ),
        ),
        # verbose_name update
        migrations.AlterField(
            model_name="revisions",
            name="notes_to_sefa",
            field=models.CharField(
                help_text="Census mapping: REVISIONS, NOTESTOSEFA",
                max_length=50,
                null=True,
                verbose_name="Indicates what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
            ),
        ),
        # verbose_name update
        migrations.AlterField(
            model_name="revisions",
            name="notes_to_sefa_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, NOTESTOSEFA_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
            ),
        ),
        migrations.AddField(
            model_name="findings",
            name="findings_text",
            field=models.ManyToManyField(to="data_distro.findingstext"),
        ),
    ]
