# Generated by Django 4.1.4 on 2023-01-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0020_alter_multiplecpasinfo_cpa_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplecpasinfo",
            name="seqnum",
            field=models.IntegerField(
                null=True,
                verbose_name="Order that Auditors were reported on page 5 of SF-SAC",
            ),
        ),
    ]
