# Generated by Django 4.1.4 on 2023-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0020_renames_and_Findings_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditor",
            name="seqence_number",
            field=models.IntegerField(
                help_text="Census mapping: GENERAL, SEQNUM (AND) Census mapping: MULTIPLE CPAS INFO, SEQNUM",
                null=True,
                verbose_name="Order that Auditors were reported on page 5 of SF-SAC (only for secondary_auditors)",
            ),
        ),
    ]
