# Generated by Django 4.1.4 on 2023-02-24 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0021_alter_auditor_seqence_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Agencies",
            new_name="Agency",
        ),
        migrations.RenameModel(
            old_name="CfdaInfo",
            new_name="FederalAward",
        ),
        migrations.RenameModel(
            old_name="Findings",
            new_name="Finding",
        ),
        migrations.RenameModel(
            old_name="Findingstext",
            new_name="FindingText",
        ),
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
        migrations.RenameModel(
            old_name="Revisions",
            new_name="Revision",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="cfda",
            new_name="federal_awards",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="notes",
            new_name="note",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="revisions",
            new_name="revision",
        ),
    ]
