# Generated by Django 4.1.4 on 2023-01-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0021_alter_multiplecpasinfo_seqnum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisions",
            name="other_explain",
            field=models.TextField(
                verbose_name="Explanation of what other miscellaneous items were edited during the revision"
            ),
        ),
    ]
