# Generated by Django 4.1.4 on 2023-01-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0022_alter_revisions_other_explain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisions",
            name="auditinfo_explain",
            field=models.TextField(
                verbose_name="Explanation of what items on the Audit Info page were edited during the revision"
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="federal_awards_explain",
            field=models.TextField(
                verbose_name="Explanation of what items on the Federal Awards page were edited during the revision"
            ),
        ),
    ]
