# Generated by Django 4.1.4 on 2023-01-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0023_alter_revisions_auditinfo_explain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisions",
            name="cap_explain",
            field=models.TextField(
                verbose_name="Explanation of what items on the CAP Text page were edited during the revision"
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="findings_explain",
            field=models.TextField(
                verbose_name="Explanation of what items on the Findings page were edited during the revision"
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="findings_text_explain",
            field=models.TextField(
                verbose_name="Explanation of what items on the Text of the Audit Findings page were edited during the revision"
            ),
        ),
        migrations.AlterField(
            model_name="revisions",
            name="notes_to_sefa_explain",
            field=models.TextField(
                verbose_name="Explanation of what items on the Notes to SEFA page were edited during the revision"
            ),
        ),
    ]
