# Generated by Django 4.1.4 on 2023-01-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0024_alter_revisions_cap_explain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency",
            field=models.IntegerField(
                null=True,
                verbose_name="Two digit Federal agency prefix of the cognizant agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="previous_completed_on",
            field=models.DateField(
                null=True,
                verbose_name="Date the Audit was Previously Posted to the Internet as Complete",
            ),
        ),
    ]
