# Generated by Django 4.1.4 on 2023-02-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0024_add_sql_docs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="general_info_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, GENINFO_EXPLAIN",
                null=True,
                verbose_name="Explanation of what items on the General Info page were edited during the revision",
            ),
        ),
    ]
