# Generated by Django 4.1.4 on 2023-01-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0025_alter_general_cognizant_agency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency",
            field=models.CharField(
                max_length=2,
                null=True,
                verbose_name="Two digit Federal agency prefix of the cognizant agency",
            ),
        ),
    ]
