# Generated by Django 4.1.4 on 2023-01-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0026_alter_general_cognizant_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency_over",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
