# Generated by Django 4.1.4 on 2023-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0027_alter_general_cognizant_agency_over"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="ein_subcode",
            field=models.IntegerField(
                null=True, verbose_name="Subcode assigned to the EIN"
            ),
        ),
    ]
