# Generated by Django 4.1.4 on 2023-01-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0028_alter_general_ein_subcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="auditee_phone",
            field=models.PositiveBigIntegerField(verbose_name="Auditee Phone Number"),
        ),
        migrations.AlterField(
            model_name="general",
            name="cpa_phone",
            field=models.PositiveBigIntegerField(verbose_name="CPA phone number"),
        ),
        migrations.AlterField(
            model_name="general",
            name="duns",
            field=models.IntegerField(
                null=True, verbose_name="Primary Data Universal Numbering System Number"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="number_months",
            field=models.IntegerField(
                null=True,
                verbose_name="Number of Months Covered by the 'Other' Audit Period",
            ),
        ),
        migrations.AlterField(
            model_name="multiplecpasinfo",
            name="cpa_phone",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="CPA phone number"
            ),
        ),
    ]
