# Generated by Django 4.1.4 on 2023-01-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_distro",
            "0029_alter_general_auditee_phone_alter_general_cpa_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="auditee_fax",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Auditee Fax Number (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cpa_fax",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="CPA fax number (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="multiplecpasinfo",
            name="cpa_fax",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="CPA fax number (optional)"
            ),
        ),
    ]
