# Generated by Django 4.1.4 on 2023-01-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_distro",
            "0030_alter_general_auditee_fax_alter_general_cpa_fax_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="cpa_foreign",
            field=models.CharField(
                max_length=200, null=True, verbose_name="CPA Address - if international"
            ),
        ),
    ]
