# Generated by Django 4.1.7 on 2023-03-22 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0030_add_api_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditor",
            old_name="seqence_number",
            new_name="sequence_number",
        ),
        migrations.RenameField(
            model_name="findingtext",
            old_name="seqence_number",
            new_name="sequence_number",
        ),
    ]
