# Generated by Django 4.1.4 on 2023-01-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0031_alter_general_cpa_foreign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="street2",
            field=models.CharField(
                max_length=45, null=True, verbose_name="Auditee Street Address"
            ),
        ),
    ]
