# Generated by Django 4.1.4 on 2023-01-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0032_alter_general_street2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="cpa_street2",
            field=models.CharField(
                max_length=45, null=True, verbose_name="CPA Street Address"
            ),
        ),
    ]
