# Generated by Django 4.1.4 on 2023-01-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0034_alter_general_sp_framework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="form_date_received",
            field=models.DateField(
                null=True,
                verbose_name="The most Recent Date the Form SF-SAC was received by the FAC. This field was not populated before 2001.",
            ),
        ),
    ]
