# Generated by Lindsay 2023-04-07

from django.db import migrations

from data_distro.management.commands.create_docs import Command


class Migration(migrations.Migration):
    dependencies = [
        ("data_distro", "0034_API_improvements"),
    ]

    operations = [
        migrations.RunPython(Command),
    ]
