# Generated by Django 4.1.4 on 2023-01-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0035_alter_general_form_date_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="type_report_financial_statements",
            field=models.CharField(
                max_length=40,
                null=True,
                verbose_name="Type of Report Issued on the Financial Statements",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="type_report_major_program",
            field=models.CharField(
                max_length=40,
                null=True,
                verbose_name="Type of Report Issued on the Major Program Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="type_report_special_purpose_framework",
            field=models.CharField(
                max_length=40,
                null=True,
                verbose_name="The auditor's opinion on the special purpose framework",
            ),
        ),
    ]
