# Generated by Django 4.1.4 on 2023-01-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0036_alter_general_type_report_financial_statements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="auditee_email",
            field=models.CharField(
                max_length=60, null=True, verbose_name="Auditee Email address"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="oversight_agency",
            field=models.IntegerField(
                null=True,
                verbose_name="Two digit Federal agency prefix of the oversight agency",
            ),
        ),
    ]
