# Generated by Django 4.1.4 on 2023-01-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0037_alter_general_auditee_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="cpa_country",
            field=models.CharField(max_length=6, null=True, verbose_name="CPA Country"),
        ),
        migrations.AlterField(
            model_name="general",
            name="cpa_email",
            field=models.CharField(
                max_length=60, null=True, verbose_name="CPA email address"
            ),
        ),
    ]
