# Generated by Django 4.1.4 on 2023-01-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0038_alter_general_cpa_country_alter_general_cpa_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="dollar_threshold",
            field=models.FloatField(
                null=True,
                verbose_name="Dollar Threshold to distinguish between Type A and Type B programs.",
            ),
        ),
    ]
