# Generated by Django 4.1.4 on 2023-01-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_distro", "0039_alter_general_dollar_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="total_fed_expenditures",
            field=models.BigIntegerField(verbose_name="Total Federal Expenditures"),
        ),
    ]
