# Generated by Django 4.2.3 on 2023-07-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("historic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ELECAUDITS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID", models.CharField(max_length=40)),
                ("AUDITYEAR", models.CharField(max_length=40)),
                ("DBKEY", models.IntegerField()),
                ("CFDASEQNUM", models.IntegerField()),
                ("CFDA", models.CharField(max_length=2)),
                ("FEDERALPROGRAMNAME", models.CharField(max_length=255)),
                ("AMOUNT", models.IntegerField()),
                ("MAJORPROGRAM", models.CharField(max_length=40)),
                ("TYPEREQUIREMENT", models.CharField(max_length=40)),
                ("QCOSTS2", models.CharField(max_length=40)),
                ("FINDINGS", models.CharField(max_length=40)),
                ("FINDINGREFNUMS", models.CharField(max_length=255)),
                ("RD", models.CharField(max_length=2)),
                ("DIRECT", models.CharField(max_length=2)),
                ("CFDA_PREFIX", models.CharField(max_length=4)),
                ("CFDA_EXT", models.CharField(max_length=4)),
                ("EIN", models.CharField(max_length=40)),
                ("CFDA2", models.CharField(max_length=2)),
                ("TYPEREPORT_MP", models.CharField(max_length=2)),
                ("TYPEREPORT_MP_OVERRIDE", models.CharField(max_length=2)),
                ("ARRA", models.CharField(max_length=40)),
                ("LOANS", models.CharField(max_length=2)),
                ("ELECAUDITSID", models.IntegerField()),
                ("FINDINGSCOUNT", models.IntegerField()),
                ("LOANBALANCE", models.IntegerField()),
                ("PASSTHROUGHAMOUNT", models.IntegerField()),
                ("AWARDIDENTIFICATION", models.CharField(max_length=255)),
                ("CLUSTERNAME", models.CharField(max_length=255)),
                ("PASSTHROUGHAWARD", models.CharField(max_length=4)),
                ("STATECLUSTERNAME", models.CharField(max_length=255)),
                ("PROGRAMTOTAL", models.IntegerField()),
                ("CLUSTERTOTAL", models.IntegerField()),
                ("OTHERCLUSTERNAME", models.CharField(max_length=255)),
                ("CFDAPROGRAMNAME", models.CharField(max_length=255)),
                ("UEI", models.CharField(max_length=40)),
                ("MULTIPLEUEIS", models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name="elecauditheader",
            name="NUMBERMONTHS",
        ),
    ]
