# Generated by Django 4.2.3 on 2023-08-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("historic", "0002_elecaudits_remove_elecauditheader_numbermonths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elecauditheader",
            name="COGAGENCY",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="elecauditheader",
            name="CPASTATE",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="elecauditheader",
            name="STATE",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="elecaudits",
            name="CFDA_EXT",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="elecaudits",
            name="CFDA_PREFIX",
            field=models.CharField(max_length=2),
        ),
    ]
