@api_user_id = 61ba59b2-f545-4c2f-9b24-9655c706a06c

###
GET http://localhost:3000/audit_access
// Have to use the JWT when testing locally.
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}     
accept-profile: admin_api_v1_0_0

###
GET http://localhost:3000/singleauditchecklist
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}     
accept-profile: admin_api_v1_0_0


###
GET http://localhost:3000/singleauditchecklist
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}     
accept-profile: admin_api_v1_0_0
x-api-roles: "fac_gov_admin_access"


###
// This should list everything using a view.
GET http://localhost:3000/tribal_access
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}     
accept-profile: admin_api_v1_0_0
x-api-roles: "fac_gov_admin_access"
X-Api-User-Id: {{api_user_id}}


###
// Call the RPC to add access
POST http://localhost:3000/rpc/add_tribal_access_email
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
content-profile: admin_api_v1_0_0
content-type: application/json 
Prefer: params=single-object
x-api-roles: "fac_gov_admin_access"
X-Api-User-Id: {{api_user_id}}

{
    "email": "darth.vader@deathstar.org"
}

### 
// Call the RPC to remove access
POST http://localhost:3000/rpc/add_tribal_access_emails
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
content-profile: admin_api_v1_0_0
content-type: application/json 
Prefer: params=single-object
x-api-roles: "fac_gov_admin_access"
X-Api-User-Id: {{api_user_id}}

{
    "emails": [
        "darth.vader@deathstar.org",
        "bob.darth.vader@deathstar.org",
        "darthy.vader@deathstar.org",
        "bob@deathstar.org"
    ]
}

### 
// Call the RPC to remove access
POST http://localhost:3000/rpc/remove_tribal_access_email
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
content-profile: admin_api_v1_0_0
content-type: application/json 
Prefer: params=single-object
x-api-roles: "fac_gov_admin_access"
X-Api-User-Id: {{api_user_id}}

{
    "email": "darth.vader@deathstar.org"
}


### 
// Call the RPC to remove access
POST http://localhost:3000/rpc/remove_tribal_access_emails
authorization: Bearer {{$processEnv CYPRESS_API_GOV_JWT}}
content-profile: admin_api_v1_0_0
content-type: application/json 
Prefer: params=single-object
x-api-roles: "fac_gov_admin_access"
X-Api-User-Id: {{api_user_id}}

{
    "emails": [
        "darth.vader@deathstar.org",
        "bob.darth.vader@deathstar.org",
        "darthy.vader@deathstar.org",
        "bob@deathstar.org"
    ]
}
