# Generated by Django 4.2.3 on 2023-09-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalUei",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
                ("additional_uei", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CapText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contains_chart_or_table",
                    models.TextField(
                        help_text="Census mapping: CAPTEXT, CHARTSTABLES",
                        verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
                    ),
                ),
                (
                    "finding_ref_number",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: IV/1; SF-SAC 2022: IV/1 Census mapping: CAPTEXT, FINDINGREFNUMS",
                        verbose_name="Audit Finding Reference Number",
                    ),
                ),
                (
                    "planned_action",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: IV/2; SF-SAC 2022: IV/2 Census mapping: CAPTEXT, TEXT",
                        verbose_name="Content of the Corrective Action Plan (CAP)",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FederalAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_award_identification",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/c; SF-SAC 2019-2021: II/1/c; SF-SAC 2022: II/1/c Census mapping: CFDA INFO, AWARDIDENTIFICATION",
                        verbose_name="Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
                    ),
                ),
                (
                    "amount_expended",
                    models.BigIntegerField(
                        help_text="Data sources: SF-SAC 1997-2000: III/6/c; SF-SAC 2001-2003: III/10/d; SF-SAC 2004-2007: III/9/e; SF-SAC 2008-2009: III/9/e; SF-SAC 2010-2012: III/9/f; SF-SAC 2013-2015: III/6/d; SF-SAC 2016-2018: II/1/e; SF-SAC 2019-2021: II/1/e; SF-SAC 2022: II/1/e Census mapping: CFDA INFO, AMOUNT",
                        verbose_name="Amount Expended for the Federal Program",
                    ),
                ),
                (
                    "award_reference",
                    models.TextField(
                        verbose_name="Order that the award line was reported"
                    ),
                ),
                (
                    "cluster_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/f; SF-SAC 2019-2021: II/1/f; SF-SAC 2022: II/1/f Census mapping: CFDA INFO, CLUSTERNAME",
                        verbose_name="The name of the cluster",
                    ),
                ),
                (
                    "cluster_total",
                    models.BigIntegerField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/h; SF-SAC 2019-2021: II/1/h; SF-SAC 2022: II/1/h Census mapping: CFDA INFO, CLUSTERTOTAL",
                        verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
                    ),
                ),
                (
                    "federal_agency_prefix",
                    models.TextField(verbose_name="2-char code refers to an agency"),
                ),
                (
                    "federal_award_extension",
                    models.TextField(
                        verbose_name="3-digit extn for a program defined by the agency"
                    ),
                ),
                (
                    "federal_program_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: III/6/b; SF-SAC 2001-2003: III/10/c; SF-SAC 2004-2007: III/9/d; SF-SAC 2008-2009: III/9/d; SF-SAC 2010-2012: III/9/e; SF-SAC 2013-2015: III/6/c; SF-SAC 2016-2018: II/1/d; SF-SAC 2019-2021: II/1/d; SF-SAC 2022: II/1/d Census mapping: CFDA INFO, FEDERALPROGRAMNAME",
                        verbose_name="Name of Federal Program",
                    ),
                ),
                (
                    "federal_program_total",
                    models.BigIntegerField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/g; SF-SAC 2019-2021: II/1/g; SF-SAC 2022: II/1/g Census mapping: CFDA INFO, PROGRAMTOTAL",
                        verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
                    ),
                ),
                (
                    "findings_count",
                    models.IntegerField(
                        help_text="Data sources: SF-SAC 2013-2015: III/6/k; SF-SAC 2016-2018: III/1/c; SF-SAC 2019-2021: III/1/c; SF-SAC 2022: III/1/c Census mapping: CFDA INFO, FINDINGSCOUNT",
                        verbose_name="Number of findings for the federal program (only available for audit years 2013 and beyond)",
                    ),
                ),
                (
                    "is_direct",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2001-2003: III/10/e; SF-SAC 2004-2007: III/9/f; SF-SAC 2008-2009: III/9/f; SF-SAC 2010-2012: III/9/g; SF-SAC 2013-2015: III/6/h; SF-SAC 2016-2018: II/1/k; SF-SAC 2019-2021: II/1/k; SF-SAC 2022: II/1/k Census mapping: CFDA INFO, DIRECT",
                        verbose_name="Indicate whether or not the award was received directly from a Federal awarding agency",
                    ),
                ),
                (
                    "is_loan",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/6/f; SF-SAC 2016-2018: II/1/i; SF-SAC 2019-2021: II/1/i; SF-SAC 2022: II/1/i Census mapping: CFDA INFO, LOANS",
                        verbose_name="Indicate whether or not the program is a Loan or Loan Guarantee (only available for audit years 2013 and beyond)",
                    ),
                ),
                (
                    "is_major",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: III/7/a; SF-SAC 2001-2003: III/10/f; SF-SAC 2004-2007: III/9/g; SF-SAC 2008-2009: III/9/g; SF-SAC 2010-2012: III/9/h; SF-SAC 2013-2015: III/6/i; SF-SAC 2016-2018: III/1/a; SF-SAC 2019-2021: III/1/a; SF-SAC 2022: III/1/a Census mapping: CFDA INFO, MAJORPROGRAM",
                        verbose_name="Indicate whether or not the Federal program is a major program",
                    ),
                ),
                (
                    "is_passthrough_award",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/n; SF-SAC 2019-2021: II/1/n; SF-SAC 2022: II/1/n Census mapping: CFDA INFO, PASSTHROUGHAWARD",
                        verbose_name="Indicates whether or not funds were passed through to any subrecipients for the Federal program",
                    ),
                ),
                (
                    "loan_balance",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/j; SF-SAC 2019-2021: II/1/j; SF-SAC 2022: II/1/j Census mapping: CFDA INFO, LOANBALANCE",
                        verbose_name="The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
                    ),
                ),
                (
                    "audit_report_type",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2004-2007: III/9/h; SF-SAC 2008-2009: III/9/h; SF-SAC 2010-2012: III/9/i; SF-SAC 2013-2015: III/6/j; SF-SAC 2016-2018: III/1/b; SF-SAC 2019-2021: III/1/b; SF-SAC 2022: III/1/b Census mapping: CFDA INFO, TYPEREPORT_MP",
                        verbose_name="Type of Report Issued on the Major Program Compliance",
                    ),
                ),
                (
                    "other_cluster_name",
                    models.TextField(
                        help_text="Census mapping: CFDA INFO, OTHERCLUSTERNAME",
                        verbose_name="The name of the cluster (if not listed in the Compliance Supplement)",
                    ),
                ),
                (
                    "passthrough_amount",
                    models.BigIntegerField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/o; SF-SAC 2019-2021: II/1/o; SF-SAC 2022: II/1/o Census mapping: CFDA INFO, PASSTHROUGHAMOUNT",
                        null=True,
                        verbose_name="Amount passed through to subrecipients",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
                (
                    "state_cluster_name",
                    models.TextField(
                        help_text="Census mapping: CFDA INFO, STATECLUSTERNAME",
                        verbose_name="The name of the state cluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_reference",
                    models.TextField(
                        verbose_name="Order that the award line was reported in Award"
                    ),
                ),
                (
                    "reference_number",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/7/d; SF-SAC 2016-2018: III/4/e; SF-SAC 2019-2021: III/4/e; SF-SAC 2022: III/4/e Census mapping: FINDINGS, FINDINGSREFNUMS",
                        verbose_name="Findings Reference Numbers",
                    ),
                ),
                (
                    "is_material_weakness",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/7/h; SF-SAC 2016-2018: III/4/i; SF-SAC 2019-2021: III/4/i; SF-SAC 2022: III/4/i Census mapping: FINDINGS, MATERIALWEAKNESS",
                        verbose_name="Material Weakness finding",
                    ),
                ),
                (
                    "is_modified_opinion",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/7/f; SF-SAC 2016-2018: III/4/g; SF-SAC 2019-2021: III/4/g; SF-SAC 2022: III/4/g Census mapping: FINDINGS, MODIFIEDOPINION",
                        verbose_name="Modified Opinion finding",
                    ),
                ),
                (
                    "is_other_findings",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/7/j; SF-SAC 2016-2018: III/4/k; SF-SAC 2019-2021: III/4/k; SF-SAC 2022: III/4/k Census mapping: FINDINGS, OTHERFINDINGS",
                        verbose_name="Other findings",
                    ),
                ),
                (
                    "is_other_matters",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/7/g; SF-SAC 2016-2018: III/4/h; SF-SAC 2019-2021: III/4/h; SF-SAC 2022: III/4/h Census mapping: FINDINGS, OTHERNONCOMPLIANCE",
                        verbose_name="Other non-compliance",
                    ),
                ),
                (
                    "is_questioned_costs",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/7/k; SF-SAC 2016-2018: III/4/l; SF-SAC 2019-2021: III/4/l; SF-SAC 2022: III/4/l Census mapping: FINDINGS, QCOSTS",
                        verbose_name="Questioned Costs",
                    ),
                ),
                (
                    "is_repeat_finding",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: III/4/m; SF-SAC 2019-2021: III/4/m; SF-SAC 2022: III/4/m Census mapping: FINDINGS, REPEATFINDING",
                        verbose_name="Indicates whether or not the audit finding was a repeat of an audit finding in the immediate prior audit",
                    ),
                ),
                (
                    "is_significant_deficiency",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: II/3; SF-SAC 2001-2003: II/3; SF-SAC 2004-2007: II/3; SF-SAC 2008-2009: II/3; SF-SAC 2010-2012: II/3; SF-SAC 2013-2015: II/3; SF-SAC 2016-2018: III/2/c; SF-SAC 2019-2021: III/2/c; SF-SAC 2022: III/2/c Census mapping: FINDINGS, SIGNIFICANTDEFICIENCY",
                        verbose_name="Significant Deficiency finding",
                    ),
                ),
                (
                    "prior_finding_ref_numbers",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: III/4/n; SF-SAC 2019-2021: III/4/n; SF-SAC 2022: III/4/n Census mapping: FINDINGS, PRIORFINDINGREFNUMS",
                        verbose_name="Audit finding reference numbers from the immediate prior audit",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
                (
                    "type_requirement",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: FINDINGS, TYPEREQUIREMENT",
                        verbose_name="Type Requirement Failure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FindingText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
                (
                    "finding_ref_number",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: III/5/a; SF-SAC 2022: III/5/a Census mapping: FINDINGSTEXT, FINDINGREFNUMS",
                        null=True,
                        verbose_name="Finding Reference Number - FK",
                    ),
                ),
                (
                    "contains_chart_or_table",
                    models.BooleanField(
                        help_text="Census mapping: FINDINGSTEXT, CHARTSTABLES",
                        null=True,
                        verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
                    ),
                ),
                (
                    "finding_text",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: III/5/b; SF-SAC 2022: III/5/b Census mapping: FINDINGSTEXT, TEXT",
                        null=True,
                        verbose_name="Content of the finding text",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accounting_policies",
                    models.TextField(
                        verbose_name="A description of the significant accounting policies used in preparing the SEFA (2 CFR 200.510(b)(6))"
                    ),
                ),
                (
                    "is_minimis_rate_used",
                    models.TextField(
                        verbose_name="'Yes', 'No', or 'Both' (2 CFR 200.414(f))"
                    ),
                ),
                (
                    "rate_explained",
                    models.TextField(verbose_name="Explanation for minimis rate"),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, CONTENT",
                        verbose_name="Content of the Note",
                    ),
                ),
                (
                    "note_title",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, TITLE",
                        verbose_name="Note title",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passthrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_reference",
                    models.TextField(
                        verbose_name="Order that the award line was reported"
                    ),
                ),
                (
                    "report_id",
                    models.TextField(
                        verbose_name="G-FAC generated identifier. FK refers to General"
                    ),
                ),
                (
                    "passthrough_id",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/m; SF-SAC 2019-2021: II/1/m; SF-SAC 2022: II/1/m Census mapping: PASSTHROUGH, PASSTHROUGHID",
                        verbose_name="Identifying Number Assigned by the Pass-through Entity",
                    ),
                ),
                (
                    "passthrough_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: II/1/l; SF-SAC 2019-2021: II/1/l; SF-SAC 2022: II/1/l Census mapping: PASSTHROUGH, PASSTHROUGHNAME",
                        verbose_name="Name of Pass-through Entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondaryAuditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_city",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                        verbose_name="CPA City",
                    ),
                ),
                (
                    "address_state",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                        verbose_name="CPA State",
                    ),
                ),
                (
                    "address_street",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                        verbose_name="CPA Street Address",
                    ),
                ),
                (
                    "address_zipcode",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                        verbose_name="CPA Zip Code",
                    ),
                ),
                (
                    "auditor_ein",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                        verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
                    ),
                ),
                (
                    "auditor_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/a; SF-SAC 2001-2003: I/7/a; SF-SAC 2004-2007: I/7/a; SF-SAC 2008-2009: I/6/a; SF-SAC 2010-2012: I/6/a; SF-SAC 2013-2015: I/6/a; SF-SAC 2016-2018: I/6/a; SF-SAC 2019-2021: I/6/a; SF-SAC 2022: I/6/a Census mapping: GENERAL, CPAFIRMNAME (AND) Data sources: SF-SAC 2008-2009: I/8/a; SF-SAC 2010-2012: I/8/a; SF-SAC 2013-2015: I/8/a; SF-SAC 2016-2018: I/8/a; SF-SAC 2019-2021: I/6/h/i; SF-SAC 2022: I/6/h/i Census mapping: MULTIPLE CPAS INFO, CPAFIRMNAME",
                        verbose_name="CPA Firm Name",
                    ),
                ),
                (
                    "contact_email",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                        verbose_name="CPA mail address (optional)",
                    ),
                ),
                ("contact_name", models.TextField(verbose_name="Name of CPA Contact")),
                (
                    "contact_phone",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/d; SF-SAC 2001-2003: I/7/d; SF-SAC 2004-2007: I/7/d; SF-SAC 2008-2009: I/6/d; SF-SAC 2010-2012: I/6/d; SF-SAC 2013-2015: I/6/e; SF-SAC 2016-2018: I/6/e; SF-SAC 2019-2021: I/6/e; SF-SAC 2022: I/6/e Census mapping: GENERAL, CPAPHONE (AND) Data sources: SF-SAC 2008-2009: I/8/d; SF-SAC 2010-2012: I/8/d; SF-SAC 2013-2015: I/8/i; SF-SAC 2016-2018: I/8/i; SF-SAC 2019-2021: I/6/h/ix; SF-SAC 2022: I/6/h/ix Census mapping: MULTIPLE CPAS INFO, CPAPHONE",
                        verbose_name="CPA phone number",
                    ),
                ),
                (
                    "contact_title",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                        verbose_name="Title of CPA Contact",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(
                        unique=True, verbose_name="G-FAC generated identifier. "
                    ),
                ),
                (
                    "auditee_certify_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYNAME",
                        verbose_name="Name of Auditee Certifying Official",
                    ),
                ),
                (
                    "auditee_certify_title",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYTITLE",
                        verbose_name="Title of Auditee Certifying Official",
                    ),
                ),
                (
                    "auditee_contact_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEECONTACT",
                        verbose_name="Name of Auditee Contact",
                    ),
                ),
                (
                    "auditee_email",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/f; SF-SAC 2001-2003: I/6/f; SF-SAC 2004-2007: I/6/f; SF-SAC 2008-2009: I/5/f; SF-SAC 2010-2012: I/5/f; SF-SAC 2013-2015: I/5/f; SF-SAC 2016-2018: I/5/e; SF-SAC 2019-2021: I/5/e; SF-SAC 2022: I/5/e Census mapping: GENERAL, AUDITEEEMAIL",
                        verbose_name="Auditee Email address",
                    ),
                ),
                (
                    "auditee_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/a; SF-SAC 2001-2003: I/6/a; SF-SAC 2004-2007: I/6/a; SF-SAC 2008-2009: I/5/a; SF-SAC 2010-2012: I/5/a; SF-SAC 2013-2015: I/5/a; SF-SAC 2016-2018: I/5/a; SF-SAC 2019-2021: I/5/a; SF-SAC 2022: I/5/a Census mapping: GENERAL, AUDITEENAME",
                        verbose_name="Name of the Auditee",
                    ),
                ),
                (
                    "auditee_phone",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/d; SF-SAC 2001-2003: I/6/d; SF-SAC 2004-2007: I/6/d; SF-SAC 2008-2009: I/5/d; SF-SAC 2010-2012: I/5/d; SF-SAC 2013-2015: I/5/d; SF-SAC 2016-2018: I/5/d; SF-SAC 2019-2021: I/5/d; SF-SAC 2022: I/5/d Census mapping: GENERAL, AUDITEEPHONE",
                        verbose_name="Auditee Phone Number",
                    ),
                ),
                (
                    "auditee_contact_title",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEETITLE",
                        verbose_name="Title of Auditee Contact",
                    ),
                ),
                (
                    "auditee_address_line_1",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, STREET1",
                        verbose_name="Auditee Street Address",
                    ),
                ),
                (
                    "auditee_city",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, CITY",
                        verbose_name="Auditee City",
                    ),
                ),
                (
                    "auditee_state",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, STATE",
                        verbose_name="Auditee State",
                    ),
                ),
                (
                    "auditee_ein",
                    models.TextField(
                        verbose_name="Primary Employer Identification Number"
                    ),
                ),
                (
                    "auditee_uei",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                        verbose_name="Auditee UEI",
                    ),
                ),
                ("is_additional_ueis", models.TextField()),
                (
                    "auditee_zip",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, ZIPCODE",
                        verbose_name="Auditee Zip Code",
                    ),
                ),
                (
                    "auditor_phone",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/d; SF-SAC 2001-2003: I/7/d; SF-SAC 2004-2007: I/7/d; SF-SAC 2008-2009: I/6/d; SF-SAC 2010-2012: I/6/d; SF-SAC 2013-2015: I/6/e; SF-SAC 2016-2018: I/6/e; SF-SAC 2019-2021: I/6/e; SF-SAC 2022: I/6/e Census mapping: GENERAL, CPAPHONE (AND) Data sources: SF-SAC 2008-2009: I/8/d; SF-SAC 2010-2012: I/8/d; SF-SAC 2013-2015: I/8/i; SF-SAC 2016-2018: I/8/i; SF-SAC 2019-2021: I/6/h/ix; SF-SAC 2022: I/6/h/ix Census mapping: MULTIPLE CPAS INFO, CPAPHONE",
                        verbose_name="CPA phone number",
                    ),
                ),
                (
                    "auditor_state",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                        verbose_name="CPA State",
                    ),
                ),
                (
                    "auditor_city",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                        verbose_name="CPA City",
                    ),
                ),
                (
                    "auditor_contact_title",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                        verbose_name="Title of CPA Contact",
                    ),
                ),
                (
                    "auditor_address_line_1",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                        verbose_name="CPA Street Address",
                    ),
                ),
                (
                    "auditor_zip",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                        verbose_name="CPA Zip Code",
                    ),
                ),
                (
                    "auditor_country",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACOUNTRY",
                        verbose_name="CPA Country",
                    ),
                ),
                (
                    "auditor_contact_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPACONTACT (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/g; SF-SAC 2016-2018: I/8/g; SF-SAC 2019-2021: I/6/h/vii; SF-SAC 2022: I/6/h/vii Census mapping: MULTIPLE CPAS INFO, CPACONTACT",
                        verbose_name="Name of CPA Contact",
                    ),
                ),
                (
                    "auditor_email",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                        verbose_name="CPA mail address (optional)",
                    ),
                ),
                (
                    "auditor_firm_name",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/7/a; SF-SAC 2001-2003: I/7/a; SF-SAC 2004-2007: I/7/a; SF-SAC 2008-2009: I/6/a; SF-SAC 2010-2012: I/6/a; SF-SAC 2013-2015: I/6/a; SF-SAC 2016-2018: I/6/a; SF-SAC 2019-2021: I/6/a; SF-SAC 2022: I/6/a Census mapping: GENERAL, CPAFIRMNAME (AND) Data sources: SF-SAC 2008-2009: I/8/a; SF-SAC 2010-2012: I/8/a; SF-SAC 2013-2015: I/8/a; SF-SAC 2016-2018: I/8/a; SF-SAC 2019-2021: I/6/h/i; SF-SAC 2022: I/6/h/i Census mapping: MULTIPLE CPAS INFO, CPAFIRMNAME",
                        verbose_name="CPA Firm Name",
                    ),
                ),
                (
                    "auditor_foreign_address",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAFOREIGN",
                        verbose_name="CPA Address - if international",
                    ),
                ),
                (
                    "auditor_ein",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                        verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
                    ),
                ),
                (
                    "cognizant_agency",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, COGAGENCY",
                        verbose_name="Two digit Federal agency prefix of the cognizant agency",
                    ),
                ),
                (
                    "oversight_agency",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, OVERSIGHTAGENCY",
                        verbose_name="Two digit Federal agency prefix of the oversight agency",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        help_text="Census mapping: GENERAL, INITIAL DATE RECEIVED",
                        verbose_name="The first date an audit component or Form SF-SAC was received by the Federal audit Clearinghouse (FAC).",
                    ),
                ),
                (
                    "ready_for_certification_date",
                    models.DateField(
                        verbose_name="The date at which the audit transitioned to 'ready for certification'"
                    ),
                ),
                (
                    "auditor_certified_date",
                    models.DateField(
                        verbose_name="The date at which the audit transitioned to 'auditor certified'"
                    ),
                ),
                (
                    "auditee_certified_date",
                    models.DateField(
                        verbose_name="The date at which the audit transitioned to 'auditee certified'"
                    ),
                ),
                (
                    "certified_date",
                    models.DateField(
                        verbose_name="The date at which the audit transitioned to 'certified'"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateField(
                        verbose_name="The date at which the audit transitioned to 'submitted'"
                    ),
                ),
                (
                    "fy_end_date",
                    models.DateField(
                        help_text="Data sources: SF-SAC 1997-2000: Part I, Item 1; SF-SAC 2001-2003: Part I, Item 1; SF-SAC 2004-2007: Part I, Item 1; SF-SAC 2008-2009: Part I, Item 1; SF-SAC 2010-2012: Part I, Item 1; SF-SAC 2013-2015: Part I, Item 1; SF-SAC 2016-2018: Part I, Item 1; SF-SAC 2019-2021: I/1/b; SF-SAC 2022: I/1/b Census mapping: GENERAL, FYENDDATE",
                        verbose_name="Fiscal Year End Date",
                    ),
                ),
                (
                    "fy_start_date",
                    models.DateField(
                        help_text="Data sources: SF-SAC 2019-2021: Part I, Item 1(a); SF-SAC 2022: Part I, Item 1(a) Census mapping: GENERAL, FYSTARTDATE",
                        verbose_name="Fiscal Year Start Date",
                    ),
                ),
                (
                    "audit_year",
                    models.TextField(
                        help_text="Census mapping: GENERAL, AUDITYEAR",
                        verbose_name="Audit year from fy_start_date.",
                    ),
                ),
                (
                    "audit_type",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/2; SF-SAC 2001-2003: I/2; SF-SAC 2004-2007: I/2; SF-SAC 2008-2009: I/2; SF-SAC 2010-2012: I/2; SF-SAC 2013-2015: I/2; SF-SAC 2016-2018: I/2; SF-SAC 2019-2021: I/2; SF-SAC 2022: I/2 Census mapping: GENERAL, AUDITTYPE",
                        verbose_name="Type of Audit",
                    ),
                ),
                (
                    "gaap_results",
                    models.TextField(verbose_name="GAAP Results by Auditor"),
                ),
                (
                    "sp_framework_basis",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: III/2/a/ii; SF-SAC 2019-2021: III/2/a/i; SF-SAC 2022: III/2/a/i Census mapping: GENERAL, SP_FRAMEWORK",
                        verbose_name="Special Purpose Framework that was used as the basis of accounting",
                    ),
                ),
                (
                    "is_sp_framework_required",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: III/2/a/iii; SF-SAC 2019-2021: III/2/a/ii; SF-SAC 2022: III/2/a/ii Census mapping: GENERAL, SP_FRAMEWORK_REQUIRED",
                        verbose_name="Indicate whether or not the special purpose framework used as basis of accounting by state law or tribal law",
                    ),
                ),
                (
                    "sp_framework_opinions",
                    models.TextField(
                        help_text="Data sources: SF-SAC 2016-2018: III/2/a/iv; SF-SAC 2019-2021: III/2/a/iii; SF-SAC 2022: III/2/a/iii Census mapping: GENERAL, TYPEREPORT_SP_FRAMEWORK",
                        verbose_name="The auditor's opinion on the special purpose framework",
                    ),
                ),
                (
                    "is_going_concern_included",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: II/2; SF-SAC 2001-2003: II/2; SF-SAC 2004-2007: II/2; SF-SAC 2008-2009: II/2; SF-SAC 2010-2012: II/2; SF-SAC 2013-2015: II/2; SF-SAC 2016-2018: III/2/b; SF-SAC 2019-2021: III/2/b; SF-SAC 2022: III/2/b Census mapping: GENERAL, GOINGCONCERN",
                        verbose_name="Whether or not the audit contained a going concern paragraph on financial statements",
                    ),
                ),
                (
                    "is_internal_control_deficiency_disclosed",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: II/3; SF-SAC 2001-2003: II/3; SF-SAC 2004-2007: II/3; SF-SAC 2008-2009: II/3; SF-SAC 2010-2012: II/3; SF-SAC 2013-2015: II/3; SF-SAC 2016-2018: III/2/c; SF-SAC 2019-2021: III/2/c; SF-SAC 2022: III/2/c Census mapping: GENERAL, SIGNIFICANTDEFICIENCY",
                        verbose_name="Whether or not the audit disclosed a significant deficiency on financial statements",
                    ),
                ),
                (
                    "is_internal_control_material_weakness_disclosed",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: II/4; SF-SAC 2001-2003: II/4; SF-SAC 2004-2007: II/4; SF-SAC 2008-2009: II/4; SF-SAC 2010-2012: II/4; SF-SAC 2013-2015: II/4; SF-SAC 2016-2018: III/2/d; SF-SAC 2019-2021: III/2/d; SF-SAC 2022: III/2/d Census mapping: GENERAL, MATERIALWEAKNESS"
                    ),
                ),
                (
                    "is_material_noncompliance_disclosed",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: II/5; SF-SAC 2001-2003: II/5; SF-SAC 2004-2007: II/5; SF-SAC 2008-2009: II/5; SF-SAC 2010-2012: II/5; SF-SAC 2013-2015: II/5; SF-SAC 2016-2018: III/2/e; SF-SAC 2019-2021: III/2/e; SF-SAC 2022: III/2/e Census mapping: GENERAL, MATERIALNONCOMPLIANCE",
                        verbose_name="Whether or not the audit disclosed a material noncompliance on financial statements",
                    ),
                ),
                ("is_aicpa_audit_guide_included", models.TextField()),
                (
                    "dollar_threshold",
                    models.BigIntegerField(
                        help_text="Data sources: SF-SAC 1997-2000: III/2; SF-SAC 2001-2003: III/3; SF-SAC 2004-2007: III/2; SF-SAC 2008-2009: III/2; SF-SAC 2010-2012: III/2; SF-SAC 2013-2015: III/2; SF-SAC 2016-2018: III/3/b; SF-SAC 2019-2021: III/3/b; SF-SAC 2022: III/3/b Census mapping: GENERAL, DOLLARTHRESHOLD",
                        verbose_name="Dollar Threshold to distinguish between Type A and Type B programs.",
                    ),
                ),
                (
                    "is_low_risk_auditee",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: III/3; SF-SAC 2001-2003: III/4; SF-SAC 2004-2007: III/3; SF-SAC 2008-2009: III/3; SF-SAC 2010-2012: III/3; SF-SAC 2013-2015: III/3; SF-SAC 2016-2018: III/3/c; SF-SAC 2019-2021: III/3/c; SF-SAC 2022: III/3/c Census mapping: GENERAL, LOWRISK",
                        verbose_name="Indicate whether or not the auditee qualified as a low-risk auditee",
                    ),
                ),
                (
                    "agencies_with_prior_findings",
                    models.TextField(
                        verbose_name="List of agencues with prior findings"
                    ),
                ),
                (
                    "entity_type",
                    models.TextField(
                        help_text="Census mapping: GENERAL, ENTITY_TYPE",
                        verbose_name="Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
                    ),
                ),
                (
                    "number_months",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/3; SF-SAC 2001-2003: I/3; SF-SAC 2004-2007: I/3; SF-SAC 2008-2009: I/3; SF-SAC 2010-2012: I/3; SF-SAC 2013-2015: I/3; SF-SAC 2016-2018: I/3; SF-SAC 2019-2021: I/3; SF-SAC 2022: I/3 Census mapping: GENERAL, NUMBERMONTHS",
                        verbose_name="Number of Months Covered by the 'Other' Audit Period",
                    ),
                ),
                (
                    "audit_period_covered",
                    models.TextField(
                        help_text="Data sources: SF-SAC 1997-2000: I/3; SF-SAC 2001-2003: I/3; SF-SAC 2004-2007: I/3; SF-SAC 2008-2009: I/3; SF-SAC 2010-2012: I/3; SF-SAC 2013-2015: I/3; SF-SAC 2016-2018: I/3; SF-SAC 2019-2021: I/3; SF-SAC 2022: I/3 Census mapping: GENERAL, PERIODCOVERED",
                        verbose_name="Audit Period Covered by Audit",
                    ),
                ),
                (
                    "total_amount_expended",
                    models.BigIntegerField(
                        help_text="Data sources: SF-SAC 1997-2000: III/6/c- Total; SF-SAC 2001-2003: III/10/d -Total; SF-SAC 2004-2007: III/9/e -Total; SF-SAC 2008-2009: III/9/e -Total; SF-SAC 2010-2012: III/9/f -Total; SF-SAC 2013-2015: III/6/d -Total; SF-SAC 2016-2018: II/1/e- Total; SF-SAC 2019-2021: II/1/e - Total; SF-SAC 2022: II/1/e - Total Census mapping: GENERAL, TOTFEDEXPEND",
                        verbose_name="Total Federal Expenditures",
                    ),
                ),
                (
                    "type_audit_code",
                    models.TextField(verbose_name="Determines if audit is A133 or UG"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        verbose_name="True for public records, False for non-public records",
                    ),
                ),
                (
                    "data_source",
                    models.TextField(
                        verbose_name="Data origin; GSA, Census, or TESTDATA"
                    ),
                ),
            ],
            options={
                "unique_together": {("report_id",)},
            },
        ),
    ]
