# Generated by Django 4.2.1 on 2023-07-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finding",
            name="is_other_matters",
        ),
        migrations.AddField(
            model_name="finding",
            name="is_other_non_compliance",
            field=models.BooleanField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/g; SF-SAC 2016-2018: III/4/h; SF-SAC 2019-2021: III/4/h; SF-SAC 2022: III/4/h Census mapping: FINDINGS, OTHERNONCOMPLIANCE",
                null=True,
                verbose_name="Other non-compliance",
            ),
        ),
    ]
