# Generated by Django 4.2.1 on 2023-07-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="audit_year",
            field=models.IntegerField(
                help_text="Census mapping: GENERAL, AUDITYEAR",
                verbose_name="Audit year from fy_start_date.",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="audit_year",
            field=models.IntegerField(
                help_text="Census mapping: REVISIONS, AUDITYEAR",
                verbose_name="Audit year from fy_start_date",
            ),
        ),
    ]
