# Generated by Django 4.2.5 on 2023-09-27 18:56

from django.db import migrations, models


# Copies the values of submitted_date to fac_accepted_date
def copy_submitted_to_accepted(apps, schema_editor):
    General = apps.get_model("dissemination", "General")
    for report in General.objects.all():
        if not report.fac_accepted_date:
            report.fac_accepted_date = report.submitted_date
            report.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="fac_accepted_date",
            field=models.DateField(
                verbose_name="The date at which the audit transitioned to 'accepted'",
            ),
        ),
        migrations.RunPython(copy_submitted_to_accepted),
    ]
