# Generated by Django 4.2.3 on 2023-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalEin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(verbose_name="; foreign key everywhere else"),
                ),
                ("additional_ein", models.TextField()),
            ],
        ),
    ]
