# Generated by Django 4.2.1 on 2023-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="federalaward",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="federalaward",
            name="award_seq_number",
            field=models.IntegerField(
                null=True, verbose_name="Order that the award line was reported"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="federalaward",
            unique_together={("report_id", "award_seq_number")},
        ),
    ]
