# Generated by Django 4.2.1 on 2023-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="federalaward",
            old_name="passthrough_award",
            new_name="is_passthrough_award",
        ),
        migrations.AddField(
            model_name="federalaward",
            name="passthrough_id",
            field=models.TextField(
                null=True,
                verbose_name="If no (Direct Award), Identifying Number Assigned by the Pass-through Entity, if assigned",
            ),
        ),
        migrations.AddField(
            model_name="federalaward",
            name="passthrough_name",
            field=models.TextField(
                null=True,
                verbose_name="If no (Direct Award), Name of Passthrough Entity",
            ),
        ),
    ]
