# Generated by Django 4.2.5 on 2023-09-29 17:22
# This migration removes null=True for fac_accepted_date

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0002_general_fac_accepted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="fac_accepted_date",
            field=models.DateField(
                verbose_name="The date at which the audit transitioned to 'accepted'"
            ),
        ),
    ]
