# Generated by Django 4.2.1 on 2023-07-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0002_alter_general_audit_year_alter_revision_audit_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passthrough",
            name="award_seq_number",
            field=models.CharField(
                null=True, verbose_name="Order that the award line was reported"
            ),
        ),
    ]
