# Generated by Django 4.2.1 on 2023-07-13 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0002_rename_passthrough_award_federalaward_is_passthrough_award_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="finding",
            old_name="modified_opinion",
            new_name="is_modified_opinion",
        ),
        migrations.RenameField(
            model_name="finding",
            old_name="other_findings",
            new_name="is_other_findings",
        ),
        migrations.RenameField(
            model_name="finding",
            old_name="other_non_compliance",
            new_name="is_other_matters",
        ),
        migrations.RenameField(
            model_name="finding",
            old_name="questioned_costs",
            new_name="is_questioned_costs",
        ),
        migrations.RenameField(
            model_name="finding",
            old_name="repeat_finding",
            new_name="is_repeat_finding",
        ),
    ]
