# Generated by Django 4.2.1 on 2023-06-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0002_rename_sequence_number_captext_ct_seq_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="auditor_country",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACOUNTRY",
                max_length=45,
                null=True,
                verbose_name="CPA Country",
            ),
        ),
    ]
