# Generated by Django 4.2.1 on 2023-07-14 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0002_alter_federalaward_award_seq_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="general",
            name="auditee_addl_duns_list",
        ),
        migrations.RemoveField(
            model_name="general",
            name="auditee_duns",
        ),
        migrations.RemoveField(
            model_name="general",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="ein_subcode",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_address_line_2",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_fax",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditor_address_line_2",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditor_fax",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_completed_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_component_date_received",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_previous_completed_on",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_previous_date_published",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_reportable_condition",
        ),
        migrations.RemoveField(
            model_name="general",
            name="modified_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="multiple_auditors",
        ),
        migrations.RemoveField(
            model_name="general",
            name="multiple_duns",
        ),
        migrations.RemoveField(
            model_name="general",
            name="multiple_ein",
        ),
        migrations.RemoveField(
            model_name="general",
            name="multiple_uei",
        ),
        migrations.AlterField(
            model_name="general",
            name="audit_year",
            field=models.CharField(
                help_text="Census mapping: GENERAL, AUDITYEAR",
                max_length=40,
                verbose_name="Audit Year, derived from fy_start_date.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_addl_ein_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Data sources: SF-SAC 1997-2000: I/5/a; SF-SAC 2001-2003: I/5/a; SF-SAC 2004-2007: I/5/a; SF-SAC 2008-2009: I/4/a; SF-SAC 2010-2012: I/4/a; SF-SAC 2013-2015: I/4/a; SF-SAC 2016-2018: I/4/a; SF-SAC 2019-2021: I/4/a; SF-SAC 2022: I/4/a Census mapping: GENERAL, EIN (AND) Data sources: SF-SAC 2001-2003: I/5/c; SF-SAC 2004-2007: I/5/c; SF-SAC 2008-2009: I/4/c; SF-SAC 2010-2012: I/4/c; SF-SAC 2013-2015: I/4/c; SF-SAC 2016-2018: I/4/c; SF-SAC 2019-2021: I/4/c; SF-SAC 2022: I/4/c Census mapping: EIN INFO, EIN",
                    max_length=30,
                    null=True,
                    verbose_name="Employer Identification Number",
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_ein",
            field=models.CharField(
                max_length=30,
                null=True,
                verbose_name="Primary Employer Identification Number",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_phone",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/d; SF-SAC 2001-2003: I/6/d; SF-SAC 2004-2007: I/6/d; SF-SAC 2008-2009: I/5/d; SF-SAC 2010-2012: I/5/d; SF-SAC 2013-2015: I/5/d; SF-SAC 2016-2018: I/5/d; SF-SAC 2019-2021: I/5/d; SF-SAC 2022: I/5/d Census mapping: GENERAL, AUDITEEPHONE",
                verbose_name="Auditee Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_uei",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                max_length=30,
                null=True,
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_phone",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/d; SF-SAC 2001-2003: I/7/d; SF-SAC 2004-2007: I/7/d; SF-SAC 2008-2009: I/6/d; SF-SAC 2010-2012: I/6/d; SF-SAC 2013-2015: I/6/e; SF-SAC 2016-2018: I/6/e; SF-SAC 2019-2021: I/6/e; SF-SAC 2022: I/6/e Census mapping: GENERAL, CPAPHONE (AND) Data sources: SF-SAC 2008-2009: I/8/d; SF-SAC 2010-2012: I/8/d; SF-SAC 2013-2015: I/8/i; SF-SAC 2016-2018: I/8/i; SF-SAC 2019-2021: I/6/h/ix; SF-SAC 2022: I/6/h/ix Census mapping: MULTIPLE CPAS INFO, CPAPHONE",
                null=True,
                verbose_name="CPA phone number",
            ),
        ),
    ]
