# Generated by Django 4.2.3 on 2023-09-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0002_additionalein"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="contains_chart_or_table",
            field=models.TextField(
                default="",
                help_text="Census mapping: ",
                verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
            ),
            preserve_default=False,
        ),
    ]
