# Generated by Django 4.2.1 on 2023-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0003_alter_federalaward_award_seq_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federalaward",
            name="award_seq_number",
            field=models.IntegerField(
                default=-1, verbose_name="Order that the award line was reported"
            ),
        ),
    ]
