# Generated by Django 4.2.1 on 2023-06-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0003_alter_general_auditor_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="is_public",
            field=models.BooleanField(
                null=True,
                verbose_name="True for public records, False for non-public records",
            ),
        ),
    ]
