# Generated by Django 4.2.5 on 2023-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0003_alter_general_fac_accepted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="findingtext",
            name="contains_chart_or_table",
            field=models.TextField(
                help_text="Census mapping: FINDINGSTEXT, CHARTSTABLES",
                verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
            ),
        ),
    ]
