# Generated by Django 4.2.1 on 2023-07-17 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0003_alter_passthrough_award_seq_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="federalaward",
            old_name="award_seq_number",
            new_name="award_reference",
        ),
        migrations.RenameField(
            model_name="finding",
            old_name="award_seq_number",
            new_name="award_reference",
        ),
        migrations.RenameField(
            model_name="passthrough",
            old_name="award_seq_number",
            new_name="award_reference",
        ),
        migrations.AlterUniqueTogether(
            name="federalaward",
            unique_together={("report_id", "award_reference")},
        ),
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together={("report_id", "award_reference", "finding_seq_number")},
        ),
        migrations.AlterUniqueTogether(
            name="passthrough",
            unique_together={("report_id", "award_reference", "passthrough_id")},
        ),
    ]
