# Generated by Django 4.2.1 on 2023-07-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0004_rename_award_seq_number_federalaward_award_reference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="accounting_policies",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="is_minimis_rate_used",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="rate_explained",
            field=models.TextField(null=True),
        ),
    ]
