# Generated by Django 4.2.6 on 2023-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0004_alter_findingtext_contains_chart_or_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, COGAGENCY",
                null=True,
                verbose_name="Two digit Federal agency prefix of the cognizant agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="oversight_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, OVERSIGHTAGENCY",
                null=True,
                verbose_name="Two digit Federal agency prefix of the oversight agency",
            ),
        ),
    ]
