# Generated by Django 4.2.1 on 2023-07-13 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0003_rename_modified_opinion_finding_is_modified_opinion_and_more",
        ),
        ("dissemination", "0004_alter_federalaward_award_seq_number"),
    ]

    operations = []
