# Generated by Django 4.2.1 on 2023-07-18 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0005_note_accounting_policies_note_is_minimis_rate_used_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="note_index",
        ),
        migrations.RemoveField(
            model_name="note",
            name="type_id",
        ),
    ]
