# Generated by Django 4.2.6 on 2023-12-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0006_migrationchangerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrationchangerecord",
            name="section",
            field=models.TextField(blank=True, null=True),
        ),
    ]
