# Generated by Django 4.2.1 on 2023-07-19 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0006_remove_note_note_index_remove_note_type_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="captext",
            old_name="charts_tables",
            new_name="contains_chart_or_table",
        ),
        migrations.RenameField(
            model_name="captext",
            old_name="cap_text",
            new_name="planned_action",
        ),
    ]
