# Generated by Django 4.2.6 on 2023-12-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0006_migrationchangerecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="migrationchangerecord",
            name="census_data",
        ),
        migrations.RemoveField(
            model_name="migrationchangerecord",
            name="gsa_fac_data",
        ),
        migrations.RemoveField(
            model_name="migrationchangerecord",
            name="transformation_function",
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="additionalein",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="additionaluei",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="captext",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="federalaward",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="finding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="findingtext",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="general",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="note",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="passthrough",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="secondaryauditor",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
