# Generated by Django 4.2.6 on 2023-12-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0006_migrationchangerecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="migrationchangerecord",
            name="census_data",
        ),
        migrations.RemoveField(
            model_name="migrationchangerecord",
            name="gsa_fac_data",
        ),
        migrations.RemoveField(
            model_name="migrationchangerecord",
            name="transformation_function",
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="additional_ein",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="additional_uei",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="cap_text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="federal_award",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="finding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="finding_text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="general",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="note",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="passthrough",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationchangerecord",
            name="secondary_auditor",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
