# Generated by Django 4.2.6 on 2024-01-08 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0007_remove_migrationchangerecord_census_data_and_more"),
        ("dissemination", "0008_alter_general_auditor_certify_name_and_more"),
    ]

    operations = []
