# Generated by Django 4.2.6 on 2023-12-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0008_general_auditor_certify_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="auditor_certify_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: UNKNOWN",
                verbose_name="Name of Auditor Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_certify_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: UNKNOWN",
                verbose_name="Title of Auditor Certifying Official",
            ),
        ),
    ]
