# Generated by Django 4.2.6 on 2024-01-08 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0009_merge_20240108_1731"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MigrationChangeRecord",
            new_name="MigrationInspectionRecord",
        ),
    ]
