# Generated by Django 4.2.2 on 2023-07-19 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0009_remove_general_pdf_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="general",
            name="auditee_certified_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="auditor_certified_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="cfac_report_id",
        ),
        migrations.RemoveField(
            model_name="general",
            name="cfac_version",
        ),
        migrations.RemoveField(
            model_name="general",
            name="date_published",
        ),
        migrations.RemoveField(
            model_name="general",
            name="date_received",
        ),
        migrations.RemoveField(
            model_name="general",
            name="fac_accepted_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="form_date_received",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_type_of_entity",
        ),
    ]
