# Generated by Django 4.2.2 on 2023-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0010_remove_general_auditee_certified_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="cfac_report_id",
            field=models.CharField(
                null=True, verbose_name="Used by CFAC to uniquely identify a submission"
            ),
        ),
    ]
