# Generated by Django 4.2.6 on 2024-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0010_rename_migrationchangerecord_migrationinspectionrecord",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key_id",
                    models.TextField(verbose_name="API key Id for the user"),
                ),
                (
                    "report_id",
                    models.TextField(
                        verbose_name="Report ID for the PDF being requested"
                    ),
                ),
            ],
        ),
    ]
