# Generated by Django 4.2.2 on 2023-07-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0011_general_cfac_report_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="dbkey",
            field=models.CharField(
                help_text="Census mapping: GENERAL, DBKEY",
                max_length=40,
                null=True,
                verbose_name="Audit Year and DBKEY (database key) combined make up the primary key. Only on records created by Census.",
            ),
        ),
    ]
