# Generated by Django 4.2.6 on 2024-02-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0012_alter_additionalein_report_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TribalApiAccessKeyIds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(verbose_name="Email of the user")),
                ("key_id", models.TextField(verbose_name="Key ID for the api access")),
                (
                    "date_added",
                    models.DateField(verbose_name="Added date of the record"),
                ),
            ],
        ),
    ]
