# Generated by Django 4.2.2 on 2023-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0012_alter_general_dbkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="auditee_certified_date",
            field=models.DateField(
                null=True,
                verbose_name="The date at which the audit transitioned to 'auditee certified'",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="auditor_certified_date",
            field=models.DateField(
                null=True,
                verbose_name="The date at which the audit transitioned to 'auditor certified'",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="certified_date",
            field=models.DateField(
                null=True,
                verbose_name="The date at which the audit transitioned to 'certified'",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="ready_for_certification_date",
            field=models.DateField(
                null=True,
                verbose_name="The date at which the audit transitioned to 'ready for certification'",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="submitted_date",
            field=models.DateField(
                null=True,
                verbose_name="The date at which the audit transitioned to 'submitted'",
            ),
        ),
    ]
