# Generated by Django 5.0.2 on 2024-02-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0012_alter_additionalein_report_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalein",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="additionaluei",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="captext",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="report_id",
            field=models.ForeignKey(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
    ]
