# Generated by Django 4.2.2 on 2023-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0013_general_auditee_certified_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genauditor",
            name="auditor_ein",
            field=models.CharField(
                max_length=30,
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
    ]
