# Generated by Django 4.2.2 on 2023-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0015_secondaryauditor_delete_genauditor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="general",
            old_name="is_special_framework_required",
            new_name="is_sp_framework_required",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="special_framework",
            new_name="sp_framework",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="type_report_special_purpose_framework",
            new_name="sp_framework_auditor_opinion",
        ),
        migrations.RemoveField(
            model_name="general",
            name="cfac_report_id",
        ),
        migrations.RemoveField(
            model_name="general",
            name="dbkey",
        ),
        migrations.RemoveField(
            model_name="general",
            name="suppression_code",
        ),
        migrations.AddField(
            model_name="general",
            name="agencies_with_prior_findings",
            field=models.TextField(
                null=True, verbose_name="List of agencues with prior findings"
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="gaap_results",
            field=models.TextField(null=True, verbose_name="GAAP Results by Auditor"),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="loan_balance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/j; SF-SAC 2019-2021: II/1/j; SF-SAC 2022: II/1/j Census mapping: CFDA INFO, LOANBALANCE",
                max_digits=10,
                null=True,
                verbose_name="The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dollar_threshold",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/2; SF-SAC 2001-2003: III/3; SF-SAC 2004-2007: III/2; SF-SAC 2008-2009: III/2; SF-SAC 2010-2012: III/2; SF-SAC 2013-2015: III/2; SF-SAC 2016-2018: III/3/b; SF-SAC 2019-2021: III/3/b; SF-SAC 2022: III/3/b Census mapping: GENERAL, DOLLARTHRESHOLD",
                max_digits=10,
                null=True,
                verbose_name="Dollar Threshold to distinguish between Type A and Type B programs.",
            ),
        ),
    ]
