# Generated by Django 5.0.2 on 2024-03-25 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0015_disseminationcombined"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CensusCfda19",
        ),
        migrations.DeleteModel(
            name="CensusCfda22",
        ),
        migrations.DeleteModel(
            name="CensusGen19",
        ),
        migrations.DeleteModel(
            name="CensusGen22",
        ),
    ]
