# Generated by Django 4.2.3 on 2023-07-25 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0016_rename_is_special_framework_required_general_is_sp_framework_required_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="general",
            name="condition_or_deficiency_major_program",
        ),
        migrations.RemoveField(
            model_name="general",
            name="current_or_former_findings",
        ),
        migrations.RemoveField(
            model_name="general",
            name="material_weakness",
        ),
        migrations.RemoveField(
            model_name="general",
            name="material_weakness_major_program",
        ),
        migrations.RemoveField(
            model_name="general",
            name="prior_year_schedule",
        ),
        migrations.RemoveField(
            model_name="general",
            name="questioned_costs",
        ),
        migrations.RemoveField(
            model_name="general",
            name="type_report_financial_statements",
        ),
    ]
