# Generated by Django 5.0.4 on 2024-06-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0017_delete_censuscfda19_delete_censuscfda22_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SacValidationWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approver_email",
                    models.TextField(
                        verbose_name="Email address of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "approver_name",
                    models.TextField(
                        verbose_name="Name of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "requester_email",
                    models.TextField(
                        verbose_name="Email address of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "requester_name",
                    models.TextField(
                        verbose_name="Name of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        verbose_name="Brief plain-text justification for the waiver"
                    ),
                ),
                (
                    "waiver_type",
                    models.CharField(
                        choices=[
                            (
                                "auditee_certifying_official",
                                "No auditee certifying official is available",
                            ),
                            (
                                "auditor_certifying_official",
                                "No auditor certifying official is available",
                            ),
                            (
                                "active_uei",
                                "The auditee cannot activate their SAM.gov UEI registration",
                            ),
                        ],
                        max_length=100,
                        verbose_name="The waiver type",
                    ),
                ),
                (
                    "report_id",
                    models.ForeignKey(
                        db_column="report_id",
                        help_text="GSAFAC generated identifier",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dissemination.general",
                        to_field="report_id",
                    ),
                ),
            ],
        ),
    ]
