# Generated by Django 4.2.3 on 2023-07-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0017_remove_general_condition_or_deficiency_major_program_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_name",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Name of CPA Contact"
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_title",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                max_length=80,
                null=True,
                verbose_name="Title of CPA Contact",
            ),
        ),
    ]
