# Generated by Django 5.0.4 on 2024-06-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0018_sacvalidationwaiver"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SacValidationWaiver",
        ),
    ]
