# Generated by Django 4.2.3 on 2023-07-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0018_alter_secondaryauditor_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/f; SF-SAC 2019-2021: II/1/f; SF-SAC 2022: II/1/f Census mapping: CFDA INFO, CLUSTERNAME",
                null=True,
                verbose_name="The name of the cluster",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/b; SF-SAC 2001-2003: III/10/c; SF-SAC 2004-2007: III/9/d; SF-SAC 2008-2009: III/9/d; SF-SAC 2010-2012: III/9/e; SF-SAC 2013-2015: III/6/c; SF-SAC 2016-2018: II/1/d; SF-SAC 2019-2021: II/1/d; SF-SAC 2022: II/1/d Census mapping: CFDA INFO, FEDERALPROGRAMNAME",
                null=True,
                verbose_name="Name of Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="other_cluster_name",
            field=models.TextField(
                help_text="Census mapping: CFDA INFO, OTHERCLUSTERNAME",
                null=True,
                verbose_name="The name of the cluster (if not listed in the Compliance Supplement)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="state_cluster_name",
            field=models.TextField(
                help_text="Census mapping: CFDA INFO, STATECLUSTERNAME",
                null=True,
                verbose_name="The name of the state cluster",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_address_line_1",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, STREET1",
                verbose_name="Auditee Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYNAME",
                null=True,
                verbose_name="Name of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYTITLE",
                null=True,
                verbose_name="Title of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_city",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, CITY",
                verbose_name="Auditee City",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_contact_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEECONTACT",
                null=True,
                verbose_name="Name of Auditee Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEETITLE",
                null=True,
                verbose_name="Title of Auditee Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_email",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/f; SF-SAC 2001-2003: I/6/f; SF-SAC 2004-2007: I/6/f; SF-SAC 2008-2009: I/5/f; SF-SAC 2010-2012: I/5/f; SF-SAC 2013-2015: I/5/f; SF-SAC 2016-2018: I/5/e; SF-SAC 2019-2021: I/5/e; SF-SAC 2022: I/5/e Census mapping: GENERAL, AUDITEEEMAIL",
                max_length=254,
                null=True,
                verbose_name="Auditee Email address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/a; SF-SAC 2001-2003: I/6/a; SF-SAC 2004-2007: I/6/a; SF-SAC 2008-2009: I/5/a; SF-SAC 2010-2012: I/5/a; SF-SAC 2013-2015: I/5/a; SF-SAC 2016-2018: I/5/a; SF-SAC 2019-2021: I/5/a; SF-SAC 2022: I/5/a Census mapping: GENERAL, AUDITEENAME",
                verbose_name="Name of the Auditee",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_address_line_1",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                max_length=45,
                null=True,
                verbose_name="CPA Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_city",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                null=True,
                verbose_name="CPA City",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_contact_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPACONTACT (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/g; SF-SAC 2016-2018: I/8/g; SF-SAC 2019-2021: I/6/h/vii; SF-SAC 2022: I/6/h/vii Census mapping: MULTIPLE CPAS INFO, CPACONTACT",
                null=True,
                verbose_name="Name of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                max_length=40,
                null=True,
                verbose_name="Title of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_email",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                max_length=254,
                null=True,
                verbose_name="CPA mail address (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_firm_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/a; SF-SAC 2001-2003: I/7/a; SF-SAC 2004-2007: I/7/a; SF-SAC 2008-2009: I/6/a; SF-SAC 2010-2012: I/6/a; SF-SAC 2013-2015: I/6/a; SF-SAC 2016-2018: I/6/a; SF-SAC 2019-2021: I/6/a; SF-SAC 2022: I/6/a Census mapping: GENERAL, CPAFIRMNAME (AND) Data sources: SF-SAC 2008-2009: I/8/a; SF-SAC 2010-2012: I/8/a; SF-SAC 2013-2015: I/8/a; SF-SAC 2016-2018: I/8/a; SF-SAC 2019-2021: I/6/h/i; SF-SAC 2022: I/6/h/i Census mapping: MULTIPLE CPAS INFO, CPAFIRMNAME",
                verbose_name="CPA Firm Name",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_foreign_addr",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAFOREIGN",
                null=True,
                verbose_name="CPA Address - if international",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, TITLE",
                null=True,
                verbose_name="Note Title",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/l; SF-SAC 2019-2021: II/1/l; SF-SAC 2022: II/1/l Census mapping: PASSTHROUGH, PASSTHROUGHNAME",
                null=True,
                verbose_name="Name of Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="audit_info",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, AUDITINFO",
                null=True,
                verbose_name="Indicates what items on the Audit Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="federal_awards",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FEDERALAWARDS",
                null=True,
                verbose_name="Indicates what items on the Federal Awards page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="findings",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGS",
                null=True,
                verbose_name="Indicates what items on the Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="general_info",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, GENINFO",
                null=True,
                verbose_name="Indicates what items on the General Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="notes_to_sefa",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, NOTESTOSEFA",
                null=True,
                verbose_name="Indicates what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="other",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, OTHER",
                null=True,
                verbose_name="Indicates what other miscellaneous items were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_street",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                null=True,
                verbose_name="CPA Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="auditor_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/a; SF-SAC 2001-2003: I/7/a; SF-SAC 2004-2007: I/7/a; SF-SAC 2008-2009: I/6/a; SF-SAC 2010-2012: I/6/a; SF-SAC 2013-2015: I/6/a; SF-SAC 2016-2018: I/6/a; SF-SAC 2019-2021: I/6/a; SF-SAC 2022: I/6/a Census mapping: GENERAL, CPAFIRMNAME (AND) Data sources: SF-SAC 2008-2009: I/8/a; SF-SAC 2010-2012: I/8/a; SF-SAC 2013-2015: I/8/a; SF-SAC 2016-2018: I/8/a; SF-SAC 2019-2021: I/6/h/i; SF-SAC 2022: I/6/h/i Census mapping: MULTIPLE CPAS INFO, CPAFIRMNAME",
                verbose_name="CPA Firm Name",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_email",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                max_length=254,
                null=True,
                verbose_name="CPA mail address (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_name",
            field=models.TextField(null=True, verbose_name="Name of CPA Contact"),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                null=True,
                verbose_name="Title of CPA Contact",
            ),
        ),
    ]
