# Generated by Django 5.1.7 on 2025-04-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0019_delete_sacvalidationwaiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalein",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="additionaluei",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="captext",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="federalaward",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="finding",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="findingtext",
            name="report_id",
        ),
        migrations.AlterUniqueTogether(
            name="general",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="note",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="passthrough",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="secondaryauditor",
            name="report_id",
        ),
        migrations.DeleteModel(
            name="OneTimeAccess",
        ),
        migrations.DeleteModel(
            name="DisseminationCombined",
        ),
        migrations.DeleteModel(
            name="AdditionalEin",
        ),
        migrations.DeleteModel(
            name="AdditionalUei",
        ),
        migrations.DeleteModel(
            name="CapText",
        ),
        migrations.DeleteModel(
            name="FederalAward",
        ),
        migrations.DeleteModel(
            name="Finding",
        ),
        migrations.DeleteModel(
            name="FindingText",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="Passthrough",
        ),
        migrations.DeleteModel(
            name="General",
        ),
        migrations.DeleteModel(
            name="SecondaryAuditor",
        ),
    ]
