# Generated by Django 5.1.2 on 2024-10-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0019_delete_sacvalidationwaiver"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="disseminationcombined",
            table='public_data_v1_0_0"."combined',
        ),
    ]
