# Generated by Django 4.2.3 on 2023-07-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0019_alter_federalaward_cluster_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="auditor_signature_date",
            field=models.DateField(
                null=True, verbose_name="The date on which the auditor signed the audit"
            ),
        ),
    ]
