# Generated by Django 5.2.3 on 2025-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0019_delete_sacvalidationwaiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="resubmission_status",
            field=models.CharField(
                choices=[
                    ("Original Submission", "Original Submission"),
                    ("Most Recent", "Most Recent"),
                    ("Depracated via Resubmission", "Depracated via Resubmission"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="resubmission_version",
            field=models.BigIntegerField(
                default=0,
                help_text="Version counter of how many times this SAC was resubmitted.",
            ),
        ),
    ]
