# Generated by Django 5.2.3 on 2025-07-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0020_general_resubmission_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="resubmission_status",
            field=models.CharField(
                choices=[
                    ("original_submission", "Original Submission"),
                    ("most_recent", "Most Recent"),
                    ("deprecated_via_resubmission", "Deprecated via Resubmission"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
