# Generated by Django 5.1.7 on 2025-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0020_remove_additionalein_report_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key_id",
                    models.TextField(verbose_name="API key Id for the user"),
                ),
                (
                    "report_id",
                    models.TextField(
                        help_text="GSAFAC generated identifier",
                        verbose_name="Report ID",
                    ),
                ),
            ],
        ),
    ]
