# Generated by Django 5.2.3 on 2025-08-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0021_alter_general_resubmission_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resubmission_version",
                    models.BigIntegerField(verbose_name="Resubmission Version"),
                ),
                (
                    "resubmission_status",
                    models.CharField(
                        choices=[
                            ("original_submission", "Original Submission"),
                            ("most_recent", "Most Recent"),
                            (
                                "deprecated_via_resubmission",
                                "Deprecated via Resubmission",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Resubmission Status (Original, Deprecated, Resubmission)",
                    ),
                ),
                (
                    "previous_report_id",
                    models.TextField(null=True, verbose_name="Previous Report ID"),
                ),
                (
                    "next_report_id",
                    models.TextField(null=True, verbose_name="Next Report ID"),
                ),
                (
                    "report_id",
                    models.ForeignKey(
                        db_column="report_id",
                        help_text="GSAFAC generated identifier",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dissemination.general",
                        to_field="report_id",
                    ),
                ),
            ],
        ),
    ]
