# Generated by Django 4.2.3 on 2023-08-02 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0021_general_auditee_signature_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="general",
            old_name="report_required",
            new_name="is_report_required",
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditee_addl_duns_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    max_length=30,
                    null=True,
                    verbose_name="",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditee_addl_ein_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    max_length=30,
                    null=True,
                    verbose_name="",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditee_address_line_2",
            field=models.TextField(
                null=True, verbose_name="Auditee Street Address Line 2 in C-FAC"
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditee_duns",
            field=models.CharField(
                max_length=30,
                null=True,
                verbose_name="Primary Employer Identification Number",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditee_fax",
            field=models.TextField(
                null=True, verbose_name="Auditee Fax Number in C-FAC"
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditor_address_line_2",
            field=models.TextField(
                null=True, verbose_name="CPA Street Address Line 2 in C-FAC"
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditor_fax",
            field=models.TextField(null=True, verbose_name="CPA fax number in C-FAC"),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_dbkey",
            field=models.IntegerField(
                null=True,
                verbose_name="Identifier for a submission along with audit_year in C-FAC",
            ),
        ),
        migrations.AddField(
            model_name="secondaryauditor",
            name="hist_address_street_line_2",
            field=models.TextField(
                null=True, verbose_name="CPA Street Address Line 2 in C-FAC"
            ),
        ),
        migrations.AddField(
            model_name="secondaryauditor",
            name="hist_contact_fax",
            field=models.TextField(null=True, verbose_name="CPA fax number"),
        ),
        migrations.AlterField(
            model_name="captext",
            name="contains_chart_or_table",
            field=models.BooleanField(
                help_text="Census mapping: CAPTEXT, CHARTSTABLES",
                null=True,
                verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="captext",
            name="finding_ref_number",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: IV/1; SF-SAC 2022: IV/1 Census mapping: CAPTEXT, FINDINGREFNUMS",
                verbose_name="Audit Finding Reference Number",
            ),
        ),
        migrations.AlterField(
            model_name="captext",
            name="planned_action",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: IV/2; SF-SAC 2022: IV/2 Census mapping: CAPTEXT, TEXT",
                null=True,
                verbose_name="Content of the Corrective Action Plan (CAP)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="additional_award_identification",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/c; SF-SAC 2019-2021: II/1/c; SF-SAC 2022: II/1/c Census mapping: CFDA INFO, AWARDIDENTIFICATION",
                null=True,
                verbose_name="Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="amount_expended",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/6/c; SF-SAC 2001-2003: III/10/d; SF-SAC 2004-2007: III/9/e; SF-SAC 2008-2009: III/9/e; SF-SAC 2010-2012: III/9/f; SF-SAC 2013-2015: III/6/d; SF-SAC 2016-2018: II/1/e; SF-SAC 2019-2021: II/1/e; SF-SAC 2022: II/1/e Census mapping: CFDA INFO, AMOUNT",
                max_digits=10,
                null=True,
                verbose_name="Amount Expended for the Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="award_reference",
            field=models.CharField(
                default=-1,
                max_length=12,
                verbose_name="Order that the award line was reported",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/h; SF-SAC 2019-2021: II/1/h; SF-SAC 2022: II/1/h Census mapping: CFDA INFO, CLUSTERTOTAL",
                max_digits=10,
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/g; SF-SAC 2019-2021: II/1/g; SF-SAC 2022: II/1/g Census mapping: CFDA INFO, PROGRAMTOTAL",
                max_digits=10,
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="passthrough_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/o; SF-SAC 2019-2021: II/1/o; SF-SAC 2022: II/1/o Census mapping: CFDA INFO, PASSTHROUGHAMOUNT",
                max_digits=10,
                null=True,
                verbose_name="Amount passed through to subrecipients",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="report_id",
            field=models.CharField(
                max_length=40,
                verbose_name="G-FAC generated identifier. FK  to a General",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="award_reference",
            field=models.CharField(
                max_length=12,
                null=True,
                verbose_name="Order that the award line was reported in Award",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="finding_ref_number",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/d; SF-SAC 2016-2018: III/4/e; SF-SAC 2019-2021: III/4/e; SF-SAC 2022: III/4/e Census mapping: FINDINGS, FINDINGSREFNUMS",
                verbose_name="Findings Reference Numbers",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="prior_finding_ref_numbers",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/4/n; SF-SAC 2019-2021: III/4/n; SF-SAC 2022: III/4/n Census mapping: FINDINGS, PRIORFINDINGREFNUMS",
                null=True,
                verbose_name="Audit finding reference numbers from the immediate prior audit",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="contains_chart_or_table",
            field=models.BooleanField(
                help_text="Census mapping: FINDINGSTEXT, CHARTSTABLES",
                null=True,
                verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="finding_ref_number",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: III/5/a; SF-SAC 2022: III/5/a Census mapping: FINDINGSTEXT, FINDINGREFNUMS",
                null=True,
                verbose_name="Finding Reference Number - FK",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_addl_uei_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    max_length=30,
                    null=True,
                    verbose_name="",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/f; SF-SAC 2001-2003: I/6/f; SF-SAC 2004-2007: I/6/f; SF-SAC 2008-2009: I/5/f; SF-SAC 2010-2012: I/5/f; SF-SAC 2013-2015: I/5/f; SF-SAC 2016-2018: I/5/e; SF-SAC 2019-2021: I/5/e; SF-SAC 2022: I/5/e Census mapping: GENERAL, AUDITEEEMAIL",
                null=True,
                verbose_name="Auditee Email address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_signature_date",
            field=models.DateField(
                null=True, verbose_name="The date on which the auditee signed the audit"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_address_line_1",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                null=True,
                verbose_name="CPA Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                null=True,
                verbose_name="Title of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_ein",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                max_length=30,
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                null=True,
                verbose_name="CPA mail address (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="data_source",
            field=models.CharField(max_length=12, verbose_name="Origin of the upload"),
        ),
        migrations.AlterField(
            model_name="general",
            name="entity_type",
            field=models.CharField(
                help_text="Census mapping: GENERAL, ENTITY_TYPE",
                max_length=40,
                null=True,
                verbose_name="Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="oversight_agency",
            field=models.CharField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, OVERSIGHTAGENCY",
                max_length=2,
                null=True,
                verbose_name="Two digit Federal agency prefix of the oversight agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="total_fed_expenditures",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/6/c- Total; SF-SAC 2001-2003: III/10/d -Total; SF-SAC 2004-2007: III/9/e -Total; SF-SAC 2008-2009: III/9/e -Total; SF-SAC 2010-2012: III/9/f -Total; SF-SAC 2013-2015: III/6/d -Total; SF-SAC 2016-2018: II/1/e- Total; SF-SAC 2019-2021: II/1/e - Total; SF-SAC 2022: II/1/e - Total Census mapping: GENERAL, TOTFEDEXPEND",
                max_digits=10,
                null=True,
                verbose_name="Total Federal Expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="is_minimis_rate_used",
            field=models.BooleanField(null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="award_reference",
            field=models.CharField(
                max_length=12,
                null=True,
                verbose_name="Order that the award line was reported",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_id",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/m; SF-SAC 2019-2021: II/1/m; SF-SAC 2022: II/1/m Census mapping: PASSTHROUGH, PASSTHROUGHID",
                null=True,
                verbose_name="Identifying Number Assigned by the Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="auditor_ein",
            field=models.CharField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                max_length=30,
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                null=True,
                verbose_name="CPA mail address (optional)",
            ),
        ),
    ]
