# Generated by Django 4.2.3 on 2023-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0021_general_auditee_signature_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="auditee_signature_date",
            field=models.DateField(
                null=True, verbose_name="The date on which the auditee signed the audit"
            ),
        ),
    ]
