# Generated by Django 5.2.3 on 2025-09-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0022_resubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalein",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="additionaluei",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="captext",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="federalaward",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="finding",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="findingtext",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="general",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="note",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="passthrough",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="resubmission",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
        migrations.AddField(
            model_name="secondaryauditor",
            name="hash",
            field=models.CharField(default="NOHASH"),
        ),
    ]
