# Generated by Django 5.2.3 on 2026-01-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0022_resubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="resubmission_status",
            field=models.CharField(
                choices=[
                    ("most_recent", "Most Recent"),
                    ("deprecated_via_resubmission", "Deprecated via Resubmission"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("most_recent", "Most Recent"),
                    ("deprecated_via_resubmission", "Deprecated via Resubmission"),
                ],
                max_length=30,
                verbose_name="Resubmission Status (Unknown, Deprecated, Resubmission)",
            ),
        ),
    ]
