# Generated by Django 5.2.3 on 2026-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0023_alter_general_resubmission_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalein",
            name="fake_field",
            field=models.TextField(null=True),
        ),
    ]
