# Generated by Django 5.2.3 on 2026-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0023_alter_general_resubmission_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="general",
            name="audit_year",
            field=models.TextField(
                help_text="Census mapping: GENERAL, AUDITYEAR",
                verbose_name="Audit year from fy_end_date.",
            ),
        ),
    ]
