# Generated by Django 4.2.3 on 2023-08-10 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0023_rename_report_required_general_is_report_required_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="general",
            old_name="total_fed_expenditures",
            new_name="total_amount_expended",
        ),
        migrations.RemoveField(
            model_name="federalaward",
            name="is_major",
        ),
        migrations.RemoveField(
            model_name="federalaward",
            name="type_requirement",
        ),
        migrations.RemoveField(
            model_name="general",
            name="type_report_major_program",
        ),
    ]
