# Generated by Django 4.2.3 on 2023-08-10 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0024_rename_total_fed_expenditures_general_total_amount_expended_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="general",
            name="is_report_required",
        ),
    ]
