# Generated by Django 4.2.3 on 2023-08-02 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0024_alter_captext_finding_ref_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="hist_auditee_addl_duns_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    max_length=30,
                    null=True,
                    verbose_name="",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditee_addl_ein_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    max_length=30,
                    null=True,
                    verbose_name="",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="hist_auditee_duns",
            field=models.CharField(
                max_length=30,
                null=True,
                verbose_name="Primary Employer Identification Number",
            ),
        ),
    ]
