# Generated by Django 5.2.3 on 2026-03-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0024_alter_general_audit_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resubmission",
            name="next_report_id",
            field=models.TextField(
                blank=True, null=True, unique=True, verbose_name="Next Report ID"
            ),
        ),
        migrations.AlterField(
            model_name="resubmission",
            name="previous_report_id",
            field=models.TextField(
                blank=True, null=True, unique=True, verbose_name="Previous Report ID"
            ),
        ),
        migrations.AlterField(
            model_name="resubmission",
            name="report_id",
            field=models.OneToOneField(
                db_column="report_id",
                help_text="GSAFAC generated identifier",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resubmission",
                to="dissemination.general",
                to_field="report_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="resubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_report_id", models.F("next_report_id")), _negated=True
                ),
                name="resubmission_previous_and_next_not_equal",
            ),
        ),
    ]
