# Generated by Django 4.2.3 on 2023-08-14 20:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0025_remove_general_is_report_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalUei",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.TextField()),
                ("additional_uei", models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="secondaryauditor",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="general",
            name="auditee_addl_uei_list",
        ),
        migrations.AddField(
            model_name="federalaward",
            name="is_major",
            field=models.BooleanField(
                help_text="Data sources: SF-SAC 1997-2000: III/7/a; SF-SAC 2001-2003: III/10/f; SF-SAC 2004-2007: III/9/g; SF-SAC 2008-2009: III/9/g; SF-SAC 2010-2012: III/9/h; SF-SAC 2013-2015: III/6/i; SF-SAC 2016-2018: III/1/a; SF-SAC 2019-2021: III/1/a; SF-SAC 2022: III/1/a Census mapping: CFDA INFO, MAJORPROGRAM",
                null=True,
                verbose_name="Indicate whether or not the Federal program is a major program",
            ),
        ),
        migrations.AddField(
            model_name="federalaward",
            name="type_requirement",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/7/b; SF-SAC 2001-2003: III/11/a; SF-SAC 2004-2007: III/10/a; SF-SAC 2008-2009: III/10/a; SF-SAC 2010-2012: III/10/a; SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: CFDA INFO, TYPEREQUIREMENT",
                null=True,
                verbose_name="Type Requirement Failure",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="additional_ueis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="general",
            name="type_report_major_program",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/1; SF-SAC 2001-2003: III/1 Census mapping: GENERAL, TYPEREPORT_MP",
                null=True,
                verbose_name="Type of Report Issued on the Major Program Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="captext",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier. FK refers to a General"
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="amount_expended",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/6/c; SF-SAC 2001-2003: III/10/d; SF-SAC 2004-2007: III/9/e; SF-SAC 2008-2009: III/9/e; SF-SAC 2010-2012: III/9/f; SF-SAC 2013-2015: III/6/d; SF-SAC 2016-2018: II/1/e; SF-SAC 2019-2021: II/1/e; SF-SAC 2022: II/1/e Census mapping: CFDA INFO, AMOUNT",
                max_digits=98,
                null=True,
                verbose_name="Amount Expended for the Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="award_reference",
            field=models.TextField(
                default=-1, verbose_name="Order that the award line was reported"
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/h; SF-SAC 2019-2021: II/1/h; SF-SAC 2022: II/1/h Census mapping: CFDA INFO, CLUSTERTOTAL",
                max_digits=98,
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_agency_prefix",
            field=models.TextField(verbose_name="2-char code refers to an agency"),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_award_extension",
            field=models.TextField(
                verbose_name="3-digit extn for a program defined by the agency"
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/g; SF-SAC 2019-2021: II/1/g; SF-SAC 2022: II/1/g Census mapping: CFDA INFO, PROGRAMTOTAL",
                max_digits=98,
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="loan_balance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/j; SF-SAC 2019-2021: II/1/j; SF-SAC 2022: II/1/j Census mapping: CFDA INFO, LOANBALANCE",
                max_digits=98,
                null=True,
                verbose_name="The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="mp_audit_report_type",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2004-2007: III/9/h; SF-SAC 2008-2009: III/9/h; SF-SAC 2010-2012: III/9/i; SF-SAC 2013-2015: III/6/j; SF-SAC 2016-2018: III/1/b; SF-SAC 2019-2021: III/1/b; SF-SAC 2022: III/1/b Census mapping: CFDA INFO, TYPEREPORT_MP",
                null=True,
                verbose_name="Type of Report Issued on the Major Program Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="passthrough_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/o; SF-SAC 2019-2021: II/1/o; SF-SAC 2022: II/1/o Census mapping: CFDA INFO, PASSTHROUGHAMOUNT",
                max_digits=98,
                null=True,
                verbose_name="Amount passed through to subrecipients",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="report_id",
            field=models.TextField(
                verbose_name="G-FAC generated identifier. FK  to a General"
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="award_reference",
            field=models.TextField(
                max_length=12,
                null=True,
                verbose_name="Order that the award line was reported in Award",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="report_id",
            field=models.TextField(
                max_length=40,
                verbose_name="G-FAC generated identifier. FK along with other fields - refers to Award",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="type_requirement",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: FINDINGS, TYPEREQUIREMENT",
                max_length=40,
                null=True,
                verbose_name="Type Requirement Failure",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="report_id",
            field=models.TextField(
                max_length=40, verbose_name="G-FAC generated identifier.l"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="audit_period_covered",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/3; SF-SAC 2001-2003: I/3; SF-SAC 2004-2007: I/3; SF-SAC 2008-2009: I/3; SF-SAC 2010-2012: I/3; SF-SAC 2013-2015: I/3; SF-SAC 2016-2018: I/3; SF-SAC 2019-2021: I/3; SF-SAC 2022: I/3 Census mapping: GENERAL, PERIODCOVERED",
                max_length=40,
                verbose_name="Audit Period Covered by Audit",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="audit_type",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/2; SF-SAC 2001-2003: I/2; SF-SAC 2004-2007: I/2; SF-SAC 2008-2009: I/2; SF-SAC 2010-2012: I/2; SF-SAC 2013-2015: I/2; SF-SAC 2016-2018: I/2; SF-SAC 2019-2021: I/2; SF-SAC 2022: I/2 Census mapping: GENERAL, AUDITTYPE",
                verbose_name="Type of Audit",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_ein",
            field=models.TextField(
                null=True, verbose_name="Primary Employer Identification Number"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, STATE",
                max_length=2,
                verbose_name="Auditee State",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_uei",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                null=True,
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_zip",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, ZIPCODE",
                null=True,
                verbose_name="Auditee Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_country",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACOUNTRY",
                null=True,
                verbose_name="CPA Country",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_ein",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                max_length=30,
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                null=True,
                verbose_name="CPA State",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_zip",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                max_length=12,
                null=True,
                verbose_name="CPA Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, COGAGENCY",
                null=True,
                verbose_name="Two digit Federal agency prefix of the cognizant agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="data_source",
            field=models.TextField(max_length=12, verbose_name="Origin of the upload"),
        ),
        migrations.AlterField(
            model_name="general",
            name="dollar_threshold",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/2; SF-SAC 2001-2003: III/3; SF-SAC 2004-2007: III/2; SF-SAC 2008-2009: III/2; SF-SAC 2010-2012: III/2; SF-SAC 2013-2015: III/2; SF-SAC 2016-2018: III/3/b; SF-SAC 2019-2021: III/3/b; SF-SAC 2022: III/3/b Census mapping: GENERAL, DOLLARTHRESHOLD",
                max_digits=98,
                null=True,
                verbose_name="Dollar Threshold to distinguish between Type A and Type B programs.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="entity_type",
            field=models.TextField(
                help_text="Census mapping: GENERAL, ENTITY_TYPE",
                null=True,
                verbose_name="Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditee_addl_duns_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    null=True,
                    verbose_name="",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditee_addl_ein_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                    null=True,
                    verbose_name="",
                ),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditee_duns",
            field=models.TextField(
                null=True, verbose_name="Primary Employer Identification Number"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="oversight_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, OVERSIGHTAGENCY",
                null=True,
                verbose_name="Two digit Federal agency prefix of the oversight agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="report_id",
            field=models.TextField(
                max_length=40, unique=True, verbose_name="G-FAC generated identifier. "
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="sp_framework",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/2/a/ii; SF-SAC 2019-2021: III/2/a/i; SF-SAC 2022: III/2/a/i Census mapping: GENERAL, SP_FRAMEWORK",
                null=True,
                verbose_name="Special Purpose Framework that was used as the basis of accounting",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="sp_framework_auditor_opinion",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/2/a/iv; SF-SAC 2019-2021: III/2/a/iii; SF-SAC 2022: III/2/a/iii Census mapping: GENERAL, TYPEREPORT_SP_FRAMEWORK",
                null=True,
                verbose_name="The auditor's opinion on the special purpose framework",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="total_amount_expended",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/6/c- Total; SF-SAC 2001-2003: III/10/d -Total; SF-SAC 2004-2007: III/9/e -Total; SF-SAC 2008-2009: III/9/e -Total; SF-SAC 2010-2012: III/9/f -Total; SF-SAC 2013-2015: III/6/d -Total; SF-SAC 2016-2018: II/1/e- Total; SF-SAC 2019-2021: II/1/e - Total; SF-SAC 2022: II/1/e - Total Census mapping: GENERAL, TOTFEDEXPEND",
                max_digits=98,
                null=True,
                verbose_name="Total Federal Expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="type_audit_code",
            field=models.TextField(
                default="", verbose_name="Determines if audit is A133 or UG"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="report_id",
            field=models.TextField(
                max_length=40,
                verbose_name="G-FAC generated identifier. FK refers to a General",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="award_reference",
            field=models.TextField(
                null=True, verbose_name="Order that the award line was reported"
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="report_id",
            field=models.TextField(
                verbose_name="G-FAC generated identifier. FK refers to General"
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="cap",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, CAP",
                max_length=6,
                null=True,
                verbose_name="Indicates what items on the CAP Text page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="findings_text",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGSTEXT",
                max_length=6,
                null=True,
                verbose_name="Indicates what items on the Text of the Audit Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="report_id",
            field=models.TextField(
                max_length=40,
                verbose_name="G-FAC generated identifier. FK refers to General",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_city",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                null=True,
                verbose_name="CPA City",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                null=True,
                verbose_name="CPA State",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_zipcode",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                null=True,
                verbose_name="CPA Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="auditor_ein",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="report_id",
            field=models.TextField(
                max_length=40, verbose_name="G-FAC generated identifier. FK to General"
            ),
        ),
        migrations.RemoveField(
            model_name="secondaryauditor",
            name="auditor_seq_number",
        ),
    ]
