# Generated by Django 4.2.3 on 2023-08-29 00:34

from django.db import migrations

modelsDict = {
    'FindingText': ['finding_ref_number', 'finding_text'],
    'Finding': ['award_reference', 'prior_finding_ref_numbers', 'type_requirement'],
    'FederalAward': ['additional_award_identification', 'federal_program_name', 'cluster_name', 'other_cluster_name', 'state_cluster_name', 'mp_audit_report_type', 'passthrough_name', 'passthrough_id', 'type_requirement'],
    'CapText': ['planned_action'],
    'Note': ['planned_action', 'note_title', 'accounting_policies', 'rate_explained'],
    'Revision': ['findings', 'federal_awards', 'general_info_explain', 'federal_awards_explain', 'notes_to_sefa_explain', 'audit_info_explain', 'findings_explain', 'findings_text_explain', 'cap_explain', 'other_explain', 'audit_info', 'notes_to_sefa', 'findings_text', 'cap', 'other', 'general_info'],
    'Passthrough': ['award_reference', 'passthrough_id', 'passthrough_name'],
    'General': ['auditee_certify_name', 'auditee_certify_title', 'auditee_contact_name', 'auditee_email', 'hist_auditee_fax', 'auditee_contact_title', 'hist_auditee_address_line_2', 'auditee_ein', 'hist_auditee_duns', 'auditee_uei', 'auditee_zip', 'auditor_phone', 'hist_auditor_fax', 'auditor_state', 'auditor_city', 'auditor_contact_title', 'auditor_address_line_1', 'hist_auditor_address_line_2', 'auditor_zip', 'auditor_country', 'auditor_contact_name', 'auditor_email', 'auditor_foreign_addr', 'auditor_ein', 'cognizant_agency', 'oversight_agency', 'gaap_results', 'sp_framework', 'sp_framework_auditor_opinion', 'agencies_with_prior_findings', 'entity_type', 'type_report_major_program'],
    'SecondaryAuditor': ['auditor_ein', 'contact_name', 'contact_title', 'contact_email', 'contact_phone', 'hist_contact_fax', 'address_street', 'hist_address_street_line_2', 'address_city', 'address_state', 'address_zipcode'],
}


def nulls_to_string(apps, schema_editor):
    for k, v in modelsDict.items() :
        Mod = apps.get_model("dissemination", k)
        for item in Mod.objects.all():
            for field_name in v:
                if item[field_name] is None:
                    item[field_name] = ''
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0026_additionaluei_alter_captext_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(nulls_to_string),
    ]
