# Generated by Django 4.2.3 on 2023-08-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0026_additionaluei_alter_captext_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalEin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.TextField()),
                ("additional_ein", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="general",
            name="additional_ueis",
        ),
        migrations.AddField(
            model_name="general",
            name="additional_eins_covered",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="general",
            name="additional_ueis_covered",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="general",
            name="secondary_auditors_exist",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="captext",
            name="planned_action",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: IV/2; SF-SAC 2022: IV/2 Census mapping: CAPTEXT, TEXT",
                verbose_name="Content of the Corrective Action Plan (CAP)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="additional_award_identification",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/c; SF-SAC 2019-2021: II/1/c; SF-SAC 2022: II/1/c Census mapping: CFDA INFO, AWARDIDENTIFICATION",
                verbose_name="Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="amount_expended",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/c; SF-SAC 2001-2003: III/10/d; SF-SAC 2004-2007: III/9/e; SF-SAC 2008-2009: III/9/e; SF-SAC 2010-2012: III/9/f; SF-SAC 2013-2015: III/6/d; SF-SAC 2016-2018: II/1/e; SF-SAC 2019-2021: II/1/e; SF-SAC 2022: II/1/e Census mapping: CFDA INFO, AMOUNT",
                null=True,
                verbose_name="Amount Expended for the Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/f; SF-SAC 2019-2021: II/1/f; SF-SAC 2022: II/1/f Census mapping: CFDA INFO, CLUSTERNAME",
                verbose_name="The name of the cluster",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_total",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/h; SF-SAC 2019-2021: II/1/h; SF-SAC 2022: II/1/h Census mapping: CFDA INFO, CLUSTERTOTAL",
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/b; SF-SAC 2001-2003: III/10/c; SF-SAC 2004-2007: III/9/d; SF-SAC 2008-2009: III/9/d; SF-SAC 2010-2012: III/9/e; SF-SAC 2013-2015: III/6/c; SF-SAC 2016-2018: II/1/d; SF-SAC 2019-2021: II/1/d; SF-SAC 2022: II/1/d Census mapping: CFDA INFO, FEDERALPROGRAMNAME",
                verbose_name="Name of Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_total",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/g; SF-SAC 2019-2021: II/1/g; SF-SAC 2022: II/1/g Census mapping: CFDA INFO, PROGRAMTOTAL",
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="loan_balance",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/j; SF-SAC 2019-2021: II/1/j; SF-SAC 2022: II/1/j Census mapping: CFDA INFO, LOANBALANCE",
                null=True,
                verbose_name="The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="mp_audit_report_type",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2004-2007: III/9/h; SF-SAC 2008-2009: III/9/h; SF-SAC 2010-2012: III/9/i; SF-SAC 2013-2015: III/6/j; SF-SAC 2016-2018: III/1/b; SF-SAC 2019-2021: III/1/b; SF-SAC 2022: III/1/b Census mapping: CFDA INFO, TYPEREPORT_MP",
                verbose_name="Type of Report Issued on the Major Program Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="other_cluster_name",
            field=models.TextField(
                help_text="Census mapping: CFDA INFO, OTHERCLUSTERNAME",
                verbose_name="The name of the cluster (if not listed in the Compliance Supplement)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="passthrough_amount",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/o; SF-SAC 2019-2021: II/1/o; SF-SAC 2022: II/1/o Census mapping: CFDA INFO, PASSTHROUGHAMOUNT",
                null=True,
                verbose_name="Amount passed through to subrecipients",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="passthrough_id",
            field=models.TextField(
                verbose_name="If no (Direct Award), Identifying Number Assigned by the Pass-through Entity, if assigned"
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="passthrough_name",
            field=models.TextField(
                verbose_name="If no (Direct Award), Name of Passthrough Entity"
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="state_cluster_name",
            field=models.TextField(
                help_text="Census mapping: CFDA INFO, STATECLUSTERNAME",
                verbose_name="The name of the state cluster",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="type_requirement",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/7/b; SF-SAC 2001-2003: III/11/a; SF-SAC 2004-2007: III/10/a; SF-SAC 2008-2009: III/10/a; SF-SAC 2010-2012: III/10/a; SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: CFDA INFO, TYPEREQUIREMENT",
                verbose_name="Type Requirement Failure",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="award_reference",
            field=models.TextField(
                verbose_name="Order that the award line was reported in Award"
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="prior_finding_ref_numbers",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/4/n; SF-SAC 2019-2021: III/4/n; SF-SAC 2022: III/4/n Census mapping: FINDINGS, PRIORFINDINGREFNUMS",
                verbose_name="Audit finding reference numbers from the immediate prior audit",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="type_requirement",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: FINDINGS, TYPEREQUIREMENT",
                verbose_name="Type Requirement Failure",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="finding_ref_number",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: III/5/a; SF-SAC 2022: III/5/a Census mapping: FINDINGSTEXT, FINDINGREFNUMS",
                verbose_name="Finding Reference Number - FK",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="finding_text",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: III/5/b; SF-SAC 2022: III/5/b Census mapping: FINDINGSTEXT, TEXT",
                verbose_name="Content of the finding text",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="agencies_with_prior_findings",
            field=models.TextField(verbose_name="List of agencues with prior findings"),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYNAME",
                verbose_name="Name of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYTITLE",
                verbose_name="Title of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_contact_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEECONTACT",
                verbose_name="Name of Auditee Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEETITLE",
                verbose_name="Title of Auditee Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_ein",
            field=models.TextField(
                verbose_name="Primary Employer Identification Number"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/f; SF-SAC 2001-2003: I/6/f; SF-SAC 2004-2007: I/6/f; SF-SAC 2008-2009: I/5/f; SF-SAC 2010-2012: I/5/f; SF-SAC 2013-2015: I/5/f; SF-SAC 2016-2018: I/5/e; SF-SAC 2019-2021: I/5/e; SF-SAC 2022: I/5/e Census mapping: GENERAL, AUDITEEEMAIL",
                verbose_name="Auditee Email address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_uei",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_zip",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, ZIPCODE",
                verbose_name="Auditee Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_address_line_1",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                verbose_name="CPA Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_city",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                verbose_name="CPA City",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_contact_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPACONTACT (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/g; SF-SAC 2016-2018: I/8/g; SF-SAC 2019-2021: I/6/h/vii; SF-SAC 2022: I/6/h/vii Census mapping: MULTIPLE CPAS INFO, CPACONTACT",
                verbose_name="Name of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                verbose_name="Title of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_country",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACOUNTRY",
                verbose_name="CPA Country",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_ein",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                verbose_name="CPA mail address (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_foreign_addr",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAFOREIGN",
                verbose_name="CPA Address - if international",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_phone",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/d; SF-SAC 2001-2003: I/7/d; SF-SAC 2004-2007: I/7/d; SF-SAC 2008-2009: I/6/d; SF-SAC 2010-2012: I/6/d; SF-SAC 2013-2015: I/6/e; SF-SAC 2016-2018: I/6/e; SF-SAC 2019-2021: I/6/e; SF-SAC 2022: I/6/e Census mapping: GENERAL, CPAPHONE (AND) Data sources: SF-SAC 2008-2009: I/8/d; SF-SAC 2010-2012: I/8/d; SF-SAC 2013-2015: I/8/i; SF-SAC 2016-2018: I/8/i; SF-SAC 2019-2021: I/6/h/ix; SF-SAC 2022: I/6/h/ix Census mapping: MULTIPLE CPAS INFO, CPAPHONE",
                verbose_name="CPA phone number",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                verbose_name="CPA State",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_zip",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                verbose_name="CPA Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, COGAGENCY",
                verbose_name="Two digit Federal agency prefix of the cognizant agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dollar_threshold",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/2; SF-SAC 2001-2003: III/3; SF-SAC 2004-2007: III/2; SF-SAC 2008-2009: III/2; SF-SAC 2010-2012: III/2; SF-SAC 2013-2015: III/2; SF-SAC 2016-2018: III/3/b; SF-SAC 2019-2021: III/3/b; SF-SAC 2022: III/3/b Census mapping: GENERAL, DOLLARTHRESHOLD",
                null=True,
                verbose_name="Dollar Threshold to distinguish between Type A and Type B programs.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="entity_type",
            field=models.TextField(
                help_text="Census mapping: GENERAL, ENTITY_TYPE",
                verbose_name="Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="gaap_results",
            field=models.TextField(verbose_name="GAAP Results by Auditor"),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditee_address_line_2",
            field=models.TextField(
                verbose_name="Auditee Street Address Line 2 in C-FAC"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditee_duns",
            field=models.TextField(
                verbose_name="Primary Employer Identification Number"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditee_fax",
            field=models.TextField(verbose_name="Auditee Fax Number in C-FAC"),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditor_address_line_2",
            field=models.TextField(verbose_name="CPA Street Address Line 2 in C-FAC"),
        ),
        migrations.AlterField(
            model_name="general",
            name="hist_auditor_fax",
            field=models.TextField(verbose_name="CPA fax number in C-FAC"),
        ),
        migrations.AlterField(
            model_name="general",
            name="oversight_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, OVERSIGHTAGENCY",
                verbose_name="Two digit Federal agency prefix of the oversight agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="sp_framework",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/2/a/ii; SF-SAC 2019-2021: III/2/a/i; SF-SAC 2022: III/2/a/i Census mapping: GENERAL, SP_FRAMEWORK",
                verbose_name="Special Purpose Framework that was used as the basis of accounting",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="sp_framework_auditor_opinion",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/2/a/iv; SF-SAC 2019-2021: III/2/a/iii; SF-SAC 2022: III/2/a/iii Census mapping: GENERAL, TYPEREPORT_SP_FRAMEWORK",
                verbose_name="The auditor's opinion on the special purpose framework",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="total_amount_expended",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/c- Total; SF-SAC 2001-2003: III/10/d -Total; SF-SAC 2004-2007: III/9/e -Total; SF-SAC 2008-2009: III/9/e -Total; SF-SAC 2010-2012: III/9/f -Total; SF-SAC 2013-2015: III/6/d -Total; SF-SAC 2016-2018: II/1/e- Total; SF-SAC 2019-2021: II/1/e - Total; SF-SAC 2022: II/1/e - Total Census mapping: GENERAL, TOTFEDEXPEND",
                null=True,
                verbose_name="Total Federal Expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="type_report_major_program",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/1; SF-SAC 2001-2003: III/1 Census mapping: GENERAL, TYPEREPORT_MP",
                verbose_name="Type of Report Issued on the Major Program Compliance",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="accounting_policies",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, CONTENT",
                verbose_name="Content of the Note",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, TITLE",
                verbose_name="Note Title",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="rate_explained",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="award_reference",
            field=models.TextField(
                verbose_name="Order that the award line was reported"
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_id",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/m; SF-SAC 2019-2021: II/1/m; SF-SAC 2022: II/1/m Census mapping: PASSTHROUGH, PASSTHROUGHID",
                verbose_name="Identifying Number Assigned by the Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/l; SF-SAC 2019-2021: II/1/l; SF-SAC 2022: II/1/l Census mapping: PASSTHROUGH, PASSTHROUGHNAME",
                verbose_name="Name of Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="audit_info",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, AUDITINFO",
                verbose_name="Indicates what items on the Audit Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="audit_info_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, AUDITINFO_EXPLAIN",
                verbose_name="Explanation of what items on the Audit Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="cap",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, CAP",
                max_length=6,
                verbose_name="Indicates what items on the CAP Text page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="cap_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, CAP_EXPLAIN",
                verbose_name="Explanation of what items on the CAP Text page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="federal_awards",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FEDERALAWARDS",
                verbose_name="Indicates what items on the Federal Awards page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="federal_awards_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FEDERALAWARDS_EXPLAIN",
                verbose_name="Explanation of what items on the Federal Awards page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="findings",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGS",
                verbose_name="Indicates what items on the Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="findings_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGS_EXPLAIN",
                verbose_name="Explanation of what items on the Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="findings_text",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGSTEXT",
                max_length=6,
                verbose_name="Indicates what items on the Text of the Audit Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="findings_text_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, FINDINGSTEXT_EXPLAIN",
                verbose_name="Explanation of what items on the Text of the Audit Findings page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="general_info",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, GENINFO",
                verbose_name="Indicates what items on the General Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="general_info_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, GENINFO_EXPLAIN",
                verbose_name="Explanation of what items on the General Info page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="notes_to_sefa",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, NOTESTOSEFA",
                verbose_name="Indicates what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="notes_to_sefa_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, NOTESTOSEFA_EXPLAIN",
                verbose_name="Explanation of what items on the Notes to Schedule of Expenditures of Federal Awards (SEFA) page were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="other",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, OTHER",
                verbose_name="Indicates what other miscellaneous items were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="other_explain",
            field=models.TextField(
                help_text="Census mapping: REVISIONS, OTHER_EXPLAIN",
                verbose_name="Explanation of what other miscellaneous items were edited during the revision",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_city",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                verbose_name="CPA City",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                verbose_name="CPA State",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_street",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                verbose_name="CPA Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_zipcode",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                verbose_name="CPA Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="auditor_ein",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                verbose_name="CPA mail address (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_name",
            field=models.TextField(verbose_name="Name of CPA Contact"),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_phone",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/d; SF-SAC 2001-2003: I/7/d; SF-SAC 2004-2007: I/7/d; SF-SAC 2008-2009: I/6/d; SF-SAC 2010-2012: I/6/d; SF-SAC 2013-2015: I/6/e; SF-SAC 2016-2018: I/6/e; SF-SAC 2019-2021: I/6/e; SF-SAC 2022: I/6/e Census mapping: GENERAL, CPAPHONE (AND) Data sources: SF-SAC 2008-2009: I/8/d; SF-SAC 2010-2012: I/8/d; SF-SAC 2013-2015: I/8/i; SF-SAC 2016-2018: I/8/i; SF-SAC 2019-2021: I/6/h/ix; SF-SAC 2022: I/6/h/ix Census mapping: MULTIPLE CPAS INFO, CPAPHONE",
                verbose_name="CPA phone number",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                verbose_name="Title of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="hist_address_street_line_2",
            field=models.TextField(verbose_name="CPA Street Address Line 2 in C-FAC"),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="hist_contact_fax",
            field=models.TextField(verbose_name="CPA fax number"),
        ),
    ]
