# Generated by Django 5.2.13 on 2026-07-06 14:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0026_unified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unified",
            name="aln",
            field=models.TextField(
                db_index=True,
                verbose_name="2-char agency code concatenated to 3-digit program extn",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                django.db.models.functions.text.Lower("auditee_certify_name"),
                name="du_auditee_certify_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                django.db.models.functions.text.Lower("auditee_name"),
                name="du_auditee_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                django.db.models.functions.text.Lower("auditor_certify_name"),
                name="du_auditor_certify_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                django.db.models.functions.text.Lower("auditor_contact_name"),
                name="du_auditor_contact_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                django.db.models.functions.text.Lower("auditor_firm_name"),
                name="du_auditor_firm_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                django.db.models.functions.text.Lower("auditee_email"),
                name="du_auditee_email_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                django.db.models.functions.text.Lower("auditor_email"),
                name="du_auditor_email_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(fields=["fy_start_date"], name="du_fy_start_date_idx"),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(fields=["fy_end_date"], name="du_fy_end_date_idx"),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(fields=["auditee_uei"], name="du_auditee_uei_idx"),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(fields=["auditee_ein"], name="du_auditee_ein_idx"),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                fields=["federal_agency_prefix"], name="du_federal_agency_prefix_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(
                fields=["federal_award_extension"],
                name="du_federal_award_extension_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=models.Index(fields=["audit_year"], name="du_audit_year_idx"),
        ),
        migrations.AlterModelTable(
            name="unified",
            table="dissemination_unified",
        ),
    ]
