# Generated by Django 4.2.3 on 2023-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dissemination",
            "0026_additionaluei_alter_secondaryauditor_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="captext",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="federalaward",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="finding",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="findingtext",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="passthrough",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="amount_expended",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/6/c; SF-SAC 2001-2003: III/10/d; SF-SAC 2004-2007: III/9/e; SF-SAC 2008-2009: III/9/e; SF-SAC 2010-2012: III/9/f; SF-SAC 2013-2015: III/6/d; SF-SAC 2016-2018: II/1/e; SF-SAC 2019-2021: II/1/e; SF-SAC 2022: II/1/e Census mapping: CFDA INFO, AMOUNT",
                max_digits=23,
                null=True,
                verbose_name="Amount Expended for the Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="award_reference",
            field=models.TextField(
                verbose_name="Order that the award line was reported"
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/h; SF-SAC 2019-2021: II/1/h; SF-SAC 2022: II/1/h Census mapping: CFDA INFO, CLUSTERTOTAL",
                max_digits=23,
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/g; SF-SAC 2019-2021: II/1/g; SF-SAC 2022: II/1/g Census mapping: CFDA INFO, PROGRAMTOTAL",
                max_digits=23,
                null=True,
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="loan_balance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/j; SF-SAC 2019-2021: II/1/j; SF-SAC 2022: II/1/j Census mapping: CFDA INFO, LOANBALANCE",
                max_digits=23,
                null=True,
                verbose_name="The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="passthrough_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 2016-2018: II/1/o; SF-SAC 2019-2021: II/1/o; SF-SAC 2022: II/1/o Census mapping: CFDA INFO, PASSTHROUGHAMOUNT",
                max_digits=23,
                null=True,
                verbose_name="Amount passed through to subrecipients",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="award_reference",
            field=models.TextField(
                null=True,
                verbose_name="Order that the award line was reported in Award",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="report_id",
            field=models.TextField(
                verbose_name="G-FAC generated identifier. FK along with other fields - refers to Award"
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="type_requirement",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: FINDINGS, TYPEREQUIREMENT",
                null=True,
                verbose_name="Type Requirement Failure",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="finding_ref_number",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: III/5/a; SF-SAC 2022: III/5/a Census mapping: FINDINGSTEXT, FINDINGREFNUMS",
                null=True,
                verbose_name="Data sources: SF-SAC 2019-2021: III/5/a; SF-SAC 2022: III/5/a Census mapping: FINDINGSTEXT, FINDINGREFNUMS",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="report_id",
            field=models.TextField(verbose_name="G-FAC generated identifier.l"),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_ein",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                null=True,
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_zip",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                null=True,
                verbose_name="CPA Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dollar_threshold",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/2; SF-SAC 2001-2003: III/3; SF-SAC 2004-2007: III/2; SF-SAC 2008-2009: III/2; SF-SAC 2010-2012: III/2; SF-SAC 2013-2015: III/2; SF-SAC 2016-2018: III/3/b; SF-SAC 2019-2021: III/3/b; SF-SAC 2022: III/3/b Census mapping: GENERAL, DOLLARTHRESHOLD",
                max_digits=23,
                null=True,
                verbose_name="Dollar Threshold to distinguish between Type A and Type B programs.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="report_id",
            field=models.TextField(
                unique=True, verbose_name="G-FAC generated identifier. "
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="total_amount_expended",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Data sources: SF-SAC 1997-2000: III/6/c- Total; SF-SAC 2001-2003: III/10/d -Total; SF-SAC 2004-2007: III/9/e -Total; SF-SAC 2008-2009: III/9/e -Total; SF-SAC 2010-2012: III/9/f -Total; SF-SAC 2013-2015: III/6/d -Total; SF-SAC 2016-2018: II/1/e- Total; SF-SAC 2019-2021: II/1/e - Total; SF-SAC 2022: II/1/e - Total Census mapping: GENERAL, TOTFEDEXPEND",
                max_digits=23,
                null=True,
                verbose_name="Total Federal Expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="report_id",
            field=models.TextField(
                verbose_name="G-FAC generated identifier. FK refers to a General"
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="report_id",
            field=models.TextField(
                verbose_name="G-FAC generated identifier. FK refers to General"
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="report_id",
            field=models.TextField(
                verbose_name="G-FAC generated identifier. FK to General"
            ),
        ),
        migrations.RemoveField(
            model_name="finding",
            name="finding_seq_number",
        ),
        migrations.RemoveField(
            model_name="note",
            name="note_seq_number",
        ),
    ]
