# Generated by Django 4.2.3 on 2023-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0026_additionaluei_alter_captext_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Revision",
        ),
        migrations.RenameField(
            model_name="finding",
            old_name="finding_ref_number",
            new_name="reference_number",
        ),
        migrations.RemoveField(
            model_name="federalaward",
            name="mp_audit_report_type",
        ),
        migrations.RemoveField(
            model_name="federalaward",
            name="passthrough_id",
        ),
        migrations.RemoveField(
            model_name="federalaward",
            name="passthrough_name",
        ),
        migrations.RemoveField(
            model_name="federalaward",
            name="type_requirement",
        ),
        migrations.RemoveField(
            model_name="finding",
            name="is_other_non_compliance",
        ),
        migrations.RemoveField(
            model_name="general",
            name="additional_ueis",
        ),
        migrations.RemoveField(
            model_name="general",
            name="auditee_signature_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="auditor_foreign_addr",
        ),
        migrations.RemoveField(
            model_name="general",
            name="auditor_signature_date",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_addl_duns_list",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_addl_ein_list",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_address_line_2",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_duns",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_fax",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditor_address_line_2",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditor_fax",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_dbkey",
        ),
        migrations.RemoveField(
            model_name="general",
            name="initial_date_received",
        ),
        migrations.RemoveField(
            model_name="general",
            name="is_duplicate_reports",
        ),
        migrations.RemoveField(
            model_name="general",
            name="is_going_concern",
        ),
        migrations.RemoveField(
            model_name="general",
            name="is_low_risk",
        ),
        migrations.RemoveField(
            model_name="general",
            name="is_material_noncompliance",
        ),
        migrations.RemoveField(
            model_name="general",
            name="is_material_weakness",
        ),
        migrations.RemoveField(
            model_name="general",
            name="is_significant_deficiency",
        ),
        migrations.RemoveField(
            model_name="general",
            name="sp_framework",
        ),
        migrations.RemoveField(
            model_name="general",
            name="sp_framework_auditor_opinion",
        ),
        migrations.RemoveField(
            model_name="general",
            name="type_report_major_program",
        ),
        migrations.RemoveField(
            model_name="secondaryauditor",
            name="hist_address_street_line_2",
        ),
        migrations.RemoveField(
            model_name="secondaryauditor",
            name="hist_contact_fax",
        ),
        migrations.AddField(
            model_name="federalaward",
            name="audit_report_type",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 2004-2007: III/9/h; SF-SAC 2008-2009: III/9/h; SF-SAC 2010-2012: III/9/i; SF-SAC 2013-2015: III/6/j; SF-SAC 2016-2018: III/1/b; SF-SAC 2019-2021: III/1/b; SF-SAC 2022: III/1/b Census mapping: CFDA INFO, TYPEREPORT_MP",
                verbose_name="Type of Report Issued on the Major Program Compliance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finding",
            name="is_other_matters",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 2013-2015: III/7/g; SF-SAC 2016-2018: III/4/h; SF-SAC 2019-2021: III/4/h; SF-SAC 2022: III/4/h Census mapping: FINDINGS, OTHERNONCOMPLIANCE",
                verbose_name="Other non-compliance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="auditor_foreign_address",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAFOREIGN",
                verbose_name="CPA Address - if international",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="date_created",
            field=models.DateField(
                default="2023-01-01",
                help_text="Census mapping: GENERAL, INITIAL DATE RECEIVED",
                verbose_name="The first date an audit component or Form SF-SAC was received by the Federal audit Clearinghouse (FAC).",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="is_additional_ueis",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="is_aicpa_audit_guide_included",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="is_going_concern_included",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 1997-2000: II/2; SF-SAC 2001-2003: II/2; SF-SAC 2004-2007: II/2; SF-SAC 2008-2009: II/2; SF-SAC 2010-2012: II/2; SF-SAC 2013-2015: II/2; SF-SAC 2016-2018: III/2/b; SF-SAC 2019-2021: III/2/b; SF-SAC 2022: III/2/b Census mapping: GENERAL, GOINGCONCERN",
                verbose_name="Whether or not the audit contained a going concern paragraph on financial statements",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="is_internal_control_deficiency_disclosed",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 1997-2000: II/3; SF-SAC 2001-2003: II/3; SF-SAC 2004-2007: II/3; SF-SAC 2008-2009: II/3; SF-SAC 2010-2012: II/3; SF-SAC 2013-2015: II/3; SF-SAC 2016-2018: III/2/c; SF-SAC 2019-2021: III/2/c; SF-SAC 2022: III/2/c Census mapping: GENERAL, SIGNIFICANTDEFICIENCY",
                verbose_name="Whether or not the audit disclosed a significant deficiency on financial statements",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="is_internal_control_material_weakness_disclosed",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 1997-2000: II/4; SF-SAC 2001-2003: II/4; SF-SAC 2004-2007: II/4; SF-SAC 2008-2009: II/4; SF-SAC 2010-2012: II/4; SF-SAC 2013-2015: II/4; SF-SAC 2016-2018: III/2/d; SF-SAC 2019-2021: III/2/d; SF-SAC 2022: III/2/d Census mapping: GENERAL, MATERIALWEAKNESS",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="is_low_risk_auditee",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 1997-2000: III/3; SF-SAC 2001-2003: III/4; SF-SAC 2004-2007: III/3; SF-SAC 2008-2009: III/3; SF-SAC 2010-2012: III/3; SF-SAC 2013-2015: III/3; SF-SAC 2016-2018: III/3/c; SF-SAC 2019-2021: III/3/c; SF-SAC 2022: III/3/c Census mapping: GENERAL, LOWRISK",
                verbose_name="Indicate whether or not the auditee qualified as a low-risk auditee",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="is_material_noncompliance_disclosed",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 1997-2000: II/5; SF-SAC 2001-2003: II/5; SF-SAC 2004-2007: II/5; SF-SAC 2008-2009: II/5; SF-SAC 2010-2012: II/5; SF-SAC 2013-2015: II/5; SF-SAC 2016-2018: III/2/e; SF-SAC 2019-2021: III/2/e; SF-SAC 2022: III/2/e Census mapping: GENERAL, MATERIALNONCOMPLIANCE",
                verbose_name="Whether or not the audit disclosed a material noncompliance on financial statements",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="sp_framework_basis",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 2016-2018: III/2/a/ii; SF-SAC 2019-2021: III/2/a/i; SF-SAC 2022: III/2/a/i Census mapping: GENERAL, SP_FRAMEWORK",
                verbose_name="Special Purpose Framework that was used as the basis of accounting",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="general",
            name="sp_framework_opinions",
            field=models.TextField(
                default="",
                help_text="Data sources: SF-SAC 2016-2018: III/2/a/iv; SF-SAC 2019-2021: III/2/a/iii; SF-SAC 2022: III/2/a/iii Census mapping: GENERAL, TYPEREPORT_SP_FRAMEWORK",
                verbose_name="The auditor's opinion on the special purpose framework",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additionaluei",
            name="report_id",
            field=models.TextField(verbose_name="; foreign key everywhere else"),
        ),
        migrations.AlterField(
            model_name="captext",
            name="contains_chart_or_table",
            field=models.TextField(
                help_text="Census mapping: CAPTEXT, CHARTSTABLES",
                verbose_name="Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="captext",
            name="planned_action",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: IV/2; SF-SAC 2022: IV/2 Census mapping: CAPTEXT, TEXT",
                verbose_name="Content of the Corrective Action Plan (CAP)",
            ),
        ),
        migrations.AlterField(
            model_name="captext",
            name="report_id",
            field=models.TextField(verbose_name="; foreign key everywhere else"),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="additional_award_identification",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/c; SF-SAC 2019-2021: II/1/c; SF-SAC 2022: II/1/c Census mapping: CFDA INFO, AWARDIDENTIFICATION",
                verbose_name="Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="amount_expended",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/c; SF-SAC 2001-2003: III/10/d; SF-SAC 2004-2007: III/9/e; SF-SAC 2008-2009: III/9/e; SF-SAC 2010-2012: III/9/f; SF-SAC 2013-2015: III/6/d; SF-SAC 2016-2018: II/1/e; SF-SAC 2019-2021: II/1/e; SF-SAC 2022: II/1/e Census mapping: CFDA INFO, AMOUNT",
                verbose_name="Amount Expended for the Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/f; SF-SAC 2019-2021: II/1/f; SF-SAC 2022: II/1/f Census mapping: CFDA INFO, CLUSTERNAME",
                verbose_name="The name of the cluster",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="cluster_total",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/h; SF-SAC 2019-2021: II/1/h; SF-SAC 2022: II/1/h Census mapping: CFDA INFO, CLUSTERTOTAL",
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/b; SF-SAC 2001-2003: III/10/c; SF-SAC 2004-2007: III/9/d; SF-SAC 2008-2009: III/9/d; SF-SAC 2010-2012: III/9/e; SF-SAC 2013-2015: III/6/c; SF-SAC 2016-2018: II/1/d; SF-SAC 2019-2021: II/1/d; SF-SAC 2022: II/1/d Census mapping: CFDA INFO, FEDERALPROGRAMNAME",
                verbose_name="Name of Federal Program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="federal_program_total",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/g; SF-SAC 2019-2021: II/1/g; SF-SAC 2022: II/1/g Census mapping: CFDA INFO, PROGRAMTOTAL",
                verbose_name="Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="findings_count",
            field=models.IntegerField(
                help_text="Data sources: SF-SAC 2013-2015: III/6/k; SF-SAC 2016-2018: III/1/c; SF-SAC 2019-2021: III/1/c; SF-SAC 2022: III/1/c Census mapping: CFDA INFO, FINDINGSCOUNT",
                verbose_name="Number of findings for the federal program (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="is_direct",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2001-2003: III/10/e; SF-SAC 2004-2007: III/9/f; SF-SAC 2008-2009: III/9/f; SF-SAC 2010-2012: III/9/g; SF-SAC 2013-2015: III/6/h; SF-SAC 2016-2018: II/1/k; SF-SAC 2019-2021: II/1/k; SF-SAC 2022: II/1/k Census mapping: CFDA INFO, DIRECT",
                verbose_name="Indicate whether or not the award was received directly from a Federal awarding agency",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="is_loan",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/6/f; SF-SAC 2016-2018: II/1/i; SF-SAC 2019-2021: II/1/i; SF-SAC 2022: II/1/i Census mapping: CFDA INFO, LOANS",
                verbose_name="Indicate whether or not the program is a Loan or Loan Guarantee (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="is_major",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: III/7/a; SF-SAC 2001-2003: III/10/f; SF-SAC 2004-2007: III/9/g; SF-SAC 2008-2009: III/9/g; SF-SAC 2010-2012: III/9/h; SF-SAC 2013-2015: III/6/i; SF-SAC 2016-2018: III/1/a; SF-SAC 2019-2021: III/1/a; SF-SAC 2022: III/1/a Census mapping: CFDA INFO, MAJORPROGRAM",
                verbose_name="Indicate whether or not the Federal program is a major program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="is_passthrough_award",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/n; SF-SAC 2019-2021: II/1/n; SF-SAC 2022: II/1/n Census mapping: CFDA INFO, PASSTHROUGHAWARD",
                verbose_name="Indicates whether or not funds were passed through to any subrecipients for the Federal program",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="loan_balance",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/j; SF-SAC 2019-2021: II/1/j; SF-SAC 2022: II/1/j Census mapping: CFDA INFO, LOANBALANCE",
                verbose_name="The loan or loan guarantee (loan) balance outstanding at the end of the audit period.  A response of ‘N/A’ is acceptable.",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="other_cluster_name",
            field=models.TextField(
                help_text="Census mapping: CFDA INFO, OTHERCLUSTERNAME",
                verbose_name="The name of the cluster (if not listed in the Compliance Supplement)",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="passthrough_amount",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/o; SF-SAC 2019-2021: II/1/o; SF-SAC 2022: II/1/o Census mapping: CFDA INFO, PASSTHROUGHAMOUNT",
                null=True,
                verbose_name="Amount passed through to subrecipients",
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="report_id",
            field=models.TextField(verbose_name="; foreign key everywhere else"),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="state_cluster_name",
            field=models.TextField(
                help_text="Census mapping: CFDA INFO, STATECLUSTERNAME",
                verbose_name="The name of the state cluster",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="award_reference",
            field=models.TextField(
                verbose_name="Order that the award line was reported in Award"
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="is_material_weakness",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/h; SF-SAC 2016-2018: III/4/i; SF-SAC 2019-2021: III/4/i; SF-SAC 2022: III/4/i Census mapping: FINDINGS, MATERIALWEAKNESS",
                verbose_name="Material Weakness finding",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="is_modified_opinion",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/f; SF-SAC 2016-2018: III/4/g; SF-SAC 2019-2021: III/4/g; SF-SAC 2022: III/4/g Census mapping: FINDINGS, MODIFIEDOPINION",
                verbose_name="Modified Opinion finding",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="is_other_findings",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/j; SF-SAC 2016-2018: III/4/k; SF-SAC 2019-2021: III/4/k; SF-SAC 2022: III/4/k Census mapping: FINDINGS, OTHERFINDINGS",
                verbose_name="Other findings",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="is_questioned_costs",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/k; SF-SAC 2016-2018: III/4/l; SF-SAC 2019-2021: III/4/l; SF-SAC 2022: III/4/l Census mapping: FINDINGS, QCOSTS",
                verbose_name="Questioned Costs",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="is_repeat_finding",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/4/m; SF-SAC 2019-2021: III/4/m; SF-SAC 2022: III/4/m Census mapping: FINDINGS, REPEATFINDING",
                verbose_name="Indicates whether or not the audit finding was a repeat of an audit finding in the immediate prior audit",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="is_significant_deficiency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: II/3; SF-SAC 2001-2003: II/3; SF-SAC 2004-2007: II/3; SF-SAC 2008-2009: II/3; SF-SAC 2010-2012: II/3; SF-SAC 2013-2015: II/3; SF-SAC 2016-2018: III/2/c; SF-SAC 2019-2021: III/2/c; SF-SAC 2022: III/2/c Census mapping: FINDINGS, SIGNIFICANTDEFICIENCY",
                verbose_name="Significant Deficiency finding",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="prior_finding_ref_numbers",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/4/n; SF-SAC 2019-2021: III/4/n; SF-SAC 2022: III/4/n Census mapping: FINDINGS, PRIORFINDINGREFNUMS",
                verbose_name="Audit finding reference numbers from the immediate prior audit",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="report_id",
            field=models.TextField(verbose_name="; foreign key everywhere else"),
        ),
        migrations.AlterField(
            model_name="finding",
            name="type_requirement",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: III/7/e; SF-SAC 2016-2018: III/4/f; SF-SAC 2019-2021: III/4/f; SF-SAC 2022: III/4/f Census mapping: FINDINGS, TYPEREQUIREMENT",
                verbose_name="Type Requirement Failure",
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="report_id",
            field=models.TextField(verbose_name="; foreign key everywhere else"),
        ),
        migrations.AlterField(
            model_name="general",
            name="agencies_with_prior_findings",
            field=models.TextField(verbose_name="List of agencues with prior findings"),
        ),
        migrations.AlterField(
            model_name="general",
            name="audit_period_covered",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/3; SF-SAC 2001-2003: I/3; SF-SAC 2004-2007: I/3; SF-SAC 2008-2009: I/3; SF-SAC 2010-2012: I/3; SF-SAC 2013-2015: I/3; SF-SAC 2016-2018: I/3; SF-SAC 2019-2021: I/3; SF-SAC 2022: I/3 Census mapping: GENERAL, PERIODCOVERED",
                verbose_name="Audit Period Covered by Audit",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="audit_year",
            field=models.TextField(
                help_text="Census mapping: GENERAL, AUDITYEAR",
                verbose_name="Audit year from fy_start_date.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certified_date",
            field=models.DateField(
                verbose_name="The date at which the audit transitioned to 'auditee certified'"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYNAME",
                verbose_name="Name of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_certify_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/g; SF-SAC 2001-2003: I/6/g; SF-SAC 2004-2007: I/6/g; SF-SAC 2008-2009: I/5/g; SF-SAC 2010-2012: I/5/g; SF-SAC 2013-2015: certifications; SF-SAC 2016-2018: certifications; SF-SAC 2019-2021: certifications; SF-SAC 2022: certifications Census mapping: GENERAL, AUDITEECERTIFYTITLE",
                verbose_name="Title of Auditee Certifying Official",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_contact_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEECONTACT",
                verbose_name="Name of Auditee Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/c; SF-SAC 2001-2003: I/6/c; SF-SAC 2004-2007: I/6/c; SF-SAC 2008-2009: I/5/c; SF-SAC 2010-2012: I/5/c; SF-SAC 2013-2015: I/5/c; SF-SAC 2016-2018: I/5/c; SF-SAC 2019-2021: I/5/c; SF-SAC 2022: I/5/c Census mapping: GENERAL, AUDITEETITLE",
                verbose_name="Title of Auditee Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_ein",
            field=models.TextField(
                verbose_name="Primary Employer Identification Number"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/f; SF-SAC 2001-2003: I/6/f; SF-SAC 2004-2007: I/6/f; SF-SAC 2008-2009: I/5/f; SF-SAC 2010-2012: I/5/f; SF-SAC 2013-2015: I/5/f; SF-SAC 2016-2018: I/5/e; SF-SAC 2019-2021: I/5/e; SF-SAC 2022: I/5/e Census mapping: GENERAL, AUDITEEEMAIL",
                verbose_name="Auditee Email address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, STATE",
                verbose_name="Auditee State",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_uei",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2022: I/4/g Census mapping: GENERAL, UEI",
                verbose_name="Auditee UEI",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditee_zip",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/6/b; SF-SAC 2001-2003: I/6/b; SF-SAC 2004-2007: I/6/b; SF-SAC 2008-2009: I/5/b; SF-SAC 2010-2012: I/5/b; SF-SAC 2013-2015: I/5/b; SF-SAC 2016-2018: I/5/b; SF-SAC 2019-2021: I/5/b; SF-SAC 2022: I/5/b Census mapping: GENERAL, ZIPCODE",
                verbose_name="Auditee Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_address_line_1",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                verbose_name="CPA Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_certified_date",
            field=models.DateField(
                verbose_name="The date at which the audit transitioned to 'auditor certified'"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_city",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                verbose_name="CPA City",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_contact_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPACONTACT (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/g; SF-SAC 2016-2018: I/8/g; SF-SAC 2019-2021: I/6/h/vii; SF-SAC 2022: I/6/h/vii Census mapping: MULTIPLE CPAS INFO, CPACONTACT",
                verbose_name="Name of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                verbose_name="Title of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_country",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACOUNTRY",
                verbose_name="CPA Country",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_ein",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                verbose_name="CPA mail address (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_phone",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/d; SF-SAC 2001-2003: I/7/d; SF-SAC 2004-2007: I/7/d; SF-SAC 2008-2009: I/6/d; SF-SAC 2010-2012: I/6/d; SF-SAC 2013-2015: I/6/e; SF-SAC 2016-2018: I/6/e; SF-SAC 2019-2021: I/6/e; SF-SAC 2022: I/6/e Census mapping: GENERAL, CPAPHONE (AND) Data sources: SF-SAC 2008-2009: I/8/d; SF-SAC 2010-2012: I/8/d; SF-SAC 2013-2015: I/8/i; SF-SAC 2016-2018: I/8/i; SF-SAC 2019-2021: I/6/h/ix; SF-SAC 2022: I/6/h/ix Census mapping: MULTIPLE CPAS INFO, CPAPHONE",
                verbose_name="CPA phone number",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                verbose_name="CPA State",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="auditor_zip",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                verbose_name="CPA Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="certified_date",
            field=models.DateField(
                verbose_name="The date at which the audit transitioned to 'certified'"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="cognizant_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, COGAGENCY",
                verbose_name="Two digit Federal agency prefix of the cognizant agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="data_source",
            field=models.TextField(
                verbose_name="Data origin; GSA, Census, or TESTDATA"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="dollar_threshold",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/2; SF-SAC 2001-2003: III/3; SF-SAC 2004-2007: III/2; SF-SAC 2008-2009: III/2; SF-SAC 2010-2012: III/2; SF-SAC 2013-2015: III/2; SF-SAC 2016-2018: III/3/b; SF-SAC 2019-2021: III/3/b; SF-SAC 2022: III/3/b Census mapping: GENERAL, DOLLARTHRESHOLD",
                verbose_name="Dollar Threshold to distinguish between Type A and Type B programs.",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="entity_type",
            field=models.TextField(
                help_text="Census mapping: GENERAL, ENTITY_TYPE",
                verbose_name="Self reported type of entity (i.e., States, Local Governments, Indian Tribes, Institutions of Higher Education, NonProfit)",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="fy_end_date",
            field=models.DateField(
                help_text="Data sources: SF-SAC 1997-2000: Part I, Item 1; SF-SAC 2001-2003: Part I, Item 1; SF-SAC 2004-2007: Part I, Item 1; SF-SAC 2008-2009: Part I, Item 1; SF-SAC 2010-2012: Part I, Item 1; SF-SAC 2013-2015: Part I, Item 1; SF-SAC 2016-2018: Part I, Item 1; SF-SAC 2019-2021: I/1/b; SF-SAC 2022: I/1/b Census mapping: GENERAL, FYENDDATE",
                verbose_name="Fiscal Year End Date",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="fy_start_date",
            field=models.DateField(
                help_text="Data sources: SF-SAC 2019-2021: Part I, Item 1(a); SF-SAC 2022: Part I, Item 1(a) Census mapping: GENERAL, FYSTARTDATE",
                verbose_name="Fiscal Year Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="gaap_results",
            field=models.TextField(verbose_name="GAAP Results by Auditor"),
        ),
        migrations.AlterField(
            model_name="general",
            name="is_public",
            field=models.BooleanField(
                default=False,
                verbose_name="True for public records, False for non-public records",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="is_sp_framework_required",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: III/2/a/iii; SF-SAC 2019-2021: III/2/a/ii; SF-SAC 2022: III/2/a/ii Census mapping: GENERAL, SP_FRAMEWORK_REQUIRED",
                verbose_name="Indicate whether or not the special purpose framework used as basis of accounting by state law or tribal law",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="number_months",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/3; SF-SAC 2001-2003: I/3; SF-SAC 2004-2007: I/3; SF-SAC 2008-2009: I/3; SF-SAC 2010-2012: I/3; SF-SAC 2013-2015: I/3; SF-SAC 2016-2018: I/3; SF-SAC 2019-2021: I/3; SF-SAC 2022: I/3 Census mapping: GENERAL, NUMBERMONTHS",
                verbose_name="Number of Months Covered by the 'Other' Audit Period",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="oversight_agency",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/9; SF-SAC 2001-2003: I/9 Census mapping: GENERAL, OVERSIGHTAGENCY",
                verbose_name="Two digit Federal agency prefix of the oversight agency",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="ready_for_certification_date",
            field=models.DateField(
                verbose_name="The date at which the audit transitioned to 'ready for certification'"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="submitted_date",
            field=models.DateField(
                verbose_name="The date at which the audit transitioned to 'submitted'"
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="total_amount_expended",
            field=models.BigIntegerField(
                help_text="Data sources: SF-SAC 1997-2000: III/6/c- Total; SF-SAC 2001-2003: III/10/d -Total; SF-SAC 2004-2007: III/9/e -Total; SF-SAC 2008-2009: III/9/e -Total; SF-SAC 2010-2012: III/9/f -Total; SF-SAC 2013-2015: III/6/d -Total; SF-SAC 2016-2018: II/1/e- Total; SF-SAC 2019-2021: II/1/e - Total; SF-SAC 2022: II/1/e - Total Census mapping: GENERAL, TOTFEDEXPEND",
                verbose_name="Total Federal Expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="type_audit_code",
            field=models.TextField(verbose_name="Determines if audit is A133 or UG"),
        ),
        migrations.AlterField(
            model_name="note",
            name="accounting_policies",
            field=models.TextField(
                verbose_name="A description of the significant accounting policies used in preparing the SEFA (2 CFR 200.510(b)(6))"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, CONTENT",
                verbose_name="Content of the Note",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="is_minimis_rate_used",
            field=models.TextField(
                verbose_name="'Yes', 'No', or 'Both' (2 CFR 200.414(f))"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2019-2021: II/2; SF-SAC 2022: II/2 Census mapping: NOTES, TITLE",
                verbose_name="Note title",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="rate_explained",
            field=models.TextField(verbose_name="Explanation for minimis rate"),
        ),
        migrations.AlterField(
            model_name="note",
            name="report_id",
            field=models.TextField(verbose_name="; foreign key everywhere else"),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="award_reference",
            field=models.TextField(
                verbose_name="Order that the award line was reported"
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_id",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/m; SF-SAC 2019-2021: II/1/m; SF-SAC 2022: II/1/m Census mapping: PASSTHROUGH, PASSTHROUGHID",
                verbose_name="Identifying Number Assigned by the Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="passthrough_name",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2016-2018: II/1/l; SF-SAC 2019-2021: II/1/l; SF-SAC 2022: II/1/l Census mapping: PASSTHROUGH, PASSTHROUGHNAME",
                verbose_name="Name of Pass-through Entity",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_city",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPACITY (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/d; SF-SAC 2016-2018: I/8/d; SF-SAC 2019-2021: I/6/h/iv; SF-SAC 2022: I/6/h/iv Census mapping: MULTIPLE CPAS INFO, CPACITY",
                verbose_name="CPA City",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_state",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTATE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/e; SF-SAC 2016-2018: I/8/e; SF-SAC 2019-2021: I/6/h/v; SF-SAC 2022: I/6/h/v Census mapping: MULTIPLE CPAS INFO, CPASTATE",
                verbose_name="CPA State",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_street",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPASTREET1 (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/c; SF-SAC 2016-2018: I/8/c; SF-SAC 2019-2021: I/6/h/iii; SF-SAC 2022: I/6/h/iii Census mapping: MULTIPLE CPAS INFO, CPASTREET1",
                verbose_name="CPA Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="address_zipcode",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/b; SF-SAC 2001-2003: I/7/b; SF-SAC 2004-2007: I/7/b; SF-SAC 2008-2009: I/6/b; SF-SAC 2010-2012: I/6/b; SF-SAC 2013-2015: I/6/c; SF-SAC 2016-2018: I/6/c; SF-SAC 2019-2021: I/6/c; SF-SAC 2022: I/6/c Census mapping: GENERAL, CPAZIPCODE (AND) Data sources: SF-SAC 2008-2009: I/8/b; SF-SAC 2010-2012: I/8/b; SF-SAC 2013-2015: I/8/f; SF-SAC 2016-2018: I/8/f; SF-SAC 2019-2021: I/6/h/vi; SF-SAC 2022: I/6/h/vi Census mapping: MULTIPLE CPAS INFO, CPAZIPCODE",
                verbose_name="CPA Zip Code",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="auditor_ein",
            field=models.TextField(
                help_text="Data sources: SF-SAC 2013-2015: I/6/b; SF-SAC 2016-2018: I/6/b; SF-SAC 2019-2021: I/6/b; SF-SAC 2022: I/6/b Census mapping: GENERAL, AUDITOR_EIN (AND) Data sources: SF-SAC 2013-2015: I/8/b; SF-SAC 2016-2018: I/8/b; SF-SAC 2019-2021: I/6/h/ii; SF-SAC 2022: I/6/h/ii Census mapping: MULTIPLE CPAS INFO, CPAEIN",
                verbose_name="CPA Firm EIN (only available for audit years 2013 and beyond)",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_email",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/f; SF-SAC 2001-2003: I/7/f; SF-SAC 2004-2007: I/7/f; SF-SAC 2008-2009: I/6/f; SF-SAC 2010-2012: I/6/f; SF-SAC 2013-2015: I/6/g; SF-SAC 2016-2018: I/6/f; SF-SAC 2019-2021: I/6/f; SF-SAC 2022: I/6/f Census mapping: GENERAL, CPAEMAIL (AND) Data sources: SF-SAC 2008-2009: I/8/f; SF-SAC 2010-2012: I/8/f; SF-SAC 2013-2015: I/8/k; SF-SAC 2016-2018: I/8/k; SF-SAC 2019-2021: I/6/h/x; SF-SAC 2022: I/6/h/x Census mapping: MULTIPLE CPAS INFO, CPAEMAIL",
                verbose_name="CPA mail address (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_name",
            field=models.TextField(verbose_name="Name of CPA Contact"),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_phone",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/d; SF-SAC 2001-2003: I/7/d; SF-SAC 2004-2007: I/7/d; SF-SAC 2008-2009: I/6/d; SF-SAC 2010-2012: I/6/d; SF-SAC 2013-2015: I/6/e; SF-SAC 2016-2018: I/6/e; SF-SAC 2019-2021: I/6/e; SF-SAC 2022: I/6/e Census mapping: GENERAL, CPAPHONE (AND) Data sources: SF-SAC 2008-2009: I/8/d; SF-SAC 2010-2012: I/8/d; SF-SAC 2013-2015: I/8/i; SF-SAC 2016-2018: I/8/i; SF-SAC 2019-2021: I/6/h/ix; SF-SAC 2022: I/6/h/ix Census mapping: MULTIPLE CPAS INFO, CPAPHONE",
                verbose_name="CPA phone number",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="contact_title",
            field=models.TextField(
                help_text="Data sources: SF-SAC 1997-2000: I/7/c; SF-SAC 2001-2003: I/7/c; SF-SAC 2004-2007: I/7/c; SF-SAC 2008-2009: I/6/c; SF-SAC 2010-2012: I/6/c; SF-SAC 2013-2015: I/6/d; SF-SAC 2016-2018: I/6/d; SF-SAC 2019-2021: I/6/d; SF-SAC 2022: I/6/d Census mapping: GENERAL, CPATITLE (AND) Data sources: SF-SAC 2008-2009: I/8/c; SF-SAC 2010-2012: I/8/c; SF-SAC 2013-2015: I/8/h; SF-SAC 2016-2018: I/8/h; SF-SAC 2019-2021: I/6/h/viii; SF-SAC 2022: I/6/h/viii Census mapping: MULTIPLE CPAS INFO, CPATITLE",
                verbose_name="Title of CPA Contact",
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="report_id",
            field=models.TextField(verbose_name="; foreign key everywhere else"),
        ),
    ]
