# Generated by Django 4.2.4 on 2023-08-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissemination", "0026_additionaluei_alter_captext_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalEin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.TextField(
                        verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
                    ),
                ),
                ("additional_ein", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_addl_duns_list",
        ),
        migrations.RemoveField(
            model_name="general",
            name="hist_auditee_addl_ein_list",
        ),
        migrations.AddField(
            model_name="general",
            name="additional_eins",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="additionaluei",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
        migrations.AlterField(
            model_name="captext",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
        migrations.AlterField(
            model_name="federalaward",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
        migrations.AlterField(
            model_name="findingtext",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
        migrations.AlterField(
            model_name="general",
            name="report_id",
            field=models.TextField(
                unique=True,
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data.",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
        migrations.AlterField(
            model_name="passthrough",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
        migrations.AlterField(
            model_name="secondaryauditor",
            name="report_id",
            field=models.TextField(
                verbose_name="GSA FAC generated identifier; PK for a given submission, equivalent to DBKEY/AY in historic data."
            ),
        ),
    ]
