# Generated by Django 5.2.16 on 2026-09-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0027_alter_unified_aln_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unified",
            old_name="report_id",
            new_name="report",
        ),
    ]
