# Generated by Django 5.2.16 on 2026-09-15 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0027_alter_unified_aln_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resubmission",
            name="audit_opinion_changes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Audit Opinion Changes"
            ),
        ),
        migrations.AddField(
            model_name="resubmission",
            name="resubmission_justification",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name="Resubmission Justification"),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="resubmission",
            name="resubmission_requester",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name="Resubmission Requester"),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="resubmission",
            name="resubmission_type",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Resubmission Type (Formerly Resubmission Action)",
            ),
        ),
    ]
