# Generated by Django 5.2.16 on 2026-09-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0028_resubmission_audit_opinion_changes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unified",
            old_name="report_id",
            new_name="report",
        ),
    ]
