# Generated by Django 5.2.16 on 2026-10-09 12:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0029_rename_report_id_unified_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="unified",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="general",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_general_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unified",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_unified_gin_idx"
            ),
        ),
    ]
