# Generated by Django 5.2.16 on 2026-10-08 18:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dissemination", "0030_general_search_vector_unified_search_vector_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="unified",
            new_name="search_vector_unified_gin_idx",
            old_name="search_vector_gin_idx",
        ),
        migrations.AddIndex(
            model_name="general",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_general_gin_idx"
            ),
        ),
    ]
