---
applications:
- name: gsa-fac
  buildpacks:
    - python_buildpack
  memory: 512M
  path: ../
  timeout: 180
  env:
    ENV: PRODUCTION
    DJANGO_BASE_URL: https://fac-prod.app.cloud.gov
    ALLOWED_HOSTS: https://fac-prod.app.cloud.gov
  routes:
  - route: fac-prod.app.cloud.gov
  instances: 2
  services:
  - fac-db
  - fac-public-s3
  - fac-key-service
  - production-deployer