---
applications:
- name: gsa-fac-dev
  buildpacks:
    - python_buildpack
  memory: 512M
  path: ../
  timeout: 180
  env:
    ENV: DEVELOPMENT
    DJANGO_BASE_URL: https://fac-dev.app.cloud.gov
    # doing in procfile because of no-hash install
    DISABLE_COLLECTSTATIC: true
  routes:
  - route: fac-dev.app.cloud.gov
  instances: 1
  services:
  - fac_dev_db
  - fac-public-s3
  - fac-key-service
