---
applications:
- name: gsa-fac
  buildpacks:
    - python_buildpack
  memory: 512M
  path: ../
  timeout: 180
  env:
    ENV: STAGING
    DJANGO_BASE_URL: https://fac-staging.app.cloud.gov
    ALLOWED_HOSTS: fac-staging.app.cloud.gov
  routes:
  - route: fac-staging.app.cloud.gov
  instances: 1
  services:
  - fac-db
  - fac-public-s3
  - fac-key-service
  - staging-deployer
- name: clamav-rest
  instances: 1
  memory: 2G
  env:
    MAX_FILE_SIZE: 25M
    SIGNATURE_CHECKS: 1  # number of checks per day for a new database signature
  docker:
    image: ajilaag/clamav-rest:20230220
  routes:
    - route: clamav-rest-staging.apps.internal
