---
applications:
  - name: ((pgrst_app_name))
    instances: ((pgrst_instances))
    disk_quota: ((pgrst_disk_quota))
    memory: ((pgrst_mem_amount))
    timeout: 180
    docker:
      image: ((pgrst_image))
    routes:
      - route: fac-((env_name))-postgrest.app.cloud.gov
    env:
      PGRST_DB_URI: ((db_uri))
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: anon
