---
applications:
  - name: gsa-fac
    buildpacks:
      - python_buildpack
    memory: 512M
    path: ../
    health-check-type: process
    timeout: 180
    env:
      ENV: DEVELOPMENT
      DJANGO_BASE_URL: https://fac-dev.app.cloud.gov
      ALLOWED_HOSTS: fac-dev.app.cloud.gov
      AV_SCAN_URL: http://clamav-rest-dev.apps.internal:9000/scan
      # The following is commented out because collectstatic in the buildpack phase does not seem to be working, so we're running it in .profile.
      # If we find out what's broken, or it's fixed up stream, then we can decide whether or not we want to disable it.
      # DISABLE_COLLECTSTATIC: true
    routes:
      - route: fac-dev.app.cloud.gov
    instances: 1
    services:
      - fac-db
      - fac-public-s3
      - fac-key-service
      - dev-deployer
  - name: clamav-rest
    instances: 1
    memory: 2G
    env:
      MAX_FILE_SIZE: 25M
      SIGNATURE_CHECKS: 1  # number of checks per day for a new database signature
    docker:
      image: ajilaag/clamav-rest:20230220
    routes:
      - route: clamav-rest-dev.apps.internal
