# Generated by Django 4.0.4 on 2022-07-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_logingovuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logingovuser",
            name="login_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
