# Generated by Django 5.2 on 2025-05-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
    ]
