# Generated by Django 4.1.3 on 2022-11-23 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_logingovuser_login_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginGovUser",
        ),
    ]
