# Generated by Django 4.2.3 on 2023-09-20 13:57

import audit.models
import audit.validators
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleAuditChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "submission_status",
                    django_fsm.FSMField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("ready_for_certification", "Ready for Certification"),
                            ("auditor_certified", "Auditor Certified"),
                            ("auditee_certified", "Auditee Certified"),
                            ("certified", "Certified"),
                            ("submitted", "Submitted"),
                            ("disseminated", "Disseminated"),
                        ],
                        default="in_progress",
                        max_length=50,
                    ),
                ),
                ("data_source", models.CharField(default="GSA")),
                (
                    "transition_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("in_progress", "In Progress"),
                                ("ready_for_certification", "Ready for Certification"),
                                ("auditor_certified", "Auditor Certified"),
                                ("auditee_certified", "Auditee Certified"),
                                ("certified", "Certified"),
                                ("submitted", "Submitted"),
                                ("disseminated", "Disseminated"),
                            ],
                            max_length=40,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "transition_date",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateTimeField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("report_id", models.CharField(max_length=17, unique=True)),
                (
                    "audit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single-audit", "Single Audit"),
                            ("program-specific", "Program-Specific Audit"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "general_information",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_general_information_json],
                    ),
                ),
                (
                    "audit_information",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_audit_information_json],
                    ),
                ),
                (
                    "federal_awards",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_federal_award_json],
                    ),
                ),
                (
                    "corrective_action_plan",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            audit.validators.validate_corrective_action_plan_json
                        ],
                    ),
                ),
                (
                    "findings_text",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_findings_text_json],
                    ),
                ),
                (
                    "findings_uniform_guidance",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            audit.validators.validate_findings_uniform_guidance_json
                        ],
                    ),
                ),
                (
                    "additional_ueis",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_additional_ueis_json],
                    ),
                ),
                (
                    "additional_eins",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_additional_eins_json],
                    ),
                ),
                (
                    "secondary_auditors",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_secondary_auditors_json],
                    ),
                ),
                (
                    "notes_to_sefa",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_notes_to_sefa_json],
                    ),
                ),
                (
                    "auditor_certification",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            audit.validators.validate_auditor_certification_json
                        ],
                    ),
                ),
                (
                    "auditee_certification",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            audit.validators.validate_auditee_certification_json
                        ],
                    ),
                ),
                (
                    "tribal_data_consent",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_tribal_data_consent_json],
                    ),
                ),
                (
                    "cognizant_agency",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Agency assigned to this large submission. Computed when the submisson is finalized, but may be overridden",
                    ),
                ),
                (
                    "oversight_agency",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Agency assigned to this not so large submission. Computed when the submisson is finalized",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SF-SAC",
                "verbose_name_plural": "SF-SACs",
            },
            bases=(models.Model, audit.models.GeneralInformationMixin),
        ),
        migrations.CreateModel(
            name="SubmissionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("access-granted", "Access granted"),
                            ("additional-eins-updated", "Additional EINs updated"),
                            ("additional-ueis-updated", "Additional UEIs updated"),
                            ("audit-information-updated", "Audit information updated"),
                            ("audit-report-pdf-updated", "Audit report PDF updated"),
                            (
                                "auditee-certification-completed",
                                "Auditee certification completed",
                            ),
                            (
                                "auditor-certification-completed",
                                "Auditor certification completed",
                            ),
                            (
                                "corrective-action-plan-updated",
                                "Corrective action plan updated",
                            ),
                            ("created", "Created"),
                            ("federal-awards-updated", "Federal awards updated"),
                            (
                                "federal-awards-audit-findings-updated",
                                "Federal awards audit findings updated",
                            ),
                            (
                                "federal-awards-audit-findings-text-updated",
                                "Federal awards audit findings text updated",
                            ),
                            (
                                "findings-uniform-guidance-updated",
                                "Findings uniform guidance updated",
                            ),
                            (
                                "general-information-updated",
                                "General information updated",
                            ),
                            ("locked-for-certification", "Locked for certification"),
                            ("notes-to-sefa-updated", "Notes to SEFA updated"),
                            (
                                "secondary-auditors-updated",
                                "Secondary auditors updated",
                            ),
                            ("submitted", "Submitted to the FAC for processing"),
                        ]
                    ),
                ),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SingleAuditReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=audit.models.single_audit_report_path,
                        validators=[audit.validators.validate_single_audit_report_file],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "component_page_numbers",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[audit.validators.validate_component_page_numbers],
                    ),
                ),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=audit.models.excel_file_path,
                        validators=[audit.validators.validate_excel_file],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("form_section", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            (
                                "certifying_auditee_contact",
                                "Auditee Certifying Official",
                            ),
                            (
                                "certifying_auditor_contact",
                                "Auditor Certifying Official",
                            ),
                            ("editor", "Audit Editor"),
                        ],
                        help_text="Access type granted to this user",
                        max_length=50,
                    ),
                ),
                ("fullname", models.CharField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User ID associated with this email address, empty if no FAC account exists",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "accesses",
            },
        ),
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "certifying_auditee_contact")),
                fields=("sac",),
                name="audit_$(class)s_single_certifying_auditee",
            ),
        ),
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "certifying_auditor_contact")),
                fields=("sac",),
                name="audit_access_single_certifying_auditor",
            ),
        ),
    ]
