# Generated by Django 4.0.3 on 2022-04-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleAuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('state', 'State'), ('local', 'Local Government'), ('tribal', 'Indian Tribe or Tribal Organization'), ('non-profit', 'Non-profit'), ('unknown', 'Unknown'), ('none', 'None of these (for example, for-profit')], max_length=12)),
                ('met_spending_threshold', models.BooleanField()),
                ('is_usa_based', models.BooleanField(verbose_name='Is USA Based')),
                ('uei', models.CharField(help_text='Unique Entity Identifier', max_length=12, verbose_name='UEI')),
                ('auditee_fiscal_period_start', models.DateField()),
                ('auditee_fiscal_period_end', models.DateField()),
                ('audit_type', models.CharField(choices=[('single-audit', 'Single Audit'), ('program-specific', 'Program-Specific Audit')], max_length=20)),
                ('audit_period_covered', models.CharField(choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('other', 'Other')], max_length=20)),
                ('ein', models.CharField(help_text='Auditee Employer Idenfication Number', max_length=12, verbose_name='EIN')),
                ('ein_not_an_ssn_attestation', models.BooleanField()),
                ('multiple_eins_covered', models.BooleanField()),
                ('multiple_ueis_covered', models.BooleanField()),
                ('auditee_name', models.CharField(max_length=100)),
                ('auditee_address_line_1', models.CharField(max_length=100)),
                ('auditee_address_line_2', models.CharField(max_length=100)),
                ('auditee_city', models.CharField(max_length=100)),
                ('auditee_zip', models.CharField(max_length=100)),
                ('auditee_state', models.CharField(max_length=2)),
                ('auditee_contact_title', models.CharField(max_length=100)),
                ('auditee_contact_name', models.CharField(max_length=100)),
                ('auditee_email', models.EmailField(max_length=100)),
                ('auditee_phone', models.CharField(max_length=100)),
                ('auditor_name', models.CharField(max_length=100)),
                ('auditor_ein', models.CharField(max_length=12)),
                ('auditor_ein_not_an_ssn_attestation', models.BooleanField()),
                ('auditor_address_line_1', models.CharField(max_length=100)),
                ('auditor_address_line_2', models.CharField(max_length=100)),
                ('auditor_city', models.CharField(max_length=100)),
                ('auditor_zip', models.CharField(max_length=100)),
                ('auditor_state', models.CharField(max_length=100)),
                ('auditor_contact_title', models.CharField(max_length=100)),
                ('auditor_contact_name', models.CharField(max_length=100)),
                ('auditor_email', models.EmailField(max_length=100)),
                ('auditor_phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'SF-SAC',
                'verbose_name_plural': 'SF-SACs',
            },
        ),
    ]
