# Generated by Django 4.0.4 on 2022-04-18 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleAuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_provided_organization_type', models.CharField(choices=[('state', 'State'), ('local', 'Local Government'), ('tribal', 'Indian Tribe or Tribal Organization'), ('non-profit', 'Non-profit'), ('unknown', 'Unknown'), ('none', 'None of these (for example, for-profit')], max_length=12)),
                ('met_spending_threshold', models.BooleanField()),
                ('is_usa_based', models.BooleanField(verbose_name='Is USA Based')),
                ('uei', models.CharField(help_text='Unique Entity Identifier', max_length=12, verbose_name='UEI')),
                ('auditee_fiscal_period_start', models.DateField()),
                ('auditee_fiscal_period_end', models.DateField()),
                ('audit_type', models.CharField(choices=[('single-audit', 'Single Audit'), ('program-specific', 'Program-Specific Audit')], max_length=20, null=True)),
                ('audit_period_covered', models.CharField(choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('other', 'Other')], max_length=20, null=True)),
                ('ein', models.CharField(help_text='Auditee Employer Identification Number', max_length=12, null=True, verbose_name='EIN')),
                ('ein_not_an_ssn_attestation', models.BooleanField(null=True, verbose_name='Attestation: EIN Not an SSN')),
                ('multiple_eins_covered', models.BooleanField(null=True, verbose_name='Multiple EINs covered')),
                ('multiple_ueis_covered', models.BooleanField(null=True, verbose_name='Multiple UEIs covered')),
                ('auditee_name', models.CharField(max_length=100, null=True)),
                ('auditee_address_line_1', models.CharField(max_length=100, null=True)),
                ('auditee_address_line_2', models.CharField(max_length=100, null=True)),
                ('auditee_city', models.CharField(max_length=100, null=True)),
                ('auditee_zip', models.CharField(max_length=100, null=True)),
                ('auditee_state', models.CharField(max_length=2, null=True)),
                ('auditee_contact_title', models.CharField(max_length=100, null=True)),
                ('auditee_contact_name', models.CharField(max_length=100, null=True)),
                ('auditee_email', models.EmailField(max_length=100, null=True)),
                ('auditee_phone', models.CharField(max_length=100, null=True)),
                ('auditor_name', models.CharField(max_length=100, null=True)),
                ('auditor_ein', models.CharField(max_length=12, null=True, verbose_name='Auditor EIN')),
                ('auditor_ein_not_an_ssn_attestation', models.BooleanField(null=True, verbose_name='Attestation: Auditor EIN Not an SSN')),
                ('auditor_address_line_1', models.CharField(max_length=100, null=True)),
                ('auditor_address_line_2', models.CharField(max_length=100, null=True)),
                ('auditor_city', models.CharField(max_length=100, null=True)),
                ('auditor_zip', models.CharField(max_length=100, null=True)),
                ('auditor_state', models.CharField(max_length=100, null=True)),
                ('auditor_contact_title', models.CharField(max_length=100, null=True)),
                ('auditor_contact_name', models.CharField(max_length=100, null=True)),
                ('auditor_email', models.EmailField(max_length=100, null=True)),
                ('auditor_phone', models.CharField(max_length=100, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SF-SAC',
                'verbose_name_plural': 'SF-SACs',
            },
        ),
    ]
