# Generated by Django 4.2.5 on 2023-09-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="report_id",
            field=models.CharField(unique=True),
        ),
    ]
