# Generated by Django 4.0.4 on 2022-04-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial_sac_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleauditchecklist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleauditchecklist',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='audit_period_covered',
            field=models.CharField(choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='audit_type',
            field=models.CharField(choices=[('single-audit', 'Single Audit'), ('program-specific', 'Program-Specific Audit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_contact_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditee_zip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_contact_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_ein',
            field=models.CharField(max_length=12, null=True, verbose_name='Auditor EIN'),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_ein_not_an_ssn_attestation',
            field=models.BooleanField(null=True, verbose_name='Attestation: Auditor EIN Not an SSN'),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='auditor_zip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='ein',
            field=models.CharField(help_text='Auditee Employer Identification Number', max_length=12, null=True, verbose_name='EIN'),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='ein_not_an_ssn_attestation',
            field=models.BooleanField(null=True, verbose_name='Attestation: EIN Not an SSN'),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='multiple_eins_covered',
            field=models.BooleanField(null=True, verbose_name='Multiple EINs covered'),
        ),
        migrations.AlterField(
            model_name='singleauditchecklist',
            name='multiple_ueis_covered',
            field=models.BooleanField(null=True, verbose_name='Multiple UEIs covered'),
        ),
    ]
