# Generated by Django 4.0.4 on 2022-05-20 22:33

import audit.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "audit",
            "0002_alter_singleauditchecklist_user_provided_organization_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="singleauditchecklist",
            old_name="auditor_name",
            new_name="auditor_firm_name",
        ),
        migrations.RemoveField(
            model_name="singleauditchecklist",
            name="auditee_address_line_2",
        ),
        migrations.RemoveField(
            model_name="singleauditchecklist",
            name="auditor_address_line_2",
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="auditor_country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name="singleauditchecklist",
            old_name="uei",
            new_name="auditee_uei",
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="auditee_uei",
            field=models.CharField(
                help_text="Auditee Unique Entity Identifier",
                max_length=12,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    audit.validators.validate_uei_alphanumeric,
                    audit.validators.validate_uei_valid_chars,
                    audit.validators.validate_uei_leading_char,
                    audit.validators.validate_uei_nine_digit_sequences,
                ],
                verbose_name="Auditee UEI",
            ),
        ),
    ]
