# Generated by Django 4.2.5 on 2023-10-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_alter_singleauditchecklist_data_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="cognizant_agency",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="oversight_agency",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
