# Generated by Django 4.0.4 on 2022-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_singleauditchecklist_submission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="report_id",
            field=models.CharField(default="foo", max_length=17, unique=True),
        ),
    ]
