# Generated by Django 4.2.6 on 2023-11-17 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0005_alter_submissionevent_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            (
                                "certifying_auditee_contact",
                                "Auditee Certifying Official",
                            ),
                            (
                                "certifying_auditor_contact",
                                "Auditor Certifying Official",
                            ),
                            ("editor", "Audit Editor"),
                        ],
                        help_text="Access type granted to this user",
                        max_length=50,
                    ),
                ),
                ("fullname", models.CharField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("removed_at", models.DateTimeField(auto_now_add=True)),
                ("removed_by_email", models.EmailField(max_length=254)),
                (
                    "removal_event",
                    models.CharField(choices=[("access-change", "Access change")]),
                ),
                (
                    "removed_by_user",
                    models.ForeignKey(
                        help_text="User ID used to delete this Access",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User ID associated with this email address, empty if no FAC account exists",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "deletedaccesses",
            },
        ),
    ]
