# Generated by Django 4.0.4 on 2022-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_singleauditchecklist_report_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="report_id",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
