# Generated by Django 4.2.6 on 2023-11-22 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0006_deletedaccess"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deletedaccess",
            options={"verbose_name_plural": "deleted accesses"},
        ),
    ]
