# Generated by Django 4.0.4 on 2022-08-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0007_alter_singleauditchecklist_auditee_uei"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="access",
            options={"verbose_name_plural": "accesses"},
        ),
        migrations.RenameField(
            model_name="access",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="access",
            name="sac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="audit.singleauditchecklist",
            ),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="auditee_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
