# Generated by Django 4.0.4 on 2022-07-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_access_options_remove_access_sac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='user_id',
            new_name='user',
        ),
    ]
