# Generated by Django 4.0.4 on 2022-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0008_alter_access_options_rename_user_id_access_user_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "auditor_cert")),
                fields=("sac",),
                name="audit_access_single_certifying_auditor",
            ),
        ),
    ]
