# Generated by Django 4.0.4 on 2022-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0008_alter_access_options_rename_user_id_access_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="auditee_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
