# Generated by Django 5.0.4 on 2024-07-02 02:13

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0008_alter_submissionevent_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="UeiValidationWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uei", models.TextField(unique=True, verbose_name="UEI")),
                (
                    "approver_email",
                    models.TextField(
                        verbose_name="Email address of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "approver_name",
                    models.TextField(
                        verbose_name="Name of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "requester_email",
                    models.TextField(
                        verbose_name="Email address of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "requester_name",
                    models.TextField(
                        verbose_name="Name of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        verbose_name="Brief plain-text justification for the waiver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SacValidationWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="When the waiver was created",
                    ),
                ),
                (
                    "approver_email",
                    models.TextField(
                        verbose_name="Email address of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "approver_name",
                    models.TextField(
                        verbose_name="Name of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "requester_email",
                    models.TextField(
                        verbose_name="Email address of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "requester_name",
                    models.TextField(
                        verbose_name="Name of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        verbose_name="Brief plain-text justification for the waiver"
                    ),
                ),
                (
                    "waiver_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "auditee_certifying_official",
                                    "No auditee certifying official is available",
                                ),
                                (
                                    "auditor_certifying_official",
                                    "No auditor certifying official is available",
                                ),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                        verbose_name="The waiver type",
                    ),
                ),
                (
                    "report_id",
                    models.ForeignKey(
                        db_column="report_id",
                        help_text="The report that the waiver applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                        to_field="report_id",
                    ),
                ),
            ],
        ),
    ]
