# Generated by Django 4.0.4 on 2022-09-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0010_alter_singleauditchecklist_audit_period_covered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("auditee_contact", "Auditee Contact"),
                    ("auditor_contact", "Auditor Contact"),
                    ("certifying_auditee_contact ", "Auditee Certifying Official"),
                    ("certifying_auditor_contact ", "Auditor Certifying Official"),
                    ("creator", "Audit Creator"),
                ],
                help_text="Access type granted to this user",
                max_length=50,
            ),
        ),
    ]
