# Generated by Django 5.0.4 on 2024-08-05 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0011_ueivalidationwaiver_expiration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sacvalidationwaiver",
            name="waiver_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "auditee_certifying_official",
                            "No auditee certifying official is available",
                        ),
                        (
                            "auditor_certifying_official",
                            "No auditor certifying official is available",
                        ),
                        (
                            "finding_reference_number",
                            "Report has duplicate finding reference numbers",
                        ),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
                verbose_name="The waiver type",
            ),
        ),
    ]
