# Generated by Django 5.1 on 2024-09-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0012_alter_sacvalidationwaiver_waiver_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleAuditChecklistFlow",
            fields=[
                (
                    "singleauditchecklist_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="audit.singleauditchecklist",
                    ),
                ),
            ],
            bases=("audit.singleauditchecklist",),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("ready_for_certification", "Ready for Certification"),
                    ("auditor_certified", "Auditor Certified"),
                    ("auditee_certified", "Auditee Certified"),
                    ("certified", "Certified"),
                    ("submitted", "Submitted"),
                    ("disseminated", "Disseminated"),
                ],
                default="in_progress",
            ),
        ),
    ]
