# Generated by Django 4.1 on 2022-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "audit",
            "0012_remove_access_audit_$(class)s_single_certifying_auditee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="federal_awards",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
