# Generated by Django 4.1.4 on 2022-12-16 14:36

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0014_alter_singleauditchecklist_federal_awards"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="general_information",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_general_information_json],
            ),
        ),
    ]
