# Generated by Django 5.1.2 on 2024-12-17 16:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0014_alter_sacvalidationwaiver_waiver_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("flagged_for_removal", "Flagged for Removal"),
                    ("ready_for_certification", "Ready for Certification"),
                    ("auditor_certified", "Auditor Certified"),
                    ("auditee_certified", "Auditee Certified"),
                    ("certified", "Certified"),
                    ("submitted", "Submitted"),
                    ("disseminated", "Disseminated"),
                ],
                default="in_progress",
            ),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="transition_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("in_progress", "In Progress"),
                        ("flagged_for_removal", "Flagged for Removal"),
                        ("ready_for_certification", "Ready for Certification"),
                        ("auditor_certified", "Auditor Certified"),
                        ("auditee_certified", "Auditee Certified"),
                        ("certified", "Certified"),
                        ("submitted", "Submitted"),
                        ("disseminated", "Disseminated"),
                    ],
                    max_length=40,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="submissionevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("access-granted", "Access granted"),
                    ("additional-eins-updated", "Additional EINs updated"),
                    ("additional-eins-deleted", "Additional EINs deleted"),
                    ("additional-ueis-updated", "Additional UEIs updated"),
                    ("additional-ueis-deleted", "Additional UEIs deleted"),
                    ("audit-information-updated", "Audit information updated"),
                    ("audit-report-pdf-updated", "Audit report PDF updated"),
                    (
                        "auditee-certification-completed",
                        "Auditee certification completed",
                    ),
                    (
                        "auditor-certification-completed",
                        "Auditor certification completed",
                    ),
                    (
                        "corrective-action-plan-updated",
                        "Corrective action plan updated",
                    ),
                    (
                        "corrective-action-plan-deleted",
                        "Corrective action plan deleted",
                    ),
                    ("created", "Created"),
                    ("federal-awards-updated", "Federal awards updated"),
                    (
                        "federal-awards-audit-findings-updated",
                        "Federal awards audit findings updated",
                    ),
                    (
                        "federal-awards-audit-findings-deleted",
                        "Federal awards audit findings deleted",
                    ),
                    (
                        "federal-awards-audit-findings-text-updated",
                        "Federal awards audit findings text updated",
                    ),
                    (
                        "federal-awards-audit-findings-text-deleted",
                        "Federal awards audit findings text deleted",
                    ),
                    (
                        "findings-uniform-guidance-updated",
                        "Findings uniform guidance updated",
                    ),
                    (
                        "findings-uniform-guidance-deleted",
                        "Findings uniform guidance deleted",
                    ),
                    ("general-information-updated", "General information updated"),
                    ("locked-for-certification", "Locked for certification"),
                    ("unlocked-after-certification", "Unlocked after certification"),
                    ("notes-to-sefa-updated", "Notes to SEFA updated"),
                    ("secondary-auditors-updated", "Secondary auditors updated"),
                    ("secondary-auditors-deleted", "Secondary auditors deleted"),
                    ("submitted", "Submitted to the FAC for processing"),
                    ("disseminated", "Copied to dissemination tables"),
                    ("tribal-consent-updated", "Tribal audit consent updated"),
                    (
                        "flagged-submission-for-removal",
                        "Flagged submission for removal",
                    ),
                    ("cancel-removal-flag", "Cancel removal flag"),
                ]
            ),
        ),
    ]
