# Generated by Django 5.1.2 on 2024-12-19 17:36

import audit.models.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0014_alter_sacvalidationwaiver_waiver_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResubmissionWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uei", models.TextField(null=True, verbose_name="UEI")),
                ("audit_year", models.TextField(null=True, verbose_name="Audit Year")),
                ("assigned_by", models.TextField(verbose_name="Assigned by")),
                (
                    "expiration",
                    models.DateTimeField(
                        default=audit.models.models.one_month_from_today,
                        verbose_name="Expiration",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
            ],
        ),
    ]
