# Generated by Django 5.1.2 on 2025-01-30 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0015_alter_singleauditchecklist_submission_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(choices=[])),
                ("report_id", models.CharField()),
                ("version", models.IntegerField()),
                ("audit", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        db_index=True, editable=False, max_length=35, unique=True
                    ),
                ),
                ("schema", models.JSONField()),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("single_audit", "Single Audit"),
                            ("program_specific", "Program-Specific Audit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("valid_start", models.DateTimeField()),
                ("valid_end", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("flagged_for_removal", "Flagged for Removal"),
                            ("ready_for_certification", "Ready for Certification"),
                            ("auditor_certified", "Auditor Certified"),
                            ("auditee_certified", "Auditee Certified"),
                            ("certified", "Certified"),
                            ("submitted", "Submitted"),
                            ("disseminated", "Disseminated"),
                        ],
                        default="in_progress",
                    ),
                ),
                ("report_id", models.CharField(unique=True)),
                ("version", models.IntegerField()),
                (
                    "audit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single_audit", "Single Audit"),
                            ("program_specific", "Program-Specific Audit"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("data_source", models.CharField(default="GSAFAC")),
                ("audit", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="audit.schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "SF-SAC",
                "verbose_name_plural": "SF-SACs",
            },
        ),
    ]
