# Generated by Django 5.1.2 on 2025-02-25 16:51

import audit.models.utils
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0015_alter_singleauditchecklist_submission_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # This custom function is needed for the generated columns.
        migrations.RunSQL(
            """
                    CREATE OR REPLACE FUNCTION json_array_to_text_array (data jsonb)
                        RETURNS text[]
                        AS $CODE$
                    BEGIN
                        RETURN ARRAY (
                            SELECT
                                jsonb_array_elements(data));
                    END
                    $CODE$
                    LANGUAGE plpgsql
                    IMMUTABLE;
            """
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("flagged_for_removal", "Flagged for Removal"),
                            ("ready_for_certification", "Ready for Certification"),
                            ("auditor_certified", "Auditor Certified"),
                            ("auditee_certified", "Auditee Certified"),
                            ("certified", "Certified"),
                            ("submitted", "Submitted"),
                            ("disseminated", "Disseminated"),
                        ],
                        default="in_progress",
                    ),
                ),
                ("report_id", models.CharField(unique=True)),
                ("version", models.IntegerField()),
                (
                    "audit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single_audit", "Single Audit"),
                            ("program_specific", "Program-Specific Audit"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("data_source", models.CharField(default="GSAFAC")),
                ("audit", models.JSONField()),
                (
                    "findings_summary",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.fields.json.KeyTextTransform(
                                "findings_summary",
                                django.db.models.fields.json.KeyTextTransform(
                                    "search_indexes", "audit"
                                ),
                            ),
                            output_field=models.IntegerField(),
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "audit_year",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.fields.json.KeyTextTransform(
                                "audit_year", "audit"
                            ),
                            output_field=models.IntegerField(),
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "auditee_state",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.fields.json.KeyTextTransform(
                            "auditee_state",
                            django.db.models.fields.json.KeyTextTransform(
                                "general_information", "audit"
                            ),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                (
                    "fac_accepted_date",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.fields.json.KeyTextTransform(
                            "fac_accepted_date", "audit"
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                (
                    "fy_end_month",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.fields.json.KeyTextTransform(
                                "fy_end_month", "audit"
                            ),
                            output_field=models.IntegerField(),
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "organization_type",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.fields.json.KeyTextTransform(
                            "user_provided_organization_type",
                            django.db.models.fields.json.KeyTextTransform(
                                "general_information", "audit"
                            ),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                (
                    "is_public",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.fields.json.KeyTextTransform(
                                "is_public", "audit"
                            ),
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "cognizant_agency",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.fields.json.KeyTextTransform(
                            "cognizant_agency", "audit"
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                (
                    "oversight_agency",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.fields.json.KeyTextTransform(
                            "oversight_agency", "audit"
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                (
                    "has_direct_funding",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.fields.json.KeyTextTransform(
                                "has_direct_funding",
                                django.db.models.fields.json.KeyTextTransform(
                                    "search_indexes", "audit"
                                ),
                            ),
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "has_indirect_funding",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.fields.json.KeyTextTransform(
                                "has_indirect_funding",
                                django.db.models.fields.json.KeyTextTransform(
                                    "search_indexes", "audit"
                                ),
                            ),
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "is_major_program",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.fields.json.KeyTextTransform(
                                "is_major_program",
                                django.db.models.fields.json.KeyTextTransform(
                                    "search_indexes", "audit"
                                ),
                            ),
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "program_names",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__search_indexes__program_names"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "additional_ueis",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__additional_ueis"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "additional_eins",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__additional_eins"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "auditee_uei",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.fields.json.KeyTextTransform(
                            "auditee_uei",
                            django.db.models.fields.json.KeyTextTransform(
                                "general_information", "audit"
                            ),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                (
                    "auditee_ein",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.fields.json.KeyTextTransform(
                            "auditee_ein",
                            django.db.models.fields.json.KeyTextTransform(
                                "general_information", "audit"
                            ),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                (
                    "passthrough_names",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__search_indexes__passthrough_names"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "search_names",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__search_indexes__search_names"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "agency_extensions",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__search_indexes__agency_extensions"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "agency_prefixes",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__search_indexes__agency_prefixes"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "compliance_requirements",
                    models.GeneratedField(
                        db_persist=True,
                        expression=audit.models.utils.JsonArrayToTextArray(
                            "audit__search_indexes__compliance_requirements"
                        ),
                        output_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(), size=None
                        ),
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SF-SAC",
                "verbose_name_plural": "SF-SACs",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("flagged_for_removal", "Flagged for Removal"),
                            ("ready_for_certification", "Ready for Certification"),
                            ("auditor_certified", "Auditor Certified"),
                            ("auditee_certified", "Auditee Certified"),
                            ("certified", "Certified"),
                            ("submitted", "Submitted"),
                            ("disseminated", "Disseminated"),
                        ]
                    ),
                ),
                ("report_id", models.CharField()),
                ("version", models.IntegerField()),
                ("audit", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
