# Generated by Django 5.1.2 on 2025-02-13 01:06

import audit.models.audit
import django.contrib.postgres.fields
import django.db.models.fields.json
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0016_history_schema_audit"),
    ]

    operations = [
        migrations.RunSQL("""
                CREATE OR REPLACE FUNCTION json_array_to_text_array (data jsonb)
                    RETURNS text[]
                    AS $CODE$
                BEGIN
                    RETURN ARRAY (
                        SELECT
                            jsonb_array_elements(data));
                END
                $CODE$
                LANGUAGE plpgsql
                IMMUTABLE;
        """),
        migrations.AddField(
            model_name="audit",
            name="additional_eins",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__additional_eins"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="additional_ueis",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__additional_ueis"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="agency_extensions",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__search_indexes__agency_extensions"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="agency_prefixes",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__search_indexes__agency_prefixes"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_year",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform(
                        "audit_year", "audit"
                    ),
                    output_field=models.IntegerField(),
                ),
                output_field=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="auditee_ein",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "auditee_ein",
                    django.db.models.fields.json.KeyTextTransform(
                        "general_information", "audit"
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="auditee_state",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "auditee_state",
                    django.db.models.fields.json.KeyTextTransform(
                        "general_information", "audit"
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="auditee_uei",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "auditee_uei",
                    django.db.models.fields.json.KeyTextTransform(
                        "general_information", "audit"
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="cognizant_agency",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "cognizant_agency", "audit"
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="compliance_requirements",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__search_indexes__compliance_requirements"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="fac_accepted_date",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "fac_accepted_date", "audit"
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="findings_summary",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform(
                        "findings_summary",
                        django.db.models.fields.json.KeyTextTransform(
                            "search_indexes", "audit"
                        ),
                    ),
                    output_field=models.IntegerField(),
                ),
                output_field=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="fy_end_month",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform(
                        "fy_end_month", "audit"
                    ),
                    output_field=models.IntegerField(),
                ),
                output_field=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="has_direct_funding",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform(
                        "has_direct_funding",
                        django.db.models.fields.json.KeyTextTransform(
                            "search_indexes", "audit"
                        ),
                    ),
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="has_indirect_funding",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform(
                        "has_indirect_funding",
                        django.db.models.fields.json.KeyTextTransform(
                            "search_indexes", "audit"
                        ),
                    ),
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="is_major_program",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform(
                        "is_major_program",
                        django.db.models.fields.json.KeyTextTransform(
                            "search_indexes", "audit"
                        ),
                    ),
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="is_public",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform("is_public", "audit"),
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="organization_type",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "user_provided_organization_type",
                    django.db.models.fields.json.KeyTextTransform(
                        "general_information", "audit"
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="oversight_agency",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "oversight_agency", "audit"
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="passthrough_names",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__search_indexes__passthrough_names"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="program_names",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__search_indexes__program_names"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="search_names",
            field=models.GeneratedField(
                db_persist=True,
                expression=audit.models.audit.JsonArrayToTextArray(
                    "audit__search_indexes__search_names"
                ),
                output_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
            ),
        ),
    ]
