# Generated by Django 5.1.2 on 2025-02-26 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0016_audit_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="audit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
        migrations.AddField(
            model_name="deletedaccess",
            name="audit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
        migrations.AddField(
            model_name="submissionevent",
            name="audit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "certifying_auditee_contact")),
                fields=("audit",),
                name="audit_access_audit_single_certifying_auditee",
            ),
        ),
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "certifying_auditor_contact")),
                fields=("audit",),
                name="audit_access_audit_single_certifying_auditor",
            ),
        ),
    ]
