# Generated by Django 5.1.2 on 2025-03-13 14:25

import django.db.models.deletion
import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0017_access_audit_deletedaccess_audit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditFlow",
            fields=[
                (
                    "audit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="audit.audit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("audit.audit",),
        ),
        migrations.RenameField(
            model_name="history",
            old_name="audit",
            new_name="event_data",
        ),
        migrations.AddField(
            model_name="audit",
            name="auditee_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "auditee_name",
                    django.db.models.fields.json.KeyTextTransform(
                        "general_information", "audit"
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="migrated_to_audit",
            field=models.BooleanField(
                default=False,
                help_text="Determines whether SAC data has already been migrated to a corresponding Audit object",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="event",
            field=models.CharField(
                choices=[
                    ("access-granted", "Access granted"),
                    ("additional-eins-updated", "Additional EINs updated"),
                    ("additional-eins-deleted", "Additional EINs deleted"),
                    ("additional-ueis-updated", "Additional UEIs updated"),
                    ("additional-ueis-deleted", "Additional UEIs deleted"),
                    ("audit-information-updated", "Audit information updated"),
                    ("audit-report-pdf-updated", "Audit report PDF updated"),
                    (
                        "auditee-certification-completed",
                        "Auditee certification completed",
                    ),
                    (
                        "auditor-certification-completed",
                        "Auditor certification completed",
                    ),
                    (
                        "corrective-action-plan-updated",
                        "Corrective action plan updated",
                    ),
                    (
                        "corrective-action-plan-deleted",
                        "Corrective action plan deleted",
                    ),
                    ("created", "Created"),
                    ("federal-awards-updated", "Federal awards updated"),
                    (
                        "federal-awards-audit-findings-updated",
                        "Federal awards audit findings updated",
                    ),
                    (
                        "federal-awards-audit-findings-deleted",
                        "Federal awards audit findings deleted",
                    ),
                    (
                        "federal-awards-audit-findings-text-updated",
                        "Federal awards audit findings text updated",
                    ),
                    (
                        "federal-awards-audit-findings-text-deleted",
                        "Federal awards audit findings text deleted",
                    ),
                    (
                        "findings-uniform-guidance-updated",
                        "Findings uniform guidance updated",
                    ),
                    (
                        "findings-uniform-guidance-deleted",
                        "Findings uniform guidance deleted",
                    ),
                    ("general-information-updated", "General information updated"),
                    ("locked-for-certification", "Locked for certification"),
                    ("unlocked-after-certification", "Unlocked after certification"),
                    ("notes-to-sefa-updated", "Notes to SEFA updated"),
                    ("secondary-auditors-updated", "Secondary auditors updated"),
                    ("secondary-auditors-deleted", "Secondary auditors deleted"),
                    ("submitted", "Submitted to the FAC for processing"),
                    ("disseminated", "Copied to dissemination tables"),
                    ("tribal-consent-updated", "Tribal audit consent updated"),
                    (
                        "flagged-submission-for-removal",
                        "Flagged submission for removal",
                    ),
                    ("cancel-removal-flag", "Cancel removal flag"),
                ]
            ),
        ),
        migrations.RemoveField(model_name="audit", name="auditee_ein"),
        migrations.AddField(
            model_name="audit",
            name="auditee_ein",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "ein",
                    django.db.models.fields.json.KeyTextTransform(
                        "general_information", "audit"
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AlterModelOptions(
            name="history",
            options={
                "verbose_name": "Audit History",
                "verbose_name_plural": "Audit History",
            },
        ),
        migrations.AlterModelOptions(
            name="audit",
            options={"verbose_name": "Audit", "verbose_name_plural": "Audits"},
        ),
        migrations.AddField(
            model_name="excelfile",
            name="audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="audit.audit",
            ),
        ),
        migrations.AddField(
            model_name="singleauditreportfile",
            name="audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="audit.audit",
            ),
        ),
        migrations.CreateModel(
            name="AuditValidationWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="When the waiver was created",
                    ),
                ),
                (
                    "approver_email",
                    models.TextField(
                        verbose_name="Email address of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "approver_name",
                    models.TextField(
                        verbose_name="Name of FAC staff member approving the waiver"
                    ),
                ),
                (
                    "requester_email",
                    models.TextField(
                        verbose_name="Email address of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "requester_name",
                    models.TextField(
                        verbose_name="Name of NSAC/KSAML requesting the waiver"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        verbose_name="Brief plain-text justification for the waiver"
                    ),
                ),
                (
                    "waiver_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "auditee_certifying_official",
                                    "No auditee certifying official is available",
                                ),
                                (
                                    "auditor_certifying_official",
                                    "No auditor certifying official is available",
                                ),
                                (
                                    "finding_reference_number",
                                    "Report has duplicate finding reference numbers",
                                ),
                                (
                                    "prior_references",
                                    "Report has invalid prior reference numbers",
                                ),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                        verbose_name="The waiver type",
                    ),
                ),
                (
                    "report_id",
                    models.ForeignKey(
                        db_column="report_id",
                        help_text="The report that the waiver applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.audit",
                        to_field="report_id",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="audit",
            name="audit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single-audit", "Single Audit"),
                    ("program-specific", "Program-Specific Audit"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
