# Generated by Django 5.1.2 on 2025-02-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0017_audit_additional_eins_audit_additional_ueis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="audit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
    ]
