# Generated by Django 4.1.4 on 2023-02-22 13:24

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0017_excelfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="file",
            field=models.FileField(
                upload_to="excel", validators=[audit.validators.validate_excel_file]
            ),
        ),
    ]
