# Generated by Django 5.1.2 on 2025-03-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0017_access_audit_deletedaccess_audit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditFlow",
            fields=[
                (
                    "audit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="audit.audit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("audit.audit",),
        ),
    ]
