# Generated by Django 5.1.2 on 2025-03-07 19:56

import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0018_auditflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="auditee_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform(
                    "auditee_name",
                    django.db.models.fields.json.KeyTextTransform(
                        "general_information", "audit"
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
    ]
