# Generated by Django 4.1.7 on 2023-04-12 20:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0018_alter_excelfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="submission_status",
            field=django_fsm.FSMField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("ready_for_certification", "Ready for Certification"),
                    ("auditor_certified", "Auditor Certified"),
                    ("auditee_certified", "Auditee Certified"),
                    ("certified", "Certified"),
                    ("submitted", "Submitted"),
                ],
                default="in_progress",
                max_length=50,
            ),
        ),
    ]
