# Generated by Django 5.1.2 on 2025-03-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0018_auditflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="migrated_to_audit",
            field=models.BooleanField(
                default=False,
                help_text="Determines whether SAC data has already been migrated to a corresponding Audit object",
            ),
        ),
    ]
