# Generated by Django 4.1.7 on 2023-04-20 21:27

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0018_alter_excelfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="corrective_action_plan",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_corrective_action_plan_json],
            ),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="findings_uniform_guidance",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_findings_uniform_guidance_json],
            ),
        ),
    ]
