# Generated by Django 5.1.2 on 2025-03-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0019_audit_auditee_name"),
        ("audit", "0019_singleauditchecklist_migrated_to_audit"),
    ]

    operations = []
