# Generated by Django 5.1.2 on 2025-04-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0019_update_json_array_to_text_array"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sacvalidationwaiver",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="singleauditchecklist",
            name="submitted_by",
        ),
        migrations.RemoveField(
            model_name="deletedaccess",
            name="sac",
        ),
        migrations.RemoveField(
            model_name="submissionevent",
            name="sac",
        ),
        migrations.RemoveField(
            model_name="excelfile",
            name="sac",
        ),
        migrations.RemoveField(
            model_name="singleauditchecklistflow",
            name="singleauditchecklist_ptr",
        ),
        migrations.RemoveField(
            model_name="singleauditreportfile",
            name="sac",
        ),
        migrations.RemoveField(
            model_name="access",
            name="sac",
        ),
        migrations.RemoveField(
            model_name="submissionevent",
            name="audit",
        ),
        migrations.RemoveField(
            model_name="submissionevent",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="access",
            name="audit_$(class)s_single_certifying_auditee",
        ),
        migrations.RemoveConstraint(
            model_name="access",
            name="audit_access_single_certifying_auditor",
        ),
        migrations.AlterField(
            model_name="access",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
        migrations.AlterField(
            model_name="deletedaccess",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
        migrations.AlterField(
            model_name="excelfile",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
        migrations.AlterField(
            model_name="singleauditreportfile",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
            ),
        ),
        migrations.DeleteModel(
            name="SacValidationWaiver",
        ),
        migrations.DeleteModel(
            name="SingleAuditChecklistFlow",
        ),
        migrations.DeleteModel(
            name="SingleAuditChecklist",
        ),
        migrations.DeleteModel(
            name="SubmissionEvent",
        ),
    ]
