# Generated by Django 5.2.3 on 2025-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0020_alter_history_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="resubmission_meta",
            field=models.JSONField(
                blank=True, help_text="Resubmission JSON structure", null=True
            ),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="resubmission_status",
            field=models.CharField(
                blank=True,
                help_text="Current status of the resubmission (e.g. ORIGINAL_SUBMISSION, MOST_RECENT, DEPRECATED_VIA_RESUBMISSION).",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="resubmission_version",
            field=models.BigIntegerField(
                default=0,
                help_text="Version counter of how many times this SAC was resubmitted.",
            ),
        ),
    ]
