# Generated by Django 5.2.3 on 2025-07-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0021_singleauditchecklist_resubmission_meta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singleauditchecklist",
            name="resubmission_status",
        ),
        migrations.RemoveField(
            model_name="singleauditchecklist",
            name="resubmission_version",
        ),
    ]
