# Generated by Django 5.2.3 on 2025-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0022_remove_singleauditchecklist_resubmission_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="resubmission_status",
            field=models.CharField(
                choices=[
                    ("original_submission", "Original Submission"),
                    ("most_recent", "Most Recent"),
                    ("deprecated_via_resubmission", "Deprecated via Resubmission"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
