# Generated by Django 4.1.7 on 2023-05-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0022_remove_access_audit_single_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("certifying_auditee_contact", "Auditee Certifying Official"),
                    ("certifying_auditor_contact", "Auditor Certifying Official"),
                    ("editor", "Audit Editor"),
                ],
                help_text="Access type granted to this user",
                max_length=50,
            ),
        ),
    ]
