# Generated by Django 4.2.1 on 2023-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0023_alter_access_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelfile",
            name="form_section",
            field=models.CharField(default="not-actually-default", max_length=255),
        ),
    ]
