# Generated by Django 5.2.3 on 2025-07-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0023_singleauditchecklist_resubmission_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singleauditchecklist",
            name="resubmission_status",
        ),
    ]
