# Generated by Django 4.2.1 on 2023-06-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0024_excelfile_form_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="form_section",
            field=models.CharField(max_length=255),
        ),
    ]
