# Generated by Django 5.2.3 on 2025-07-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0023_alter_submissionevent_event"),
        ("audit", "0024_remove_singleauditchecklist_resubmission_status"),
    ]

    operations = []
