# Generated by Django 4.2.1 on 2023-06-22 16:04

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0025_alter_excelfile_form_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="additional_ueis",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_additional_ueis_json],
            ),
        ),
    ]
