# Generated by Django 5.2.3 on 2025-08-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0026_alter_audit_submission_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("access-granted", "Access granted"),
                    ("additional-eins-updated", "Additional EINs updated"),
                    ("additional-eins-deleted", "Additional EINs deleted"),
                    ("additional-ueis-updated", "Additional UEIs updated"),
                    ("additional-ueis-deleted", "Additional UEIs deleted"),
                    ("audit-information-updated", "Audit information updated"),
                    ("audit-report-pdf-updated", "Audit report PDF updated"),
                    (
                        "auditee-certification-completed",
                        "Auditee certification completed",
                    ),
                    (
                        "auditor-certification-completed",
                        "Auditor certification completed",
                    ),
                    (
                        "corrective-action-plan-updated",
                        "Corrective action plan updated",
                    ),
                    (
                        "corrective-action-plan-deleted",
                        "Corrective action plan deleted",
                    ),
                    ("created", "Created"),
                    ("federal-awards-updated", "Federal awards updated"),
                    (
                        "federal-awards-audit-findings-updated",
                        "Federal awards audit findings updated",
                    ),
                    (
                        "federal-awards-audit-findings-deleted",
                        "Federal awards audit findings deleted",
                    ),
                    (
                        "federal-awards-audit-findings-text-updated",
                        "Federal awards audit findings text updated",
                    ),
                    (
                        "federal-awards-audit-findings-text-deleted",
                        "Federal awards audit findings text deleted",
                    ),
                    (
                        "findings-uniform-guidance-updated",
                        "Findings uniform guidance updated",
                    ),
                    (
                        "findings-uniform-guidance-deleted",
                        "Findings uniform guidance deleted",
                    ),
                    ("general-information-updated", "General information updated"),
                    ("locked-for-certification", "Locked for certification"),
                    ("unlocked-after-certification", "Unlocked after certification"),
                    ("notes-to-sefa-updated", "Notes to SEFA updated"),
                    ("secondary-auditors-updated", "Secondary auditors updated"),
                    ("secondary-auditors-deleted", "Secondary auditors deleted"),
                    ("submitted", "Submitted to the FAC for processing"),
                    ("disseminated", "Copied to dissemination tables"),
                    ("tribal-consent-updated", "Tribal audit consent updated"),
                    (
                        "flagged-submission-for-removal",
                        "Flagged submission for removal",
                    ),
                    ("cancel-removal-flag", "Cancel removal flag"),
                    (
                        "fac-administrative-uei-replacement",
                        "FAC administrative replacement of UEI",
                    ),
                    (
                        "fac-administrative-ein-replacement",
                        "FAC administrative replacement of EIN",
                    ),
                    (
                        "resubmission-initiated",
                        "A resubmission was started on this report.",
                    ),
                    (
                        "resubmission-started",
                        "This report was started as a resubmission of another report.",
                    ),
                    (
                        "fac-administrative-suppression-change",
                        "FAC administrative change of Tribal suppression status.",
                    ),
                ]
            ),
        ),
    ]
