# Generated by Django 4.2.2 on 2023-07-07 20:17

import audit.models
import audit.validators
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0026_singleauditchecklist_transition_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="additional_ueis",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_additional_ueis_json],
            ),
        ),
        migrations.AlterField(
            model_name="excelfile",
            name="file",
            field=models.FileField(
                upload_to=audit.models.excel_file_path,
                validators=[audit.validators.validate_excel_file],
            ),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="transition_date",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="transition_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("in_progress", "In Progress"),
                        ("ready_for_certification", "Ready for Certification"),
                        ("auditor_certified", "Auditor Certified"),
                        ("auditee_certified", "Auditee Certified"),
                        ("certified", "Certified"),
                        ("submitted", "Submitted"),
                    ],
                    max_length=40,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="SingleAuditReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=audit.models.single_audit_report_path,
                        validators=[audit.validators.validate_single_audit_report_file],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
