# Generated by Django 5.2.3 on 2025-08-12 16:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0027_alter_submissionevent_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("flagged_for_removal", "Flagged for Removal"),
                    ("ready_for_certification", "Ready for Certification"),
                    ("auditor_certified", "Auditor Certified"),
                    ("auditee_certified", "Auditee Certified"),
                    ("certified", "Certified"),
                    ("submitted", "Submitted"),
                    ("disseminated", "Disseminated"),
                    ("resubmitted", "Resubmitted"),
                ],
                default="in_progress",
            ),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="transition_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("in_progress", "In Progress"),
                        ("flagged_for_removal", "Flagged for Removal"),
                        ("ready_for_certification", "Ready for Certification"),
                        ("auditor_certified", "Auditor Certified"),
                        ("auditee_certified", "Auditee Certified"),
                        ("certified", "Certified"),
                        ("submitted", "Submitted"),
                        ("disseminated", "Disseminated"),
                        ("resubmitted", "Resubmitted"),
                    ],
                    max_length=40,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
