# Generated by Django 4.2.1 on 2023-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0027_singleauditchecklist_additional_ueis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="additional_auditors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
