# Generated by Django 4.2.2 on 2023-07-19 19:52

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0028_singleauditchecklist_notes_to_sefa"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="audit_information",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_audit_information_json],
            ),
        ),
    ]
