# Generated by Django 5.2.3 on 2025-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0029_alter_submissionevent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="hash",
            field=models.CharField(
                blank=True, help_text="A hash of the row", null=True
            ),
        ),
        migrations.AddField(
            model_name="singleauditreportfile",
            name="hash",
            field=models.CharField(
                blank=True, help_text="A hash of the report", null=True
            ),
        ),
    ]
