# Generated by Django 4.2.3 on 2023-08-02 17:44

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0029_singleauditchecklist_secondary_auditors"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="auditee_certification",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_auditee_certification_json],
            ),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="auditor_certification",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_auditor_certification_json],
            ),
        ),
    ]
