# Generated by Django 5.2.3 on 2026-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0029_alter_submissionevent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="fake_field",
            field=models.TextField(null=True),
        ),
    ]
