# Generated by Django 5.2.3 on 2026-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0029_alter_submissionevent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditreportfile",
            name="keep_previous_report",
            field=models.BooleanField(
                default=False,
                help_text="In resubmission, whether the user opted to bring forward their SAR from the previous report or not.",
                verbose_name="Keep Previous Single Audit Report File",
            ),
        ),
    ]
