# Generated by Django 4.2.3 on 2023-07-31 17:38

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0029_singleauditchecklist_secondary_auditors"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="audit_information",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_audit_information_json],
            ),
        ),
    ]
