# Generated by Django 5.2.3 on 2025-09-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0029_alter_submissionevent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="data_hash",
            field=models.CharField(
                blank=True, help_text="A hash of the SAC data", null=True
            ),
        ),
    ]
