# Generated by Django 4.2.3 on 2023-08-07 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0030_singleauditchecklist_audit_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("certifying_auditee_contact", "Auditee Certifying Official"),
                    ("certifying_auditor_contact", "Auditor Certifying Official"),
                    ("editor", "Audit Editor"),
                ],
                help_text="Access type granted to this user",
            ),
        ),
        migrations.AlterField(
            model_name="excelfile",
            name="filename",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="excelfile",
            name="form_section",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="audit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single-audit", "Single Audit"),
                    ("program-specific", "Program-Specific Audit"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="report_id",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="transition_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("in_progress", "In Progress"),
                        ("ready_for_certification", "Ready for Certification"),
                        ("auditor_certified", "Auditor Certified"),
                        ("auditee_certified", "Auditee Certified"),
                        ("certified", "Certified"),
                        ("submitted", "Submitted"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="singleauditreportfile",
            name="filename",
            field=models.TextField(),
        ),
    ]
