# Generated by Django 4.2.3 on 2023-08-04 16:00

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0030_singleauditchecklist_audit_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditreportfile",
            name="component_page_numbers",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_component_page_numbers],
            ),
        ),
    ]
