# Generated by Django 4.2.1 on 2023-06-30 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0026_singleauditchecklist_additional_ueis"),
        ("audit", "0031_alter_singleauditchecklist_transition_date_and_more"),
    ]

    operations = []
