# Generated by Django 4.2.1 on 2023-06-28 21:16

import audit.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0031_alter_singleauditchecklist_transition_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleAuditReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="singleauditreport",
                        validators=[audit.validators.validate_single_audit_report_file],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "sac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.singleauditchecklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
