# Generated by Django 4.2.3 on 2023-08-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0031_alter_access_role_alter_excelfile_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditreportfile",
            name="filename",
            field=models.CharField(),
        ),
    ]
