# Generated by Django 4.2.3 on 2023-08-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0031_singleauditreportfile_component_page_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="data_source",
            field=models.TextField(default="GSA"),
        ),
    ]
