# Generated by Django 4.2.3 on 2023-08-10 19:49

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0032_singleauditchecklist_auditee_certification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="tribal_data_consent",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_tribal_data_consent_json],
            ),
        ),
    ]
