# Generated by Django 4.2.3 on 2023-08-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0032_singleauditchecklist_data_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="data_source",
            field=models.CharField(default="GSA"),
        ),
    ]
