# Generated by Django 4.2.1 on 2023-07-03 18:28

import audit.models
import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0032_merge_20230630_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="file",
            field=models.FileField(
                upload_to=audit.models.excel_file_path,
                validators=[audit.validators.validate_excel_file],
            ),
        ),
    ]
