# Generated by Django 4.2.1 on 2023-07-06 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0032_alter_excelfile_file"),
        ("audit", "0033_alter_excelfile_file"),
    ]

    operations = []
