# Generated by Django 4.2.3 on 2023-08-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0033_singleauditchecklist_tribal_data_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="fullname",
            field=models.CharField(default=""),
        ),
    ]
