# Generated by Django 4.2.3 on 2023-08-15 19:58

import audit.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0033_singleauditchecklist_tribal_data_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="additional_eins",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[audit.validators.validate_additional_eins_json],
            ),
        ),
    ]
