# Generated by Django 5.2.16 on 2026-08-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0033_alter_submissionevent_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singleauditreportfile",
            name="keep_previous_report",
        ),
    ]
