# Generated by Django 4.2.3 on 2023-08-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0034_singleauditchecklist_additional_eins"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="data_source",
            field=models.CharField(default="GSA"),
        ),
    ]
