# Generated by Django 5.2.16 on 2026-10-06 16:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0034_remove_singleauditreportfile_keep_previous_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sacvalidationwaiver",
            name="waiver_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "auditee_certifying_official",
                            "No auditee certifying official is available",
                        ),
                        (
                            "auditor_certifying_official",
                            "No auditor certifying official is available",
                        ),
                        (
                            "finding_reference_number",
                            "Report has duplicate finding reference numbers",
                        ),
                        (
                            "prior_references",
                            "Report has invalid prior reference numbers",
                        ),
                        (
                            "expenditure_threshold",
                            "Report is under the expenditure threshold for their audit period",
                        ),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
                verbose_name="The waiver type",
            ),
        ),
    ]
