# Generated by Django 4.2.3 on 2023-08-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0035_singleauditchecklist_data_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="CognizantBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dbkey",
                    models.IntegerField(
                        null=True,
                        verbose_name="Identifier for a submission along with audit_year in C-FAC",
                    ),
                ),
                (
                    "audit_year",
                    models.IntegerField(
                        null=True, verbose_name="Audit year from fy_start_date"
                    ),
                ),
                (
                    "ein",
                    models.CharField(
                        max_length=30,
                        null=True,
                        verbose_name="Primary Employer Identification Number",
                    ),
                ),
                (
                    "cognizant_agency",
                    models.CharField(
                        max_length=2,
                        null=True,
                        verbose_name="Two digit Federal agency prefix of the cognizant agency",
                    ),
                ),
            ],
            options={
                "unique_together": {("dbkey", "audit_year")},
            },
        ),
    ]
