# Generated by Django 4.2.3 on 2023-08-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0036_cognizantbaseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="fullname",
            field=models.CharField(blank=True),
        ),
    ]
