# Generated by Django 4.2.3 on 2023-08-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0037_access_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="cognizant_agency",
            field=models.CharField(blank=True, default="", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="oversight_agency",
            field=models.CharField(blank=True, default="", max_length=2, null=True),
        ),
    ]
