# Generated by Django 4.2.3 on 2023-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0038_submissionevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("access-granted", "Access granted"),
                    ("additional-eins-updated", "Additional EINs updated"),
                    ("additional-ueis-updated", "Additional UEIs updated"),
                    ("audit-information-updated", "Audit information updated"),
                    ("audit-report-pdf-updated", "Audit report PDF updated"),
                    (
                        "auditee-certification-completed",
                        "Auditee certification completed",
                    ),
                    (
                        "auditor-certification-completed",
                        "Auditor certification completed",
                    ),
                    (
                        "corrective-action-plan-updated",
                        "Corrective action plan updated",
                    ),
                    ("created", "Created"),
                    ("federal-awards-updated", "Federal awards updated"),
                    (
                        "federal-awards-audit-findings-updated",
                        "Federal awards audit findings updated",
                    ),
                    (
                        "federal-awards-audit-findings-text-updated",
                        "Federal awards audit findings text updated",
                    ),
                    (
                        "findings-uniform-guidance-updated",
                        "Findings uniform guidance updated",
                    ),
                    ("general-information-updated", "General information updated"),
                    ("locked-for-certification", "Locked for certification"),
                    ("notes-to-sefa-updated", "Notes to SEFA updated"),
                    ("secondary-auditors-updated", "Secondary auditors updated"),
                    ("submitted", "Submitted to the FAC for processing"),
                ]
            ),
        ),
    ]
