# Generated by Django 4.2.3 on 2023-08-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0038_singleauditchecklist_cognizant_agency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="cognizant_agency",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="singleauditchecklist",
            name="oversight_agency",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
