# Generated by Django 4.2.3 on 2023-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0038_submissionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleauditchecklist",
            name="cognizant_agency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="oversight_agency",
            field=models.TextField(null=True),
        ),
    ]
