# Generated by Django 4.2.3 on 2023-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0038_submissionevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CognizantBaseline",
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="cognizant_agency",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Agency assigned to this large submission. Computed when the submisson is finalized, but may be overridden",
            ),
        ),
        migrations.AddField(
            model_name="singleauditchecklist",
            name="oversight_agency",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Agency assigned to this not so large submission. Computed when the submisson is finalized",
            ),
        ),
    ]
