select_additional_eins = (
    "select a.report_id, a.auditee_uei, a.audit_year, "
    "ft_elem::text as additional_ein "
    "from audit_audit as a, "
    "LATERAL jsonb_array_elements(a.audit->'additional_eins') as ft_elem "
    "where a.audit_year = {audit_year}"
)

select_additional_ueis = (
    "select a.report_id, a.auditee_uei, a.audit_year, "
    "ft_elem::text as additional_uei "
    "from audit_audit as a, "
    "LATERAL jsonb_array_elements(a.audit->'additional_ueis') as ft_elem "
    "where a.audit_year = {audit_year}"
)


select_general_information = (
    "select a.report_id, a.audit->'general_information'->>'auditee_uei' as auditee_uei, "
    "a.audit->>'audit_year' as audit_year, "
    "a.audit->'auditee_certification' -> 'auditee_signature' ->> 'auditee_name' as auditee_certify_name, "
    "a.audit->'auditee_certification' -> 'auditee_signature' ->> 'auditee_title' as auditee_certify_title, "
    "a.audit->'general_information'->>'auditee_contact_name' as auditee_contact_name, "
    "a.audit->'general_information'->>'auditee_email' as auditee_email, "
    "a.audit->'general_information'->>'auditee_name' as auditee_name, "
    "a.audit->'general_information'->>'auditee_phone' as auditee_phone, "
    "a.audit->'general_information'->>'auditee_contact_title' as auditee_contact_title, "
    "a.audit->'general_information'->>'auditee_address_line_1' as auditee_address_line_1, "
    "a.audit->'general_information'->>'auditee_city' as auditee_city, "
    "a.audit->'general_information'->>'auditee_state' as auditee_state, "
    "a.audit->'general_information'->>'ein' as auditee_ein, "
    "a.audit->'general_information'->>'auditee_zip' as auditee_zip, "
    "a.audit->'auditor_certification' -> 'auditor_signature' ->> 'auditor_name' as auditor_certify_name, "
    "a.audit->'auditor_certification' -> 'auditor_signature' ->> 'auditor_title' as auditor_certify_title, "
    "a.audit->'general_information'->>'auditor_phone' as auditor_phone, "
    "a.audit->'general_information'->>'auditor_state' as auditor_state, "
    "a.audit->'general_information'->>'auditor_city' as auditor_city, "
    "a.audit->'general_information'->>'auditor_contact_title' as auditor_contact_title, "
    "a.audit->'general_information'->>'auditor_address_line_1' as auditor_address_line_1, "
    "a.audit->'general_information'->>'auditor_zip' as auditor_zip, "
    "a.audit->'general_information'->>'auditor_country' as auditor_country, "
    "a.audit->'general_information'->>'auditor_contact_name' as auditor_contact_name, "
    "a.audit->'general_information'->>'auditor_email' as auditor_email, "
    "a.audit->'general_information'->>'auditor_firm_name' as auditor_firm_name, "
    "a.audit->'general_information'->>'auditor_international_address' as auditor_foreign_address, "
    "a.audit->'general_information'->>'auditor_ein' as auditor_ein, "
    "a.audit->'cognizant_agency' as cognizant_agency, "
    "a.audit->'oversight_agency' as oversight_agency, "
    "a.created_at as date_created, "
    "a.audit->'general_information'->>'ready_for_certification_date'as ready_for_certification_date, "
    "a.audit->'general_information'->>'auditor_certified_date' as auditor_certified_date, "
    "a.audit->'general_information'->>'auditee_certified_date' as auditee_certified_date, "
    "a.audit->'general_information'->>'submitted_date' as submitted_date, "
    "a.audit->'general_information'->>'fac_accepted_date' as fac_accepted_date, "
    "a.audit->'general_information'->>'auditee_fiscal_period_end' as fy_end_date, "
    "a.audit->'general_information'->>'auditee_fiscal_period_start' as fy_start_date, "
    "a.audit->'general_information'->>'audit_type' as audit_type, "
    "a.audit->'general_information'->>'gaap_results' as gaap_results, "
    "a.audit->'general_information'->>'sp_framework_basis' as sp_framework_basis, "
    "a.audit->'general_information'->>'is_sp_framework_required' as is_sp_framework_required, "
    "a.audit->'general_information'->>'sp_framework_opinions' as sp_framework_opinions, "
    "a.audit->'general_information'->>'is_going_concern_included' as is_going_concern_included, "
    "a.audit->'general_information'->>'is_internal_control_deficiency_disclosed' as is_internal_control_deficiency_disclosed, "
    "a.audit->'general_information'->>'is_internal_control_material_weakness_disclosed' as is_internal_control_material_weakness_disclosed, "
    "a.audit->'general_information'->>'is_material_noncompliance_disclosed' as is_material_noncompliance_disclosed, "
    "a.audit->'general_information'->>'dollar_threshold' as dollar_threshold, "
    "a.audit->'general_information'->>'is_low_risk_auditee' as is_low_risk_auditee, "
    "a.audit->'general_information'->>'agencies_with_prior_findings' as agencies_with_prior_findings, "
    "a.audit->'general_information'->>'entity_type' as entity_type, "
    "a.audit->'general_information'->>'number_months' as number_months, "
    "a.audit->'general_information'->>'audit_period_covered' as audit_period_covered, "
    "a.audit->'federal_awards'->>'total_amount_expended' as total_amount_expended, "
    "a.audit->'general_information'->>'type_audit_code' as type_audit_code, "
    "a.audit->'general_information'->>'is_public' as is_public, "
    "a.data_source as data_source, "
    "a.audit->'general_information'->>'is_aicpa_audit_guide_included' as is_aicpa_audit_guide_included, "
    "a.audit->'general_information'->>'is_additional_ueis' as is_additional_ueis "
    "from audit_audit as a"
)
