"""
Mapping for upload.
Used by public_data_loader.
Update with create_upload_mapping management command.
"""
upload_mapping = {
    "gen": {
        "AUDITEECERTIFYNAME": ["Auditee", "auditee_certify_name"],
        "AUDITEECERTIFYTITLE": ["Auditee", "auditee_certify_title"],
        "AUDITEECONTACT": ["Auditee", "auditee_contact"],
        "AUDITEEEMAIL": ["Auditee", "auditee_email"],
        "AUDITEEFAX": ["Auditee", "auditee_fax"],
        "AUDITEENAME": ["Auditee", "auditee_name"],
        "AUDITEENAMETITLE": ["Auditee", "auditee_name_title"],
        "AUDITEEPHONE": ["Auditee", "auditee_phone"],
        "AUDITEETITLE": ["Auditee", "auditee_title"],
        "STREET1": ["Auditee", "auditee_street1"],
        "STREET2": ["Auditee", "auditee_street2"],
        "CITY": ["Auditee", "auditee_city"],
        "STATE": ["Auditee", "auditee_state"],
        "EIN": ["Auditee", "ein"],
        "EINSUBCODE": ["Auditee", "ein_subcode"],
        "ZIPCODE": ["Auditee", "auditee_zip_code"],
        "CPACOUNTRY": ["Auditor", "cpa_country"],
        "CPAPHONE": ["Auditor", "cpa_phone"],
        "CPAFAX": ["Auditor", "cpa_fax"],
        "CPASTATE": ["Auditor", "cpa_state"],
        "CPACITY": ["Auditor", "cpa_city"],
        "CPATITLE": ["Auditor", "cpa_title"],
        "CPASTREET1": ["Auditor", "cpa_street1"],
        "CPASTREET2": ["Auditor", "cpa_street2"],
        "CPAZIPCODE": ["Auditor", "cpa_zip_code"],
        "CPACONTACT": ["Auditor", "cpa_contact"],
        "CPAEMAIL": ["Auditor", "cpa_email"],
        "CPAFIRMNAME": ["Auditor", "cpa_firm_name"],
        "CPAEIN": ["Auditor", "cpa_ein"],
        # this needs to go 2 places will handle manually
        # "DBKEY": ["Auditor", "dbkey"],
        "SEQNUM": ["Auditor", "seqence_number"],
        "CPAFOREIGN": ["Auditor", "cpa_foreign"],
        "AUDITOR_EIN": ["FederalAward", "cpa_ein"],
        "COGAGENCY": ["General", "cognizant_agency"],
        "COG_OVER": ["General", "cognizant_agency_over"],
        "AUDITEEDATESIGNED": ["General", "auditee_date_signed"],
        "CPADATESIGNED": ["General", "cpa_date_signed"],
        "AUDITTYPE": ["General", "audit_type"],
        "AUDITYEAR": ["General", "audit_year"],
        "COMPLETED_ON": ["General", "completed_date"],
        "COMPONENT DATE RECEIVED": ["General", "component_date_received"],
        "REPORTABLECONDITION": ["General", "reportable_condition"],
        "SIGNIFICANTDEFICIENCY": ["General", "significant_deficiency"],
        "REPORTABLECONDITION_MP": [
            "General",
            "condition_or_deficiency_major_program",
        ],
        "CYFINDINGS": ["General", "current_or_former_findings"],
        "DATEFIREWALL": ["General", "date_published"],
        # this needs to go 2 places
        "DBKEY": ["General", "dbkey"],
        "DOLLARTHRESHOLD": ["General", "dollar_threshold"],
        "DUP_REPORTS": ["General", "dup_reports"],
        "ENTITY_TYPE": ["General", "entity_type"],
        "FACACCEPTEDDATE": ["General", "fac_accepted_date"],
        "FORM DATE RECEIVED": ["General", "form_date_received"],
        "FYENDDATE": ["General", "fy_end_date"],
        "FYSTARTDATE": ["General", "fy_start_date"],
        "GOINGCONCERN": ["General", "going_concern"],
        "INITIAL DATE RECEIVED": ["General", "initial_date_received"],
        "LOWRISK": ["General", "low_risk"],
        "MATERIALNONCOMPLIANCE": ["General", "material_noncompliance"],
        "MATERIALWEAKNESS": ["General", "material_weakness"],
        "MATERIALWEAKNESS_MP": ["General", "material_weakness_major_program"],
        "NUMBERMONTHS": ["General", "number_months"],
        "OVERSIGHTAGENCY": ["General", "oversight_agency"],
        "PERIODCOVERED": ["General", "period_covered"],
        "PREVIOUS_COMPLETED_ON": ["General", "previous_completed_on"],
        "PREVIOUSDATEFIREWALL": ["General", "previous_date_published"],
        "PYSCHEDULE": ["General", "prior_year_schedule"],
        "QCOSTS": ["General", "questioned_costs"],
        "REPORTREQUIRED": ["General", "report_required"],
        "SP_FRAMEWORK": ["General", "special_framework"],
        "SP_FRAMEWORK_REQUIRED": ["General", "special_framework_required"],
        "TOTFEDEXPEND": ["General", "total_fed_expenditures"],
        "TYPEOFENTITY": ["General", "type_of_entity"],
        "TYPEREPORT_FS": ["General", "type_report_financial_statements"],
        "TYPEREPORT_MP": ["General", "type_report_major_program"],
        "TYPEREPORT_SP_FRAMEWORK": ["General", "type_report_special_purpose_framework"],
    },
    "cfda": {
        "RD": ["FederalAward", "research_and_development"],
        "LOANS": ["FederalAward", "loans"],
        "ARRA": ["FederalAward", "arra"],
        "DIRECT": ["FederalAward", "direct"],
        "PASSTHROUGHAWARD": ["FederalAward", "passthrough_award"],
        "MAJORPROGRAM": ["FederalAward", "major_program"],
        "FINDINGREFNUMS": ["FederalAward", "finding_ref_numbers"],
        "AMOUNT": ["FederalAward", "amount"],
        "PROGRAMTOTAL": ["FederalAward", "program_total"],
        "CLUSTERTOTAL": ["FederalAward", "cluster_total"],
        "PASSTHROUGHAMOUNT": ["FederalAward", "passthrough_amount"],
        "LOANBALANCE": ["FederalAward", "loan_balance"],
        "FEDERALPROGRAMNAME": ["FederalAward", "federal_program_name"],
        "CFDAPROGRAMNAME": ["FederalAward", "agency_name"],
        "AWARDIDENTIFICATION": ["FederalAward", "award_identification"],
        "CFDA": ["FederalAward", "agency_cfda"],
        "CLUSTERNAME": ["FederalAward", "cluster_name"],
        "STATECLUSTERNAME": ["FederalAward", "state_cluster_name"],
        "OTHERCLUSTERNAME": ["FederalAward", "other_cluster_name"],
        "TYPEREQUIREMENT": ["FederalAward", "type_requirement"],
        "TYPEREPORT_MP": ["FederalAward", "type_report_major_program"],
        "FINDINGSCOUNT": ["FederalAward", "findings_count"],
        "ELECAUDITSID": ["FederalAward", "audit_id"],
        "DBKEY": ["FederalAward", "dbkey"],
        "AUDITYEAR": ["FederalAward", "audit_year"],
        "QCOSTS2": ["FederalAward", "questioned_costs"],
        "FINDINGS": ["FederalAward", "findings_page"],
        "EIN": ["FederalAward", "cpa_ein"],
    },
    "findings": {
        "MODIFIEDOPINION": ["Finding", "modified_opinion"],
        "OTHERNONCOMPLIANCE": ["Finding", "other_non_compliance"],
        "MATERIALWEAKNESS": ["Finding", "material_weakness"],
        "SIGNIFICANTDEFICIENCY": ["Finding", "significant_deficiency"],
        "OTHERFINDINGS": ["Finding", "other_findings"],
        "QCOSTS": ["Finding", "questioned_costs"],
        "REPEATFINDING": ["Finding", "repeat_finding"],
        "FINDINGSREFNUMS": ["Finding", "finding_ref_number"],
        "PRIORFINDINGREFNUMS": ["Finding", "prior_finding_ref_numbers"],
        "TYPEREQUIREMENT": ["Finding", "type_requirement"],
        "ELECAUDITSID": ["Finding", "audit_id"],
        "ELECAUDITFINDINGSID": ["Finding", "audit_findings_id"],
        "AUDITYEAR": ["Finding", "audit_year"],
        "DBKEY": ["Finding", "dbkey"],
    },
    "findingstext_formatted": {
        "CHARTSTABLES": ["FindingText", "charts_tables"],
        "FINDINGREFNUMS": ["FindingText", "finding_ref_number"],
        "SEQ_NUMBER": ["FindingText", "seqence_number"],
        "TEXT": ["FindingText", "text"],
        "DBKEY": ["FindingText", "dbkey"],
        "AUDITYEAR": ["FindingText", "audit_year"],
    },
    "captext_formatted": {
        "CHARTSTABLES": ["CapText", "charts_tables"],
        "FINDINGREFNUMS": ["CapText", "finding_ref_number"],
        "SEQ_NUMBER": ["CapText", "sequence_number"],
        "TEXT": ["CapText", "text"],
        "DBKEY": ["CapText", "dbkey"],
        "AUDITYEAR": ["CapText", "audit_year"],
    },
    "notes": {
        "TYPE_ID": ["Note", "type_id"],
        "ID": ["Note", "fac_id"],
        "REPORTID": ["Note", "report_id"],
        "VERSION": ["Note", "version"],
        "SEQ_NUMBER": ["Note", "sequence_number"],
        "NOTE_INDEX": ["Note", "note_index"],
        "CONTENT": ["Note", "content"],
        "TITLE": ["Note", "title"],
        "DBKEY": ["Note", "dbkey"],
        "AUDITYEAR": ["Note", "audit_year"],
    },
    "cpas": {
        "CPAPHONE": ["Auditor", "cpa_phone"],
        "CPAFAX": ["Auditor", "cpa_fax"],
        "CPASTATE": ["Auditor", "cpa_state"],
        "CPACITY": ["Auditor", "cpa_city"],
        "CPATITLE": ["Auditor", "cpa_title"],
        "CPASTREET1": ["Auditor", "cpa_street1"],
        "CPAZIPCODE": ["Auditor", "cpa_zip_code"],
        "CPACONTACT": ["Auditor", "cpa_contact"],
        "CPAEMAIL": ["Auditor", "cpa_email"],
        "CPAFIRMNAME": ["Auditor", "cpa_firm_name"],
        "CPAEIN": ["Auditor", "cpa_ein"],
        "DBKEY": ["Auditor", "dbkey"],
        "SEQNUM": ["Auditor", "seqnum"],
    },
    "revisions": {
        "FINDINGS": ["Revision", "findings"],
        "ELECRPTREVISIONID": ["Revision", "revision_id"],
        "FEDERALAWARDS": ["Revision", "federal_awards"],
        "GENINFO_EXPLAIN": ["Revision", "general_info_explain"],
        "FEDERALAWARDS_EXPLAIN": ["Revision", "federal_awards_explain"],
        "NOTESTOSEFA_EXPLAIN": ["Revision", "notes_to_sefa_explain"],
        "AUDITINFO_EXPLAIN": ["Revision", "audit_info_explain"],
        "FINDINGS_EXPLAIN": ["Revision", "findings_explain"],
        "FINDINGSTEXT_EXPLAIN": ["Revision", "findings_text_explain"],
        "CAP_EXPLAIN": ["Revision", "cap_explain"],
        "OTHER_EXPLAIN": ["Revision", "other_explain"],
        "AUDITINFO": ["Revision", "audit_info"],
        "NOTESTOSEFA": ["Revision", "notes_to_sefa"],
        "FINDINGSTEXT": ["Revision", "findings_text"],
        "CAP": ["Revision", "cap"],
        "OTHER": ["Revision", "other"],
        "GENINFO": ["Revision", "general_info"],
        "AUDITYEAR": ["Revision", "audit_year"],
        "DBKEY": ["Revision", "dbkey"],
    },
    "ueis": {},
    # Not in mapping. We handle the agency table in it's own function
    "agency": {
        "AGENCYCFDA": ["Agency", "agency_cdfa"],
        # "AGENCY": ["FederalAward", "agency_prior_findings_list"],
        # EIN, DBKEY, and AUDITYEAT are used to make the relationship with awards data and are not uploaded
        "EIN": ["FederalAward", "cpa_ein"],
        "DBKEY": ["FederalAward", "dbkey"],
        "AUDITYEAR": ["FederalAward", "audit_year"],
    },
    "passthrough": {
        "PASSTHROUGHNAME": ["Passthrough", "passthrough_name"],
        "PASSTHROUGHID": ["Passthrough", "passthrough_id"],
        "ELECAUDITSID": ["Passthrough", "audit_id"],
        "AUDITYEAR": ["Passthrough", "audit_year"],
        "DBKEY": ["Passthrough", "dbkey"],
    },
    # Not in mapping. We handle EINS and DUNS in their own functions
    "eins": {},
    "duns": {},
}
