###
GET {{scheme}}://{{apiUrl}}/general?limit=20000&offset=100000
authorization: {{authorization}}
x-api-user-id: {{xApiUserId}}
accept-profile: {{acceptProfile}}
Accept: application/vnd.pgrst.plan

###
GET {{scheme}}://{{apiUrl}}/general?report_id=eq.2021-12-CENSUS-0000250449
authorization: {{authorization}}
x-api-user-id: {{xApiUserId}}
accept-profile: api_v1_1_0
Accept: application/vnd.pgrst.plan

###
GET {{scheme}}://{{apiUrl}}/general?report_id=eq.2021-12-CENSUS-0000250449
authorization: {{authorization}}
x-api-user-id: {{xApiUserId}}
accept-profile: public_api_v2_0_0_alpha
Accept: application/vnd.pgrst.plan

###
GET {{scheme}}://{{apiUrl}}/federal_awards?batch_number=eq.200
authorization: {{authorization}}
x-api-user-id: {{xApiUserId}}
accept-profile: public_api_v2_0_0_alpha
Accept: application/vnd.pgrst.plan


###
GET {{scheme}}://{{apiUrl}}/federal_awards?batch_number=eq.200&limit=1
authorization: {{authorization}}
x-api-user-id: {{xApiUserId}}
accept-profile: public_api_v2_0_0_alpha

###
GET {{scheme}}://{{apiUrl}}/combined?report_id=eq.2021-12-CENSUS-0000250449
authorization: {{authorization}}
x-api-user-id: {{xApiUserId}}
accept-profile: public_api_v2_0_0_alpha
Accept: application/vnd.pgrst.plan

###
GET {{scheme}}://{{apiUrl}}/rpc/compute_batch?row_id=41000
authorization: {{authorization}}
x-api-user-id: {{xApiUserId}}
accept-profile: public_api_v2_0_0_alpha
