---
name: Build and publish docker container
on:
    workflow_dispatch:

env:
    GH_REPO: ghcr.io/asteel-gsa/fac

jobs:
    build-with-docker:
      name: Build with Docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Create .env file
          working-directory: ./backend
          run: touch .env

        # - name: Set up Docker Buildx
        #   id: buildx
        #   uses: docker/setup-buildx-action@v2

        # - name: Build and Push Action
        #   uses: docker/build-push-action@v4
        #   with:
        #     context: ./backend
        #     cache-from: type=gha
        #     cache-to: type=gha,mode=max

        - name: Build
          working-directory: ./backend
          run: docker builder build . -t ${{ env.GH_REPO }}/web:latest --cache-from type=gha

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Push Image
          run: docker push ${{ env.GH_REPO }}/web:latest


        # - name: Build and push
        #   uses: docker/build-push-action@v4
        #   with:
        #     context: ./backend
        #     cache-from: type=gha
        #     cache-to: type=gha,mode=max
        #     push: true
        #     tags: ${{ env.GH_REPO }}/web:latest
        #     secrets: GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

        # - uses: jpribyl/action-docker-layer-caching@v0.1.1
        #   continue-on-error: false
        # - uses: docker/bake-action@v3
        #   with:
        #     workdir: ./backend
        #     files: docker-compose.yml
        #     push: false
        #     load: true
        #     set: |
        #       web.cache-from=type=gha
        #       web.cache-to=type=gha,mode=max
