---
name: Docker Caching
on:
    workflow_dispatch:

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GH_REPO: ghcr.io/asteel-gsa/fac

jobs:
    build-with-docker:
      name: Build with Docker
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Create .env file
          working-directory: ./backend
          run: touch .env

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Push Image
          run: docker push ${{ env.GH_REPO }}
        # - uses: jpribyl/action-docker-layer-caching@v0.1.1
        #   continue-on-error: false
        # - uses: docker/bake-action@v3
        #   with:
        #     workdir: ./backend
        #     files: docker-compose.yml
        #     push: false
        #     load: true
        #     set: |
        #       web.cache-from=type=gha
        #       web.cache-to=type=gha,mode=max
