---
name: Clean stale table backup files
on:
  schedule:
    # Invoke at 12p UTC on the 1st and 15th of every month
    - cron: '0 12 1,15 * *'
  workflow_dispatch: null

jobs:
  delete-stale-backups:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - name: dev
          - name: staging
          - name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Django command to delete table backups older than 7 days
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-tts-oros-fac
          cf_space: ${{ matrix.environment.name }}
          command: cf run-task gsa-fac -k 2G -m 2G --name delete_backups_older_than_7_days --command "python manage.py delete_stale_backups --days 7 --delete true" --wait

