---
name: Scheduled Deploy From Dev to Staging
on:
  schedule:
    # Invoke every Mon-Sat
    - cron: '0 10 * * 1-6'
  workflow_dispatch:

jobs:
  trivy-scan:
    uses: ./.github/workflows/scanning-trivy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write

  create-pr:
    needs:
      - trivy-scan
    name: Create Pull Request to Staging
    uses: ./.github/workflows/pull_request-to-staging.yml
    secrets: inherit
