---
    name: Pull Third Party Containers, Scan, and Publish to GHCR
    on:
      workflow_dispatch:
      schedule:
        - cron: '0 8 * * 0'

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    jobs:
      pull-and-scan:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        env:
          GH_REPO: asteel-gsa/fac
        strategy:
          fail-fast: false
          matrix:
            image:
              - name: postgrest/postgrest:latest
                short-name: postgrest
              - name: ghcr.io/gsa-tts/clamav-rest/clamav:latest
                short-name: clamav

        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v2

          - name: Pull Docker Image
            run: docker pull ${{ matrix.image.name }}

          - name: Scan Image
            run: docker run aquasec/trivy:latest  image --timeout 5m --scanners vuln --exit-code 1 --severity CRITICAL,HIGH  ${{ matrix.image.name }}

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ env.GH_TOKEN }}

          - name: Setup Keys for DCT
            working-directory: ./backend
            env:
              SSH_PRIVATE_KEY: ${{secrets.RSA_KEY}}
            run: |
              echo "$SSH_PRIVATE_KEY" > private.pem
              chmod 600 private.pem
              openssl rsa -in "private.pem" -pubout > "public.pem"

          # - name: Add Signer
          #   working-directory: ./backend
          #   env:
          #     ROOT_PASS: ${{ secrets.DCT_ROOT_PASS}}
          #     REPO_PASS: ${{ env.GH_TOKEN }}
          #   shell: bash
          #   run: |
          #     { echo "$ROOT_PASS"; echo "$ROOT_PASS"; echo "$REPO_PASS"; echo "$REPO_PASS"; } | docker trust signer add --key public.pem fac ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}

          - name: Load the private key onto Docker Trust Store
            env:
              ROOT_PASS: ${{secrets.DCT_ROOT_PASS}}
            working-directory: ./backend
            shell: bash
            run: |
              { echo "$ROOT_PASS"; echo "$ROOT_PASS"; } | docker trust key load private.pem --name fac

          - name: Tag Image
            run: |
              docker tag ${{ matrix.image.name }} ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}:latest

          - name: Set Docker Content Trust
            run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV

          - name: Sign and Push to GHCR
            env:
              ROOT_PASS: ${{secrets.DCT_ROOT_PASS}}
              REPO_PASS: ${{ env.GH_TOKEN }}
            shell: bash
            run: |
              { echo "$ROOT_PASS"; echo "$ROOT_PASS"; echo "$REPO_PASS"; echo "$REPO_PASS"; } | docker push ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}:latest

          - name: Inspect Content Trust
            run: |
              docker trust inspect --pretty ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.short-name }}:latest
