---
name: Deploy Application Manual Trigger
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - preview
          - staging

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Application
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
