---
name: Deploy to Development and Meta Environments
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend:
              - './backend/**'
            terraform:
              - './terraform/**'

  deploy-infrastructure-dev:
    name: Deploy infrastructure (development)
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.terraform == 'true'
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "dev"
      autoapprove: false
    secrets: inherit

  deploy-infastructure-meta:
    name: Deploy infrastructure (meta)
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.terraform == 'true'
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "meta"
      autoapprove: false
    secrets: inherit

  publish-image:
    name: Build and push image
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.backend == 'true'
    uses: ./.github/workflows/containers-build-fac-container.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      docker-name: fac
      image-name: web-container
      repo-name: gsa-tts/fac
      work-dir: ./backend

  deploy-application:
    name: Deploy application
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.backend == 'true'
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: "dev"
    secrets: inherit

  new-relic-record:
    name: Record deployment to New Relic
    needs: 
      - deploy-application
    uses: ./.github/workflows/deploy-record-newrelic-deployment.yml
    with:
      environment: "dev"
    secrets: inherit

  scan-dev-post-deploy:
    name: ZAP Scan
    needs:
      - deploy-application
    uses: ./.github/workflows/scanning-zap-scan.yml
    with:
      url: "https://fac-dev.app.cloud.gov/"

