# deploy.yml
name: Deploy to cloud.gov

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update service keys
        uses: 18f/cg-deploy-action@main
        env:
          SAM_API_KEY: ${{ secrets.SAM_API_KEY }}
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-10x-prototyping
          cf_space: dev
          full_command: "cf update-user-provided-service fac-key-service -p '{\"SAM_API_KEY\":\"$SAM_API_KEY\"}'"

      - name: Deploy to cloud.gov
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-10x-prototyping
          cf_space: dev
          push_arguments: "-f backend/manifests/manifest-dev.yml"
