---
name: Deploy to the Production Environment
on:
  push:
    tags:
      - v1.*

jobs:
  # testing:
  #   uses: ./.github/workflows/testing-from-ghcr.yml
  #   secrets: inherit

  linting:
    uses: ./.github/workflows/pull_request-linting.yml
    secrets: inherit

  deploy-infrastructure-production:
    name: Deploy infrastructure (production)
    # needs:
    #   - testing
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "production"
      autoapprove: false
    secrets: inherit

  new-relic-record:
    name: Record deployment to New Relic
    needs:
      - deploy-infrastructure-production
    uses: ./.github/workflows/deploy-record-newrelic-deployment.yml
    with:
      environment: "production"
    secrets: inherit

  deploy-production:
    name: Deploy application
    needs:
      - deploy-infrastructure-production
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: "production"
    secrets: inherit

  scan-production-post-deploy:
    name: Zap Scan
    needs:
      - deploy-production
    uses: ./.github/workflows/scanning-zap-scan.yml
    with:
      url: "https://app.fac.gov/"
