---
name: Deploy to the Staging Environment
on:
  push:
    branches:
      - prod

permissions:
  contents: read

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          base: 'main'
          filters: |
            backend:
              - './backend/**'
            terraform:
              - './terraform/**'

  deploy-infrastructure:
    name: Deploy infrastructure
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.terraform == 'true'
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "staging"
      autoapprove: false
    secrets: inherit

  deploy-application:
    name: Deploy application
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.backend == 'true'
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: "staging"
    secrets: inherit

  new-relic-record:
    name: Record deployment to New Relic
    needs:
      - deploy-application
    uses: ./.github/workflows/deploy-record-newrelic-deployment.yml
    with:
      environment: "staging"
    secrets: inherit

  scan-staging:
    needs:
      - deploy-application
    name: Zap Scan
    uses: ./.github/workflows/scanning-zap-scan.yml
    with:
      url: "https://fac-staging.app.cloud.gov/"

  regression-test:
    needs:
      - deploy-application
    name: Run Regression Tests
    uses: ./.github/workflows/testing-cypress-regression-tests.yml
    secrets: inherit
    with:
      url: "https://fac-staging.app.cloud.gov"
      environment: "staging"
