name: Record Deployment And Add New Relic Monitor
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic Record Deployment
    environment: ${{ inputs.environment }}
    steps:
    - name: Set Release Version from Tag
      run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Add New Relic Application Deployment Marker
      uses: newrelic/deployment-marker-action@v2.6.2
      with:
        apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
        guid: ${{ secrets.NEW_RELIC_ENTITY_GUID }}
        version: "${{ env.RELEASE_VERSION }}"
        user: "${{ github.actor }}"

 