---
name: Deploy to the Staging Environment
on:
  push:
    branches:
      - prod

permissions:
  contents: read

jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "staging"
      autoapprove: false
    secrets: inherit

  deploy-application:
    name: Deploy application
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: "staging"
    secrets: inherit

  new-relic-record:
    name: Record deployment to New Relic
    needs:
      - deploy-application
    uses: ./.github/workflows/deploy-record-newrelic-deployment.yml
    with:
      environment: "staging"
    secrets: inherit

  scan-staging:
    needs:
      - deploy-application
    name: Zap Scan
    uses: ./.github/workflows/scanning-zap-scan.yml
    with:
      url: "https://fac-staging.app.cloud.gov/"

  regression-test:
    needs:
      - deploy-application
    name: Run Regression Tests
    uses: ./.github/workflows/testing-cypress-regression-tests.yml
    secrets: inherit
    with:
      url: "https://fac-staging.app.cloud.gov"
      environment: "staging"
