---
name: "Task: run Django command to delete and then regenerate all dissemination objects"
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        # dev, staging, production

jobs:
  destroy-and-regenerate-dissemination-objects:
    name: Destroy and regenerate dissemination objects in ${{ inputs.environment }} database
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      space: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Django command to destroy and regenerate dissemination objects in ${{ inputs.environment }}
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-tts-oros-fac
          cf_space: ${{ env.space }}
          command: cf run-task gsa-fac -k 2G -m 2G --name rebuild_dissemination --command "python manage.py delete_and_regenerate_dissemination_from_intake"
