---
name: Docker Images
on:
  workflow_call:

jobs:
  download-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull PostGREST Docker Image
        run: docker pull postgrest/postgrest:latest
      - name: Pull swagger Docker Image
        run: docker pull swaggerapi/swagger-ui:latest
      - name: Pull ClamAV Docker Image
        run: docker pull clamav/clamav:latest

      - name: Save PostGREST Docker Image as Tar File
        run: docker save postgrest/postgrest:latest -o postgrest-image.tar
      - name: Save swagger Docker Image as Tar File
        run: docker save swaggerapi/swagger-ui:latest -o swagger-image.tar
      - name: Save ClamAV Docker Image as Tar File
        run: docker save clamav/clamav:latest -o clamav-image.tar

      - name: grab trivy container
        run: docker pull aquasec/trivy:latest
      - name: Scan PostGREST
        run: docker run  aquasec/trivy:latest image postgrest/postgrest:latest
      - name: Scan swagger
        run: docker run  aquasec/trivy:latest image swaggerapi/swagger-ui:latest
      - name: Scan ClamAV
        run: docker run  aquasec/trivy:latest image  --scanners vuln clamav/clamav:latest

