---
name: Export Audit Data to CSV
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: choice
        description: The environment the workflow should run on.
        options:
          - dev
          - staging
          - production
      year:
        required: true
        type: string
        description: Provide audit year.

jobs:
  scheduled-audit-data-export:
    name: Run bulk data export on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      space: ${{ inputs.environment }}
    steps:
      - name: Run bulk data export
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-tts-oros-fac
          cf_space: ${{ env.space }}
          command: cf run-task gsa-fac -k 2G -m 4G --name export_audit_data_to_csv_scheduled --command "python manage.py export_data_audit --year ${{ inputs.year }}" --wait
          # TO DO:  Update above line to 
          # run bulk export for 2016 through (current_year +1) + bulk export all 
          # one at a time waiting for one export to complete before kicking off the next