---
name: Export Audit Data to CSV Scheduler
on:
  schedule:
    # Staging, Prod test - Tuesday, Wednesday, Thursday at 11 PM UTC
    - cron: '0 23 * * [2,3,4]'

jobs:
  scheduled-audit-data-export:
    strategy:
      fail-fast: false
      matrix:
        environment: 
          - name: staging
          - name: production
    name: Run bulk data export
    uses: ./.github/workflows/export-audit-data-to-csv-scheduled.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment.name }}
