---
name: Export Audit Data to CSV
on:
  schedule:
    # Every week on Sunday 1 AM UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:
    null

jobs:
  scheduled-audit-data-export:
    strategy:
      fail-fast: false
      matrix:
        environment: 
          - name: dev
          - name: staging
          - name: production
    name: Run bulk data export on ${{ inputs.environment }}
    uses: ./.github/workflows/export-audit-data-to-csv-scheduled.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment.name }}
