---
name: Check Tables Daily
on:
  schedule:
    # Invoke every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: null

jobs:
  check-tables:
    strategy:
      fail-fast: false
      matrix:
        environment:
          - name: dev
          - name: staging
          - name: production
          - name: preview
    uses: ./.github/workflows/fac-check-tables.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment.name }}
      util_version: "v0.1.7"
      backup_operation: "check_tables"
