---
name: Lint Files
on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      ENV: TESTING
      SECRET_KEY: secrets.SECRET_KEY
    steps:
      - uses: actions/checkout@v3
      - name: Restore npm cache
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: fac-build-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            fac-build-npm-
            fac-build-
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Restore pip cache
        uses: actions/cache@v3
        id: cache-pip
        with:
          path: |
            ~/.cache/pip
            /opt/hostedtoolcache/Python/
          key: fac-build-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            fac-build-pip-${{ hashFiles('**/requirements.txt') }}-
            fac-build-pip-
            fac-build-
      - name: Install linters
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint with flake8
        working-directory: ./backend
        run: flake8 . --count --show-source --statistics
      - name: Check formatting with black
        working-directory: ./backend
        run: black --check .
      - name: Run bandit
        working-directory: ./backend
        run: bandit -c pyproject.toml -r .
      - name: Run type checking
        working-directory: ./backend
        run: mypy .
      - name: Run HTML template linting
        working-directory: ./backend
        run: djlint --lint .

  frontend-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore npm cache
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: fac-build-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            fac-build-npm-
            fac-build-
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm packages
        working-directory: ./backend
        run: npm ci
      - name: Lint JS & SCSS
        working-directory: ./backend
        run: npm run check-all

  validate-terraform:
    uses: ./.github/workflows/terraform-lint.yml
