---
name: Run the Materialize Views Django Function
on:
  # schedule:
  #   # This needs to match scheduled-materialize-views: if conditional
  #   # Run every 1 hours
  #   - cron: '0 */1 * * *'

  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       required: true
  #       type: choice
  #       description: The environment the workflow should run on.
  #       options:
  #         - dev
  #         - staging
  #         - preview
  #         - production
  push:
    branches:
      - jadudm/materialized-views
jobs:
  # scheduled-materialize-views:
  #   # This needs to match the cron above. Just makes it safer to ensure it doesnt execute when we don't want it.
  #   if: ${{ github.event.schedule == '0 */1 * * *' }}
  #   strategy:
  #     matrix:
  #       environments: ["dev", "staging", "production"]
  #   name: Run Materialize Views Matrix
  #   runs-on: ubuntu-latest
  #   environment: ${{ matrix.environments }}
  #   env:
  #     space: ${{ matrix.environments }}
  #   steps:
  #     - name: Run Command
  #       uses: cloud-gov/cg-cli-tools@main
  #       with:
  #         cf_username: ${{ secrets.CF_USERNAME }}
  #         cf_password: ${{ secrets.CF_PASSWORD }}
  #         cf_org: gsa-tts-oros-fac
  #         cf_space: ${{ env.space }}
  #         command: cf run-task gsa-fac -k 2G -m 2G --name scheduled_refresh_materialized_views --command "python manage.py materialize_views --refresh"

  dispatch-materialize-views:
    # if: ${{ github.event.inputs.environment != '' }}
    # name: Run Materialize Views on ${{ inputs.environment }}
    name: Run Materialize Views on preview
    runs-on: ubuntu-latest
    environment: preview # ${{ inputs.environment }}
    env:
      space: preview # ${{ inputs.environment }}
    steps:
      - name: Run Command
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsa-tts-oros-fac
          cf_space: ${{ env.space }}
          command: cf run-task gsa-fac -k 2G -m 2G --name dispatch_refresh_materialize_views --command "python manage.py materialized_views --refresh"
