---
name: Merge Queue
on:
  merge_group:
    branches:
      - main

jobs:
  merge-queue:
    if: github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - name: "Entering Merge Queue"
        run: echo "Merge queue has been activated"
