---
name: Merge Queue Push
on:
  merge_group:
    branches:
      - main

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: "Entering Merge Queue"
        run: echo "Merge queue has been activated"
