---
name: Pull Request Checks
permissions:
  contents: read
  pull-requests: write
  checks: write
on:
  pull_request:
    branches:
      - main
      - prod
    paths:
      - '**'
      - '!docs/**'
      - 'docs/bpmn-workflow-models/**'
      - '!.github/ISSUE_TEMPLATE/**'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      requirements: ${{ steps.filter.outputs.requirements }}
      migration: ${{ steps.filter.outputs.migration }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - './backend/**'
            requirements:
              - './backend/requirements.txt'
            migration:
              - './backend/audit/models/**'
              - './backend/dissemination/models/**'
            terraform:
              - './terraform/**'

  linting:
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.backend == 'true' || github.base_ref == 'prod'
    uses: ./.github/workflows/pull_request-linting.yml
    secrets: inherit

  testing-from-build:
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.backend == 'true' || github.base_ref == 'prod'
    permissions: write-all
    uses: ./.github/workflows/testing-from-build.yml
    secrets: inherit

  cypress-from-container:
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.backend == 'true' || github.base_ref == 'prod'
    uses: ./.github/workflows/testing-cypress-container.yml
    with:
      environment: testing
    secrets: inherit

  terraform-validate: 
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.terraform == 'true' || github.base_ref == 'prod'
    uses: ./.github/workflows/terraform-lint.yml

  # Generate Terraform Plans
  terraform-plan-dev:
    needs: 
      - check-for-changes
    if: github.base_ref == 'main' && needs.check-for-changes.outputs.terraform == 'true'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: dev
    secrets: inherit

  terraform-plan-meta:
    needs: 
      - check-for-changes
    if: github.base_ref == 'main' && needs.check-for-changes.outputs.terraform == 'true'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: meta
    secrets: inherit

  terraform-plan-staging:
    if: github.base_ref == 'prod'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: staging
    secrets: inherit

# uses tags "v1.*"
  terraform-plan-prod:
    if: github.base_ref == 'prod'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: production
    secrets: inherit

  repo-event:
    if: ${{ github.base_ref == 'prod' && always() }}
    name: Set Repository Event
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [terraform-plan-staging, testing-from-build]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: ready-to-merge
          client-payload: '{"github": ${{ toJson(github) }}}'
        if: github.event_name == 'pull_request'

  validate-migrations:
    needs: 
      - check-for-changes
    if: needs.check-for-changes.outputs.requirements == 'true' || needs.check-for-changes.outputs.migration == 'true'
    uses: ./.github/workflows/validate-migrations.yml
    secrets: inherit
