---
name: Run Regression Tests
on:
  workflow_dispatch:
    inputs:
      url:
        description: "Base URL for Cypress"
        required: true
        type: string
        default: "https://fac-staging.app.cloud.gov"
      environment:
        required: true
        type: string
        default: "staging"
  workflow_call:
    inputs:
      url:
        description: "Base URL for Cypress"
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  regression-testing:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      CYPRESS_API_GOV_KEY: ${{ secrets.CYPRESS_API_GOV_KEY }}
      CYPRESS_API_GOV_USER_ID: ${{ secrets.CYPRESS_API_GOV_USER_ID }}
      CYPRESS_API_GOV_KEY_ADMIN: ${{ secrets.CYPRESS_API_GOV_KEY_ADMIN }}
      CYPRESS_API_GOV_USER_ID_ADMIN: ${{ secrets.CYPRESS_API_GOV_USER_ID_ADMIN }}
      CYPRESS_API_GOV_URL: ${{ secrets.CYPRESS_API_GOV_URL }}
      CYPRESS_API_VERSION: ${{ secrets.CYPRESS_API_VERSION }}
      CYPRESS_ADMIN_API_VERSION: ${{ secrets.CYPRESS_ADMIN_API_VERSION }}
      CYPRESS_BASE_URL: ${{ inputs.url }}
      CYPRESS_LOGIN_TEST_EMAIL: ${{ secrets.CYPRESS_LOGIN_TEST_EMAIL }}
      CYPRESS_LOGIN_TEST_PASSWORD: ${{ secrets.CYPRESS_LOGIN_TEST_PASSWORD }}
      CYPRESS_LOGIN_TEST_OTP_SECRET: ${{ secrets.CYPRESS_LOGIN_TEST_OTP_SECRET }}
      CYPRESS_LOGIN_TEST_EMAIL_AUDITEE: ${{ secrets.CYPRESS_LOGIN_TEST_EMAIL_AUDITEE }}
      CYPRESS_LOGIN_TEST_PASSWORD_AUDITEE: ${{ secrets.CYPRESS_LOGIN_TEST_PASSWORD_AUDITEE }}
      CYPRESS_LOGIN_TEST_OTP_SECRET_AUDITEE: ${{ secrets.CYPRESS_LOGIN_TEST_OTP_SECRET_AUDITEE }}
      DISABLE_AUTH: False
      # useful for debugging but otherwise complete overwhelm
      # DEBUG: cypress:server:util:process_profiler
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: touch .env

      - name: Run Cypress full submission test
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: ./backend
          spec: cypress/e2e/full-submission.cy.js

      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: backend/cypress/screenshots
          if-no-files-found: warn # 'warn' or 'error' are also available, defaults to `warn`
