---
name: Production Media Snapshot
on:
  #schedule:
    # Invoke at 9 UTC every monday
    #- cron: '0 9 * * 1'
  workflow_dispatch: null

jobs:
  production-media-snapshot:
    uses: ./.github/workflows/tar-s3-media.yml
    secrets: inherit
    with:
      environment: "production"

