---
    name: Scheduled Deploy From Main to Staging
    on:
        schedule:
        - cron: '0 10 * * *'
    jobs:
      create-pr:
        name: Auto Create PR at 430am UTC Daily
        uses: ./.github/workflows/auto-create-pr.yml
        secrets: inherit
