---
name: Scheduled Deploy From Main to Staging
on:
  schedule:
    # Invoke every Mon-Sat
    - cron: '0 10 * * 1-6'
  workflow_dispatch:

jobs:
  trivy-scan:
    uses: ./.github/workflows/trivy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write

  build-container:
    needs:
      - trivy-scan
    uses: ./.github/workflows/build-docker-container.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      docker-name: fac
      image-name: web-container
      repo-name: gsa-tts/fac
      work-dir: ./backend

  testing:
    name: Run Django and lint
    needs:
      - build-container
    uses: ./.github/workflows/testing-from-ghcr.yml
    secrets: inherit

  linting:
    uses: ./.github/workflows/linting.yml
    secrets: inherit

  create-pr:
    needs:
      - testing
    name: Create Pull Request to Staging
    uses: ./.github/workflows/create-pull-request-to-staging.yml
    secrets: inherit
