name: TEST - Terraform Plan Manual Trigger
on:
  workflow_dispatch:
    inputs:
        environment:
            required: true
            type: string

permissions:
  contents: read

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan-prod.yml
    with:
        environment: ${{ inputs.environment }}

