---
name: Terraform plan
on:
  pull_request:
    # These two branches are deployment-sensitive
    branches:
      - main
      - prod

jobs:
  management:
    name: Generate plan for management space
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: "management"
    secrets: inherit
  dev:
    name: Generate plan for dev space
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: "dev"
    secrets: inherit
  staging:
    name: Generate plan for staging space
    if: github.event.ref == 'refs/heads/prod'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: "staging"
    secrets: inherit
  production:
    name: Generate plan for prod space
    if: github.event.ref == 'refs/heads/prod'
    uses: ./.github/workflows/terraform-plan-env.yml
    with:
      environment: "prod"
    secrets: inherit


