name: Deploy to the dev space from a temporary branch
on:
  push:
    branches:
      - https-proxy-test

jobs:
  # deploy to Dev & Management spaces
  deploy-infrastructure-dev:
    name: Deploy infrastructure (dev)
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "dev"
    secrets: inherit

  deploy-dev:
    name: Deploy dev app to cloud.gov
    needs:
        - deploy-infrastructure-dev
    uses: ./.github/workflows/deploy-apps.yml
    with:
        environment: "dev"
    secrets: inherit
