---
name: Terraform Format
on:
  workflow_call:

jobs:
  test:
    name: Test format and validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Terraform Format
        uses: dflook/terraform-fmt-check@v3.0.0
        with:
          path: ./terraform

      - name: Terraform Validate
        uses: dflook/terraform-validate@v2.2.3
        with:
          path: ./terraform

