---
name: terraform fmt+validate

on: 
  push:
    paths:
      - 'terraform/**'

jobs:
  test:
    name: test format and validity
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./terraform

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: ./terraform

