name: Production Infrastructure Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  contents: read

env:
  TF_PLAN_FILE: "tf-plan-${{inputs.environment}}-${{ github.sha }}-${{ github.run_id }}"

jobs:
  plan:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_VAR_cf_user: ${{ secrets.CF_USERNAME }}
      TF_VAR_cf_password: ${{ secrets.CF_PASSWORD }}
      TF_VAR_new_relic_license_key: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      TF_VAR_new_relic_account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      TF_VAR_new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
      TF_VAR_pgrst_jwt_secret: ${{ secrets.PGRST_JWT_SECRET }}
      KEY: "terraform.tfstate.${{ inputs.environment }}"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v6
      - name: Install CF CLI
        run: |
          apt-get update
          apt-get install -y zip python

          curl -k -O -L https://github.com/cloudfoundry/cli/releases/download/v8.8.0/cf8-cli-installer_8.8.0_x86-64.deb
          apt-get install --assume-yes ./cf8-cli-installer_8.8.0_x86-64.deb

          cf api api.fr.cloud.gov
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
      - name: Terraform Init
        run: |
          terraform init \
            --backend-config="bucket=${{ secrets.terraform_BUCKET }}" \
            --backend-config="region=${{ secrets.terraform_REGION }}"
            --backend-config="key=${{ env.KEY }}"
      - name: Terraform Plan
        run: |
          terraform plan -out=${{ env.TF_PLAN_FILE }}
      - name: Upload to S3
        run: |
          aws s3 cp ${{ env.TF_PLAN_FILE }} s3://${{ secrets.terraform_BUCKET }}
      - name: Remove tfplan file
        if: always()
        run: rm -f ${{ env.TF_PLAN_FILE }}

  apply:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_cf_user: ${{ secrets.CF_USERNAME }}
      TF_VAR_cf_password: ${{ secrets.CF_PASSWORD }}
      TF_VAR_new_relic_license_key: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      TF_VAR_new_relic_account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      TF_VAR_new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
      TF_VAR_pgrst_jwt_secret: ${{ secrets.PGRST_JWT_SECRET }}
      KEY: "terraform.tfstate.${{ inputs.environment }}"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Install CF CLI
        run: |
          apt-get update
          apt-get install -y zip python

          curl -k -O -L https://github.com/cloudfoundry/cli/releases/download/v8.8.0/cf8-cli-installer_8.8.0_x86-64.deb
          apt-get install --assume-yes ./cf8-cli-installer_8.8.0_x86-64.deb

          cf api api.fr.cloud.gov
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
      - name: Download Plan File
        run: |
          aws s3 cp s3://${{ secrets.terraform_BUCKET }}/${{ env.TF_PLAN_FILE }}
      - name: Terraform Apply
        run: |
          terraform apply
      - name: Remove tfplan file from S3
        run: |
          aws s3 rm s3://${{ secrets.terraform_BUCKET}}/${{ env.TF_PLAN_FILE}}
      - name: Remove tfplan file from runner
        if: always()
        run: rm -f ${{ env.TF_PLAN_FILE}}
