---
name: Daily Cypress Regression Tests
on:
  schedule:
    - cron: '0 9 * * 1-5'

jobs:
  regression-test:
    name: Run Regression Tests
    uses: ./.github/workflows/testing-cypress-regression-tests.yml
    secrets: inherit
    with:
      url: "https://fac-staging.app.cloud.gov"
      environment: "staging"
