---
name: Run Django and A11y Tests
on:
  workflow_call:

jobs:
  django-test:
    runs-on: ubuntu-latest
    env:
      ENV: TESTING
      SAM_API_KEY: ${{ secrets.SAM_API_KEY }}
      DJANGO_BASE_URL: 'http://localhost:8000'
      DJANGO_SECRET_LOGIN_KEY: ${{ secrets.DJANGO_SECRET_LOGIN_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: '0.0.0.0 127.0.0.1 localhost'
      DISABLE_AUTH: False
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create .env
        working-directory: ./backend
        run: touch .env
      - name: Start services
        working-directory: ./backend
        run: docker compose -f docker-compose.yml up -d
      - name: Run Django test suite
        working-directory: ./backend
        run:
          docker compose -f docker-compose.yml run web bash -c 'coverage run --parallel-mode --concurrency=multiprocessing manage.py test --parallel && coverage combine && coverage report -m --fail-under=90'

  a11y-testing:
    runs-on: ubuntu-20.04
    env:
      ENV: TESTING
      SAM_API_KEY: ${{ secrets.SAM_API_KEY }}
      DJANGO_BASE_URL: 'http://localhost:8000'
      DJANGO_SECRET_LOGIN_KEY: ${{ secrets.DJANGO_SECRET_LOGIN_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: '0.0.0.0 127.0.0.1 localhost'
      DISABLE_AUTH: True
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create .env
        working-directory: ./backend
        run: touch .env
      - name: Start services
        working-directory: ./backend
        run: docker compose -f docker-compose.yml up -d
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
      - name: run pa11y
        run: |
          npm i -g pa11y-ci
          pa11y-ci
