# deploy.yml
name: Deploy to cloud.gov

on:
  push:
    branches:
    - main
    - prod
    tags:
    - v1.*
  pull_request:
    branches:
    - main
    - prod
  workflow_dispatch:

jobs:
  linting_and_tests:
    name: Linting and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: @actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: ./.github/actions/tests

  deploy-dev:
    name: Deploy to dev
    if: github.event.ref == 'refs/heads/main'
    needs: linting_and_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          envionment: dev
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}

  # deploy-staging:
  #   name: Deploy to staging
  #   if: github.event.ref == 'refs/heads/prod'
  #   needs: linting_and_tests
  #   runs-on: ubuntu-latest
  #   envionment: staging
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/deploy
  #       with:
  #         cf_username: ${{ secrets.CF_USERNAME }}
  #         cf_password: ${{ secrets.CF_PASSWORD }}

  # deploy-production:
  #   name: Deploy to produciton
  #   if: github.event.ref == 'refs/tag/v1.*'
  #   needs: linting_and_tests
  #   runs-on: ubuntu-latest
  #   envionment: production
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/deploy
  #       with:
  #         cf_username: ${{ secrets.CF_USERNAME }}
  #         cf_password: ${{ secrets.CF_PASSWORD }}
