---
name: Test and deploy flow
on:
  push:
    branches:
      - main
      - prod
    tags:
      - v1.*
  pull_request:
    branches:
      - main
      - prod
  workflow_dispatch: null

jobs:
  test_and_lint:
    uses: ./.github/workflows/test.yml

  deploy-dev:
    name: Deploy to dev
    if: github.event.ref == 'refs/heads/main'
    needs: test_and_lint
    uses: ./.github/workflows/deploy.yml
    with:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      cf_space: dev
    secrets: inherit

  # deploy-staging:
  #   name: Deploy to staging
  #   runs-on: ubuntu-latest
  #   if: github.event.ref == 'refs/heads/prod'
  #   needs: test_and_lint
  #   environment: staging
  #   steps:
  #     - uses: ./.github/workflows/deploy.yml
  #       with:
  #         cf_username: ${{ secrets.CF_USERNAME }}
  #         cf_password: ${{ secrets.CF_PASSWORD }}
  #         cf_space: staging

  # deploy-production:
  #   name: Deploy to production
  #   runs-on: ubuntu-latest
  #   if: github.event.ref == 'refs/tag/v*'
  #   needs: test_and_lint
  #   environment: production
  #   steps:
  #     - uses: ./.github/workflows/deploy.yml
  #       with:
  #         cf_username: ${{ secrets.CF_USERNAME }}
  #         cf_password: ${{ secrets.CF_PASSWORD }}
  #         cf_org: gsa-tts-oros-fac
  #         cf_space: production
