---
name: Deploy to cloud.gov
on:
  push:
    branches:
      - main
      - prod
      # for testing
      - ly/owasp#712
    tags:
      - v1.*
  pull_request:
    branches:
      - main
      - prod
  workflow_dispatch: null

jobs:
  test_and_lint:
    uses: ./.github/workflows/test.yml

  scan-dev:
    uses: ./.github/workflows/zap-scan.yml
    with:
      url: "https://fac-dev.app.cloud.gov/"

  deploy-infrastructure-dev:
    name: Deploy infrastructure (dev)
    if: github.event.ref == 'refs/heads/main'
    needs:
      - test_and_lint
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "dev"
    secrets: inherit

  deploy-infrastructure-staging:
    name: Deploy infrastructure (staging)
    if: github.event.ref == 'refs/heads/prod'
    needs:
      - test_and_lint
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "staging"
    secrets: inherit

  deploy-infrastructure-production:
    name: Deploy infrastructure (production)
    if: github.event.ref == 'refs/tag/v1.*'
    needs:
      - test_and_lint
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "production"
    secrets: inherit

  deploy-dev:
    name: Deploy dev app to cloud.gov
    if: github.event.ref == 'refs/heads/main'
    needs:
      - test_and_lint
      - deploy-infrastructure-dev
    uses: ./.github/workflows/deploy-apps.yml
    with:
      environment: "dev"
    secrets: inherit

  deploy-staging:
    name: Deploy staging app to cloud.gov
    if: github.event.ref == 'refs/heads/prod'
    needs:
      - test_and_lint
      - deploy-infrastructure-staging
    uses: ./.github/workflows/deploy-apps.yml
    with:
      environment: "staging"
    secrets: inherit

  deploy-production:
    name: Deploy production to cloud.gov
    if: github.event.ref == 'refs/tag/v1.*'
    needs:
      - test_and_lint
      - deploy-infrastructure-production
    uses: ./.github/workflows/deploy-apps.yml
    with:
      environment: "production"
    secrets: inherit
