---
name: Deploy to cloud.gov
on:
  push:
    branches:
      - main
      - prod
    tags:
      - v1.*
  pull_request:
    branches:
      - main
      - prod
  workflow_dispatch: null

jobs:
  # testing
  test-and-lint:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  # deploy to dev
  deploy-infrastructure-dev:
    name: Deploy infrastructure (dev)
    if: github.event.ref == 'refs/heads/main'
    needs:
      - test-and-lint
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "dev"
    secrets: inherit

  deploy-dev:
    name: Deploy dev app to cloud.gov
    if: github.event.ref == 'refs/heads/main'
    needs:
      - deploy-infrastructure-dev
    uses: ./.github/workflows/deploy-apps.yml
    with:
      environment: "dev"
    secrets: inherit

  scan-dev-post-deploy:
    name: Zap scan of the dev site
    needs:
      - deploy-dev
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/zap-scan.yml
    with:
      url: "https://fac-dev.app.cloud.gov/"

  # deploy to staging
  scan-dev:
    name: Zap scan of the dev site
    if: github.event.ref == 'refs/heads/prod'
    uses: ./.github/workflows/zap-scan.yml
    with:
      url: "https://fac-dev.app.cloud.gov/"

  deploy-infrastructure-staging:
    name: Deploy infrastructure (staging)
    if: github.event.ref == 'refs/heads/prod'
    needs:
      - test-and-lint
      - scan-dev
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "staging"
    secrets: inherit

  deploy-staging:
    name: Deploy staging app to cloud.gov
    if: github.event.ref == 'refs/heads/prod'
    needs:
      - deploy-infrastructure-staging
    uses: ./.github/workflows/deploy-apps.yml
    with:
      environment: "staging"
    secrets: inherit

  # deploy to production
  scan-staging:
    name: Zap scan of the staging site
    if: github.event.ref == 'refs/tags/v1.*'
    uses: ./.github/workflows/zap-scan.yml
    with:
      url: "https://fac-staging.app.cloud.gov/"

  deploy-infrastructure-production:
    name: Deploy infrastructure (production)
    if: github.event.ref == 'refs/tags/v1.*'
    needs:
      - test-and-lint
      - scan-staging
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "production"
    secrets: inherit

  deploy-production:
    name: Deploy production to cloud.gov
    if: github.event.ref == 'refs/tags/v1.*'
    needs:
      - deploy-infrastructure-production
    uses: ./.github/workflows/deploy-apps.yml
    with:
      environment: "production"
    secrets: inherit

  scan-production-post-deploy:
    name: Zap scan of the production site
    if: github.event.ref == 'refs/tags/v1.*'
    needs:
      - deploy-production
    uses: ./.github/workflows/zap-scan.yml
    with:
      url: "https://fac-prod.app.cloud.gov/"
